### ISSUE TITLE
Feature Request - Mod Menu Support 

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#10]
Add the mod menu button for Forge users (which Forge adds by itself) and Fabric/Quilt users (which is done through Mod Menu, a mod for Fabric) to the Legacy Title Screen (and in Fabric's case, pause screen too). 
It can probably fit in Help & Options or just have its own dedicated button on both screens.

**Comment by Chilly-roll** [comment]
(this would be an enhancement, can't assign that label.. oops)

**Comment by Wilyicaro** [comment]
It's a planned addition, not as a mod menu support, but rather I want to make it in the Legacy Edition style
