### ISSUE TITLE
Can't hold maps AT ALL

### ISSUE THREAD

**Issue by BigWrinklySack** [Wilyicaro/Legacy-Minecraft#100]
If you hold a map and look at it, your game crashes and you're softlocked unless you delete your player file for the world.

(also you cant go into mod options)

**Comment by BigWrinklySack** [comment]
Im on macos high sierra

**Comment by Wilyicaro** [comment]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/09683bda-80cc-410d-8b5c-9330fc56b8fc)
It's working normally in version 1.4, probably this is a specific problem, which requires a crash report to be fixed

**Comment by BigWrinklySack** [comment]
[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/14336084/latest.log)
(i recently crashed from trying to trade with something, another bug.)

**Comment by Wilyicaro** [comment]
This isn't directly a bug, it's an incompatibility, as under normal circumstances it doesn't occur, but it may take a while to fix, if possible, due the size of the log, and apparently you were on a server with plugins

**Comment by Wilyicaro** [comment]
At least in this log you are using version 1.3.3, which actually has this crashing problem on servers without the mod installed, install version 1.4 and go play ;)
