### ISSUE TITLE
When buying stuff from villagers and wandering traders, it doesn't play trade accepted sound

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#102]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/696a9e4e-bcab-4d5c-b753-bb25886c5c59

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/b44a6089-d77a-4b9f-836a-c4991686d022

**Comment by Wilyicaro** [comment]
Fixed in version 1.4.1, thanks for reporting.
