### ISSUE TITLE
Dispensers and droppers plays legacy console clicking sound instead of their own sounds

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#104]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4e50f2fd-e645-4cd5-a5ff-70db538a91ad

**Comment by Wilyicaro** [comment]
The dispenser sound used in Java Edition by default is the UI_BUTTON_CLICK, the same used in GUI buttons with a different pitch, so now I'll have to change the dispenser sound, or create a new sound for the Legacy UI click sound, but I don't know why this sound is called UI_BUTTON_CLICK and is used for dispensers too, lol, a bit lazy

**Comment by AgentMindStorm** [comment]
Not quite true. Dispensers and all other blocks have unique sounds.json entries separate from ui.button.click entry. They can be changed independently of menu sounds.

Also, the click sound used in menus is click_stereo.ogg. If you replace click_stereo but do not change click.ogg, the menus will sound correct!

**Comment by DanielMC101** [comment]
@Wilyicaro speaking of UI sounds, honestly do u think u can maybe make the UI sounds a bit more louder? cuz honestly it sounds a bit too quiet compared to legacy console

**Comment by Wilyicaro** [comment]
> Not quite true. Dispensers and all other blocks have unique sounds.json entries separate from ui.button.click entry. They can be changed independently of menu sounds.
> 
> Also, the click sound used in menus is click_stereo.ogg. If you replace click_stereo but do not change click.ogg, the menus will sound correct!
Good to know! I'll test it right now.

**Comment by Wilyicaro** [comment]
> @Wilyicaro speaking of UI sounds, honestly do u think u can maybe make the UI sounds a bit more louder? cuz honestly it sounds a bit too quiet compared to legacy console
Of course, I tested it with the focus sounds, as you can hear.
