### ISSUE TITLE
Classic Crafting doesn't include Stonecutter UI

### ISSUE THREAD

**Issue by BuddarScotchy** [Wilyicaro/Legacy-Minecraft#107]
Simply put, in the latest version of Legacy4J attempting to use the Stonecutter regarding of whether Classic Crafting is enabled will display the Legacy design for the UI instead of the other more mouse/keyboard friendly variant.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/158768860/2c6d8e2d-1138-4322-9a93-aaa535fbc368

**Comment by Wilyicaro** [comment]
Do you know what the Stonecutter looks like with Classic Crafting enabled in LE? I don't have access to the PS4 Edition, so I left it like that.

**Comment by Chilly-roll** [comment]
I think the way they're wording this is.. they want classic crafting to affect the stonecutter screen by having the vanilla stonecutter screen in the legacy style through that option

**Comment by BuddarScotchy** [comment]
> I think the way they're wording this is.. they want classic crafting to affect the stonecutter screen by having the vanilla stonecutter screen in the legacy style through that option

Yeah that's what I mean, but if we want this to be as consistent with Legacy Edition, I'll have a picture of what the UI looks like tomorrow

**Comment by Wilyicaro** [comment]
If you're just having difficulty using Stone Cutter's interface with mouse/keyboard, you can press the X key and it will only show craftable recipes

**Comment by artorigusknight** [comment]
> Do you know what the Stonecutter looks like with Classic Crafting enabled in LE? I don't have access to the PS4 Edition, so I left it like that.

i have the ps4 legacy edition and its the same as legacy crafting gui even with classic crafting

**Comment by Wilyicaro** [comment]
Added in version 1.6, thanks for suggesting.
