### ISSUE TITLE
<Suggestion> Crouching while in elytra flight makes you raise your arm like superman

### ISSUE THREAD

**Issue by Narrowlegacy87** [Wilyicaro/Legacy-Minecraft#108]
In the original legacy console versions if you crouch while in elytra flight you raise your arm forward like superman, would be cool to add since it was a niche yet nice feature in the original game 
![2020-09-10_18](https://github.com/Wilyicaro/Legacy-Minecraft/assets/63093346/f307299e-ee21-4489-b513-94d242e0d036)

**Comment by S-N00B-1** [comment]
Wasn’t this added last month.

**Comment by AgentMindStorm** [comment]
This is already in the mod! It doesn't work if you're holding an item, like Legacy. Your hand has to be empty.

**Comment by Narrowlegacy87** [comment]
oh my bad, maybe I have a mod conflict then cause it wasn't working for me

sorry guys my bad
