### ISSUE TITLE
At 1080p and 900p, it has some artifacts with GUIs and at 1600x900, when set on auto or max GUI, it's slightly smaller compared to 1080p

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#110]
1080p artifacts:
![2024-02-21_19 39 13](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/dcf36309-c550-4c68-a7c9-289b960ddc4c)
![2024-02-21_19 38 35](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/c3134d07-1ae5-4950-af07-1b66959a4bfc)
![2024-02-21_19 39 07](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/a1aea459-2a8b-4c79-bef2-8837b0db926d)
![2024-02-21_19 40 10](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/3cfdf231-651d-4058-8b38-8e77b1f4d324)
![2024-02-21_19 40 17](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/ba18f034-be8d-4105-8202-626170a118ef)
![2024-02-21_19 39 00](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/30e4dfd3-5d44-4a7a-8e71-9ded0f750f66)
900p artifacts (This mostly affects texts)
![2024-02-21_19 41 43](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/d8f70d65-f77e-47c1-9241-2bdc8395d051)
![2024-02-21_19 42 04](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/66923ffc-60d2-4d6d-8677-4a1af00b929b)
![2024-02-21_19 42 38](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/09adcd49-cfce-4f66-8178-3fc3dc336cb4)

**Comment by Wilyicaro** [comment]
This is expected, because unlike the LE, the JE version is made to work on different devices with multiple resolutions, so there's no way to be perfect on all of them with the textures of the LE with different resolutions, as you may already know, but this also bothers me a lot.
I tried to solve this previously by applying blur, however other artifacts appeared between the tiles of the textures, much worse in my view, so I left it that way

**Comment by DanielMC101** [comment]
@Wilyicaro oh can u at least like fix the black pixel on the left of the crosshair?

**Comment by Wilyicaro** [comment]
Partially fixed in version 1.4.2

**Comment by Quartzmaven** [comment]
I'm on the latest version in 1080p. I still see the black pixel for me.

**Comment by Wilyicaro** [comment]
Strange, because for me there are no black pixels in 1080p (native), just a gray line at the bottom of the texture, when playing in fullscreen

**Comment by Wilyicaro** [comment]
Fully fixed in version 1.5, you will certainly need to change the Interface Resolution if you are still experiencing artifacts.
