### ISSUE TITLE
Can't find shields in crafting menu

### ISSUE THREAD

**Issue by Narrowlegacy87** [Wilyicaro/Legacy-Minecraft#111]
I don't think theres an option for them, that or I'm just really dumb. I've gotten iron and wood so I should have the recipe and I don't understand why in the crafting menu there isn't an option for shields. 

until this is fixed I guess I gotta switch to classic crafting

(Played on latest version)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/63093346/3a7f82a1-959c-485c-9ce4-56d93c6399f2)

**Comment by Wilyicaro** [comment]
No, you're certainly not dumb, I'm the one who's really forgetful.
It'll be added in the next version, thanks for reporting.

**Comment by Narrowlegacy87** [comment]
ah thanks lmao

by the way will the other crafting table tabs ever come to the mod? (like the fireworks one)
![Crafting_Table_LCE](https://github.com/Wilyicaro/Legacy-Minecraft/assets/63093346/330b8e12-6734-4131-bc85-3232d9c5d0e9)
