### ISSUE TITLE
Legacy Crafting doesn't work on servers

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#112]
I assume this is probably intentional, but regardless.. you straight up can't use the legacy crafting interface if you go on a multiplayer server that isn't running the mod, meaning Classic Crafting is mandatory for multiplayer as a result.

**Comment by Wilyicaro** [comment]
This is impossible to work in servers without the mod, sorry, but 2 versions of the same screen(Classic Crafting) with different functions, and auto-crafting are impossible without modding the server-side.
