### ISSUE TITLE
Suggestion - Controller Tooltips

### ISSUE THREAD

**Issue by Migheyy** [Wilyicaro/Legacy-Minecraft#113]
It would be nice to have the controller tooltips from legacy

Made this video to show what it could look like for keyboard and mouse

https://github.com/Wilyicaro/Legacy-Minecraft/assets/119352011/781cdcb7-2f74-42e8-94af-f01369054f02

**Comment by G01dY05h1** [comment]
How did you get the hud to act like that? Is it a separate mod or am I missing something?

**Comment by Wilyicaro** [comment]
How have I not closed this issue yet? Thanks for suggesting and inspiring me to add this in version 1.5

**Comment by Migheyy** [comment]
> How have I not closed this issue yet? Thanks for suggesting and inspiring me to add this in version 1.5

no problem, i'm really liking how this mod is turning out
