### ISSUE TITLE
Lantern not in crafting menu

### ISSUE THREAD

**Issue by Narrowlegacy87** [Wilyicaro/Legacy-Minecraft#115]
Can't locate the lantern in the crafting menu, the lights section (scrolling on the torch) does not include the lantern or soul lantern

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/63093346/9012382d-10b5-4c3f-9d04-49390338824d)

Unless its somewhere else

**Comment by Narrowlegacy87** [comment]
there is also no chains recipe

**Comment by Wilyicaro** [comment]
Added in version 1.4.3, thanks for reporting.
