### ISSUE TITLE
(Suggestion) Expand stonecutter categories

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#116]
There's a ton of blocks you can make with the stonecutter, yet so few tabs to store them. This leads to there being 20+ blocks in one tab. I suggest making more sections for more specific items such as bricks, chiseled items, or smooth items.

**Comment by Wilyicaro** [comment]
Press X and you will be able to filter only the craftable blocks, this might help while I don't update the mod

**Comment by Wilyicaro** [comment]
I would say that it is a bit annoying to do this for the sake of compatibility with other mods, as there are no tags for these mentioned blocks, so it would have to be done manually for each one present in vanilla, and those from other mods would still be "messy"  in another group, so I will close this.
If you still feel the need for this, please suggest it again on the Legacy4J discord server, as it's a better and higher priority place for this
