### ISSUE TITLE
Feature Request - Scrolling makes arrows fade for a bit

### ISSUE THREAD

**Issue by Pedro270707** [Wilyicaro/Legacy-Minecraft#12]
Scrolling in LCE makes these arrows fade for a bit. That's valid for every menu, including the Creative inventory.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/89267077/fc63031b-6e67-4acb-a12b-0480d882b682)

**Comment by Wilyicaro** [comment]
Thanks for reporting, it's already a planned addition
