### ISSUE TITLE
<Suggestion> Add a way to access the regular resource pack and mod menu in the UI

### ISSUE THREAD

**Issue by Narrowlegacy87** [Wilyicaro/Legacy-Minecraft#120]
The problem with the current UI is that you can't config your mods or properly config your resource packs (Its difficult to put one over the other so maybe keep it the same on world creation but in the actual settings give us the option to change things)

Also sodium options get removed from the settings when this mod is active so there should be a way to access them (as it also makes it hard to enable shaders)

**Comment by Wilyicaro** [comment]
There is already a way to access the "regular" resource pack menu, shift-click the resource pack selector in the Graphics section or on the Load/Create World screen.
About the mod menu, not if you are referring to the fact that it is not compatible with most configuration screens, but the Mods screen can be accessed through the Game Options section
Regarding the sodium options, this is a compatibility issue, I will probably focus on this in future versions
