### ISSUE TITLE
slider_highlighted not showing

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#123]
As title says. 

The slider's highlighted sprite doesn't show up, the mod only uses slider.png regardless of being highlighted or not.

**Comment by Wilyicaro** [comment]
![2024-02-28_19 38 04](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/28ff7f9a-0608-44ce-b536-66dfdb7542d8)
Not quite true, the slider highlighted texture is only used when focusing the slider with arrow navigation, or obviously with a controller now.
