### ISSUE TITLE
Various Controller Bugs in Legacy4J 1.4.3a

### ISSUE THREAD

**Issue by BuddarScotchy** [Wilyicaro/Legacy-Minecraft#124]
https://youtu.be/HbkaR_uwpTQ

I've included a video I compiled together of quite a few little bugs within the latest release. I think these issues could be ironed out with time, but I also believe that specific compatibility with other controller mods could be beneficial for players who enjoy having options. 

MidnightControls has some nice customization options honestly (although Controllable feels more like Legacy). Maybe reaching out to those creators could result in some cross development making it better for everyone ^o^

**Comment by BuddarScotchy** [comment]
Just stumbled across a new one, if you just play the game normally. Occasionally is hides the HUD. I have know idea why it keeps doing that.

**Comment by G01dY05h1** [comment]
> Just stumbled across a new one, if you just play the game normally. Occasionally it hides the HUD. I have know idea why it keeps doing that.

It might have something to do with pressing B iirc

**Comment by BuddarScotchy** [comment]
> > Just stumbled across a new one, if you just play the game normally. Occasionally it hides the HUD. I have know idea why it keeps doing that.
> 
> It might have something to do with pressing B iirc

You see, I'd be willing to agree with that... if it didn't also happen when playing with just mouse and keyboard as well.

**Comment by DanielMC101** [comment]
About small black line on left of the crosshair, and on the crafting interface, it only affects when you're on 1080p, and when in 1440p and 4K, there's no issues

**Comment by Wilyicaro** [comment]
> https://youtu.be/HbkaR_uwpTQ
> 
> I've included a video I compiled together of quite a few little bugs within the latest release. I think these issues could be ironed out with time, but I also believe that specific compatibility with other controller mods could be beneficial for players who enjoy having options.
> 
> MidnightControls has some nice customization options honestly (although Controllable feels more like Legacy). Maybe reaching out to those creators could result in some cross development making it better for everyone ^o^

Thanks for making this video, this was very helpful, I think a lot of the issues you pointed out have been fixed in version 1.4.3b, and about any controller options, like dead zone, will only be added when I deal with the tooltips of the controller, because of the mapping of the controller buttons, which obviously needs the button sprite.
Regarding the HUD hiding, I have no idea what could be causing this, as it has never happened to me

**Comment by G01dY05h1** [comment]
> > https://youtu.be/HbkaR_uwpTQ
> > I've included a video I compiled together of quite a few little bugs within the latest release. I think these issues could be ironed out with time, but I also believe that specific compatibility with other controller mods could be beneficial for players who enjoy having options.
> > MidnightControls has some nice customization options honestly (although Controllable feels more like Legacy). Maybe reaching out to those creators could result in some cross development making it better for everyone ^o^
> 
> Thanks for making this video, this was very helpful, I think a lot of the issues you pointed out have been fixed in version 1.4.3b, and about any controller options, like dead zone, will only be added when I deal with the tooltips of the controller, because of the mapping of the controller buttons, which obviously needs the button sprite. Regarding the HUD hiding, I have no idea what could be causing this, as it has never happened to me

for me, pushing "B" does not drop my item, instead, it turns on the cinematic camera (which doesn't affect the controller's camera) it also zooms, but that's because I have a zoom mod

**Comment by DanielMC101** [comment]
@Wilyicaro 
So the cursor jumping to the opposite at the edge of the grid, doesn't happen on PS4 Edition, and I've tried playing xbox 360 edition myself on Xenia emulator, and it only does that sometimes, it could just be a bug on that version.
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/920eb60c-209f-44a4-8353-7cad646fb3fe

**Comment by Wilyicaro** [comment]
I'm almost sure that it was something intentional in the version corresponding to the latest Xbox 360, just like in the mod, there's no way it could be a bug due to having to manually define what each controller input should do, or make different inputs do the same thing. function, which is not the case
