### ISSUE TITLE
Crafting table: Shield location, missing items.

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#128]
The shield should be to the right of the sword, left of the bucket.

The composter should be above the bucket

The crossbow should be below the regular bow, 
followed by the arrow, 
followed by "Arrow of splashing", 
followed by "Arrow of Night Vision Night Vision (0:22)", 
followed by "Arrow of Invisibility Invisibility (0:22)", 
followed by "Arrow of Leaping Jump Boost (0:22)", 
followed by "Arrow of Fire Resistance Fire Resistance (0:22)", 
followed by "Arrow of Swiftness Speed (0:22)", 
followed by "Arrow of Slowness Slowness (0:11)", 
followed by "Arrow of Water Breathing (0:22)", 
followed by "Arrow of Healing Instant Health", 
followed by "Arrow of Harming Instant Damage", 
followed by "Arrow of Poison Poison (0:05)", 
followed by "Arrow of Regeneration Regeneration (0:05)", 
followed by "Arrow of Strength Strength (0:22)", 
followed by "Arrow of Weakness Weakness (0:11)", 
followed by "Arrow of Luck Luck (0:37)", 
followed by "Arrow of the Turtle Master Slowness IV (0:02)", 
followed by "Arrow of Slow Falling Slow Falling (0:11)", 
(There is a lot omg)
followed by "Arrow of Night Vision Night Vision (1:00)", 
followed by "Arrow of Invisibility Invisibility (1:00)",
followed by "Arrow of Leaping Jump Boost (1:00)", 
followed by "Arrow of Fire Resistance Fire Resistance (1:00)", 
followed by "Arrow of Swiftness Speed (1:00)", 
followed by "Arrow of Slowness Slowness (0:30)", 
followed by "Arrow of Water Breathing (1:00)", 
followed by "Arrow of Poison Poison (0:15)", 
followed by "Arrow of Regeneration Regeneration (0:15)", 
followed by "Arrow of Strength Strength (1:00)", 
followed by "Arrow of Weakness Weakness (0:30)",
followed by "Arrow of the Turtle Master Slowness IV (0:05)", 
followed by "Arrow of Decay Wither II (0:05)", 
followed by "Arrow of Slow Falling Slow Falling (0:30)", 
followed by "Arrow of Leaping Jump Boost II (0:11)", 
followed by "Arrow of Swiftness Speed II (0:11)", 
followed by "Arrow of Healing Instant Health II", 
followed by "Arrow of Harming Instant Damage II", 
followed by "Arrow of Poison Poison II (0:02)", 
followed by "Arrow of Regeneration Regeneration II (0:02)", 
followed by "Arrow of Strength Strength II (0:11)", 
followed by "Arrow of the Turtle Master Slowness VI (0:02)", 

End Rod should be left of the book in decorations (or in the case of the mod, to the left of the paper)

**Comment by ShatterdPotato** [comment]
I am curious to see how the mod creator incorporates the tipped arrows, because since the crafting_tab_listing.json is using the formats of the loot_table data directory and jsons. Each tipped arrow does not have thier own json file in loot_tables, but instead all the arrows are condensed into one file called tipped_arrows.json, which doesn't work if you place it in the crafting json(I tried). It is a similar case for the shulker boxes.

**Comment by G01dY05h1** [comment]
> I am curious to see how the mod creator incorporates the tipped arrows, because since the crafting_tab_listing.json is using the formats of the loot_table data directory and jsons. Each tipped arrow does not have thier own json file in loot_tables, but instead all the arrows are condensed into one file called tipped_arrows.json, which doesn't work if you place it in the crafting json(I tried). It is a similar case for the shulker boxes.

Perhaps they can just add them to the loot tables?

**Comment by ShatterdPotato** [comment]
> > I am curious to see how the mod creator incorporates the tipped arrows, because since the crafting_tab_listing.json is using the formats of the loot_table data directory and jsons. Each tipped arrow does not have thier own json file in loot_tables, but instead all the arrows are condensed into one file called tipped_arrows.json, which doesn't work if you place it in the crafting json(I tried). It is a similar case for the shulker boxes.
> 
> 
> 
> Perhaps they can just add them to the loot tables?

Maybe, but there probably is a more code and time efficient way. Because then he would also have to create all those again for shulkee boxes as well😅

**Comment by Wilyicaro** [comment]
Added in version 1.4.2b, I changed the End Rod position because the Decoration category will probably need more space for other recipe groups.
Regarding the custom recipes, like the tipped_arrows, I'm working on a fallback, unfortunately it won't be customizable by resource packs.

**Comment by G01dY05h1** [comment]
> Added in version 1.4.3b, I changed the End Rod position because the Decoration category will probably need more space for other recipe groups. Regarding the custom recipes, like the tipped_arrows, I'm working on a fallback, unfortunately it won't be customizable by resource packs.

Seems like mossy cobblestone is not in the crafting table either

**Comment by G01dY05h1** [comment]
> Added in version 1.4.3b, I changed the End Rod position because the Decoration category will probably need more space for other recipe groups. Regarding the custom recipes, like the tipped_arrows, I'm working on a fallback, unfortunately it won't be customizable by resource packs.

Would the new components coming in the latest snapshot be able to fix that?

**Comment by Wilyicaro** [comment]
> > Added in version 1.4.3b, I changed the End Rod position because the Decoration category will probably need more space for other recipe groups. Regarding the custom recipes, like the tipped_arrows, I'm working on a fallback, unfortunately it won't be customizable by resource packs.
> 
> Would the new components coming in the latest snapshot be able to fix that?

Probably yes
