### ISSUE TITLE
Suggestion: Discord Server

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#129]
A basic discord server for people who use this mod.

Maybe even a Minecraft server with the largest legacy console world size with a world border and all.

This is less of a mod suggestion, just thought it would be nice for there to be an official server by the mod creator

**Comment by S-N00B-1** [comment]
#54

**Comment by Wilyicaro** [comment]
I'm working on it
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/cdb40b21-6d73-40dc-bcad-f631cdbc7acc)
