### ISSUE TITLE
Feature Request - Reorganize Creative tabs

### ISSUE THREAD

**Issue by Pedro270707** [Wilyicaro/Legacy-Minecraft#13]
You can copy the LCE-UI organization: https://github.com/Pedro270707/LCE-UI/tree/1.20/src/main/resources/assets/lceui/creative_tabs/tabs
I'd also like it if a tab was created for each mod, or at least one tab for items that are currently being put in Miscellaneous.

**Comment by Chilly-roll** [comment]
I second this; LCE's organization in creative is very distinct and with the creative menu being functional it's the only thing it really lacks. Mod organization in creative is also very nice to have!

**Comment by Wilyicaro** [comment]
This actual organization is temporary, and is one of the reason I added Legacy Creative Tab option

**Comment by Wilyicaro** [comment]
Added in 1.2 version.
