### ISSUE TITLE
World fails to load when opening a world while using a controller

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#132]
World seems to fail to load when opening a world while using a controller

(Tested using a DualSense with the free version of DualSenseX)

**Comment by Wilyicaro** [comment]
What version of the mod are you using? It's probably unrelated, as I can load the world normally using the Xbox One controller.

**Comment by G01dY05h1** [comment]
> What version of the mod are you using? It's probably unrelated, as I can load the world normally using the Xbox One controller.

I was actually using the last update so it was probably my bad ~~you update so quickly sometimes, it's hard to know when a new update is out lol~~

**Comment by G01dY05h1** [comment]
> > What version of the mod are you using? It's probably unrelated, as I can load the world normally using the Xbox One controller.
> 
> I was actually using the last update so it was probably my bad ~you update so quickly sometimes, it's hard to know when a new update is out lol~

Actually, the issue still occurs after the update

**Comment by G01dY05h1** [comment]
Luckily, I can get around it by leaving DualSenceX open, opening the game, closing DSX, loading a world, and reopening DSX and it works fine until I need to load a world again

**Comment by Wilyicaro** [comment]
I actually wanted to ask the modloader and the version of the game used

**Comment by G01dY05h1** [comment]
> I actually wanted to ask the modloader and the version of the game used

I am using Modrinth, Minecraft 1.20.4 with Fabric

**Comment by G01dY05h1** [comment]
> I actually wanted to ask the modloader and the version of the game used

I mindlessly loaded my world again using the controller and it worked fine this time, the only thing that changed is I charged my controller more
