### ISSUE TITLE
"What's this?" missing features

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#133]
Iron ingot, Cobblestone Stairs, Most Birch items (possibly other woods too), tools, and music discs do not appear to have a "What's This?" pop up (tested by pressing the "What's this?" Button)

You cannot use "What's This?" again until after the popup goes away, unlike console edition where you can instantly swap between "What's This?" popups

**Comment by Wilyicaro** [comment]
Added in version 1.4.4
