### ISSUE TITLE
Right Joystick (or Look movement) is completely choppy and broken.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#134]
Others worked fine, but the right joystick is really really stuttery and glitchy. I've never had the issue on MidnightControls and Controlify.
I trimmed the video to the part where there's an exact issue. The cut thing is in the game itself.
I tried that on Steam Deck as well, same thing.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/9728d654-7288-4666-95bd-9cd28e70fda2

**Controller used:** Logitech F310
Launcher: Modrinth
FPS: 60 (120 as Max Framerate)
VSync: On
Steps reproduced:

1. Use a 1080p 60FPS monitor. Or just set the resolution and refresh rate.
3. Load the game with the mod installed.
4. Connect controller.
5. Open/create a new world.
7. When in-game, move the right joystick.

**Comment by Cloud5474** [comment]
Hm, this didn’t happen to me

**Comment by Quartzmaven** [comment]
in 1080p?

**Comment by Wilyicaro** [comment]
Fixed in version 1.4.4, thanks for reporting.
