### ISSUE TITLE
Crash at startup in 1.20.2 (Forge and Fabric)

### ISSUE THREAD

**Issue by BestChoripans** [Wilyicaro/Legacy-Minecraft#136]
With fabric and the mods ("Fabric API", "Legacy4J 1.20.2-1.4.3b" and Architectury API for Fabric") it simply does not start and shows a crash report.

Crash report with Fabric:
[crash-2024-03-02_11.57.03-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14469803/crash-2024-03-02_11.57.03-client.txt)

And with Forge 1.20.2 it crashes also with the mods ("Legacy4J 1.20.2-1.4.3b" and "Architectury API for Forge").

Crash report with Forge:
[crash-2024-03-02_12.01.00-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14469809/crash-2024-03-02_12.01.00-client.txt)

**Comment by Wilyicaro** [comment]
Thanks for reporting, it'll be fixed in the next version.
