### ISSUE TITLE
When moving cursor with a stick, it goes into slot when it's not supposed to, and the cursor doesn't function when customizing superflat.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#138]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/8cba4b0f-8f0d-48d1-81ca-d645986650c7

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/3c23c547-4fc3-4b54-b784-90cffe092de9

**Comment by Wilyicaro** [comment]
Fixed in version 1.4.4
