### ISSUE TITLE
Feature Request - Opening a menu plays the CLICK_STEREO sound.

### ISSUE THREAD

**Issue by Pedro270707** [Wilyicaro/Legacy-Minecraft#14]
This is the sound: https://github.com/Pedro270707/LCE-UI/blob/1.20/src/main/resources/assets/lceui/sounds/click_stereo.ogg

**Comment by Wilyicaro** [comment]
Thanks for the sound, but I think that it's almost the same as what I'm using
It'll be added in the next version
