### ISSUE TITLE
Villager Trading on multiplayers servers causes the game to crash

### ISSUE THREAD

**Issue by HollyBlocky** [Wilyicaro/Legacy-Minecraft#140]
I had a friend using this mod on his PC and we were playing on another friend's server while he was using it. Apparently, according to him, trying to trade with villagers with only this mod causes problems (whether it's a complete game crash or a kick-to-main-menu one, I'm not sure). All in all, he wasn't able to do villager trading while having this mod installed on his client.

**Comment by Wilyicaro** [comment]
When you only have Legacy4J on the client, you cannot auto-trade with merchants( villagers and wandering traders), I didn't know about this crash, I probably can't fix it, but you can still trade with villagers by manually placing the item in the slot (the fake item will dissapear when you place)

**Comment by DanielMC101** [comment]
This actually happened to me while playing on re-console server
