### ISSUE TITLE
Going on boat with controller feels very rough

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#141]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/6e8e7430-3a07-481a-8028-3a356e5d61ed

**Comment by bor-real** [comment]
It was like this in the original console edition. I do agree that it should be changed.

**Comment by Cloud5474** [comment]
> It was like this in the original console edition. I do agree that it should be optionally changed.

Nah It's the fact that when you hold forward it turns for some reason

**Comment by Wilyicaro** [comment]
Fixed in version 1.5, thanks for reporting.
