### ISSUE TITLE
Pushing B doesn't drop an item, instead in enters cinematic camera

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#144]

**Comment by Wilyicaro** [comment]
Obviously I didn't purposely put the B button to perform this function, it's working correctly in normal situations, this is some kind of incompatibility with Steam from what I know

**Comment by G01dY05h1** [comment]
> Obviously I didn't purposely put the B button to perform this function, it's working correctly in normal situations, this is some kind of incompatibility with Steam from what I know

I didn't have steam open when this happens

**Comment by Wilyicaro** [comment]
So it's the controller mapping or other software opened
