### ISSUE TITLE
Crafting UI and Nametags issues

### ISSUE THREAD

**Issue by Excalibart** [Wilyicaro/Legacy-Minecraft#145]
First I just wanna say I really appreciate your work on this mod, It is amazing.

I have noticed some weird issues with the Nametags and crafting 
First I realized I am unable to access the legacy crafting interface when connecting to a server. However, it works perfectly in single-player. And when I open the legacy crafting UI I notice a good amount of frame drops. 

The issue with nametags is that when multiple people are in view they all bridge off and connect to each other as seen in the photo attached.
![2024-03-03_13 36 54](https://github.com/Wilyicaro/Legacy-Minecraft/assets/86888161/a08f9b4a-67d5-4120-be83-96a305341794)

And Finally, I have a question. How do you plan to add custom skin support? Would it be only visible to those with the mod? or would you be adapting support for custom skin mods? Or even dumping legacy skinpacks into the game's installation.

**Comment by Wilyicaro** [comment]
Unfortunately, this is a duplicated "issue", as you can see in #112 and an Issue I can no longer see, which I explained that this is a graphics artifacts with some video card drivers implementations, so I can't fix it for now without having this problem.
About the custom skin support, it'll be probably like in Bedrock before the skin customizer, you will be able to change your skin with the default skin packs available in the mod or select from a file (there'll be a way to add more skin packs with resource packs).
