### ISSUE TITLE
On villager/wandering trader UI, it's supposed to display item names, and it's not supposed to play navigating UI sounds

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#146]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/1d818168-3282-4890-bd3c-6bdb325c734a

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/75baffd8-c2e5-43aa-bd5c-595aaaeb01b2

It's also missing the level indicator as you can see here.

**Comment by Cloud5474** [comment]
Since you seem to have the PS4 edition, could you post the loom and cartography table gui? I want to see it

**Comment by Wilyicaro** [comment]
Added the item tooltips when using arrow navigation/controller, but I kept the navigation sounds for the reasons I already explain in the dc, thanks for reporting.
