### ISSUE TITLE
Interface opacity functionality is inaccurate

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#148]
When interface opacity is set to 80% or below, it should only be faded in to 80% instead of 100% when moving the hotbar. Additionally, it's supposed to be faded in when moving over an empty hotbar instead of being strict only for items. I believe it's supposed to take like exactly 5.9 seconds for the opacity to fade out after moving the hotbar. 
(Btw the controller tooltips is also part of the interface opacity just so you know)

https://streamable.com/0jne9c

**Comment by Wilyicaro** [comment]
Fixed in version 1.5, thanks for reporting.
