### ISSUE TITLE
Some controller optimization

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#149]
I have made a list of some suggestions to improve controller gameplay:

-In LE, a toggle sneak was put because holding sneak while looking around would be extremely difficult. So to replicate this method you would have to turn on the "Toggle Sneak" in the settings. However, doing this makes it so that while flying in Creative Mode, sneaking to go down just constantly send you down until you re-press it, which isn't like LE and personally also a bit worse than holding to go down. Potentially making a feature where while on the ground sneak set to is toggle-on while flying is hold sneak, which would be more accurate and easier to use.

-Another thing is in the Creative Inventory Screen, in LE clicking with A or Y (In Xbox, other controllers have their respective buttons) would give a single or stack of that block/item respectfully, and immediately send it to the hot bar, However doing it here instead gives it to the cursor, making you have to drag it back every time, which can be a bit repetitive. I understand that this is because of the fact that it is mouse and controller inclusive so it gives it to the cursor as it does in java, so perhaps there could be a detection of input which could then either give it to you by hand or send it to hot bar upon clicking immediately.

-In addition, LE also had two methods of maneuvering, the "free roam" joystick method and the d-pad grid system. Both of these are already pretty seamlessly added, however some tweaking could be made to make it more alike to LE. First, while moving around in the "free roam" joystick mode, there's a little grid snap that occurs, which from what I can recall, didn't occur or at least not to the extent that it does here, so maybe smoothening the snap to either happen when the cursor is closer to the center of the inventory slot or not to happen at all would make moving through the inventory better and quicker. Second, in the grid d-pad system in LE, any input from the d-pad whilst in an inventory screen would immediately send the cursor to the closest inventory slot, regardless of location, which is missing, so adding it would be nice.

The last two things I want to add to this long list of requests is first, better sprint flying. In LE, sprint flying would also make it so you would also change elevation(looking slightly upwards would also fly you up whilst moving and vise versa). And second, in the settings menu, the controller seems to scroll slowly through the bar if you want to change a setting like the Hud opacity or anything that requires scrolling through a bar. These are all some good QOL changes but in the end its up to you want you wish to add, so you don't have to add all of these👍

**Comment by Wilyicaro** [comment]
Regarding the third suggestion, the D-Pad movement is as intended, at least in the Xbox 360 Edition, the D-Pad only sends the pointer to the slot in its direction (before confirming this I had done it the way you commented) if the pointer is hovering the slot, and the joystick also has a "grid snapping", but not to the sensivity that is occuring now, so it may be adjusted

**Comment by G01dY05h1** [comment]
> Regarding the third suggestion, the D-Pad movement is as intended, at least in the last Xbox 360 Edition update, the D-Pad only sends the pointer to the slot in its direction (before confirming this I had done it the way you commented) if the pointer is already hovering a slot, and the joystick also has a "grid snapping", but its quick slot movement, like using the D-Pad, isn't accurate with LE sensivity, so it must be adjusted

When using the stick the snapping doesn't occur until the moment you release the stick. If you keep moving the stick, it should not stop at all.

**Comment by Wilyicaro** [comment]
> > Regarding the third suggestion, the D-Pad movement is as intended, at least in the last Xbox 360 Edition update, the D-Pad only sends the pointer to the slot in its direction (before confirming this I had done it the way you commented) if the pointer is already hovering a slot, and the joystick also has a "grid snapping", but its quick slot movement, like using the D-Pad, isn't accurate with LE sensivity, so it must be adjusted
> 
> When using the stick the snapping doesn't occur until the moment you release the stick. If you keep moving the stick, it should not stop at all.

That's what I'm talking about, in LE there is only this "free movement" in the slots if you have the analog stick close to maximum, if you have it slowly, it will resemble using the D-Pad but smoother, and I will add this behavior in the next version

**Comment by ShatterdPotato** [comment]
So automatic d-pad snapping to the nearest inventory slot when the cursor is outside the inventory area will not be added, or am I confused here?

**Comment by Wilyicaro** [comment]
> So automatic d-pad snapping to the nearest inventory slot when the cursor is outside the inventory area will not be added, or am I confused here?

Probably not, as I said, at least in the last version of Xbox 360 Edition this doesn't exist, only if you show me this working on PS4 Edition

**Comment by ShatterdPotato** [comment]
> > So automatic d-pad snapping to the nearest inventory slot when the cursor is outside the inventory area will not be added, or am I confused here?
> 
> 
> 
> Probably not, as I said, at least in the last version of Xbox 360 Edition this doesn't exist, only if you show me this working on PS4 Edition

I remember this working on ps4 edition when I played it last 3-4 months ago, but I lost the disc so I can't show proof really😅

**Comment by Wilyicaro** [comment]
Also, like I said, it's not that I didn't want to add this, but it needs to be as close to LE as possible, to have an idea for me to add this function, I just need to change 1 line of code

**Comment by ShatterdPotato** [comment]
I understand, I will try to show proof if I find any.

**Comment by Wilyicaro** [comment]
> > So automatic d-pad snapping to the nearest inventory slot when the cursor is outside the inventory area will not be added, or am I confused here?
> 
> I remembered this too, but I actually tested it and it's not true.

Literally definition of herd effect, even I thought that lol

**Comment by ShatterdPotato** [comment]
So it really doesnt exist??
Wow, Mandela Effect si real.

**Comment by G01dY05h1** [comment]
> > > So automatic d-pad snapping to the nearest inventory slot when the cursor is outside the inventory area will not be added, or am I confused here?
> 
> > 
> 
> > I remembered this too, but I actually tested it and it's not true.
> 
> 
> 
> Literally definition of mandela effect, even I thought that lol

For a moment, I thought using the d-pad in the inventory was supposed to make the menu navigation sound. But that doesn't happen either.

**Comment by G01dY05h1** [comment]
> > > Regarding the third suggestion, the D-Pad movement is as intended, at least in the last Xbox 360 Edition update, the D-Pad only sends the pointer to the slot in its direction (before confirming this I had done it the way you commented) if the pointer is already hovering a slot, and the joystick also has a "grid snapping", but its quick slot movement, like using the D-Pad, isn't accurate with LE sensivity, so it must be adjusted
> > 
> > 
> > When using the stick the snapping doesn't occur until the moment you release the stick. If you keep moving the stick, it should not stop at all.
> 
> That's what I'm talking about, in LE there is only this "free movement" in the slots if you have the analog stick close to maximum, if you have it slowly, it will resemble using the D-Pad but smoother, and I will add this behavior in the next version

Just triple checked this and I figured out what you are talking about.

When holding the stick in any direction at any amount, it's semi-free movement, it doesn't snap to the grid, but regardless of speed it does sort of lock into 8 directions.

It only actually snaps to the grid when you let go of the stick, which is why simply flicking the stick works, you're moving just enough for it to lock onto the grid space in the direction you're heading.

You might've already figured this out by now, but it's good info to know just in case,

**Comment by Wilyicaro** [comment]
Basically all the "optimizations" mentioned here have already been added, obviously it is not identical, as it is impossible, but throughout the version I will make changes according to feedback. 
Only the first one, which isn't even something specifically related to the controller, hasn't been added but is planned for version 1.6
