### ISSUE TITLE
Title screen panorama doesn't get affected by resource packs

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#15]
As title says. If one sets up a custom panorama to replace the built-in TU69 panorama in a resource pack, it gets ignored by the game and continues to show the TU69 panorama despite there being a replacement provided by the resource pack.

**Comment by Wilyicaro** [comment]
It's a vanilla problem and my mistake in the panorama path, I wrote "/" at the start, that is invalid, but still the texture loads normally, and causes this problem with resource packs.
Whatever, it will be solved in the next version
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/7b576d5e-d849-43f9-a696-b2660886aaa7)
