### ISSUE TITLE
Plenty of missing crafting recipes

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#152]
So far the missing crafting recipes I've found are:
Brush
Soul torch
Tipped arrows
Beehive
Recovery compass
Spyglass
There could be more, so here's website that could help you find all of the missing crafting recipes:
https://www.minecraft-crafting.net/

**Comment by Wilyicaro** [comment]
Added in version 1.5, thanks for reporting.
