### ISSUE TITLE
Cobweb hint is outdated (I think?)

### ISSUE THREAD

**Issue by SnowyBoi64** [Wilyicaro/Legacy-Minecraft#154]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/80140847/2fe20944-ff7d-46e2-b032-ca9fa03e9535)
You can collect cobwebs with shears or a silk touch tool now (I believe it used to only be silk touch shears but that was changed a while ago), breaking them with tnt or a sword drops string.

**Comment by SnowyBoi64** [comment]
Could maybe be referring to collecting them with shears and then breaking them with a sword to collect string?

**Comment by SnowyBoi64** [comment]
Also another small thing, the enchanting_table in the crafting_tab_listing is incorrectly put as enchantment_table, making it not appear

**Comment by Wilyicaro** [comment]
Updated in version 1.5, thanks for reporting.
