### ISSUE TITLE
Game crashes when attempting to trade with villagers

### ISSUE THREAD

**Issue by Traynack** [Wilyicaro/Legacy-Minecraft#155]
### Expected Behavior
Be able to trade with villagers in desktop mode
### Current Behavior
Game crashes when attempting to trade with villagers and (assuming) wandering traders
### Steps to Reproduce
1. Summon villager
2. Trade with villager by selecting its trade and putting trade items into its inventory with the mouse.
3. Game crashes
### Version
`1.20.4-1.4.4+fabric`
### Mods Used & Game Version
Game Version: `1.20.4`
#### Modlist
`Architectuary API 11.1.17+fabric`
`Fabric API 0.96.4+1.20.4`
`Legacy4J 1.20.4-1.4.4+fabric`

**Comment by Wilyicaro** [comment]
**Step** 2-1. Use Legacy4J on a server without it (hypothesis)
You are probably trying auto trade on a server without the mod, my game never crashed when using the mod in a singleplayer world and not even on a dedicated server with Legacy4J. You can also manually trade with the villager/merchant as seen in #140

**Comment by Traynack** [comment]
I initially experienced the problem in multiplayer (through manually trying to trade, because auto-trading doesn't work on multiplayer on servers without the mod. I then tried it in singleplayer to see if I have the same issue. The crash only happens when trying to manually trade (putting the item in the slot). See video for more information.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/36650344/8b291c7a-c043-4200-b5db-efbc112e7315

I can provide crash logs and game logs if you can't reproduce the glitch on your end, if those would help :)
