### ISSUE TITLE
[Bug?] A server's MOTD can get cut off if it's long enough.

### ISSUE THREAD

**Issue by 5imGitHub** [Wilyicaro/Legacy-Minecraft#156]
Here's what the MOTD normally looks like in vanilla:
![vanilla](https://github.com/Wilyicaro/Legacy-Minecraft/assets/123900464/7e2833a3-f565-4e8b-bd8c-0e139cb08062)
While this is what the MOTD looks like with Legacy4J:
![withLegacy4J](https://github.com/Wilyicaro/Legacy-Minecraft/assets/123900464/05581962-8b90-4fee-a6c1-43b4eee17871)

The MOTDs with Legacy4J looks fine on most servers, but MCC Island's MOTD doesn't look great because it's missing the entire MOTD, while for Hideaway it's missing the light gray-coloured "1.20.1" part.

**Comment by Wilyicaro** [comment]
It wasn't necessarily a bug, but rather the fact that MOTD wasn't made for a button with a smaller width, anyway this was fixed in version 1.5, thanks for reporting.
