### ISSUE TITLE
Feature Request - Mod Menu Support

### ISSUE THREAD

**Issue by SnowyBoi64** [Wilyicaro/Legacy-Minecraft#16]
Maybe allow the mod menu button to appear on the pause menu if mod menu for fabric is installed so you are able to still access config menus. 

An actual legacy console styled mod menu would be cool but that sounds like something for the farther future.

**Comment by Wilyicaro** [comment]
An mod screen in legacy edition style is already planned, probably it is easier than add the mod menu support
