### ISSUE TITLE
Game crashes if gravel falls

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#160]
Make any gravel fall at all and the gravel will then crash the game.

Other mods were enabled during testing, but disabling them did not correct the issue, only disabling this one did

**Comment by Wilyicaro** [comment]
This issue is known, and you would know if you were on the [Legacy4J Discord](https://discord.gg/CVas58uPyb) server, this issue is simple and will be resolved in the next update, it has not been fixed yet due to features not being completed in the version when I discovered this issue.

**Comment by DanielMC101** [comment]
It also affects sand, and concrete powder, pretty much any falling block.
