### ISSUE TITLE
Controller input unavailable on certain screens

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#162]
On certain screens, the controller doesn't give any input, and since mouse input in the settings gets disabled when a controller is active, you are essentially softlocked unless you quit or turn off bluetooth which disconnects the controller. The two screens where ive seen this happen is book  and quill/ lectern screen and mod config screens that come with the Mod Menu mod(I understand you are creating a native mod menu for the mod, so this is lower priority).

I also reccomend implementing a way to temporarily disable the controller state to avoid further soft locks in other screens that haven't been documented.

**Comment by Wilyicaro** [comment]
It has not been completely fixed, but I will work on fixes for these screens that present these problems, for now you can activate the cursor by associating a button or key with this mapping, which will workaround most of these
