### ISSUE TITLE
Can't sprint in creative flight on controller or keyboard

### ISSUE THREAD

**Issue by NeoEclipsis** [Wilyicaro/Legacy-Minecraft#163]

**Comment by Wilyicaro** [comment]
This is not a problem with Legacy4J, it's a parity to be made with the Legacy Edition, as this is not present in the Java Edition when running normally, you need to press the key binding/ button mapping defined to run, by default set as control in the keyboard.
If you want to suggest adding this, in this case it is already a planned addition as you can see on the mod page, I give preference to the suggestions made on the Legacy4J Discord server https://discord.gg/CVas58uPyb
