### ISSUE TITLE
Suggestion: Add the texture packs from 360

### ISSUE THREAD

**Issue by AverageFNFFan** [Wilyicaro/Legacy-Minecraft#164]
You know like the plastic texture pack, medieval, and those festive worlds and everything? If its possible can you add those in the game?

**Comment by Wilyicaro** [comment]
I could, but for copyright reasons I won't risk including it in the mod, plus it would significantly increase the size of the mod.
However, you can find users on the Legacy4J discord server who are redoing Legacy Edition textures and mashups
https://discord.gg/CVas58uPyb
