### ISSUE TITLE
unbinding controller buttons

### ISSUE THREAD

**Issue by Sylvorus** [Wilyicaro/Legacy-Minecraft#165]
Any way to unbind a controller button? When I bind a button wrong to another mod, I just can't unbind it so for example every time I jump it opens up the Iris Shaders config menu.

**Comment by Wilyicaro** [comment]
Added in version 1.5.1, see the changelog for more information.

**Comment by cordlessblues** [comment]
This issue makes it so that I can't use Do A Barrel roll as it uses separate bindings to roll pitch and yaw but I can't set them without blanking out my movement binds maybe highlight duplicate binds red but still allow them and then hitting two buttons at once clears the bind
