### ISSUE TITLE
(suggestion) Ability to create different tutorial worlds from the different versions

### ISSUE THREAD

**Issue by repletsin5** [Wilyicaro/Legacy-Minecraft#166]
The title says it all, but i dont know if it will take up too much space(if so maybe add it as a plugin/module for the mod?) and if players want it.

**Comment by Wilyicaro** [comment]
This has already been suggested before, and you specified the main reason that I won't add, which is the size of the mod, you can create a resource pack for that yourself:
https://github.com/Wilyicaro/Legacy-Minecraft/wiki/World-Templates
