### ISSUE TITLE
Quilt Incompatibility

### ISSUE THREAD

**Issue by omo50** [Wilyicaro/Legacy-Minecraft#169]
Despite being marked as compatible for Quilt on Modrinth, as of QSL+QFAPI 9.0.0-alpha.5+0.96.11-1.20.4, the mod is **incompatible** with Quilt.

Crash Report: https://pastebin.com/qrEqymvx
Log: https://mclo.gs/limj9O5

If it would be possible to make a fix for Quilt, i feel it'd be appreciated by users. Or please go and unmark the versions as Quilt Compatible

**Comment by Wilyicaro** [comment]
![2024-03-30_14 07 26](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/6eadc87e-878d-4778-a019-9911d11299a1)
Legacy4J is compatible with Quilt, but not with the Quilted Fabric API, which for some reason changed support for builtin Resource Packs, you must use the Fabric API

**Comment by forkiesassds** [comment]
Ideally you should report this to the Quilted Fabric API issue tracker as it IS an incompatibility with Fabric API

**Comment by sylv256** [comment]
https://github.com/QuiltMC/quilted-fabric-api/issues/168#issuecomment-2246042185
