### ISSUE TITLE
Crash when pressing menu button in game when using with controlify mod

### ISSUE THREAD

**Issue by GlitchSlayed** [Wilyicaro/Legacy-Minecraft#17]
^ what the tittle says basically, ik controller support might be work in progress but thought i should report anyways. Will the mod support external controller mods like controlify or midnightcontrols, or will it have its own implementation? ik controlify has an api for other mod devs to tie their mods in.

**Comment by Wilyicaro** [comment]
It's a known issue, probably will not be fixed, a native controller support is a planned addition for now, as there are no good controller support mods for forge and fabric
