### ISSUE TITLE
Villager crossed line price are missing

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#171]
So basically, whenever you get hero of the village achievement or when you anger them, it's supposed to show if price of items increased or not, on LCE, it seems like it doesn't increase item price when you anger them as that's what it does in JE, but I think it's better off leave both.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/aa3d1b53-0039-489b-98c4-f3dca1e7b753

**Comment by Wilyicaro** [comment]
Fixed in version 1.5.1, thanks for reporting.
