### ISSUE TITLE
Interface sensitivity only affects when moving cursor to sides, and game sensitivity affects cursor when moving up/down

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#172]
Seems like interface sensitivity isn't quite properly implemented

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/21aa6db3-a6e1-4347-b003-21262d414a40

**Comment by Wilyicaro** [comment]
Fixed in version 1.5.1, thanks for reporting.
