### ISSUE TITLE
Regular candle should be the main one in the candles section of crafting interface

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#173]
![2024-03-31_01 28 43](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/036f115e-5daa-48ae-909a-a7b1e6f67785)

**Comment by Wilyicaro** [comment]
Why? Obviously there are no candles in LE, and the order of colors in the Crafting Interface has no pattern, and I can't change the order, as it's defined by the order in which the recipe is loaded, because I used the item tag minecraft:candles for it.

**Comment by DanielMC101** [comment]
@Wilyicaro cuz I just felt like it would make more sense for regular candle to appear first
