### ISSUE TITLE
Background dimmed on clientside crafting table interaction

### ISSUE THREAD

**Issue by AmeliaGL0w0** [Wilyicaro/Legacy-Minecraft#174]
I joined a server that didn't have legacy4j installed, so it forced me into classic crafting. But the background isn't dimmed, meaning that also tooltips get broken.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101548356/f4fcf0b2-f226-4e7f-acf0-7973b9ca1a02)

**Comment by Wilyicaro** [comment]
This was a bug that returned the vanilla dark transparent background, fixed in 1.5.1a
