### ISSUE TITLE
Locked into flying in survival

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#175]
If you switch to survival/adventure mode and enable can fly in host options, then double tap jump and then disabling can fly, you won’t stop flying, even if you double tap jump again

**Comment by Wilyicaro** [comment]
This is a JE bug, which I must obviously fix, if don't have this Issue at https://bugs.mojang.com/projects/MC/summary, report it, although it's not possible to fly in survival without modifications to the server
