### ISSUE TITLE
Issues with in-game tooltips

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#176]
-It's supposed to say "Empty" instead of "Fill" when on the surface block
-When holding a bucket on cow, it's supposed to say "Milk"
-Ender chest is missing "Open" tooltip
-"Carve" on pumpkin is bugged
-"Play" on noteblock is bugged
-Hoppers should say 'Open" instead of "Use"
-Missing 'Dye" on sheep
-Missing tooltips for minecarts with chest, and hopper it should say 'Open"
-Missing "Open" on Book and Quill and "Read" when it's signed
-Missing "Use' on trapdoors, doors, and gates as it is in Console Edition
-Missing "invert" on daylight sensor
-Missing tooltip 'Collect" when picking up fishes with water bucket
-Missing tooltip for Bell. On PS4 Edition is says "Use" but honestly I think it should instead say "Ring"
-Missing "Douse" when using shovel to remove fire from campfire. That's how it is in PS4 Edition.
-Missing 'Drink" when holding a milk bucket
-Planting any plants like saplings, seeds, etc. should say "Plant" instead of "Place"
![2024-03-31_23 20 33](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/fad90bb8-7302-4289-8091-bd7228d45bbf)
![2024-03-31_22 51 58](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/3bccbe1e-c51f-453c-bfcc-2dd67e3c5567)
![2024-03-31_23 51 25](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4b9b5166-f377-4cab-bccb-d34f0a8cf47d)
![2024-03-31_23 51 59](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/badf5512-34ef-4d9b-94c8-0b75b4fc2595)

**Comment by DanielMC101** [comment]
Updated what tooltips are missing.

**Comment by Wilyicaro** [comment]
I'm going to close this one, why repeat basically the same Issue? I don't prioritize the most recent ones, in fact I go for the fastest ones first

**Comment by Wilyicaro** [comment]
#158
