### ISSUE TITLE
Weird artifacts on the crafting and creative tabs

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#177]
With the new update, the tabs in both the creative and crafting screens seems to have artifacts around them:

![2024-04-01_10 05 44](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/12dd914b-1e53-4a17-b0b6-cdc7d88c34f7)

![2024-04-01_10 08 03](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/6c96d80d-0c98-4633-9a51-86114dd40fc4)

**Comment by Wilyicaro** [comment]
Change Interface Resolution

**Comment by Wilyicaro** [comment]
#110
