### ISSUE TITLE
Pretty sure it’s using the wrong controller hint for keyboard and mouse 

### ISSUE THREAD

**Issue by dragonplus8** [Wilyicaro/Legacy-Minecraft#178]
For changing to the dyeing section of the crafting table the controller hint shows shift +arrow keys however this is not the thing to change groups its shift +] 
![IMG_6309](https://github.com/Wilyicaro/Legacy-Minecraft/assets/125908478/e60e2ca7-e7fd-4f84-ab21-b91e9269171e)

**Comment by Wilyicaro** [comment]
Fixed in version 1.5.1, thanks for reporting.
