### ISSUE TITLE
F1 toggles when changing any setting

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#182]
It seems like upon changing a setting, F1 is toggled on.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/ade27625-9e00-4c20-a890-6d46a2381eba

**Comment by Wilyicaro** [comment]
This doesn't happen and has never happened to me, so I don't know how I can help.

**Comment by Cloud5474** [comment]
Huh, that's weird. I don't think I did anything specific to make it this way. It just starts when I open the game and join a world.

**Comment by Wilyicaro** [comment]
Are you only using Legacy4J and its dependencies? It could simply be an incompatibility with a mod

**Comment by Cloud5474** [comment]
I am using additional mods, that being WorldEdit, LazyDFU, Entity Model Features, and Entity Texture Features. I turned each off individually and tested, and then turned all off collectively and tested (All besides Fabric API, Architectury API, and Legacy4J) but the issue still persisted. If it's any help, I'm on Fabric 1.20.4.

**Comment by DanielMC101** [comment]
this doesn't happen to me either

**Comment by Wilyicaro** [comment]
There is nothing wrong, you certainly have the Display HUD option in User Interface disabled and you are forcing the HUD to appear with F1
