### ISSUE TITLE
When hovering over things in menus (like items) the text doesn't seem to scale to your window anymore.

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#186]
When hovering over things in menus (like items) the text doesn't seem to scale to your window anymore. Instead, it remains the same despite resolution. (For instance, it looks really small at a 2k or 4k resolution)

**Comment by Wilyicaro** [comment]
Have you checked out the Legacy Text Scaling option?  It is precisely to disable this.
