### ISSUE TITLE
Feature Request - Togglable Legacy Edition Chat Bar and Colored  - Legacy NameTags - 

### ISSUE THREAD

**Issue by SpringDoesStuff** [Wilyicaro/Legacy-Minecraft#19]
![Scresenshot 2024-01-15 161147](https://github.com/Wilyicaro/Legacy-Minecraft/assets/106285829/80a3519f-bbbc-4f96-9e32-8355c29ff7a3)

**Comment by SpringDoesStuff** [comment]
Thought it'd be a nice ask!

**Comment by Wilyicaro** [comment]
This is such a nice feature, that it'll likely be added along with LE map coordinates.

**Comment by Wilyicaro** [comment]
Added in 1.2 and 1.3 versions
