### ISSUE TITLE
cant add or change shaders (IRIS)

### ISSUE THREAD

**Issue by sussyboy123** [Wilyicaro/Legacy-Minecraft#191]
i cant add or change shaders. i cant find the shader option

**Comment by DanielMC101** [comment]
the only way to open the shader menu or any other kind of menus like mod menu is by setting keybinds

**Comment by omo50** [comment]
> i cant add or change shaders. i cant find the shader option

@sussyboy123 Disable Legacy4J, enable the shaders, close the game and then reenable the mod

**Comment by lilm0nsterdemon** [comment]
bind it to a key in the controls.
