### ISSUE TITLE
(Suggestion) LCE Flight Sprinting

### ISSUE THREAD

**Issue by notabirb1** [Wilyicaro/Legacy-Minecraft#192]
In Legacy Console Edition, sprinting flying (either in Creative Mode or with flight enabled in Survival) will move the player at a much faster speed in the direction they're looking. Currently, this isn't part of the mod. 

I'm not sure how this would work with keyboard & mouse players if this were implemented, but for controllers it helps to get around (and to feel more like legacy console.)
**This could also pose some challenges on servers, where it could potentially trigger an anticheat.**

**Comment by Wilyicaro** [comment]
You can see on the Legacy4J main page (Modrinth, CuseForge and GitHub README) that this is already a planned addition

**Comment by notabirb1** [comment]
That... is the only place I didn't look. Sorry!
