### ISSUE TITLE
Changing the panorama scrolls speed option changes the camera position in the panorama background

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#193]
If you change the panorama scroll speed option, it changes the position of the panorama. It looks like the position of the panorama is multiplied with the panorama scroll speed option. This means that there is only one single position of the panorama possible if the panorama scroll speed option is set to 0%. I guess there is some value that determines the position, where the panorama currently is and this number is increased every frame. The panorama scroll speed option should multiply the number that is added to this value, not the value itself. That would probably fix it and match with the panoram scroll speed option in vanilla. (In vanilla the panorama rotates, while on LCE it is a flat screen where it scrolls.)

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/56959bdd-0718-4772-92c3-5b357e0a37ed

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/86895375-af29-44bb-815c-5efbeb472cfc

**Comment by Wilyicaro** [comment]
In vanilla, the speed of the panorama does not make it rotate (move horizontally in the case of the Legacy4J panorama), simply because the value added to its rotation is "stored", while in Legacy4J it's based on the current time since the game was started, which makes it more optimized in a way. And of course, I knew about this movement, but I decided to keep it because I think it's a very silly detail.

**Comment by bugsbugsbugsLCE** [comment]
> while in Legacy4J it's based on the current time since the game was started, which makes it more optimized in a way.
That probably means that it stops spinning if this time overflows. This was an issue in vanilla and fixed in 22w42a. https://youtu.be/H6wa62K8hM4?t=717 (I assume that this happened because the number overflowed)

**Comment by Wilyicaro** [comment]
I don't think this will cause an overflow, since I don't use the entire value for the movement effect, it stays in a loop due to using the remainder of the division
