### ISSUE TITLE
Controllers don't work on Linux

### ISSUE THREAD

**Issue by shrobbyy** [Wilyicaro/Legacy-Minecraft#195]
Logs provide no information. Both Bluetooth and USB connection don't work. Starting the game with a controller plugged in also has no effect.

**Comment by Wilyicaro** [comment]
No, it does work on Linux, I've seen many reports of it working on Steam Deck, controller support depends on the native library used for it. In other words, it is possibly your control that does not have a cataloged mapping (preventing it from working), despite having seen on the Legacy4J Discord that strangely this same controller works in Controlify.
However, I'm not sure, it could be some incompatibility with another mod, but I can't help with anything without any more information.

**Comment by shrobbyy** [comment]
> No, it does work on Linux, I've seen many reports of it working on Steam Deck, controller support depends on the native library used for it. In other words, it is possibly your control that does not have a cataloged mapping (preventing it from working), despite having seen on the Legacy4J Discord that strangely this same controller works in Controlify. However, I'm not sure, it could be some incompatibility with another mod, but I can't help with anything without any more information.

I'm using Prism Launcher with following mods: Architectury, Fabric API, Legacy4J (obviously), Lithium, Mod Menu, Reese's Sodium Options, Sodium, Sodium Extra
Controllify works fine for me, it just fails with Legacy4J.

**Comment by emilyastranova** [comment]
I'm having this same issue on Fedora. I even tried switching to the Xone driver. Works in Controlify, just not Legacy4J. Odd.

**Comment by tajo48** [comment]
Same issue

**Comment by Fxzzi** [comment]
XBox Elite Series 2 Controller is not being detected by the modpack. Controlify works fine.

**Comment by Avenred** [comment]
Why is this issue closed? The Xbox Series X/S Controller is not working for me either on Fedora. I haven't tried Windows yet, but Controlify works just fine for me as well.

**Comment by Wilyicaro** [comment]
> Why is this issue closed? The Xbox Series X/S Controller is not working for me either on Fedora. I haven't tried Windows yet, but Controlify works just fine for me as well.

Because it's not a Legacy4J problem, but rather a GLFW problem, for me to "fix" it would be another API, but that would already be a suggestion

**Comment by tristann21** [comment]
> > Why is this issue closed? The Xbox Series X/S Controller is not working for me either on Fedora. I haven't tried Windows yet, but Controlify works just fine for me as well.
> 
> Because it's not a Legacy4J problem, but rather a GLFW problem, for me to "fix" it would be another API, but that would already be a suggestion

I'm kinda confused after reading this. So does this mean you're thinking to use another API? the one like controlify is using? I'm not a developer so I don't know much about this type of stuff, but I'm having the same issue and I'm unable to use a controller on both my steam deck and my PC running Fedora (bazzite) which really sucks. 

At the very least I wish the modpack wouldn't bork whenever I tried using controlify. It'd be nice for it to use a library or API that worked with all distributions, not just Steam OS.

It appears people on other distributions are having the same issue. https://github.com/Legacy-Union/Re-Console/issues/6

**Comment by tristann21** [comment]
> > Why is this issue closed? The Xbox Series X/S Controller is not working for me either on Fedora. I haven't tried Windows yet, but Controlify works just fine for me as well.
> 
> Because it's not a Legacy4J problem, but rather a GLFW problem, for me to "fix" it would be another API, but that would already be a suggestion

I found someone supposedly made a fix for this in the GLFW github if you're interested

https://github.com/glfw/glfw/issues/2484#issue-2130489167

**Comment by Wilyicaro** [comment]
I've already implemented the SDL Controller in the dev builds, which is much better in many ways, I hope I don't need GLFW anymore
