### ISSUE TITLE
Crafting table doesn't show legacy crafting UI on server with mod installed

### ISSUE THREAD

**Issue by emilyastranova** [Wilyicaro/Legacy-Minecraft#196]
Deployed a Fabric server with this mod on the server-side and client. Everything seems to be working except the crafting table. Legacy crafting works in the normal "X" menu, but not when right-clicking on a crafting table.

**Comment by Wilyicaro** [comment]
Honestly, I was in doubt, even though I tested this before releasing the version, so I tested it rn and it worked perfectly when installed on a server.
I believe you're using an old version of Legacy4J on the server.

**Comment by emilyastranova** [comment]
@Wilyicaro I am running `1.20.4-1.5.1a`
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/16725119/c3176264-7f40-45b6-9ceb-dd1ff9736745)

**Comment by Wilyicaro** [comment]
And you client?

**Comment by emilyastranova** [comment]
> And your client?

Same jar file, dragged and dropped from client to server

**Comment by emilyastranova** [comment]
When I get home I can grab logs from both client and server so theres more to work with :+1:
