### ISSUE TITLE
Can't bind controls in-game.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#20]
I tried out your mod, it's REALLY REALLY GOOD. However there's this one bug and it's the issue with saving changes in keybinds. When I switch the binds for sprinting, it's still using the default.

Steps reproduced:
1. Open the world.
2. Go to the controls tab.
3. Keybind any buttons, like binding from "Ctrl" to "Shift" for sprinting.
4. Go back to the game.
5. Press "Shift"

**Comment by Wilyicaro** [comment]
If you press the key bind button by pressing "Shift", it will reset to default, I don't know if this is your case, but this is a useful info

**Comment by Wilyicaro** [comment]
This will be fixed in the next version, and again, thanks for reporting.
