### ISSUE TITLE
Vulkanmod doesnt work with L4J

### ISSUE THREAD

**Issue by AmeliaGL0w0** [Wilyicaro/Legacy-Minecraft#200]
[logs](https://github.com/Wilyicaro/Legacy-Minecraft/files/15077353/message.txt)

**Comment by Wilyicaro** [comment]
I can't do anything much about this, Legacy4J makes use of specific OpenGL related functions for the controller handler, which makes it incompatible

**Comment by AmeliaGL0w0** [comment]
alright, will leave that to vkmod dev team then

**Comment by AmeliaGL0w0** [comment]
l4j now launches on vulkanmod, has some weird graphical glitches and gamma settings hard lock the game, so you have to reset them to make it work, otherwise everything else looks good.
video showcasing l4j under vulkanmod: https://youtu.be/npgRTebdAkA
