### ISSUE TITLE
Some creative flight stuff

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#201]
From my testing with the recent update, I have found a few things that don't seem too right with the creative flying:
1. Flying against the ground slows down your flight speed, while on LE flying against the ground would make your speed go perpendicular to the ground
![Screenshot_1371](https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/4ce9a4b9-5772-48a7-83bf-859a47a83d7d)
2. Jumping (not flying or sprinting, just regular jumping) is really slow for some reason
3. Sprint jumping seems fast
4. Flying without sprinting seems just a tad bit slow
5. Pressing space with the elytra has behavior different from LCE, attempted to depict in image
![Screenshot_1372](https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/0ba061fe-2665-4ac6-a026-87db0b362bb1)

**Comment by Wilyicaro** [comment]
Honestly, despite your effort to make the images to better visualize your understanding, you're wrong about the issues regarding them, in LE you slow downs your flight speed when looking at the ground, just like in Legacy4J, I just tested it now, and elytra "momentum" is completely overwritten
