### ISSUE TITLE
Cannot create when adding more than 1 pattern on loom

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#202]
On PS4 Edition, it's supposed to allow you to do that.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/f5806e8f-892a-4094-9d39-6c35573d3d5b

**Comment by Wilyicaro** [comment]
You don't have enough yellow dye :/

**Comment by DanielMC101** [comment]
@Wilyicaro Ohh omg I'm an idiot sorry.

**Comment by Wilyicaro** [comment]
np

**Comment by DanielMC101** [comment]
might as well just change this bug report to not showing that you don't have enough dye on loom when using same dye.
