### ISSUE TITLE
Low Resolution Interface with Using NucleusCoOp

### ISSUE THREAD

**Issue by BigThiccRanch** [Wilyicaro/Legacy-Minecraft#203]
Hey!

I figured it would properly be easier for you to see this instead of me messaging you via Discord (rundellvonranch) and since you are more active on here than Discord.

The inputs work perfectly for NucleusCoOp, as after I manually assign the controllers to each instance, I don’t need to change it again when I first boot the instances again.

However, when I do 8 Player Splitscreen via NucleusCoOp, the HUD resolution is very very low, which I attempted to change with the “Interface Resolution” setting, which only slightly made it better.

I also messed with the GUI settings, which did not improve it either.

I believe if you make the slider all the way down to 50% for the Interface Resolution, that it would be incredibly sharp and legible.

Down below are images of what it looks like.

Thanks
![IMG_5882](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168059011/f6ba9c77-925c-47f8-ab40-39b737d14b98)
![IMG_5886](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168059011/19801c4d-c785-4b4a-bd39-54f4e56d261e)

**Comment by BigThiccRanch** [comment]
Here is what the single player world screen looks like as well.

![IMG_5887](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168059011/94b7480b-a0c7-420c-b6ca-377feff55ec9)

**Comment by Wilyicaro** [comment]
The only way around this I think is to increase the Interface Resolution change, since the screens in Nucleos Coop have an inadequate resolution, which does not have a correct GUI Scale

**Comment by BigThiccRanch** [comment]
Which is what I did, I messed around with the interface resolutions.

Here in this image is the game at 100% Interface Resolution, as you can see, the image gotten smaller.
![IMG_5888](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168059011/6959933f-e4e5-4587-ae0b-f708728b4ca8)

And then this is what it looks like at 50% resolution, which the text size increased, but it’s still illegible.
![IMG_5889](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168059011/395a3d4a-e201-4ee1-a715-aeab0278c74a)

So, if there is a way to make the slider go farther than 50% Interface Resolution, perhaps all the way down to 20% or 30%, it should be perfectly legible in these split screens

**Comment by Wilyicaro** [comment]
Fixed in 1.6.1, thanks for reporting.
