### ISSUE TITLE
Obtaining an item with the /give command plays the item dropping sound

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#204]
If you obtain an item with the /give command, it plays the sound for dropping an item that was added. Picking up an item normally doesn't play the sound.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/217af188-5d47-49b7-aa65-d52abb7b2d35

**Comment by Wilyicaro** [comment]
There's nothing wrong there, simply /give is considered a drop for some reason, and don't even complain, as there is no such command in LE
But now I'm hoping the same doesn't happen with the dispenser.

**Comment by bugsbugsbugsLCE** [comment]
> /give is considered a drop for some reason
That's weird.

> But now I'm hoping the same doesn't happen with the dispenser.
It doesn't.

**Comment by Wilyicaro** [comment]
It may not be counted on the scoreboard, but it's definitely a drop, the name of the method is literally that
