### ISSUE TITLE
The UI sound when placing item in an empty slot menus except creative menu is a bit loud.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#205]
So as you can see, pretty much when just placing item in an empty slot on any kind of menu just makes UI click sound bit loud.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/f269c2a3-2950-44de-9ba7-1a7736adf96e

**Comment by Wilyicaro** [comment]
Fixed in 1.6.2a
