### ISSUE TITLE
Inventory menu, cursor snapping when using the analogue stick (possible solution)

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#206]
When moving the analogue stick in the inventory, the game snaps the cursor to the nearest slot in the direction the user is holding, then begins to move. When the user attempts to flick the stick, it snaps two slots over due to this.

This causes confusion as it appears as if your cursor teleports one slot over when attempting to move it, rather than it seamlessly moving from the position it was already at when you first moved the stick

Maybe make it so the cursor only snaps after the analogue stick returns to it's dead zone

This should solve both issues.

**Comment by Wilyicaro** [comment]
This would not solve it, as this check is already done, the cursor will only snap into the slot if the analog stick is released, that is, returning the dead zone.
