### ISSUE TITLE
Holding shift and touching the ground while flying forward makes the hand bob down

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#209]
I'm not sure why this happens, but I don't think it should.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/3721256a-bf8c-4ae9-9030-18023e8acfed

**Comment by Wilyicaro** [comment]
It's not a Legacy4J issue, it may not match LE, but it's still not a problem, the change should preferably be suggested on the Legacy4J Group
