### ISSUE TITLE
I feel like the hotbar and crosshair GUI should be a bit more bigger.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#21]
when making the GUI menus a bit more smaller so that it doesn't look too big, the hotbar and the crosshair look quite small and doesn't make it equal to how it is in the legacy console editions.

**Comment by Wilyicaro** [comment]
You're right, the LE hotbar is bigger, compared on the same proportional scale to the Legacy4J.
It's something I'm working on now, so I'll close this issue.

**Comment by Wilyicaro** [comment]
I was testing a bigger hotbar, and the results aren't satisfactory... 
Minecraft Java Edition GUI Scale doesn't look good with a bigger hotbar in some cases, playing with it in 2 in windowed mode will result in:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/e4d426ed-3f02-4b2c-9612-b58ed8fe8a97)

**Comment by Wilyicaro** [comment]
Unfortunately, for now the hotbar scale will be the same

**Comment by Wilyicaro** [comment]
This was added in 1.2 version, thanks for requesting.
