### ISSUE TITLE
Using Programmer Art with Legacy4J 1.6 removes mipmapping

### ISSUE THREAD

**Issue by Permdog99** [Wilyicaro/Legacy-Minecraft#210]
Before
![2024-04-26_19 41 24](https://github.com/Wilyicaro/Legacy-Minecraft/assets/34215218/e8f7a6d9-bc11-4475-bb47-ebfc29472ffb)

After
![2024-04-26_19 41 51](https://github.com/Wilyicaro/Legacy-Minecraft/assets/34215218/9f7bf130-7d66-4966-890c-f66b59c1dd96)

**Comment by Wilyicaro** [comment]
This isn't a Legacy4J issue, only resources provided by Fabric API were used to modify Programmer Art

**Comment by Permdog99** [comment]
Actually it is L4J. The armor slot textures added in programmer art is too large for the game to handle, making it fallback to a mipmap of 1

**Comment by Permdog99** [comment]
[22:10:45] [Worker-Main-9/WARN]: Texture minecraft:item/empty_armor_slot_chestplate with size 38x38 limits mip level from 4 to 1
[22:10:45] [Worker-Main-9/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 1, because of minimum power of two: 2

These are my logs. Removing the armor textures fixes the issue from my testing
