### ISSUE TITLE
Incompatibility with Essential

### ISSUE THREAD

**Issue by malkXp** [Wilyicaro/Legacy-Minecraft#212]
This mod is great in many ways, but I feel like it would work better if you could join your friends along side it.
Currently the mod gives the options for realms, servers, and lan games, but not friends (which is understandable)

Essential, which is a mod made for joining friends worlds without the need of setting a server up or needing to be on a lan connection would be a great addition if it worked.

Currently, the UI of this mod (which is very accurate to legacy console editions UI) does not allow for things like essential to work, deeming the ability to join friends without a set up server or lan games impossible currently.

I feel like this compatibility feature would add a large gateway to many things in the future like minigame support for this mod since tutorials seem to be working.

I also know that trying to add stuff like this would be very unnecessary currently due to the fact that the mod isn't finished and that many things are currently being fixed. However, in the future, I hope to see that you understand/make this a compatible mod to run simultaneously with essential so that we can join our friends worlds.

**Comment by omo50** [comment]
Essential has no public source code; compatibility cannot be worked on.

**Comment by malkXp** [comment]
> Essential has no public source code; compatibility cannot be worked on.

Essential actually does have public source codes that are constantly updated in github.
You can find these sources under the repositories of https://github.com/orgs/EssentialGG/repositories

So basically compatibility can be worked on but it would take longer than a normal mod since this isn't exactly like a normal mod. (multiple repositories that would require looking through in order to understand) The public source code as mentioned before, is updated to the latest version (1.20.4) of essential, meaning that this is entirely possible but I don't know if it should be considered yet until most bugs with Legacy Minecraft are resolved

**Comment by Wilyicaro** [comment]
I believe that none of these repositories actually have the Essential mod code, they are just from the same group, precisely because it is closed source and has All rights Reserved, and being open source with the cosmetics would not be a good idea.
