### ISSUE TITLE
Going all the way down by pressing the up key makes too many sounds in some menus

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#216]
If you press the up key when you are at the top in certain menus, the menu scoll sound is too loud. It seems that the sound is play multiple times.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/09ca88ee-f3b8-4586-be88-a50663bd4703

**Comment by DanielMC101** [comment]
I was just about to report this, and it also affects the crafting, loom, etc. interface.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/83408153-1c1d-4ced-baf8-8815055c73db

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.2a, thanks for reporting
