### ISSUE TITLE
Pressing ESC in the datapacks menu when creating a world doesn't go back into the world options menu

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#217]
If you press ESC in the superflat customization menu when creating a world, you will go back to the world options menu as expected. If you however press ESC in the datapacks menu, it goes back to the menu, where you see the game mode, world name etc.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/5bfba61c-4332-4f1d-8201-75941a680d2b

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.2, thanks for reporting

**Comment by bugsbugsbugsLCE** [comment]
The issue has returned

https://github.com/user-attachments/assets/8e294b71-6f44-4da9-91e1-3903699e25bb
