### ISSUE TITLE
Game crashes when attempting to craft with a full inventory

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#218]
Game crashes when attempting to craft seemingly any item with a full inventory.

Example: all inventory spaces are full, one slot has three or more sticks attempting to craft a shovel crashes the game.

This doesn't apply if your inventory wouldn't be full after crafting

Example: all inventory spaces are full, one slot has two sticks attempting to craft a shovel works fine

**Comment by Wilyicaro** [comment]
You are probably using a mod that purposely causes this crash, because the item drop is not being executed by the server, something that I think is useless if it is intended for optimization

**Comment by G01dY05h1** [comment]
> You are probably using a mod that purposely causes this crash, because the item drop is not being executed by the server, something that I think is useless if it is intended for optimization

It seems like that was the case, the mod being "Concurrent Chunk Management Engine"
