### ISSUE TITLE
The loom doesn't work anymore in 1.6.1

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#219]
So basically, when trying to put patterns on banners in loom, it doesn't work at all.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/1f3045f2-fba8-4e83-867b-6ee9cd62c998

**Comment by Wilyicaro** [comment]
Fixed in 1.6.2, thanks for reporting.
