### ISSUE TITLE
Quartz's Feature Requests

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#22]
Hi! I have so much things that needed to be added for this mod. My friend found out about the mod, and it still needs some things to be added.

- [X] The button turns blue and the text turns yellow when hovering in the main menu
- [X] "Initializing **Server**" to "Initializing **server**" - lowercase "s" to match accuracy
- [X] ~~Minecraft Console Edition logo - can be customized via resource pack~~
- [X]  Making the boss bar more accurate to the console edition bar - mentioned by TechSupportRed
- [X] Controller tooltips - since you're also planning on adding native controller support in the future, include this one.
- [X] Semi-transparent white crosshair - Legacy has this, not inverted.
- [X] ~~Legacy-like mipmaps - an actual mod with this feature has been made and it's available on [Modrinth](https://modrinth.com/mod/legacy-mipmaps).~~
![grass](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/5894cf04-8818-4b07-96e1-fffb7ecd2c64)

- [ ] Close spacing on signs.
![closetext](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/0b1764fb-2441-43ac-bf10-cf1c4b303e18)

- [X] ~~Custom loading screen tips - can be customized via resource pack~~

- [ ] Water became semi-opaque in the distance. - could be part of option 7 but unsure.
![waterfade(1)](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/64a873fa-e4d4-4859-a29c-d18143bff54a)

I think that's about it. You can message me on Discord (quartzmaven) for something. Thank you!

**Comment by Wilyicaro** [comment]
Thank you for all these requests.
Unfortunately, the first and third request will not be added by default in the mod, as Legacy4J's goal is to adapt LE for new versions of Minecraft as unified with JE, and the 1.14 button highlight with white text probably would be added to LE at some point, even if in the last update of the PS4 version with the new textures don't have this.

**Comment by Quartzmaven** [comment]
Understood, thanks!

Also, I edited the 5th one.

**Comment by Quartzmaven** [comment]
Added, another one, which is "idle hands animation". Even though, Bedrockify works with Legacy4J by disabling mixins but unfortunately, when you create the world, it crashes the game instantly.

**Comment by Quartzmaven** [comment]
Turns out, in the 3rd request, I can change the logo using resource packs. Well, ignore that request.
![legacy4jwithmclcelogo](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/a2a4b059-fac2-4ad3-8ff9-579619ca7a01)

**Comment by Wilyicaro** [comment]
Now I see, the last request is already in the mod, only if you set the interface opacity to a value less than 100%.
I maintained the invert behavior in 100% because the LE versions without this config has this feature.

**Comment by Quartzmaven** [comment]
I'm about to publish my modpack with your mod. Is it okay if I can use it? Thanks.

**Comment by Quartzmaven** [comment]
I have updated the request with images.

**Comment by Quartzmaven** [comment]
This one might be the best example of the 12th request.
![distant](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/71508085-5eaf-4636-934e-34eb050a9143)

**Comment by Wilyicaro** [comment]
I've never worked with mipmaps, but from what I know JE's mipmaps are generated automatically, as the textures are separate files, as you may already know, and LE still used the atlas images for items and blocks and the mipmap levels.
So I might try changing JE's actual mipmapping method to be more like LE

**Comment by Quartzmaven** [comment]
Closing this issue as I'm no longer involved with the Legacy community.
