### ISSUE TITLE
Bunch of bugs in NeoForge port

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#220]
So while I was trying out the neoforge port, there are some bugs that either are still present from previous versions of legacy4j, and some other bugs as well.

Flying into water gets interrupted (Also happens in forge)

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/b48afcff-b76a-4325-acb1-4e3b1b037d5f

The item sizes are incorrect. 

![2024-04-27_12 52 02](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/e8e14661-d70c-4cd2-99ea-12d0ccf12b0a)
![2024-04-27_12 52 06](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/a43c22e2-694a-409b-a031-b2d65df0e3c6)
![2024-04-27_12 56 53](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/827871ab-c809-429d-b095-2e57e46ac858)
![2024-04-27_12 57 01](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/70c188b6-ca41-424f-9550-51c929c10cbe)

Plays Java Edition's clicking sound than Legacy

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/dd78da20-13f3-4871-8fa6-611f9217b4e2

**Comment by Wilyicaro** [comment]
Most of these "bugs" are caused by the mods' resource pack being below the vanilla one, for some reason this is Neoforge's default now
