### ISSUE TITLE
Iron door in crafting menu is misplaced

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#221]
So on the console editions like PS4 Edition, the iron door should be like way at the button of the other doors, and for this I think it should be right at the buttom of the warped door as that's the very last one.
![Minecraft_20240427144016](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/0d37f12c-7420-46c6-9a27-72c8e2fc80a8)

**Comment by DanielMC101** [comment]
I have in fact already fixed this myself.

[crafting_tab_listing.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/15139905/crafting_tab_listing.json)

**Comment by Wilyicaro** [comment]
Fixed in 1.6.2, thanks for reporting.
