### ISSUE TITLE
Any other languages other than English US doesn't translate to LCE style properly.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#223]
Like on the inventory tooltip, it says "Open/close inventory" and says "options..." isntead of "Help & options" host privllages says "Allow cheats" pretty much any language that's not English US especially different English like Canada, United Kingdom, etc.

![2024-04-27_18 37 32](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/64eba82e-2b8d-48d0-9526-aa40747bd45f)
![2024-04-27_18 37 49](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/9e6c3db7-baa2-499b-a238-214807472723)
![2024-04-27_18 37 59](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/47e176ba-22ce-4acc-a8ed-fadc733ac24a)
![2024-04-27_18 38 09](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/72550d40-ba05-4dcd-8c1a-cfb62c793829)
![2024-04-27_18 38 15](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/a93750b3-49bc-4256-b174-901f2134ca62)
![2024-04-27_18 38 18](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/0e6c336a-1ffd-4d35-9d82-c5b8c6a5ace8)
![2024-04-27_18 38 31](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/3f2d7307-43d0-4211-9b41-f0421c93fdc6)

**Comment by Wilyicaro** [comment]
I'm a developer, not a translator, I translated into the languages I speak, if anyone wants to translate into their language feel free to make a Pull Request, which I will accept as soon as possible.
And no, I won't try to get the LE language files as I believe it's much more work than translating manually (which I did with the languages currently available), especially small texts, the tips make it even acceptable to do so.

**Comment by DanielMC101** [comment]
@Wilyicaro i don't  exactly mean like properly translating into different language, I mean like not properly having proper LCE style words like it says "allow cheats" instead of "host privllages" and also inventory tooltip says "Open/close inventory" affects English Canada, UK, etc.

**Comment by Wilyicaro** [comment]
@DanielMC101 Simply put, this is translating, whether you like it or not, other variations of English are also other languages, I could simply copy and paste en_us.json, but there may be differences that I wouldn't know
