### ISSUE TITLE
Cannot unsprint when flying in creative/spectator

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#224]
A bug I found in the recently released 1.6.2, so basically when sprinting while you're flying either in creative or spectator mode, and if you stop, you're still sprinting.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/c195587c-ffb6-45e6-9137-7710400c465e

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.2a, thanks for reporting.
