### ISSUE TITLE
Missing sound for adding in loom interface.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#225]
Sound works when creating, but missing sound for when adding.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/cb7e34c7-423f-4fae-b816-e55bd72f8540

And this is the sound it's supposed to make when adding in the loom interface in PS4 Edition, which is also present in JE when adding.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/24426e38-75d8-4e5c-9f9b-2be3b5e8baba

**Comment by Wilyicaro** [comment]
Added in version 1.6.2a, thanks for reporting.
