### ISSUE TITLE
Grid and arrows disappearing on crafting tabs, and the loom.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#226]
So basically, when adding pattern in loom without any single navigating in UI, it works, but when creating pattern after navigating the UI, the arrows and box grid disappears.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/9bff7e2f-dbb8-48a4-ab4b-6c4d4cb63539

**Comment by DanielMC101** [comment]
turns out, the arrows can disappear sometimes on the crafting tabs
![2024-04-28_12 42 50](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/f5d26f90-2339-45f2-8a77-4838e8da611e)

**Comment by Wilyicaro** [comment]
What arrows are you talking about? I don't see anything wrong in either the video or the screenshot, just the selected banner, which appears two instead of 1

**Comment by DanielMC101** [comment]
@Wilyicaro basically these 
![Capture](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/ec604d27-fa24-4880-8299-3c5313f33a27)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
