### ISSUE TITLE
Bug - World visually ignores time skipping or adding (Fabric 1.20.4)

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#23]
Very bizarre, but if you use any time related commands or even just sleep in a bed, the game will acknowledge time being skipped, but won't _show_ the change (exception being clocks) until you reload the world by going back into it.

https://www.youtube.com/watch?v=63jZE8eEhNM
https://www.youtube.com/watch?v=Mvw6Hr6i2Zw

First video is of the game acknowledging the time change but not showing it and the second video is showing it actually being the case with a reload

**Comment by Wilyicaro** [comment]
Are you using other mods with Legacy4J? What options did you use to create the world?

**Comment by Chilly-roll** [comment]
I've tested this on its own-- this is the fabric 1.20.4 version if that means anything. It's a standard world as well

**Comment by Chilly-roll** [comment]
(standard as in no datapacks messing with anything)

**Comment by Wilyicaro** [comment]
I didn't have this bug in any test I did, so for now I can't help you

**Comment by Chilly-roll** [comment]
I'll see if it's just an issue with fabric 1.20.4 on my end by seeing if it continues in the other versions of the mod available

**Comment by Chilly-roll** [comment]
Fabric 1.20.2 - Doesn't have this issue
Forge 1.20.2 - Doesn't have this issue
Forge 1.20.4 - Doesn't have this issue

This means there's something on Fabric's side for the 1.20.4 version since it's not an issue for me with the other three available versions of the mod. Just makes this case even weirder.. since it works fine on Forge 1.20.4

**Comment by Wilyicaro** [comment]
You can try the latest update, the 1.2 version

**Comment by Chilly-roll** [comment]
Addendum, I have no idea how I missed this, but turns out the game properly acknowledges the time change visually if you pause and then unpause after sleeping/using /time?

**Comment by Wilyicaro** [comment]
For me, it's working normally
https://clipchamp.com/watch/NA4YCmJpzYD

**Comment by Chilly-roll** [comment]
~That's weird.. If it's working for you and not me (Heck, I even tried using the same specific versions of fabric, fabric api, and architectury as you) then I dunno what's going on. Maybe it's some sorta spec related thing?~

Ok so I dunno what or why this is the case, but I managed to figure out the culprit-- I reset options.txt and.. now it works. It just works. I dunno why that of all things was the reason why this was happening but it works now. I even compared it to the old options.txt that had something to do with it and nothing seemed off whatsoever. Heck, I even enabled all the same options as the old options.txt and it STILL works. Dunno what's going on there but it's fixed.

**Comment by Wilyicaro** [comment]
I found out what the problem was, simply the Autosave Interval option was changing the singleplayer server tick value, i.e. this was only affecting the client
