### ISSUE TITLE
weird lines above icons

### ISSUE THREAD

**Issue by Kaunis-GH** [Wilyicaro/Legacy-Minecraft#230]
![image_2024-04-28_234130287](https://github.com/Wilyicaro/Legacy-Minecraft/assets/151996554/d109f78b-b1c5-4023-a8c4-38de12cb8d2c)

**Comment by Wilyicaro** [comment]
It's not a Legacy4J problem, it's your current resolution that causes this, change the Interface Resolution slider a little in the User Interface section to fix this
