### ISSUE TITLE
The ImmediatelyFast mod causes the interface opacity leave tooltips, and items unaffected on hotbar

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#231]
![2024-04-28_17 52 25](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/200245b4-e86e-44bb-b291-99f9368dd6e8)
![2024-04-28_17 52 30](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/31b18715-2e13-4bb8-9899-d68aa883b498)

**Comment by Wilyicaro** [comment]
This is an Immediately Fast optimization, not a Legacy4J issue
