### ISSUE TITLE
custom crafting menus (shops on servers) dont work on L4J when trying to purchase item, etc

### ISSUE THREAD

**Issue by skyer1a** [Wilyicaro/Legacy-Minecraft#237]
![image2](https://github.com/Wilyicaro/Legacy-Minecraft/assets/144589136/97807410-a294-4fa9-b574-a6c141bebe1e)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/144589136/272d2ed0-1726-43c3-8827-84ab09641102)

the 2nd image is on java where it works perfectly fine.

the first image is via L4J where i cant purchase anything with this menu at all.
(i know i cant afford the item but even when i can, ive not been able to make the trade)

**Comment by Wilyicaro** [comment]
In the version you are using, yes, just place the trade item in the slot (to disable automatic crafting) and then press the trade you want to make.
But anyway, there will be changes to this interface in 1.6.3, so you'll see 👀
