### ISSUE TITLE
Suggestions/Bugs

### ISSUE THREAD

**Issue by malkXp** [Wilyicaro/Legacy-Minecraft#238]
Suggestions:
1. Add the legacy console block placement (where it consistently places blocks in the way you're going)
2. Add operator items tab into the legacy creative menu when toggled on
3. Custom mod controls should be added to the controls menu (for keyboard and controller)

Bugs: 
1. On certain buttons, there is an audio delay when clicked.
2. Also on certain buttons, the click sounds play twice instead of once 
3. When creating a world, a crash can occur whenever switching game settings tabs
4. Most gui-related mods do not work on the menu screen but sometimes work on the pause screen

Summary: Make mod support overall better, maybe fix button sounds, and also update menus to fit current mc features (like operator items tab)

**Comment by DanielMC101** [comment]
Suggestions goes on on discord, also operator item tab does work. You just gotta either hold shift and right arrow, or use right stick on your controller to go to the operators tab, and also you can still bind the modded keybinds.

**Comment by malkXp** [comment]
> Suggestions goes on on discord, also operator item tab does work. You just gotta either hold shift and right arrow, or use right stick on your controller to go to the operators tab, and also you can still bind the modded keybinds.

Oh i didnt know about the operator tabs thing, but I seem to have issues mapping keybinds in game and in file, though, its probably just me being stupid.
