### ISSUE TITLE
Legacy4J legacy water resource pack not working

### ISSUE THREAD

**Issue by Jeb529** [Wilyicaro/Legacy-Minecraft#239]
Exactly as the title says, as of 1.6.1, legacy water just stops working, I can no longer enable the resource pack normally, but if I somehow manage to, the water is still very transparent. I've disabled all other mods other than required by Legacy4j, but the water still does not work, and it's starting to annoy me a little bit.

**Comment by Wilyicaro** [comment]
Nothing has changed in this resource pack or in its working in the latest versions, you are probably using the Sodium mod with Legacy4J, which changes the transparency of the water, and that is why Legacy Waters is disabled, so as not to cause conflicts.

**Comment by Jeb529** [comment]
But how did it work before? Somehow the water was very opaque on older versions
