### ISSUE TITLE
How do I get the rename and delete options?

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#24]
I want this world setting from the screenshot.
![1dd85d27820e9d29b3b3dd8c3eebfb494cddc4d2](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/40ca2b9e-ebe3-4401-8a09-8d511c029054)

I can't seem to find a way to open this menu. I pressed everything from mouse and keyboard, no luck.

**Comment by Wilyicaro** [comment]
Press the E key with the save selected, same with servers

**Comment by Quartzmaven** [comment]
Thanks!

**Comment by Wilyicaro** [comment]
You're welcome!
