### ISSUE TITLE
[bug] Crashes with a few mods (see description

### ISSUE THREAD

**Issue by Merith-TK** [Wilyicaro/Legacy-Minecraft#240]
I have a modpack I call Vanillia (mispelled)
and it includes two mods that conflict with and cause a crash,

I request that these mod-id's be added to the `conflicts` section on the mod-metadata files
[BetterRecipieBook](https://www.curseforge.com/minecraft/mc-mods/brb)
[ClientStorage](https://github.com/samolego/ClientStorage)
[Controlify](https://modrinth.com/mod/controlify)

**Comment by Ivanoshechka** [comment]
I think i know why it's crashing with controlify. Wilyicaro just did a crazy move, and added support controllers with midnightcontrols. And did it very well. (Need improvements.) 
Maybe some conflicts and L4J mod just can't understand what the hell is controlify.

Ig we need a mark in description like: "If you want play with controllers - play with MidnightControls!" or smth.

**Comment by omo50** [comment]
@Ivanoshechka midnight controls isnt supported; controller support is natively built in

**Comment by Ivanoshechka** [comment]
> @Ivanoshechka midnight controls isnt supported; controller support is natively built in

Yeah? Mine start working only from midnight. Ig Bluetooth issuse. Alr sorry.

**Comment by Wilyicaro** [comment]
What is planned to be compatible is already in 1.6.4, thanks for reporting
