### ISSUE TITLE
Turning around on boats using controller is unstable

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#241]
So basically, when going on boats, and when you turn right or left when going straight, it gets you locked in. Which doesn't happen in console edition.

Here's a video of Legacy4J

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/8244b54f-d26c-45df-8e80-0e21677a8a21

And here's video of the Console Edition (PS4 Edition)

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/79865ccf-21bd-43be-9f43-8767f73b4fee

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3, thanks for reporting.
