### ISSUE TITLE
When running out of ingredients on the loom, on the the 3x3 grid, it doesn't really have the red background with yellow icon

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#242]
Basically, this only happens after you run out of the dye and/or banner patterns, and going into the same thing you're trying to create, it doesn't have the red background with yellow icon. (idk what exactly it's called lol)
![2024-05-01_20 02 50](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/e4e909c6-30bc-4473-88f6-d1be5b18dd66)

**Comment by Wilyicaro** [comment]
Currently, you still have dye in your inventory, this cannot be considered a bug, as it works the way it should, in LE the dye is consumed even if you haven't crafted it yet
