### ISSUE TITLE
The loom is missing the crafting fail sound.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#243]
On the PS4 Edition, it's supposed to play that sound when you don't have enough stuff for the loom.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/473c61f8-7101-4ac7-92bd-8555778cfc6c

**Comment by Wilyicaro** [comment]
There is currently no such sound as it was not played on the Xbox 360 Edition, thankfully they added it in PS4 Edition
