### ISSUE TITLE
ui is massive

### ISSUE THREAD

**Issue by jaceTheNormie** [Wilyicaro/Legacy-Minecraft#245]
for some reason every time i do something that uses the ui it becomes massive and doesn't go back to normal unless i go in or out of fullscreen please help me i really like the mod but it's currently unusable. :(
![Minecraft_ 1 20 4 - Singleplayer 03_05_2024 02_04_41](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168787496/4e9fa15c-07d2-4eb8-901b-b4a2e4a70a51)
![Minecraft_ 1 20 4 - Singleplayer 03_05_2024 02_04_15](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168787496/a5cc2c5c-4617-4942-aa78-f39fb6b1a55a)
![Minecraft_ 1 20 4 - Singleplayer 03_05_2024 02_04_28](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168787496/0c0e9ef2-d425-4487-8e28-723aa94c842b)

**Comment by Wilyicaro** [comment]
This is an incompatibility with some mod, it doesn't normally happen with Legacy4J, you're probably using Essentials

**Comment by jaceTheNormie** [comment]
> This is an incompatibility with some mod, it doesn't normally happen with Legacy4J, you're probably using Essential

i actually am tsm 🥰🥰🥰
