### ISSUE TITLE
Ui absolutely tiny

### ISSUE THREAD

**Issue by Skyoooo** [Wilyicaro/Legacy-Minecraft#246]
Using 1.20.4 on fabric and when i first load into the game the ui is so small i cant read the buttons

**Comment by DanielMC101** [comment]
Did you try turning up GUI scaling?

**Comment by Wilyicaro** [comment]
You probably already had a GUI Scale defined before, and as Legacy4J increases the number of scales to better suit the resolution, it stayed that size because the number before meant a smaller size when using the mod.

**Comment by Skyoooo** [comment]
i have tried scalling but it still looks really ugly

**Comment by Skyoooo** [comment]
yeaah there are random line in the ui 
and things look distorrted

**Comment by DanielMC101** [comment]
@Skyoooo adjust the interface resolution in the user interface settings
