### ISSUE TITLE
UI sound balance

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#247]
When navigating the UI, the focus sound seemed to be much quieter compared to the other navigation sounds. The sound is much more "soft" in comparison, meaning the others sound much louder depending on speaker setup.
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/1592b915-de40-409c-b288-1dda5624312a

Comparison between PS4 (via https://www.youtube.com/watch?v=fMxiNWhauLY), Java with Legacy4J, and Bedrock with Project 4JD:
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/0b97c4e9-8251-41b8-ba58-6aff32d9dee7

**Comment by Wilyicaro** [comment]
The focus sound is already at maximum volume, it's impossible for it to have the exact same volume due to several factors that you yourself have already mentioned.
