### ISSUE TITLE
Using "Take Half" on a single item clears hotbar

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#248]
When pressing the "Take Half" button, it works completely correctly in the standard inventory, but in the Creative inventory, taking half of a single item clears the hotbar and hotbar only. The rest of the inventory remains intact.
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/43c1398e-756c-470b-baaf-f11281b9a749
Re-Console 0.2.3, Fabric 1.20.4, Windows 11

**Comment by Wilyicaro** [comment]
There wasn't even a way to "Take Half" in the Creative Mode Interface of the LE, this is an additional feature of the mod to maintain the functions of the JE, when you take only one item, as the slot becomes empty, you end up doing the action of cleaning the selection bar (or the hotbar, better said)
