### ISSUE TITLE
Bracket keyboard buttons are the wrong way around

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#250]
In GUIs, some menus use the bracket keys to cycle through tabs. In the controller tooltip, the bracket keys for this action are swapped.

**Comment by Wilyicaro** [comment]
Nope, the brackets aren't swapped, the left bracket is for cycling left and right bracket is for cycling right, if the key doesn't match the same one on your keyboard, there's nothing I can do, it's a GLFW problem

**Comment by Cjnator38** [comment]
I dug into the .jar file for the mod and it seems that the left and right bracket keys are simply named incorrectly
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/49c8e690-c6f8-494d-a4b2-35cb825a51c5)

**Comment by Cloud5474** [comment]
Yeah that’s what I meant
