### ISSUE TITLE
[bug] Pressing E closes GUI.

### ISSUE THREAD

**Issue by PeytonMinecraft** [Wilyicaro/Legacy-Minecraft#252]
When trying to name an item, pressing the E button closed the menu instead of typing an E in the text box.

**Comment by Wilyicaro** [comment]
If you are referring to Anvil, it isn't true, because if you place an item and press "E" or "I", this will not happen, but the Cartography Table really has this problem, but as you are talking about items in general, I imagine you don't refer to it
