### ISSUE TITLE
[Solve problem?]  "Сonsole gamer" wanna play with console things with java only gamers.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#253]
_I came across this problem with my server._ 
I think, i pretty know why only classic craft for servers. But. What if i wanna play with console crafting on my _java server_. A vanilla one, but with allowed a console gui things from client who have mod..?

Like, when i install legacy mod on my server - crafting starting working. But... People who don't wanna experience the console - now need install "legacy" mod to connect my server. So... 
Can we figure out what we can do with this? Create like a addon-mod that's allowed clients things on server.. Or... Idk..

I'm sure that's combining both sides will be great. Who java - java. Who console - can feel even better on the server.

**Comment by Wilyicaro** [comment]
You can still play with a vanilla player (or java, for you to better understand) using the mod on the server, I won't technically explain why it doesn't support Classic Crafting on a server without the mod (it should be something obvious), but in short this would be considered a cheat anyway
