### ISSUE TITLE
trading bug

### ISSUE THREAD

**Issue by T4zey** [Wilyicaro/Legacy-Minecraft#255]
When i try to trade the game kicks me out to menu with a message Connection Lost Internal Exception java.util.ConcurrentModificationException: Async entity load

**Comment by Wilyicaro** [comment]
It's probably a incompatibility with some "optimization" mod, I can't do much.

**Comment by paperoll** [comment]
I would like to say that when I re-enabled the new trades in .minecraft/.config/VillagerConfig/villagerconfig.json5 this issue appeared, the kick is only because of the "Legacy4J" mod.
