### ISSUE TITLE
Significant FPS decrease on 4k

### ISSUE THREAD

**Issue by KashiraFur** [Wilyicaro/Legacy-Minecraft#256]
1080p, I usually get around 200-350 FPS on max settings, but if I try to switch to a higher resolution, the framerate drops significantly, down to 30-50 fps. 
4k
![2024-05-05_15 42 03](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168997375/702e67f2-2e85-4c1f-909a-95f9600940c2)
1080p
![2024-05-05_15 42 22](https://github.com/Wilyicaro/Legacy-Minecraft/assets/168997375/ce75bb9b-a6c4-41e5-b990-ce3de1353d1b)

**Comment by Wilyicaro** [comment]
I would be surprised if you didn't have this drop in FPS, Gamma is responsible for this, when increasing the resolution of your screen, this shader will have more "difficulty" doing its "work".
