### ISSUE TITLE
Split screen

### ISSUE THREAD

**Issue by NotThatRqd** [Wilyicaro/Legacy-Minecraft#257]
I remember playing Legacy Console Edition with my sibling and it would be magical if I could relive that with them using split screen. Not sure if this is where to ask for split screen or if split screen would be something for the ReConsole mod pack

**Comment by Cloud5474** [comment]
There is a suggestions channel in the discord for stuff like this, and splitscreen has been talked about among developers. The mod is compatible witth nucleus coop for now so you can use that

**Comment by Wilyicaro** [comment]
Unfortunately, suggestions need to be made on the Legacy4J Discord server in order to better organize GitHub for _issues_ and incompatibilities only (please note that suggestions prior to the creation of this server will be kept)
