### ISSUE TITLE
Nintendo Switch controllers having improperly mapped joystick range and analog movement locking to cardinal directions

### ISSUE THREAD

**Issue by ladmantis** [Wilyicaro/Legacy-Minecraft#258]
When using a Nintendo Switch Pro controller, the expected range of input for the joystick is larger than what's possible, and thus movement is always limited to a slow walk, unable to run.
As for joysticks in general, while this was only tested with the mod's native Switch Pro Controller support and an XInput version of the same controller, analog input doesn't appear to be handled properly. Holding slightly in any of the 8 directions normally possible with WASD will move the character slowly, but it starts running into issues beyond that. If you hold full up and then very slightly to the left/right, then it won't actually move you in those directions. It will simply make you walk slower, as the joystick is being held in a position that has a lower y-coordinate. Once you do reach the threshold to move diagonally things begin to work again. Full analog input in all 360 degrees appears to work the moment any diagonal input is held. This behavior is not present in Legacy Console Edition, as tested on Minecraft Wii U Edition. There is no locking towards moving straight forward unless another direction is held.

**Comment by Wilyicaro** [comment]
It's a GLFW problem (API used in the last version to support controllers), I can't do anything about it, just switch to SDL (another API)
