### ISSUE TITLE
Game Crashes When I Sleep

### ISSUE THREAD

**Issue by Garsash** [Wilyicaro/Legacy-Minecraft#261]
Whenever I try to sleep in a bed the game crashes. It starts to do the sleep animation and it displays the sweet dreams advancement but almost immediately after that it crashes. I'm using Re-Console.

**Comment by Wilyicaro** [comment]
No additional information was given, and I've never seen this happen to anyone in any version, other than this being Legacy4J's GitHub, not Re-Console
