### ISSUE TITLE
Controller input speed

### ISSUE THREAD

**Issue by FruitChips** [Wilyicaro/Legacy-Minecraft#263]
When I plug in an Xbox One controller and use directional inputs on menus like the main menu and crafting, it's really fast. The d-pad skips every other selection when used. Is there a way to lower the sensitivity of the input speed?

**Comment by Zapiltar** [comment]
This could be an issue with Steam if you have it installed. Steam is known to cause issues with gamepad inputs in non-steam games. Closing steam via the icon tray could resolve the issue

**Comment by Wilyicaro** [comment]
It's a Steam input issue, I only have xbox controllers and I don't have any problems with them

**Comment by Auxy6858** [comment]
> This could be an issue with Steam if you have it installed. Steam is known to cause issues with gamepad inputs in non-steam games. Closing steam via the icon tray could resolve the issue

I've had the same issue in other games, you can download a community made controller bind for when you're not in game that binds all the buttons to nothing
