### ISSUE TITLE
switch joycons dont work at all for me

### ISSUE THREAD

**Issue by FuryFurryMCModder** [Wilyicaro/Legacy-Minecraft#265]
the switch joycons dont detect while connected via bluetooth

**Comment by Daralexen05** [comment]
Have you tried to use them with the grip while connected to a cable?

**Comment by ladmantis** [comment]
> Have you tried to use them with the grip while connected to a cable?

Unfortunately, that isn't possible. The grip is literally just a piece of plastic that holds the two together. The Joy-Cons don't behavior any differently while using them. Software is needed to take 2 separate Joy-Con controllers to treat them as one. That is something that might be possible in Legacy4J, but it is ambiguous which connected should be merged into one. For now, Steam Input would be a good temporary solution.

**Comment by Wilyicaro** [comment]
It's a problem with GLFW (API used in the last version to support controllers), I can't do anything about it, just switch to SDL (another API) and I still can't guarantee that it will work, as I don't have access to that controller
