### ISSUE TITLE
Server-side issue on vanilla clients

### ISSUE THREAD

**Issue by Spicytin** [Wilyicaro/Legacy-Minecraft#266]
If the vanilla player drops any item in (fabric) L4J server, they instantly disconnect with the message on their screen:

`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Can't find element with id 1542`

Vanilla players near the dropped item (or when the fabric player drops it near them) get disconnected too, but anyone who uses the mod are unaffected in the server.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.3, thanks for reporting.
