### ISSUE TITLE
The Yellow splashtext on the main menu should change everytime the user presses "Play Game" or any of the other options but then backs out into the main menu

### ISSUE THREAD

**Issue by DaAceGamer** [Wilyicaro/Legacy-Minecraft#269]
In the video below, you can see how whenever I press on any of the menu buttons but then go back to the main menu, it preserves the splashtext
https://github.com/Wilyicaro/Legacy-Minecraft/assets/74100324/11374913-63eb-49ef-9740-9175285ed706
This does not happen in the legacy editions of Minecraft
Comparison with Xbox One Edition below:
https://github.com/Wilyicaro/Legacy-Minecraft/assets/74100324/60ca873a-4d2a-45d3-9e17-be58b02c5ff7

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.3, thanks for reporting
