### ISSUE TITLE
Mixin conflict

### ISSUE THREAD

**Issue by isXander** [Wilyicaro/Legacy-Minecraft#270]
https://github.com/Wilyicaro/Legacy-Minecraft/blob/1.20.4/common/src/main/java/wily/legacy/mixin/CreateWorldScreenMixin.java#L99

Here you are overriding init completely, which makes any mods that inject here fail hard. An easy solution is to just inject at `HEAD` and always cancel.

Related issue isXander/Controlify#310

**Comment by DanielMC101** [comment]
Why would you want controlify tho?

**Comment by isXander** [comment]
> Why would you want controlify tho?

I bet this isn't exclusive to Controlify, and to answer your question: Controlify is a significantly more powerful controller mod than what is included in this mod, such as vibration.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.3, thanks for reporting!
