### ISSUE TITLE
Can't sprint a few seconds after entering a new world

### ISSUE THREAD

**Issue by Jappawastaken** [Wilyicaro/Legacy-Minecraft#273]
I've checked/changed key binds and tried with and without toggle sprint but every time I join a world, immediately or after 10 seconds I can't sprint no matter what. Only fix I've seen on GitHub and the discord is to remove controller software on the PC but I don't have any in the first place.

**Comment by Wilyicaro** [comment]
I disabled sprint in version 1.6.6b, which is not a common update, but one to celebrate the anniversary of LE, more specifically the Xbox 360 Edition, which did not have sprint in the first version
