### ISSUE TITLE
Cannot Sprint

### ISSUE THREAD

**Issue by Adunaio** [Wilyicaro/Legacy-Minecraft#274]
For whatever reason sprinting doesn't work at all for me. I tried re-binding spring on the controller and keyboard but nothing works. Maybe I am missing something? The only other mod I have installed is windowed borderless which doesn't seem to work lol. Ill try removing it and seeing if it fixes the issue.

**Comment by Wilyicaro** [comment]
I disabled sprint in version 1.6.6b, which is not a common update, but one to celebrate the anniversary of LE, more specifically the Xbox 360 Edition, which did not have sprint in the first version
