### ISSUE TITLE
Exit game button has artifacting (playing in 4k)

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#276]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101886628/179a30b0-3acf-4830-85b3-afd2a26b9766)

**Comment by G01dY05h1** [comment]
(actually applies to any button that is in that spot)

**Comment by Wilyicaro** [comment]
Manually edit the Interface Resolution in options.txt to 1.0 and see if this continues (Idk if you changed this)
Also, were there artifacts in 4k resolution in the previous version?
And please don't report anything related to artifacts on GitHub, "fixing" this is out of my scope as I don't have all the screen resolutions, the only thing I can do is make small tweaks.

**Comment by G01dY05h1** [comment]
> Manually edit the Interface Resolution in options.txt to 1.0 and see if this continues (Idk if you changed this) Also, were there artifacts in 4k resolution in the previous version? And please don't report anything related to artifacts on GitHub, "fixing" this is out of my scope as I don't have all the screen resolutions, the only thing I can do is make small tweaks.

Changing this has corrected that specific issue, but now most things appear slightly too small and other things simply look off. This was not an issue in the previous update

**Comment by G01dY05h1** [comment]
> > Manually edit the Interface Resolution in options.txt to 1.0 and see if this continues (Idk if you changed this) Also, were there artifacts in 4k resolution in the previous version? And please don't report anything related to artifacts on GitHub, "fixing" this is out of my scope as I don't have all the screen resolutions, the only thing I can do is make small tweaks.
> 
> Changing this has corrected that specific issue, but now most things appear slightly too small and other things simply look off. This was not an issue in the previous update

However, Changing this setting, then modifying the same setting in game to "100%" has fixed my issue

**Comment by Wilyicaro** [comment]
Interesting, I applied the tweak in 4k resolution because someone told me that in this resolution there were artifacts in the previous versions, it will be removed in the next version
