### ISSUE TITLE
Some text have drop shadows when they should not have dropshadows

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#277]
(example: text that appears when hovering over items)

**Comment by Wilyicaro** [comment]
This is definitely not a problem, it's more of a suggestion of parity, I imagine you noticed in this version that the shadows are more visible

**Comment by G01dY05h1** [comment]
> This is definitely not a problem, it's more of a suggestion of parity, I imagine you noticed in this version that the shadows are more visible

yes
