### ISSUE TITLE
Panoramas are broken

### ISSUE THREAD

**Issue by Permdog99** [Wilyicaro/Legacy-Minecraft#278]
Panoramas aren't blurry, pixelated, and lag when moving.

![2024-05-10_18 00 49](https://github.com/Wilyicaro/Legacy-Minecraft/assets/34215218/b6a0522b-ac22-40f9-a6d7-cb6b85bc90bb)

**Comment by Wilyicaro** [comment]
This is definitely some incompatibility, since I'm not having this, I didn't make changes to the panorama, I saw a screenshot of someone having the same problem
