### ISSUE TITLE
Crafting Tables Unusable

### ISSUE THREAD

**Issue by Jeb529** [Wilyicaro/Legacy-Minecraft#279]
In fabric servers with the latest legacy4j version, crafting menus completely stop working, and if you hold down the keybind to open it while walking, the server thinks you are in the same place you were when you pressed it if you rejoin.

**Comment by Wilyicaro** [comment]
It's not true, I just tested it now and it's working normally, you need to update the mod on the server and on the client for this to work, as changes have been made to this issue

**Comment by Jeb529** [comment]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/90934981/f74fc167-10ef-49f5-aea4-47ae453740d8)

I got this error when opening the crafting menu in singleplayer
