### ISSUE TITLE
Hints incorrectly categorized as "In-Game Tooltips"

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#28]
In Legacy Console Edition, the popups in the corner when looking at new blocks are controlled by the "Hints" setting. Controller button icons in menus to tell you what to press are controlled by "In-Game Tooltips". The setting to disable Hints is named incorrectly in this mod.

(Side note: I have so many assets in Console Aspects that you have full permission to use in this mod. If you contact me directly, I can give you detailed explanations for how these assets should be implemented. There are many sounds and texture differences in Legacy compared to Java today!)

**Comment by Wilyicaro** [comment]
Thanks for reporting this mistake, for some reason I thought In-Game Tooltips changed this behavior.
I came to know through your resource packs, particularly Console Aspects, and I'm very grateful for you offering your help in implementing *aspects* from your BE resource pack
