### ISSUE TITLE
2 bugs with the loom in the 1.6.3a

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#280]
So firstly, after creating the banner pattern, then selecting different or same banner. It will apply the same exact pattern as you've already selected from last time. And secondly, the crafting fail sound plays after creating the banner pattern in loom.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/026f9e56-bfee-4ccd-b82f-b5b008488131

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3, thanks for reporting.
