### ISSUE TITLE
Game thinks headset is a controller

### ISSUE THREAD

**Issue by SnowyBoi64** [Wilyicaro/Legacy-Minecraft#282]
I use a turtle beach bluetooth headset and i have a usb that plugs into my computer, and whenever it's plugged in it recognizes it as a controller. This makes it so i cant use my mouse in certain menus like the pause menus and the world screen menus. Is this fixable hopefully?

**Comment by SnowyBoi64** [comment]
This is only a new problem btw this didnt happen before

**Comment by Wilyicaro** [comment]
Certainly a problem with SDL, or not, maybe it's intentional, but anyway just change the controller used in the slider in Controller section

**Comment by SnowyBoi64** [comment]
thank you i probably would've taken a bit to figure that solution out
