### ISSUE TITLE
Sneaking is no longer toggleable when jumping

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#284]
So basically, when you have toggle sneak on game options, then when jumping when on surface, it's not toggleable as it used to.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/033695a8-f8ac-4d50-849d-5137aa1c4a7c

**Comment by Wilyicaro** [comment]
Fixed in version 1 6.3b, thanks for reporting.
