### ISSUE TITLE
when exiting without saving, the world is saved but the player isn't

### ISSUE THREAD

**Issue by Un1q32** [Wilyicaro/Legacy-Minecraft#286]
This can lead to lost items by for example destroying a chest and collecting the items and then exiting without saving, the chest is still gone but your inventory doesn't have the items.

Can also be used to dupe by placing items in a chest then rolling back to when those items were still in your inventory.

**Comment by Un1q32** [comment]
This is a bit more complicated then i thought, the dupe instructions dont work with chests, placed furnaces will stay but the inventories don't.  The inventories do stay sometimes but I don't understand how.  When it first happened to me the furnaces didn't exist in the saved world but existed and were cooking items in the unsaved world.

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3b, thanks for reporting
