### ISSUE TITLE
other versions of english doesn't copy everything from en_us

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#288]
so it does seem like that not everything is copied from the en_us to have a proper legacy console texts like tooltips saying "inventory" instead of "open/close inventory" and also host privillages instead of "allow cheats"
![2024-05-10_23 07 09](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4a8c8096-c0ab-49bf-84e6-6fe19d3cbad8)
![2024-05-10_23 06 59](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/7bddb3d2-fcea-4ef3-bc7a-27e80df2ea74)

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4cd6fece-008c-48b8-9844-a12c3f22bfdc

**Comment by DanielMC101** [comment]
here's the files for the copied en_us to other versions of english
[en_nz.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/15281683/en_nz.json)
[en_au.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/15281684/en_au.json)
[en_ca.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/15281685/en_ca.json)
[en_gb.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/15281686/en_gb.json)

**Comment by Wilyicaro** [comment]
It's not necessary to copy everything, just what was modified from the vanilla translations, I ended up forgetting the ones you mentioned
