### ISSUE TITLE
Game input is not moved when window is out of focus

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#289]
Currently, in both L4J 1.6.3a with SDL and Re-Console 0.2.4 with L4J 1.6.2a and GLFW, moving focus outside of the game window does not move controller input away from it. Not only does this cause unintentional keypresses, but stops utilities like the Steam OSK from working.

Steam Input is enabled in the first video, but with the “Desktop Layout” set to as controller buttons instead of KBM inputs. Client using Re-Console 0.2.4.
Second video is with the Steam client closed, just to show that it isn’t a Steam Input issue. Client using Legacy4J 1.6.3a.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/69744081-37e7-49ee-bdfc-056b6bdbdff6

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/8ee6b5e6-fb26-4155-8bb6-9bb2f9bb94bd

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3b, thanks for reporting

**Comment by NIMFER** [comment]
hey, is it possible to have background input processing as a toggle, that'd be nice for makeshift split-screen with 2 instances of the game running
