### ISSUE TITLE
Looking into a book makes the wrong sound

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#291]
If you open a book, it plays the legacy:random.focus instead of the LCE clicking sound.
Note: This happens when opening the chat too, though you cannot type into chat on LCE.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/86b67862-c3af-44f3-ab2a-40fd008afe1a

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/c8e2a7cf-88df-4b18-9ca7-3a746411f868

**Comment by Wilyicaro** [comment]
If you're referring to what's happening, yes, that's right, but it's incorrect to say that I "swapped" the focus sound with the click sound (which you can understand), that was a coincidence, there simply isn't the click sound, as it is not a menu (screens with slot), this will be added in the next version

**Comment by bugsbugsbugsLCE** [comment]
I didn't say that you "swapped" the sounds. I meant that it plays the scroll sound (or however you want to call it) instead of the select sound.
