### ISSUE TITLE
Random white lines appear in parts of the UI on steam deck

### ISSUE THREAD

**Issue by Un1q32** [Wilyicaro/Legacy-Minecraft#294]
![PXL_20240511_092032212.jpg](https://github.com/Wilyicaro/Legacy-Minecraft/assets/57970114/06b3886b-7a86-4886-82f5-21f2e499dc3e)

![PXL_20240511_092016791.jpg](https://github.com/Wilyicaro/Legacy-Minecraft/assets/57970114/d69ff64f-dbf1-4b44-943a-f5ea05342149)

**Comment by Wilyicaro** [comment]
just screen artifacts, adjust your Interface Resolution
