### ISSUE TITLE
Exitting the advancements and statistics menu with ESC closes the entire UI.

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#295]
If you press ESC while you are in the advancements or statistics menu, it closes the pause menu instead of going back one section like the other menus. I assume that statistics will be replaced by the leaderboards menu at some point.
https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/83fded0b-3d26-4153-ac81-29690fcc3c63

**Comment by Wilyicaro** [comment]
This isn't a bug, this is present in the JE, and I don't modified these screens

**Comment by bugsbugsbugsLCE** [comment]
Ok but if the leaderboards menu is added, this should probably be changed for that menu.

**Comment by Wilyicaro** [comment]
ofc

**Comment by bugsbugsbugsLCE** [comment]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/1e19291e-b3e6-4566-b912-3c8a400fc03a

This doesn't happen in vanilla in 24w21b.

**Comment by Wilyicaro** [comment]
Good thing they fixed this in 1.20.5-6
