### ISSUE TITLE
Can't fly up using the jump key while gliding in creative mode after dying

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#296]
I am unsure how exactly this works but sometimes if I die, I am unable to use the feature where you can fly up with the elytra using the jump key in creative mode. If I die in survival or adventure mode while gliding with an elytra with keepInventory on, it doesn't work anymore after respawning and going into creative mode. Relogging fixes it.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/0571bd31-91c0-45c9-89e6-c58f6e83a684

**Comment by bugsbugsbugsLCE** [comment]
This also seems to cause you to have Java's flying mechanics instead of the ones from LCE.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
