### ISSUE TITLE
Hover events don't work in the death screen

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#297]
If renamed items or entities are mentioned in death messages, you can hover over them to see corresponding tooltips. In vanilla this works in the death screen too. For items it displays the tooltip of the item as if it was in the inventory and for entites it displays the UUID. However with the mod this only works in the chat, not in the death screen. I know you cannot hover over text in death messages on LCE but was this functionality removed with the mod on purpose? I don't think it makes sense to remove it.
![2024-05-11_12 14 58](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/073892fe-52d9-4ab6-85b3-a188fb835042)
![2024-05-11_12 15 02](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/87cea9bc-ddec-4536-84fe-1ba2e9f2e431)
![2024-05-11_12 16 53](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/dcd1e478-8804-49d2-b5f3-820f2c5e5168)
![2024-05-11_12 21 06](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/eec47544-7521-407a-9a44-a4613035141d)
![2024-05-11_12 21 13](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/f22ee0d8-849b-437a-b701-28be0b853009)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.6, thanks for reporting!
