### ISSUE TITLE
"Swap Huts" typo

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#298]
There is a small type seen in the superflat world creation menu. It says "Swap Huts" instead of "Swamp Huts". The vanilla game doesn't seem to have translation keys for the structure names.
![2024-05-11_12 38 49](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/3437320e-4781-45ae-99bb-78236e920d74)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
