### ISSUE TITLE
Custom Toast is tied to the framerate

### ISSUE THREAD

**Issue by DBTDerpbox** [Wilyicaro/Legacy-Minecraft#3]
The custom toast for "Work in progress!!" Is tied to the framerate, resulting in it disappearing faster at higher framerates

https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/4722d2ba-41d4-49ac-a97a-52a9d317c57a

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it was fixed in 1.1.1
