### ISSUE TITLE
I've noticed that there's like 6 missing enchantment books from the legacy console creative menu.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#30]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4f51f51c-f9ce-4242-a392-52d662bde24b

**Comment by Wilyicaro** [comment]
Can you list them for me? I don't remember, as this organization wasn't made by me

**Comment by DanielMC101** [comment]
> Can you list them for me? I don't remember, as this organization wasn't made by me
Quick shot III
Piercing IV
Multishot
Sweeping edge III
Swift sneak III
Soul speed III
