### ISSUE TITLE
Chat is inaccurate

### ISSUE THREAD

**Issue by Appl26J** [Wilyicaro/Legacy-Minecraft#301]
The one in Legacy Console Edition has more spacing between lines, or more margin.
Also the lines should extend horizontally till the width of the window, but it could be made toggleable for people.
Awesome mod though!

**Comment by Appl26J** [comment]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/169542541/2be7e50c-4134-4b2a-9294-b8562f84c041)
for reference

**Comment by Wilyicaro** [comment]
Just change chat spacing, GitHub isn't place for suggestions

**Comment by Appl26J** [comment]
> Just change chat spacing, GitHub isn't place for suggestions

"The main objective of this project is remake every aspect of Legacy Console Edition in 1:1 for Java Edition versions, adding its exclusive features, and bringing it to modern versions." - README.md

this is the problem when only one person manages stuff lol you broke your own sentence

**Comment by Wilyicaro** [comment]
> > Just change chat spacing, GitHub isn't place for suggestions
> 
> "The main objective of this project is remake every aspect of Legacy Console Edition in 1:1 for Java Edition versions, adding its exclusive features, and bringing it to modern versions." - README.md
> 
> this is the problem when only one person manages stuff lol you broke your own sentence
I didn't break any sentences, this is a simple option to be changed in the User Interface, I didn't change its default value, as most people will anyway use the mod with options already defined (including the chat spacing). And I don't know if you know, but 1:1 is a proportion, and not an obligation to be 100% identical, as that is impossible
