### ISSUE TITLE
Loom interface, and crafting interface when going into different tab, the selection doesn't start from the beginning

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#302]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/d243b7d0-e253-497b-b81e-b95305ab8455

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/8f5723d2-6f1a-48e7-bf09-1d13c092d492

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
