### ISSUE TITLE
Holding down the button on crafting, and stone cutter interface no longer repeats pressing.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#303]
So basically on console edition, when holding down the button on crafting interface and stone cutter, it no longer repeats. I hope you can fix this without conflicting other stuff like jumping, etc.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/498c7f2a-1fad-44cd-80ea-1260efcf2201

**Comment by Un1q32** [comment]
Same issue here, very annoying to have to spam the button

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
