### ISSUE TITLE
After dying, it switches to default java edition creative flight.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#304]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/ecc139b3-fd99-4079-954b-9692066933ef

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/d437edfb-8166-4683-9f29-8ef790e0252c

**Comment by DanielMC101** [comment]
Oh and idk if it's just me, but the controller seems to disconnect and reconnect on occasion, as that's what happened on the first video of this post.

**Comment by bugsbugsbugsLCE** [comment]
I think this is the same issue as https://github.com/Wilyicaro/Legacy-Minecraft/issues/296. This issue also gets rid of the ability to fly up with the elytra by pressing the jump key.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
