### ISSUE TITLE
Using the right trigger for "what's this" takes the item on inventory, and creative menu.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#305]
So basically, the right trigger on inventory takes the item which makes it impossible to get "what's this" hint and when on creative menu, it takes the item by pressing the right trigger which isn't supposed to happen. And also, doesn't really seem to affect other interfaces.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/b2605f24-e507-4e46-a5bd-1034422609ac

**Comment by Un1q32** [comment]
in survival it takes half the stack

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
