### ISSUE TITLE
Gamma at 49% is brighter than 50%

### ISSUE THREAD

**Issue by TrenchcoatCraig** [Wilyicaro/Legacy-Minecraft#307]
Title. Version 1.6.3c

https://github.com/Wilyicaro/Legacy-Minecraft/assets/148669985/180e599a-aa7f-4351-a946-5ad3c846b28a

**Comment by Wilyicaro** [comment]
In 0.5 it's disabled, for people that doesn't like it

**Comment by skedgyedgy** [comment]
-- that's really weird behavior to be intentional
