### ISSUE TITLE
Update 1.20.6-1.20.5

### ISSUE THREAD

**Issue by ShrikerChestTrees** [Wilyicaro/Legacy-Minecraft#309]
1.20.6-1.20.5 came out so long ago that you didn't even pay attention to it so please make support for these versions.
I will be glad if you add it!

**Comment by ShrikerChestTrees** [comment]
If you are not going to add support for new versions then give me a reason why.

**Comment by DanielMC101** [comment]
@ShrikerChestTrees patience please. it will support eventually.

**Comment by Wilyicaro** [comment]
These versions will be supported, I'm trying to make the mod as complete as possible before porting to any version

**Comment by ShrikerChestTrees** [comment]
Got it thanks for telling me!
