### ISSUE TITLE
Interface sensitivity is a bit low

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#311]
The sensitivity of the cursor when using controller seems quite low compared to last time

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/ea61beab-024b-4a7f-84f4-3b1df2b203e4

**Comment by Wilyicaro** [comment]
For me the speed at 100% is enough, at 200% it's very fast

**Comment by DanielMC101** [comment]
@Wilyicaro oh btw, is it just me? or does the controller disconnects and re connects again? like it just happened in the video

**Comment by Wilyicaro** [comment]
Never happened to me, if it's bluetooth, that could be the problem

**Comment by DanielMC101** [comment]
@Wilyicaro and yes i am using bluetooth
