### ISSUE TITLE
Trading on server doesn't really work even if server has mod installed.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#312]
So recently while playing in the unofficial re-console discord server, trading doesn't seem to work, last time it even kicked me out to the  menu when attempted to trade, and it did go through, now second time i try to trade, it doesn't do anything.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/29cb1f3d-3240-4c05-845a-9ba1123aaaad

**Comment by Wilyicaro** [comment]
It's not true, it's working normally, this could be due to some modpack incompatibility or the mod is not updated on the server

**Comment by Wilyicaro** [comment]
Preferably when it is something related to a server with the mod, it is better for the host owner to make the issue himself, as he has more knowledge about
