### ISSUE TITLE
Crashes shortly after launch on PojavLauncher, Fabric 1.20.4 (Fabric Loader 0.15.11)

### ISSUE THREAD

**Issue by HunterBoy344** [Wilyicaro/Legacy-Minecraft#315]
Here's the log from when I tried to run it:
[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/15284490/latest.log)

Device is a Samsung Galaxy S20 Ultra running Android 11.

Made sure to include Fabric API and Architectury API using the exact same files that worked on my PC for this mod. Would really love to see this fixed, since Legacy on mobile would be a dream come true!

**Comment by omo50** [comment]
Pojav is not supported

**Comment by HunterBoy344** [comment]
Why isn't it? Would really like to run this on mobile

**Comment by omo50** [comment]
Pojav has numerous issues, mod compatibility problems, etc.

Ask around and no mod dev will support this. I do not support Pojav with the official modpack personally. I reccomend using a laptop or Handheld system (like the steam deck) if possible

**Comment by Wilyicaro** [comment]
In reality, this is a simple SDL problem on Linux, if you use 1.6.2a it will work normally.

**Comment by HunterBoy344** [comment]
> In reality, this is a simple SDL problem on Linux, if you use 1.6.2a it will work normally.

Will try, thank you! Just curious, what was changed after version 1.6.2a that broke Linux SDL support? Are there plans to restore support in future updates?

**Comment by Wilyicaro** [comment]
In reality, GLFW was previously used, now that Legacy4J supports SDL as well, which is clearly superior.
Maybe before working on a fix, I'll add an option to use GLFW (which is currently only used on mac)
