### ISSUE TITLE
PS3 Controller

### ISSUE THREAD

**Issue by ShrikerChestTrees** [Wilyicaro/Legacy-Minecraft#317]
Your mod doesn't support PS3 controllers (Sixaxis, Dualshock 3) from 2023.
 
It is very strange that “R3” is “x” and “L3” is “o” etc...
In addition some buttons don't work like “x”, “o” and “PS”.

 
Please fix it and by the way it is in all mods to support controllers like this.

**Comment by Wilyicaro** [comment]
I don't have a PS3 controller and saying it works on all controller support mods is a bit much, isn't it? 
There are several support mods for controllers, I really doubt that I have tested them all to find out, anyway, there is no way for me to test anything if I don't have the controller, so information about it would be very helpful, such as what system you use , what mods have you tested and the version of the mod, modloader, etc. All of this can influence its performance.

**Comment by ShrikerChestTrees** [comment]
> I don't have a PS3 controller and saying it works on all controller support mods is a bit much, isn't it? There are several support mods for controllers, I really doubt that I have tested them all to find out, anyway, there is no way for me to test anything if I don't have the controller, so information about it would be very helpful, such as what system you use , what mods have you tested and the version of the mod, modloader, etc. All of this can influence its performance.

OS - Windows 11
Mods - Controlify from 1.7.0 to the new version, Legacy 4J with modpack Re-Console latest version and MidnightControls latest version.
Mod Loader - Fabric 0.15.11
Version - 1.20.4
Further I do not know what to say more.

**Comment by ShrikerChestTrees** [comment]
> > I don't have a PS3 controller and saying it works on all controller support mods is a bit much, isn't it? There are several support mods for controllers, I really doubt that I have tested them all to find out, anyway, there is no way for me to test anything if I don't have the controller, so information about it would be very helpful, such as what system you use , what mods have you tested and the version of the mod, modloader, etc. All of this can influence its performance.
> 
> OS - Windows 11 Mods - Controlify from 1.7.0 to the new version, Legacy 4J with modpack Re-Console latest version and MidnightControls latest version. Mod Loader - Fabric 0.15.11 Version - 1.20.4 Further I do not know what to say more.

On the back of this controller it says this:
SONY model no CECHZC2E b1
WIRELESS CONTROLLER
dc 5v 500mA

MADE IN CHINA
ZW610104311199

**Comment by ShrikerChestTrees** [comment]
I checked on older PS3 controllers and the same thing happens.

**Comment by ShrikerChestTrees** [comment]
I think the problem is in the version of minecraft or the mod loader fabric...

**Comment by ShrikerChestTrees** [comment]
In 1.19.4 (2023) the Controllify mod worked fine.

**Comment by ShrikerChestTrees** [comment]
I realized that it wasn't the version, but the controller support itself. 
I fixed it, that's why all I was saying was that it was due to a bug in the support application for that controller!
