### ISSUE TITLE
Player turns with any entity when riding

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#320]
Due to the addition of player turning with the minecart, the player turns with any entity they are riding, while it should only work with minecarts (and boats). Notably riding pigs, striders untamed horses or even random entities using the /ride command causes the player to turn whenever the entity turns horizontally.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/00e59d40-b828-426d-903e-0854e58f9a71

**Comment by Wilyicaro** [comment]
Considering that nothing is an issue if it is intentional, then this will be closed

**Comment by Wilyicaro** [comment]
Of course this will be considered, but it is still a parity suggestion

**Comment by bugsbugsbugsLCE** [comment]
Well it seemed unintentional to me but it doesn't matter if it's gonna be changed.

**Comment by TheKamboy** [comment]
> Of course this will be considered, but it is still a parity suggestion

i hope this will be a setting because its annoying with certain minecart situations

**Comment by Wilyicaro** [comment]
> > Of course this will be considered, but it is still a parity suggestion
> 
> i hope this will be a setting because its annoying with certain minecart situations

Good idea, but this issue wasn't about this

**Comment by TheKamboy** [comment]
> > > Of course this will be considered, but it is still a parity suggestion
> > 
> > 
> > i hope this will be a setting because its annoying with certain minecart situations
> 
> Good idea, but this issue wasn't about this

Minecarts ARE entities though, and the issue is about entities.

**Comment by Wilyicaro** [comment]
> > > > Of course this will be considered, but it is still a parity suggestion
> > > 
> > > 
> > > i hope this will be a setting because its annoying with certain minecart situations
> > 
> > 
> > Good idea, but this issue wasn't about this
> 
> Minecarts ARE entities though, and the issue is about entities.

The title may even imply this, but if you read the issue itself you will know that the problem is that this applied to living entities as well.
