### ISSUE TITLE
Incompatible with Sodium or it's open source derivatives

### ISSUE THREAD

**Issue by EvanWilsonGithub** [Wilyicaro/Legacy-Minecraft#322]
When attempting to use Sodium, Rubidium, or any of the other Sodium ports, the game will keep causing the loading symbol to appear on the title screen every few seconds. Based on the fact that music restarts when this happens, I'd assume it is due to how resource packs are handled in Sodium.

**Comment by omo50** [comment]
qhar ?

**Comment by Wilyicaro** [comment]
This isn't happening
