### ISSUE TITLE
Stone Presure Plate appears in the crafting menu twice with the same recipe

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#324]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101886628/38de78cf-c58e-4ecd-b17f-e97f11cc86d1)

**Comment by BzzzThe18th** [comment]
able to reproduce immediately
[output.webm](https://github.com/Wilyicaro/Legacy-Minecraft/assets/69125495/a4138ede-e219-4a81-aa7a-eb945b27ec1c)

**Comment by BzzzThe18th** [comment]
https://github.com/Wilyicaro/Legacy-Minecraft/pull/374

**Comment by Wilyicaro** [comment]
Fixed in version 1.20.6-1.6.4, thanks for reporting.
