### ISSUE TITLE
Certain items do not hide from the menu after crafting an item from "Show Craftable Recipes" and then no longer having the required items

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#326]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101886628/ae008a6f-d1f6-4504-a387-723a6d421973)

(also happens with gold/iron nuggets)

(The items cannot be crafted despite appearing craftable, and the item is correctly removed once you reopen the crafting table or switch out and back into "Show Craftable Recipes" mode )

**Comment by BzzzThe18th** [comment]
I experience this as well with the stonecutter, a specific instance I remember is turning polished deepslate into deepslate brick stairs.

**Comment by BzzzThe18th** [comment]
reproduction:
[stonecutterstuckrecipe_.webm](https://github.com/Wilyicaro/Legacy-Minecraft/assets/69125495/482b0e13-8aa8-4787-ba6e-a77b66820b8d)
xbox one s controller
fabric
re-console

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
