### ISSUE TITLE
You can continue the "zoom out and clear" craft in cartography tables after it's maxed out

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#327]
For some reason you can keep putting a map through the "zoom out and clear" crafting method in the cartography table. Whenever you craft the map past the max level, it just wastes paper. This might be a base game issue.

**Comment by BzzzThe18th** [comment]
I think this is a base game **feature** rather than issue, it's not just zoom out as you said, it's also clearing the map, why not be able to clear it once you've zoomed out a certain distance?

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
