### ISSUE TITLE
Versions 1.6.3 and up crash on macOS (M1)

### ISSUE THREAD

**Issue by Hand-Lock** [Wilyicaro/Legacy-Minecraft#329]
Log: https://mclo.gs/L11gjVT

Previous versions work fine. 
Tested both on Re-Console and Legacy4J only install (removing Legacy4J >= 1.6.3 from Re-Console fixes the crash).

**Comment by ivabus** [comment]
[This](https://github.com/Wilyicaro/Legacy-Minecraft/issues/323#issuecomment-2112612647) fixes the problem.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
