### ISSUE TITLE
On NeoForge, you can't create patterns on loom at all.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#333]
I'm kinda surprised no one has ever noticed this

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/f8c252d2-06d0-4526-a883-8e4709119358

**Comment by BzzzThe18th** [comment]
works on fabric though :/
[output.webm](https://github.com/Wilyicaro/Legacy-Minecraft/assets/69125495/2cd1703b-c354-42d6-bb71-716c56b2e5b4)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
