### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by macedonianperson** [Wilyicaro/Legacy-Minecraft#336]
so when my game starts up, it immediately crashes. My device is Windows 10. Version 1.20.4, and the only file in my .mods section in %appdata% is the .jar file of the latest version. Exit code is 1. Would like to know how to fix

**Comment by Wilyicaro** [comment]
As described on all platforms where it is available for download, you need the Architectury API, and the Fabric API if you are using Fabric

**Comment by macedonianperson** [comment]
thanks, someone told me on the dc server
