### ISSUE TITLE
Jukebox can be heard infinitely in any direction and the background music does not stop while the jukebox plays

### ISSUE THREAD

**Issue by TreeStain0** [Wilyicaro/Legacy-Minecraft#337]
It's as the title says. Normally, the jukebox has limited range, but I ran away from my house and heard it tons of blocks away. It was also jarring because the normal Minecraft background music was playing at the same time, causing the two songs to overlap.

**Comment by Wilyicaro** [comment]
Not a Legacy4J issue

**Comment by Wilyicaro** [comment]
#103
