### ISSUE TITLE
On world template, when setting direct join to false, then after trying to load the world, it crashes the game.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#338]
Here's the crash log

[crash-2024-05-14_22.21.53-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15315512/crash-2024-05-14_22.21.53-client.txt)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
