### ISSUE TITLE
Mod incompatible with figura

### ISSUE THREAD

**Issue by S0apyy** [Wilyicaro/Legacy-Minecraft#343]
upon installation of the mod "figura" along side legacy4j the game crashes and leaves this crash log
[crash-2024-05-15_20.54.26-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15325899/crash-2024-05-15_20.54.26-client.txt)

**Comment by S0apyy** [comment]
looking closer this seems to be a rendering issue caused by l4j and figura combined, idk if this is fixable at all

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
