### ISSUE TITLE
game crashes when crafting items with a full inventory

### ISSUE THREAD

**Issue by izutsumii** [Wilyicaro/Legacy-Minecraft#345]

**Comment by angeld23** [comment]
Same here, when doing it on a server this is the error I get:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/59970528/62999ffe-4473-43a0-a071-db0e34d0ffc4)

**Comment by Wilyicaro** [comment]
#218 
Please, before sending an issue, see if there is another one about the same thing, that would help me a lot.
