### ISSUE TITLE
Mod crashes during loading

### ISSUE THREAD

**Issue by What-ZenZ14** [Wilyicaro/Legacy-Minecraft#347]
the game loads up for a single frame, and then crashes. This has happened for me on the forge, neo forge, and fabric versions of the game. The log i provided is for the last time i booted it up with fabric. 
I have tried disconnecting my ps4 controller from my pc, but that does not solve the issue.
Tried going through modrinth but it still refuses to load properly.  
I am on Windows 11
[2024-05-15-7.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/15327952/2024-05-15-7.log)
![mods folder](https://github.com/Wilyicaro/Legacy-Minecraft/assets/41239454/c5f7dfc3-cf19-4290-bc6b-d894ac762315)

**Comment by AdroitJackson** [comment]
I have the same problem actually it loads but crashes while loading it literally terminates it before it can even run

**Comment by PerryPlaysMC** [comment]
on Mac
Unhandled game exception
java.lang.UnsatisfiedLinkError: Unable to load library 'SDL2':
dlopen(libSDL2.dylib, 0x0009): tried: 'libSDL2.dylib'

And
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.forEach(HashMap.java:1424)
	at net.minecraft.class_1060.close(class_1060.java:173)
	at net.minecraft.class_310.close(class_310.java:1246)
	at net.minecraft.class_310.method_1490(class_310.java:1220)
	at net.minecraft.client.main.Main.main(Main.java:281)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MrTXD** [comment]
**I have an M1**, exact thing happened. Maybe it's only for M chips, idk some other apps does that on an M chip.

**Comment by Cjnator38** [comment]
There should be a note on the Modrinth page telling you how to install SDL2, as it's required but not pre-installed

**Comment by Cjnator38** [comment]
Wasn't on the main L4J mod page but the Re-Console Modrinth page has the instructions under "Important notes for MacOS users"

**Comment by AdroitJackson** [comment]
I dont use mac which makes this more confusing

**Comment by WubTheGame** [comment]
Solution for Windows users: Download the latest SDL from here and put it into your system32 folder (It wasn't already there for me, if it is for you I advise you rename the original in case anything happens). This should fix it. https://github.com/libsdl-org/SDL/releases/latest

For Mac users, I don't know if/how this translates to Mac, sorry.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
