### ISSUE TITLE
Whether to support Traditional Chinese and Simplified Chinese？

### ISSUE THREAD

**Issue by MiwuMeow** [Wilyicaro/Legacy-Minecraft#349]
I am a Chinese player. I found that when I switch the language to "Traditional Chinese" or "Simplified Chinese", there will be garbled characters, so I want to ask when Chinese will be supported.
![2024-05-16_18 54 17](https://github.com/Wilyicaro/Legacy-Minecraft/assets/66874885/b277cf8a-641e-4825-b072-4f345f752a72)
![2024-05-16_18 53 50](https://github.com/Wilyicaro/Legacy-Minecraft/assets/66874885/d4e1786d-0f69-4af7-ab39-e423e560fdf6)
![2024-05-16_18 59 49](https://github.com/Wilyicaro/Legacy-Minecraft/assets/66874885/3fc23af9-5621-4b8b-8135-34013a9662bc)
![2024-05-16_18 59 14](https://github.com/Wilyicaro/Legacy-Minecraft/assets/66874885/ce3893dc-87c9-460a-8f6c-1d2e6d1b8b2f)
![2024-05-16_18 59 53](https://github.com/Wilyicaro/Legacy-Minecraft/assets/66874885/84166c24-5c1d-4e4c-b7f3-a2d7d752dbe8)

**Comment by Wilyicaro** [comment]
Make a Pull Request with this language entries, I'm not a chinese speaker, so I can make wrong translations using tools for this
