### ISSUE TITLE
Main Menu Panorama Scroll Speed Inaccurate

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#35]
The main menu panorama on Legacy took exactly 136 seconds to complete one loop. The speed in the mod is faster than that.

**Comment by AgentMindStorm** [comment]
Affects 1.3. Due to the stretch fix, the duration has changed. It is now slightly _slower_ than Legacy.

Legacy time: 136s
Legacy4J mod time: 164s

**Comment by Wilyicaro** [comment]
I think it's now accurate in 1.3.1 version, so I'll close this issue

**Comment by AgentMindStorm** [comment]
Yes, I just timed it in 1.3.1 and it is now exactly 136 seconds. Excellent fix!
