### ISSUE TITLE
Game crashes instantly when trying to load

### ISSUE THREAD

**Issue by ebbe010** [Wilyicaro/Legacy-Minecraft#350]
When i start minecraft with the mod it loads for a while and then crashes with "exit code 1" before it starts. I have fabric, fabric api, and architectury api. What am i doing wrong?
![Skärmbild (110)](https://github.com/Wilyicaro/Legacy-Minecraft/assets/170002463/b1f5e0e3-7d47-478a-946f-e037b3aa2237)

**Comment by AdroitJackson** [comment]
still the same for me here hopefully this one isn't related to mac this time.

**Comment by Wilyicaro** [comment]
1.20.6?
