### ISSUE TITLE
Minecraft keeps crashing ill send my log files 

### ISSUE THREAD

**Issue by AdroitJackson** [Wilyicaro/Legacy-Minecraft#353]
I honestly need a concrete answer why this is happening.
[2024-05-16-7.log.gz](https://github.com/Wilyicaro/Legacy-Minecraft/files/15342392/2024-05-16-7.log.gz)

**Comment by AdroitJackson** [comment]
[latestlog.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15342452/latestlog.txt)

**Comment by AdroitJackson** [comment]
I've been having this issue fir days now

**Comment by Wilyicaro** [comment]
Use version 1.6.2a for now, your linux system (Android in this case) is using an outdated version of SDL for the game, which is causing this problem

**Comment by AdroitJackson** [comment]
I hope  you know how people play on android And thank you this genuinely helps
