### ISSUE TITLE
I need it for minecraft bedrock 

### ISSUE THREAD

**Issue by CARTGIT** [Wilyicaro/Legacy-Minecraft#354]
I would love to have an add-on similar to this but for minecraft bedrock since there is more compatibility with more things 👍🙏🙏👍

**Comment by Wilyicaro** [comment]
Sorry, that won't happen, currently what addons exist for Bedrock are more like Java Edition datapacks than mods, that is, very limited, and in reality the closest thing to this is with resource packs, I suggest trying CrisXolt's 4JD Project/Legacy Console UI

**Comment by CARTGIT** [comment]
OK thank you very much it was just question 👍
