### ISSUE TITLE
Villager trading is very broken. Duplicate items are created and don't stack.

### ISSUE THREAD

**Issue by AntMet57** [Wilyicaro/Legacy-Minecraft#356]
When trading with villagers, some trades out right don't work and the ones that do create duplicate items of whatever you get from the trade, causing multiple stacks of the same items that don't stack with each other. I'm currently playing on the latest fabric version on a server with friends. PLEASE fix this!!!

https://github.com/Wilyicaro/Legacy-Minecraft/assets/133797504/f03a2b5a-3ff0-48c8-abbc-8afba66b163f

**Comment by Wilyicaro** [comment]
You wrote and practically demonstrated nothing, much less gave enough information (such as the mod version, the modloader, etc.), clearly the items you were placing were different, whether it was not having NBT or a different name. This doesn't normally happen, I even just tested it.

**Comment by AntMet57** [comment]
Sorry, I've never went out of my way to report bugs before and it didn't even cross my mind to include that information.
