### ISSUE TITLE
Ingot section order doesn't really make sense

### ISSUE THREAD

**Issue by psychoshay** [Wilyicaro/Legacy-Minecraft#357]
List currently goes kelp, gold, iron, netherrite, copper, diamond etc which seems very wrong?

Ignore everything non vanilla I am making recipes for a mod
![Screenshot 2024-05-17 135723](https://github.com/Wilyicaro/Legacy-Minecraft/assets/169887728/3f7ab7ec-478a-4164-9a37-90eaac74b82c)

**Comment by Wilyicaro** [comment]
It's not wrong, almost the recipes in LE follow the order of addition and other requirements, in this case the ingots come first and the gems second (I wasn't the one who made this specific layout, I'm not defending it because I did it)
