### ISSUE TITLE
Credit Screen Background Does Not Match LCE

### ISSUE THREAD

**Issue by theminecraftarchitect** [Wilyicaro/Legacy-Minecraft#358]
The credit screen has the dirt background similar to Java Edition. However, LCE uses a special image corresponding to the title update. See images below

![JE Credit Background, 1.20.4](https://github.com/Wilyicaro/Legacy-Minecraft/assets/137523879/5e9b59d0-e896-4446-96df-769c235b8f5c)

![LCE Credit Background, TU69](https://github.com/Wilyicaro/Legacy-Minecraft/assets/137523879/c729b0e8-f321-4ae7-bce8-cba5c7e6dd3b)

**Comment by Wilyicaro** [comment]
This is not an issue, it's a parity suggestion, it will be considered, but I will close it for that reason
