### ISSUE TITLE
Enhancement: Split Screen (?)

### ISSUE THREAD

**Issue by SpectralPixel** [Wilyicaro/Legacy-Minecraft#360]
I know this is really far fetched, and would require some really big changes to how a lot of things work, but it would be a cool addition if this ever managed to make it into the modpack. I totally understand if this is way out of scope though; there's a reason that nobody has ever made a split screen mod for java, ever.

**Comment by BzzzThe18th** [comment]
iirc l4j is compatible with nucleus co-op, allowing for splitscreen

**Comment by BzzzThe18th** [comment]
> iirc l4j is compatible with nucleus co-op, allowing for splitscreen
https://github.com/Wilyicaro/Legacy-Minecraft/issues/257#issuecomment-2095051937 yep

**Comment by Wilyicaro** [comment]
#257
