### ISSUE TITLE
The game crashes when I press the “graphics” button

### ISSUE THREAD

**Issue by xNqcho** [Wilyicaro/Legacy-Minecraft#362]
Hello everyone, I hope you are well, I wanted to ask you for help with the Legacy4J mod, I installed version 1.20.4-1.6.3c (fabric), also the Architectury API version 1.20.4 v.11.1.17, and the Fabric API version 1.20.4 v0.97.0. I installed the Fabric Launcher correctly, then I started the game many times and every time I pressed the "graphics" button and directly em The game was closing, has anyone here experienced this error?

**Comment by Wilyicaro** [comment]
You need to send your crash report, there is no way to guess the error, I have never seen this happen, especially if there is no other mod than the ones you reported

**Comment by Blob1YT** [comment]
I got this aswell I am going to send the report over
[report.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15365242/report.txt)

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
