### ISSUE TITLE
Crafting menu does not work with controller shoulder buttons, exits menu instead

### ISSUE THREAD

**Issue by hahayupgit** [Wilyicaro/Legacy-Minecraft#368]
Using a Steam Deck and Re-Console v0.3.4. When I open the crafting menu, either through a crafting table or through the `X` button, using either of my shoulder buttons does not cycle through the tabs, but rather closes the crafting menu and cycles to the next/prev hotbar slot.

**Comment by Cjnator38** [comment]
Try changing your Steam Input settings to a configuration that has the controller buttons maps as controller inputs only, and trackpads used a mouse input. iirc this might be called something along the lines “Controller with Touchpad Mouse”. If it’s still an issue, disable Steam Input for your launcher

**Comment by Wilyicaro** [comment]
#139

**Comment by hahayupgit** [comment]
Thank you, apologies for the duplicate. I was searching for other issues like this but I couldn't find any, I appreciate the response!
