### ISSUE TITLE
Game won't open after selecting mod's resource packs

### ISSUE THREAD

**Issue by KubaKubek** [Wilyicaro/Legacy-Minecraft#369]
When launching the game without mod resource packs enabled, it works fine but when i try to select the resource packs and relaunch the game it crashes when loading.
I'm playing on Forge and these are the mods I'm using:
- 1.20.4-MacroKeybinds-1.3.1
- architectury-11.1.17-minecraftforge
- Legacy4J-1.20.4-1.6.3c-forge
- OptiFine_1.20.4_HD_U_I7

Crash report:
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 2024-05-18 13:42:07
> Description: Initializing game
> 
> java.lang.UnsupportedOperationException: null
> 	at jdk.nio.zipfs.ZipPath.toFile(ZipPath.java:669) ~[jdk.zipfs:?] {}
> 	at net.optifine.util.ResUtils.collectFiles(ResUtils.java:99) ~[srg:?] {re:classloading}
> 	at net.optifine.util.ResUtils.collectFiles(ResUtils.java:61) ~[srg:?] {re:classloading}
> 	at net.optifine.CustomItems.update(CustomItems.java:164) ~[srg:?] {re:classloading}
> 	at net.optifine.CustomItems.update(CustomItems.java:118) ~[srg:?] {re:classloading}
> 	at net.optifine.util.TextureUtils.resourcesPreReload(TextureUtils.java:310) ~[srg:?] {re:classloading}
> 	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:56) ~[forge-1.20.4-49.0.50-client.jar:?] {re:classloading,xf:OptiFine:default}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:598) ~[forge-1.20.4-49.0.50-client.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:196) ~[forge-1.20.4-49.0.50-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) ~[bootstrap-2.1.0.jar!/:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Suspected Mods: NONE
> Stacktrace:
> 	at jdk.nio.zipfs.ZipPath.toFile(ZipPath.java:669) ~[jdk.zipfs:?] {}
> 	at net.optifine.util.ResUtils.collectFiles(ResUtils.java:99) ~[srg:?] {re:classloading}
> 	at net.optifine.util.ResUtils.collectFiles(ResUtils.java:61) ~[srg:?] {re:classloading}
> 	at net.optifine.CustomItems.update(CustomItems.java:164) ~[srg:?] {re:classloading}
> 	at net.optifine.CustomItems.update(CustomItems.java:118) ~[srg:?] {re:classloading}
> 	at net.optifine.util.TextureUtils.resourcesPreReload(TextureUtils.java:310) ~[srg:?] {re:classloading}
> 	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:56) ~[forge-1.20.4-49.0.50-client.jar!/:?] {re:classloading,xf:OptiFine:default}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:598) ~[forge-1.20.4-49.0.50-client.jar!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
> -- Initialization --
> Details:
> 	Modules: 
> 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		COMCTL32.dll:Biblioteka formantów czynności użytkownika:6.10 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPT32.dll:Crypto API32:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.3527:Microsoft Corporation
> 		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
> 		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		DNSAPI.dll:Biblioteka DLL interfejsu API klienta usługi DNS:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
> 		GLU32.dll:Biblioteka DLL OpenGL Utility Library:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		KERNEL32.DLL:Biblioteka DLL klienta Windows NT BASE API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		KERNELBASE.dll:Biblioteka DLL klienta Windows NT BASE API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		MMDevApi.dll:Interfejs API MMDevice:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		MSCTF.dll:Biblioteka DLL serwera MSCTF:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		OpenAL.dll:Main implementation library:1.23.0:
> 		POWRPROF.dll:Pomocnicza biblioteka DLL dla profilu zasilania:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		RPCRT4.dll:Czas wykonania zdalnego wywoływania procedury:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		SETUPAPI.dll:Interfejs API Instalatora systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		SHCORE.dll:SHCORE:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		SHELL32.dll:Wspólna biblioteka DLL Powłoki systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		USER32.dll:Współużytkowana biblioteka DLL klienta Windows USER API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		USERENV.dll:Userenv:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		WINHTTP.dll:Usługi Windows HTTP Services:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		WINMM.dll:MCI API DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		WINSTA.dll:Winstation Library:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		WS2_32.dll:Biblioteka DLL 32-bitowej wersji usługi Windows Socket 2.0:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		aswAMSI.dll:Avast AMSI COM object:24.4.9067.0:Gen Digital Inc.
> 		aswhook.dll:Avast Hook Library:24.4.9067.0:AVAST Software
> 		bcrypt.dll:Biblioteka podstawowych elementów kryptograficznych systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
> 		combase.dll:Microsoft COM for Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		dhcpcsvc.DLL:Usługa klienta DHCP:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		dhcpcsvc6.DLL:Klient DHCPv6:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		dinput8.dll:Microsoft DirectInput:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		drvstore.dll:Driver Store API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		dwmapi.dll:Interfejs API menedżera okien Microsoft Desktop Window Manager:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		dxcore.dll:DXCore:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		fastprox.dll:WMI Custom Marshaller:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		fwpuclnt.dll:Interfejs API trybu użytkownika funkcji FWP/IPSec:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		gdi32full.dll:GDI Client DLL:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
> 		gpapi.dll:Interfejs API klienta zasad grupy:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
> 		imagehlp.dll:Windows NT Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		inputhost.dll:InputHost:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		jemalloc.dll
> 		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		jna4858894023143511467.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
> 		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
> 		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
> 		lwjgl.dll
> 		lwjgl_opengl.dll
> 		lwjgl_stb.dll
> 		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		mdnsNSP.dll:Bonjour Namespace Provider:3,1,0,1:Apple Inc.
> 		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		mscms.dll:Biblioteka DLL systemu dopasowywania kolorów firmy Microsoft:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		mswsock.dll:Microsoft Windows Sockets 2.0 Dostawca usługi:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		napinsp.dll:Dostawca podkładek nazewnictwa poczty e-mail:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		ncrypt.dll:Router programu NCrypt w systemie Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
> 		ntdll.dll:Biblioteka NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		ntmarta.dll:Windows NT - dostawca MARTA:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 551.23 :31.0.15.5123:NVIDIA Corporation
> 		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.5123:NVIDIA Corporation
> 		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.120:NVIDIA Corporation
> 		ole32.dll:Microsoft OLE for Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		opengl32.dll:OpenGL Client DLL:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		perfos.dll:Biblioteka DLL obiektów wydajności systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		pnrpnsp.dll:Dostawca obszaru nazw PNRP:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		profapi.dll:User Profile Basic API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		sapi.dll:Speech API:5.3.26906.00 (WinBuild.160101.0800):Microsoft Corporation
> 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		shlwapi.dll:Biblioteka dodatkowych narzędzi powłoki:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
> 		uxtheme.dll:Biblioteka Microsoft UxTheme:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> 		wbemcomn.dll:WMI:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
> 		wbemprox.dll:WMI:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
> 		wbemsvc.dll:WMI:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
> 		win32u.dll:Win32u:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
> 		windows.storage.dll:Interfejs API magazynu systemu Microsoft WinRT:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
> 		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
> 		wintypes.dll:Biblioteka DLL typów systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		wldp.dll:Zasady blokady systemu Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
> 		xinput1_4.dll:Interfejs API typowego kontrolera firmy Microsoft:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
> 		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(Main.java:196) ~[forge-1.20.4-49.0.50-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) ~[bootstrap-2.1.0.jar!/:?] {}
> 	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) ~[bootstrap-2.1.0.jar!/:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.20.4
> 	Minecraft Version ID: 1.20.4
> 	Operating System: Windows 11 (amd64) version 10.0
> 	Java Version: 17.0.8, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 274300472 bytes (261 MiB) / 805306368 bytes (768 MiB) up to 2147483648 bytes (2048 MiB)
> 	CPUs: 8
> 	Processor Vendor: GenuineIntel
> 	Processor Name: Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
> 	Identifier: Intel64 Family 6 Model 158 Stepping 13
> 	Microarchitecture: Coffee Lake
> 	Frequency (GHz): 2.40
> 	Number of physical packages: 1
> 	Number of physical CPUs: 4
> 	Number of logical CPUs: 8
> 	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x2191
> 	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 2.67
> 	Memory slot #0 type: DDR4
> 	Virtual memory max (MB): 16224.48
> 	Virtual memory used (MB): 11842.49
> 	Swap memory total (MB): 8112.24
> 	Swap memory used (MB): 551.59
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Launched Version: 1.20.4-forge-49.0.50
> 	Launcher name: minecraft-launcher
> 	Backend library: LWJGL version 3.3.2+13
> 	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.23, NVIDIA Corporation
> 	Window size: <not initialized>
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Universe: 404
> 	Type: Client (map_client.txt)
> 	Locale: pl_PL
> 	CPU: 8x Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
> 	OptiFine Version: OptiFine_1.20.4_HD_U_I7
> 	OptiFine Build: 20240317-172634
> 	Render Distance Chunks: 12
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.6.0 NVIDIA 551.23
> 	OpenGlRenderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 8
> 	ModLauncher: 10.1.2
> 	ModLauncher launch target: forge_client
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/ slf4jfixer PLUGINSERVICE 
> 		/ runtimedistcleaner PLUGINSERVICE 
> 		/ runtime_enum_extender PLUGINSERVICE 
> 		/ object_holder_definalize PLUGINSERVICE 
> 		/ capability_token_subclass PLUGINSERVICE 
> 		/ accesstransformer PLUGINSERVICE 
> 		/ eventbus PLUGINSERVICE 
> 		/ mixin PLUGINSERVICE 
> 		/ OptiFine TRANSFORMATIONSERVICE 
> 		/ fml TRANSFORMATIONSERVICE 
> 		/ mixin TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		lowcodefml@49
> 		javafml@49.0.50
> 	Mod List: 
> 		forge-1.20.4-49.0.50-client.jar                   |Minecraft                     |minecraft                     |1.20.4              |COMMON_SET|Manifest: NOSIGNATURE
> 		Legacy4J-1.20.4-1.6.3c-forge.jar                  |Legacy4J                      |legacy                        |1.6.3c              |COMMON_SET|Manifest: NOSIGNATURE
> 		forge-1.20.4-49.0.50-universal.jar                |Forge                         |forge                         |49.0.50             |COMMON_SET|Manifest: NOSIGNATURE
> 		architectury-11.1.17-minecraftforge.jar           |Architectury                  |architectury                  |11.1.17             |COMMON_SET|Manifest: NOSIGNATURE
> 		1.20.4-MacroKeybinds-1.3.1.jar                    |Macro Keybinds                |macrokeybinds                 |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
> 	Crash Report UUID: 0307803b-a058-4289-88f5-39702e5b15fc
> 	FML: 0.0
> 	Forge: net.minecraftforge:49.0.50

**Comment by Wilyicaro** [comment]
Legacy4J does not actually support Optifine, it may work, but it has not been tested, and also, I do not see any problems directly related to Legacy4J in the log
