### ISSUE TITLE
Tool tips show the "L2 - place" prompt when holding a non-placeable item while looking at a block

### ISSUE THREAD

**Issue by ChamiIion** [Wilyicaro/Legacy-Minecraft#370]
Just like the title says there is a place prompt when I was holding a diamond.
![image_2024-05-18_164652630](https://github.com/Wilyicaro/Legacy-Minecraft/assets/145168195/d6d0bd3a-08f2-4c8c-a917-00a4dadb51c5)

**Comment by Wilyicaro** [comment]
This doesn't happen normally, are you sure you don't have any blocks in your off hand?

**Comment by ChamiIion** [comment]
I checked it again and you're right I was holding a torch 😅
I'm so sorry this inconvenience!

**Comment by Wilyicaro** [comment]
No problem!
