### ISSUE TITLE
Game reverts to Classic Crafting after dying, can only be deactivated by rejoining world after manually disabling it

### ISSUE THREAD

**Issue by FredMCGamer** [Wilyicaro/Legacy-Minecraft#371]
Whenever I die, for some reason the classic Crafting option gets turned on indefinitely until I rejoin the world after deactivating it manually once again. 

Disabling the option after dying does not change anything, only Rejoining the world after disabling it once again.

This happens after every death.

**Comment by Wilyicaro** [comment]
#321
