### ISSUE TITLE
Can't use Legacy Crafting in servers

### ISSUE THREAD

**Issue by DrewGryffindor** [Wilyicaro/Legacy-Minecraft#373]
I have my own SMP server with a few friends. It's privately hosted on our own hardware so there isn't a third party involved so I don't get kicked from the server, I can play it with this mod. The only problem I've noticed right away though is that the mod instantly turns on Classic Crafting in the server and even when I turn it off, the next time I try to open the crafting menu it defaults right back to Classic Crafting. I don't know if this is supposed to be this way but it's kind of aggravating.

**Comment by Wilyicaro** [comment]
#321
