### ISSUE TITLE
essential mod support? 

### ISSUE THREAD

**Issue by goobigobbler** [Wilyicaro/Legacy-Minecraft#376]
could you guys add essential mod support? or fix the way the menu works on mouse and keyboard

**Comment by DanielMC101** [comment]
just use e4mc mod to play with friends without server. it's also compatible with latest java edition versions, and plus using that mod, people doesn't even have to have the mod.

**Comment by omo50** [comment]
@RedPCat Essential is closed source; compatibility cannot be worked on
Don't agree with it all you want; compatibility just.. cant be done because we have no source to work with

 There are also better alternatives to Essential (ie: e4mc)

**Comment by FlashlightET** [comment]
better alternative if you can port forward - i can port forward fine but my internets the worst in the group but im one of the only ones who can port forward on their router

**Comment by Lenuilu** [comment]
> Don't agree with it all you want; compatibility just.. cant be done because we have no source to work with

@FlashlightET As omo said, its the better alternative that anyone has access to. If you can't port forward you can TRY to handle with essential mod breaking things. Rather than that there's nothing to be done.

**Comment by Ch1216** [comment]
Any possibilities of this being re-opened now that [Essential is open sourced](https://github.com/EssentialGG/Essential/tree/main)?

**Comment by RedRain0o0** [comment]
nope, use World Host or E4MC
