### ISSUE TITLE
Adding modded items to crafting menu?

### ISSUE THREAD

**Issue by FullMetalMaster** [Wilyicaro/Legacy-Minecraft#380]
I've been trying to sort through conflicts and I can't seem to find anywhere that allows me to add more mods to the crafting screen?
if this could be made possible that would be great

**Comment by Wilyicaro** [comment]
https://github.com/Wilyicaro/Legacy-Minecraft/wiki/Listing%E2%80%90Based-Manager#crafting-tab-listing

**Comment by Wilyicaro** [comment]
Also, you can access "modded" items by activating the Display Vanilla Tabs option in the User Interface
