### ISSUE TITLE
Emeralds gain the NBT tag requiredLevel: 2 when trading on a server

### ISSUE THREAD

**Issue by toaferson** [Wilyicaro/Legacy-Minecraft#382]
Started a server, and when trading with villagers an NBT tag gets added, but in a singleplayer world this doesn't happen.
![Screenshot 2024-05-21 195307](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54555471/d963b1c9-df74-42a8-8b5c-d243dfa42db2)
1.20.4, L4J version  1.6.3b, running the modpack.
Update: The bug doesn't happen with Classic Crafting on

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
