### ISSUE TITLE
Pressing F3+ESC opens the pause menu

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#384]
Normally pressing F3 and ESC pauses the game without opening the pause menu (It says "Game paused" at the top instead). With the mod this feature is broken. It is interesting that pressing F3+ESC allows you to toggle the F3 debug screen while the pause menu is open. If you open the pause menu by just pressing ESC, you cannot do it, so pressing F3+ESC still behaves differently than just pressing ESC.

**Comment by Wilyicaro** [comment]
I removed this feature for the simple reason that it looks strange just when the game is paused with a dark screen (without the paused game title)
