### ISSUE TITLE
Classic crafting UI disappears after awhile

### ISSUE THREAD

**Issue by Gnegsvskjn** [Wilyicaro/Legacy-Minecraft#385]
Whenever I pull up the crafting menu, either by using a crafting table or pressing E, it stops showing the classic UI after playing for a bit in the client. I have to restart my game in order for it to show up again.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/161182843/e165a460-ae95-4c8b-81b6-aed37e176703)

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/161182843/2bcab506-3891-4674-87c4-142fcff99573)

**Comment by Wilyicaro** [comment]
#321
