### ISSUE TITLE
Ability to toggle controller support

### ISSUE THREAD

**Issue by Y1rd** [Wilyicaro/Legacy-Minecraft#388]
There are some rare edge cases where loading the controller library will fail and crash the game (e.g. Arm64 Android https://mclo.gs/lZHs0aw). It'd be nice for a configuration option to disable controller support and not load the library.

**Comment by Y1rd** [comment]
> For note, the last version that works is 1.6.2a. Later versions crash.

Even this version is buggy, opening the graphics screen instant crashes the game. 
https://mclo.gs/u9VG30c

**Comment by Y1rd** [comment]
Same error and startup crash as of version 1.6.4

**Comment by Y1rd** [comment]
Works now if `selectedControllerHandler:0` is set in options.txt. The other crash does not happen on this version.
Maybe this should be mentioned somewhere because the mod doesn't automatically turn it off.

**Comment by Wilyicaro** [comment]
> Works now if `selectedControllerHandler:0` is set in options.txt. The other crash does not happen on this version. Maybe this should be mentioned somewhere because the mod doesn't automatically turn it off.

It is worth noting that to do what is being asked, just set the ´´selectedControllerHandler´´ to 2, which will actually disable

**Comment by Y1rd** [comment]
>It is worth noting that to do what is being asked, just set the ´selectedControllerHandler´ to 2, which will actually disable

Ah, okay. Good to know.
Also, quick question. Mind if I make a new wiki page on the github repo mentioning the issue and how to solve it? Just in-case some poor user can't load the controller libraries.

**Comment by Y1rd** [comment]
Actually I can't PR on the wiki, but I can create a page locally and send it to someone who can add it.
