### ISSUE TITLE
Crosshair gets inverted when switching items or blocks then it goes back to white after a few seconds.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#39]
I set my Instance Opacity to 99% to bring back the white crosshair, but when you switch items or blocks on hand, it turns inverted, then goes back to white. I'm sure it has something to do with the attack indicator.

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it'll be fixed in the next update.
