### ISSUE TITLE
Disabling auto save and saving after long session

### ISSUE THREAD

**Issue by ShunkyMunk** [Wilyicaro/Legacy-Minecraft#390]
Turning off auto save then playing for a long period and then trying to save the game causes everything to freeze and stop responding essentially crashing.

upon loading back in items and anything gathered before hand is saved, though the world reverts to the last point the game was saved, I have lost several hours of progress on multiple occasions due to this.

So keep auto save on unless you remember to save often!!

**Comment by Wilyicaro** [comment]
This is expected, mainly depending on the amount of time that was played, and what was done in that amount of time, the longer it takes to save, the more things there will be to save obviously, and it will require more processing to do so.

**Comment by Wilyicaro** [comment]
This wasn't a frequent problem in LE, due to the limited world size, I imagine, but even in it, especially in older versions, there are problems when auto-saving is disabled.
