### ISSUE TITLE
On the server, the tooltip on java gui is not fully working. 

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#391]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/373b21e7-afe3-436b-86f2-0e32272a7777

The items are good.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/d96c2986-1460-418d-b0c7-3717c0b83658)

So it's works fine, if villager not using all 9+ slots for the trade.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.6, thanks for reporting.
