### ISSUE TITLE
Resource Packs screen now scrolls to the bottom on controller

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#392]
When scrolling down the resource packs list on controller, scrolling to the bottom of the viewed area immediately jumps the selection to the bottom of the full list. Same happens with upward scrolling on controller

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/d4a3a896-5661-44a1-b4d1-318ee2f79097

**Comment by Wilyicaro** [comment]
Fixed in 1.6.4, thanks for reporting (please close what you see has been fixed)
