### ISSUE TITLE
Left button no longer opens Resource Packs screen

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#394]
L4J 1.6.5, all dependencies up to date as well

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/5ba68d81-40a2-4ac7-a38a-9756458696f3

**Comment by Cjnator38** [comment]
In addition, trying to open it through shift clicking crashes the game
https://mclo.gs/67N7t6a

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/6ef325f0-ec5a-44d2-8177-ea63c4336bba

**Comment by Wilyicaro** [comment]
This is not happening normally, it must be an incompatibility or a specific case

**Comment by Cjnator38** [comment]
I might need to reinstall and test again, cause this is happening on an instance with up-to-date Fabric API, Architectury API and Legacy4J 1.20.6-1.6.5

**Comment by Cjnator38** [comment]
Can confirm it’s still happening on a fresh instance

**Comment by Cjnator38** [comment]
Tried on different hardware, still happens

**Comment by Cjnator38** [comment]
log from other hardware: https://mclo.gs/sNC6rcX
