### ISSUE TITLE
Crash on start up on steamdeck

### ISSUE THREAD

**Issue by tomas231** [Wilyicaro/Legacy-Minecraft#395]
been playing the through the re-console modpack but adding this issue here because it seems to be an issue with Legacy4J specifically. Uploaded the crash report to my browser and opened it and it is reporting that Legacy4J is incompatible with mod menu causing a crash immediately on start up.

https://mclo.gs/0ij8m8A

**Comment by tomas231** [comment]
update disabled mod menu and restarted and still resulted in a crash so im not sure whats happening

**Comment by Cjnator38** [comment]
Did you update from 0.3.6 to 0.4.0 or 0.4.1 via Prism Launcher?

**Comment by tomas231** [comment]
yes

**Comment by Cjnator38** [comment]
Remove Loqui, Load My Resources, Keep That Music, and Very Many Players

**Comment by tomas231** [comment]
giving me a different crash now "code 255"

**Comment by Cjnator38** [comment]
do you have a log file?

**Comment by Cjnator38** [comment]
If you have Prism Launcher, select your instance and click Edit, go to Other Logs and click Upload. Paste the link here.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/7db4c7b0-6c34-4c9e-8b63-bec5d91674bc)

**Comment by Cjnator38** [comment]
Are you using Java 21?

**Comment by tomas231** [comment]
yes im using java 21 collecting the crash log now

**Comment by tomas231** [comment]
heres the crash log 

https://mclo.gs/7l4XgWb

**Comment by Cjnator38** [comment]
is that log from the code 255 crash? if so, it seems like load my resources is still enabled and is causing a crash for some reason

**Comment by tomas231** [comment]
yup it was load my resources. didnt realize it was still enabled. crash has been fixed 'preciate the help mate
