### ISSUE TITLE
Selecting Data Packs crashes the game

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#398]
So, when clicking on datapack with cursor, it crashes the game, and with non-cursor, it's unselectable.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/bca6fcbc-8f87-4a41-8b45-cb00cf12a857

[crash-2024-05-24_23.55.57-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15441549/crash-2024-05-24_23.55.57-client.txt)

**Comment by Wilyicaro** [comment]
I tested it on 1.20.4 and 1.20.6 and it's not crashing normally, but I found another more serious problem that should have already been reported, the selected datapacks aren't saved
