### ISSUE TITLE
Nintendo Switch ABXY are inverted ingame

### ISSUE THREAD

**Issue by shrobbyy** [Wilyicaro/Legacy-Minecraft#399]
A = B | B = A | X = Y | Y = X

**Comment by Wilyicaro** [comment]
Enable Invert Buttons Layout, and this isn't an issue, this is expected

**Comment by shrobbyy** [comment]
> Enable Invert Buttons Layout, and this isn't an issue, this is expected

Doesn't fix it. The button layout shown ingame will still be wrong compared to the button on the controller.

**Comment by Wilyicaro** [comment]
Try to change your Controller Handler
