### ISSUE TITLE
<Contribution> Legacy-style Gamerule Names and Descriptions

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#40]
NOTE: Not a pull request because I don't know how you want to implement this.

This lang file changes all Game Rules to use Legacy Console-style names and gives every one a unique description. Some descriptions were pulled straight from PS4 Edition, but Java-exclusive game rules have been given new descriptions in the same style.

[en_us.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/14002767/en_us.json)

**Comment by Wilyicaro** [comment]
Thanks for the lang file and sorry for bothering you, but there are some repeated keys in the lang, which is not a real problem because I know what the real keys are.

**Comment by AgentMindStorm** [comment]
Apologies for those repeated keys. They affected the sendCommandFeedback and showDeathMessages gamerule descriptions.

**Comment by AgentMindStorm** [comment]
Here is a fixed version of the file. Repeated keys fixed 
[en_us.json](https://github.com/Wilyicaro/Legacy-Minecraft/files/14017306/en_us.json)
and some slight description changes to better match the Legacy style.
