### ISSUE TITLE
When theres no free slot for the picking block, it's replacing with item in inventory, but destroyed this item when quick moved.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#400]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/b7fd9fc2-19e3-4919-a841-e2de635e41a1

Plus it's multiplied by two.

**Comment by Wilyicaro** [comment]
Vanilla "issue", I don't modified anything about this
