### ISSUE TITLE
After selecting "Open to LAN" navigating with controller, you cannot really go to the Open to LAN checkbox

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#401]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/1d0f7eb8-9b87-4af6-9b31-816c89dddac1

**Comment by Wilyicaro** [comment]
Vanilla arrow navigation issue, and why do you want to disable the Open LAN after opening?
