### ISSUE TITLE
Open to LAN option not working on customized worlds

### ISSUE THREAD

**Issue by RubenHutten** [Wilyicaro/Legacy-Minecraft#402]
When loading a world with customized generation the Open to LAN setting will not properly work. The world will load normally but no LAN server will be started. I assume this is due to the warning screen that gets shown when loading a customized world. A current way to get around this issue is to use a mod that removes this warning.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
