### ISSUE TITLE
"Classic Crafting" option randomly turns on.

### ISSUE THREAD

**Issue by Goonmaster67** [Wilyicaro/Legacy-Minecraft#403]
The "Classic Crafting" option is randomly enabled while playing and disables the console edition crafting menu. If disabled, the option re-enables itself after exiting the in-game settings. The only solution I've found is to update the modpack to a newer version then revert it back to my previous version (I play on Re-Console version 0.3..6 due to  mod incompatibility issues on newer Minecraft versions), this solution only works from anywhere around 10 - 20 mins to 1 - 2 hours.

**Comment by Wilyicaro** [comment]
So update the modpack, this issue was fixed, and this is a duplicate
