### ISSUE TITLE
Crashes on loom, stonecutter and crafting interface in 1.6.6

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#405]
Ok so, it seems like it crashes when scrolling up inside the crafting interface.

[crash-2024-05-25_12.09.40-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15444156/crash-2024-05-25_12.09.40-client.txt)

**Comment by DanielMC101** [comment]
Ok, so it seems like it happens on loom interface as well
[crash-2024-05-25_12.22.05-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/15444201/crash-2024-05-25_12.22.05-client.txt)
, basically when going into a certain slot.

**Comment by Cjnator38** [comment]
Happens on d-pad, but not scroll wheel

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/6bee6f0d-4004-470d-9d48-485b3ddb8952

https://mclo.gs/MK3512x

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
