### ISSUE TITLE
Swords/Tools/Trident show incorrect tooltips in the creative menu when using the mod with combatedit

### ISSUE THREAD

**Issue by BoyImYush** [Wilyicaro/Legacy-Minecraft#409]
On every Fabric 1.20.6 version of legacy4j, when using the mod with combatedit, the tooltips of the swords, tools and the trident all show the default Minecraft attack damage values and it also shows the attack speeds (it shouldn't show the attack speeds because of combatedit). 
The tooltips are correct everywhere else besides the creative menu. It works normally on 1.20.4. It also isn't combatedit not changing the tooltips because it works normally without legacy4j installed. Reloading or changing the layout of the resource packs fixes the tooltips for some reason though.

I only have architectury, combatedit, fabric api, sodium and Legacy4j installed.

Here's a video to showcase the bug: 
https://github.com/Wilyicaro/Legacy-Minecraft/assets/88425735/368a9b15-f7e0-4036-b2a5-5ed5ead74374

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
