### ISSUE TITLE
Starter empty map turns into level 0 map when opened after relogging

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#410]
In the last update it was made that the starter empty map that you get when creating a new world turns into a level 3 map when opened. However if you relog before opening the map, it will turn into a level 0 map instead. This is because there is an empty components tag on the map that is lost upon relogging.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/5461f7cc-2006-4c38-865f-4f3fa4006248

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
