### ISSUE TITLE
villager trades are very broken

### ISSUE THREAD

**Issue by gage64** [Wilyicaro/Legacy-Minecraft#412]
a lot of villager trades get randomly locked when they level up, or in the case of one villager i have, all of his trades are locked despite never trading with him, making leveling him up or just trading with him impossible
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/28501503/5b3abbf8-66f5-4ba4-a18f-f29d032b1b60)
i think what's happening for trades being locked is that for some reason, the mod sets the required villager level for an item trade at something absurd like level 30, despite villagers max level being 5
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/28501503/2d9eb51f-55dc-4ed1-81a0-102f620ed4e6)
i don't know what's causing trades to suddenly become locked behind another level they didn't require before

**Comment by angeld23** [comment]
Seems like trades have their `requiredLevel` field set to either 1 or a multiple of 5. May be related to another bug that we were experiencing that for some reason gave emeralds bought from villagers an NBT tag of `requiredLevel` as well, making them both unstackable with other emeralds and also untradeable with villagers.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/59970528/9cf25f22-9483-407a-b54f-6a219f0a867a)

**Comment by Wilyicaro** [comment]
Please tell me the version of the mod where this is happening, currently 1.20.6 and 1.20.4 are completely different versions in this regard

**Comment by angeld23** [comment]
> Please tell me the version of the mod where this is happening, currently 1.20.6 and 1.20.4 are completely different versions in this regard

1.20.6

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
