### ISSUE TITLE
Craftify mod settings page broken.

### ISSUE THREAD

**Issue by canofjuice** [Wilyicaro/Legacy-Minecraft#415]
This is probably due to the mod using it's own custom settings page and not like other mods.

![2024-05-27 14_32_07-Minecraft_ 1 20 6](https://github.com/Wilyicaro/Legacy-Minecraft/assets/135176122/ad77568e-a6e3-4059-8ce0-d831b0284cde)

**Comment by Wilyicaro** [comment]
It's not because of that, certainly this mod is not scaling correctly the screen elements
