### ISSUE TITLE
when i go to the crafting table and go up it crashes the game

### ISSUE THREAD

**Issue by ZAPlord321** [Wilyicaro/Legacy-Minecraft#416]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/155524048/93b91e2b-4b7d-4f72-b94b-e44deda4fe17

mostly i try brushing it off if it doesn't affect anything with the gameplay but if it crashes i try to report it, i don't really mean to put presser or anything.

(this optional but make essential mod combatable with legacy4j)

**Comment by DanielMC101** [comment]
Only happens in 1.6.6, just play any version below that and it won't happen.

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.7, thanks for reporting!
