### ISSUE TITLE
Villager Trades Locking

### ISSUE THREAD

**Issue by kr0wzz** [Wilyicaro/Legacy-Minecraft#419]
I've noticed that when I close out of a world sometimes and open it up later, all of my villager's trades besides the initial ones are locked with no way to fix them. Here is a screenshot of this bug occurring.
![Screenshot 2024-05-27 201646](https://github.com/Wilyicaro/Legacy-Minecraft/assets/171082853/20711ccb-bbae-4c2d-ad78-64a612ac1051)

**Comment by Wilyicaro** [comment]
Update to 1.6.7 version

**Comment by kr0wzz** [comment]
Updated earlier today, maybe it's still locked out because the villagers were there before I did so? In any case hopefully this will prevent the issue from repeating

**Comment by wowgoodlmao** [comment]
> Update to 1.6.7 version

The villager trades are still locked.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/169317019/c2202905-d9d7-4c0b-8350-8633bd1e535d

**Comment by Wilyicaro** [comment]
> > Update to 1.6.7 version
> 
> The villager trades are still locked.
> 
>  video.mp4

It's obvious, they were saved like this
