### ISSUE TITLE
Getting kicked from singleplayer loads vanilla multiplayer menu

### ISSUE THREAD

**Issue by DBTDerpbox** [Wilyicaro/Legacy-Minecraft#42]
This *only* happens if you get kicked in singleplayer, not multiplayer (as shown in video)

I'm using chat spam to get kicked easily with cheats disabled, youll have to get kicked some other way if cheats if enabled

[YouTube Video](https://youtu.be/6WVlIDYzgoU) (Using YouTube because the file is too big)

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it'll be fixed in the next version
