### ISSUE TITLE
[1.20.4 Fabric] [Mod Incompatibility]: The Player is unable to control Xaero's World Map when a controller is connected

### ISSUE THREAD

**Issue by Daralexen05** [Wilyicaro/Legacy-Minecraft#421]
The title explains the issue. The Player cannot scroll or view the whole Xaero Worldmap when a controller is connected, even when switching to a mouse. I play with a Starfield Xbox Series X controller and when I open the world map with my controller connected to my PC, I am unable to scroll or view the whole wordmap even when I use my mouse to try to scroll or interact with it. I am only able to view the currently loaded chunks as opposed to being able to view all explored chunks as if I were using my mouse and keyboard.

**Comment by Wilyicaro** [comment]
just bind a key in the "Toggle Cursor" mapping, I think it's better to be something like this than every time you move the mouse the cursor appears
