### ISSUE TITLE
Music no longer stops playing when changing the dimension

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#422]
Normally music stops playing when changing the dimension, since all 3 dimensions have different music. Music still stops playing if you enter or leave a world. (On LCE music doesn't stop playing when entering a world but it stops when leaving a world.)
https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/71c41285-470d-4501-a0e3-8daf087d85e9

**Comment by Wilyicaro** [comment]
#396

**Comment by bugsbugsbugsLCE** [comment]
Couldn't find it, since it's closed.

**Comment by Wilyicaro** [comment]
so remove your filters
