### ISSUE TITLE
Crash on MacOS when using this specific mod

### ISSUE THREAD

**Issue by OneTrackMinded** [Wilyicaro/Legacy-Minecraft#423]
Immediate crash with error code 0 when mod is enabled. 
[17:13:27] [Render thread/ERROR]: Unhandled game exception
java.lang.UnsatisfiedLinkError: Unable to load library 'SDL2':
dlopen(libSDL2.dylib, 0x0009): tried: 'libSDL2.dylib'

**Comment by Wilyicaro** [comment]
#347

**Comment by OneTrackMinded** [comment]
I'm on version 1.6.7 and the issue still occurs

**Comment by Wilyicaro** [comment]
Check options.txt, the selectedControllerHandler option must certainly be set to 0 if your PC is detected as a Mac OS by the game, if not, make sure to set it to 0.
In any case, if it is still occurring (unlikely, as it no longer occurs on Linux/Android systems that have the same problem), read the issue that I referenced, as it contains the definitive solution
