### ISSUE TITLE
Strange arrows on world selection screens

### ISSUE THREAD

**Issue by TyTyCameraYT** [Wilyicaro/Legacy-Minecraft#426]
Hello, for some reason these arrows are now appearing on the game on my steam deck. I haven't modified the modpack besides add the From The Fog mod.
![PXL_20240530_212247168](https://github.com/Wilyicaro/Legacy-Minecraft/assets/171293397/c91e8ea9-4699-4c87-8e79-828ac73606c4)

**Comment by Wilyicaro** [comment]
Disable Touchscreen mode in Mouse Settings section

**Comment by TyTyCameraYT** [comment]
> Disable Touchscreen mode in Mouse Settings section

thanks man
