### ISSUE TITLE
Multiple controllers of different types cause issues

### ISSUE THREAD

**Issue by Easyidle123** [Wilyicaro/Legacy-Minecraft#427]
**Legacy4j 1.6.7 - Neoforge**
When using multiple controllers of different types, several strange issues occur. Test notes are written between an Xbox and Playstation controller for clarity, but the issues were observed between xbox one / series X controllers as well.

Using controller handler GLFW:
- When the XBox controller is plugged in first, switching to controller two (the PS4) will continue to display as XInput gamepad and use XBox glyphs.
- Switching to an unused controller slot and then back again, both controllers will instead display as PS4 controllers
- Despite these visual issues, controllers work correctly on their assigned slot

Using controller handler SDL2
- When plugging in the PS4 controller in first, similar issues occur, but trying to use a controller when the wrong name is displayed will result in the controller not working. Instead, the listed controller name will be the controller which works, regardless of the selected slot.
- Moving to an unused slot and back causes the Xbox controller to take priority, and further alternating to an unused slot has no effect. This effectively softlocks you if you use the PS4 controller
- Unplugging the Xbox controller allows the PS4 controller to continue functioning.

Similar issues occur when attempting to use any combination of these controllers together, including the two Xbox controllers. with DLFW they display only one type but all work, with SDL2 only the displayed controller type will function.

Exact controllers used:
Playstation 4 Dualshock Wireless Controller - connected by cable
Xbox Series X - Connected by bluetooth
PowerA Enhanced Wired Controller for Xbox Series X|S - Officially licensed by Xbox, registered in game as "Xbox one for windows"

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
