### ISSUE TITLE
Host options not persistent in gui on servers

### ISSUE THREAD

**Issue by Easyidle123** [Wilyicaro/Legacy-Minecraft#428]
Host Options like fire spread, mob briefing, etc don't display correctly on servers, even if the user is opped. Changing them runs the command successfully, but even those changes do not visually update when re-checking the menu. The one exception I could find was daylight cycle, which will correctly show as disabled if toggled off.
If a fix to have it check the server settings isn't possible, at least having it update client side when edited would be better than current.

Note: changing daylight cycle via command correctly updates it visually in Host Options.

**Comment by Wilyicaro** [comment]
Sorry if this is not documented, but the gamerules are not synchronized with the client in vanilla, that is, it was necessary to modify the server side to send this information, if you use the Host Options Interface on a vanilla server, the gamerules are always at its default value
