### ISSUE TITLE
Invisible Player option partially broken on servers

### ISSUE THREAD

**Issue by Easyidle123** [Wilyicaro/Legacy-Minecraft#429]
Invisible is partially broken on servers, even with OP.
When applying invisibility, the player is given invisibility and resistance correctly. when the menu is reopened, the toggle is shown as disabled, so the player is unable to return to being visible without using commands manually.

**Comment by Wilyicaro** [comment]
The same case as gamerules, this is obviously not synchronized with the server, so a modification was made on the server side to do this, so you need to have Legacy4J installed for this to work
