### ISSUE TITLE
Actionbar is not moved with the hotbar

### ISSUE THREAD

**Issue by DBTDerpbox** [Wilyicaro/Legacy-Minecraft#43]
Actionbar does not move with the hotbar changes, this results in it clipping into the hotbar

Command: `/title @s actionbar "text here"`

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/f0e11f82-f268-42ab-8425-eca740fa1188)

**Comment by Wilyicaro** [comment]
This is already known and will be tweaked in the next version to be released.
