### ISSUE TITLE
Cannot scroll down on the leaderboards

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#430]
So, i was playing with this mod on the re-console server, and I just noticed that you can't really scroll down on leaderboards to see more players

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/da1e76b5-c8f7-4532-b271-19c0d12b355e

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
