### ISSUE TITLE
On-screen multiplayer support 

### ISSUE THREAD

**Issue by CART5744** [Wilyicaro/Legacy-Minecraft#432]
I know this can be difficult but one of the things that causes me the most nostalgia is playing minecraft with my little sister in split screen since I have many memories of this, please if it can be achieved or not, I only ask for the attempt to make it possible 👍 please and Thank you for your understanding

**Comment by jhanna001** [comment]
There is a suggestions channel in the discord for stuff like this, and splitscreen has been talked about among developers. The mod is compatible witth nucleus coop for now so you can use that

**Comment by Wilyicaro** [comment]
#257

**Comment by CART5744** [comment]
> There is a suggestions channel in the discord for stuff like this, and splitscreen has been talked about among developers. The mod is compatible witth nucleus coop for now so you can use that

Thank you for your attention, yes I already heard about the Discord, but what happens is that I uploaded this message a long time ago but thank you anyway 👍
