### ISSUE TITLE
Switch to the new 4j studios logo 

### ISSUE THREAD

**Issue by CART5744** [Wilyicaro/Legacy-Minecraft#435]
A few months ago 4j studios changed their logo for a more modern and minimalist one and this can be seen in their new YouTube videos in which the logo of 4j studios does not have the letter "y" in large but they removed it from their current logo and it looks better and I would like it if it can,  that at the beginning of the game with this mod you could see its new logo 👍

**Comment by nonetrix** [comment]
Make it a setting

**Comment by TheAwesome98-Real** [comment]
the old one should be in programmer art

**Comment by Wilyicaro** [comment]
Added in version 1.7, thanks for suggesting.
