### ISSUE TITLE
The legacy shrub item causes the player that doesn't have mod to disconnect from the server.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#437]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/5f40c6f3-d2eb-4b07-b845-70dab59c854a

**Comment by Wilyicaro** [comment]
I can't do anything, and this isn't a issue, Legacy4J is not intended to change the internal workings of Fabric

**Comment by DanielMC101** [comment]
oh, and it also happens with potions on cauldrons as well
