### ISSUE TITLE
The auto scale on Full HD needs more attention.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#438]
After moving by 1 pixel, it added black line:

![2024-06-02_08 59 26](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/0b2e0294-3cde-4c39-a4e4-757342cffde3)

![2024-06-02_09 00 29](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/65f6e23a-9f22-40ba-b453-ffa49fe05595)

The text on right side begin more fatty then on the left.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/e064cf94-4e5d-40a8-bb41-4a0d20f334e6)

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/d6ecd3cb-8d1a-4f6e-bc1a-2c24ef9357e4)

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/287d6c40-cb68-4d36-8df5-9948f55201cc)

You can see it on the first screenshot too.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/c79b669e-6e6f-4b94-9d94-ab936d9dc487)

(And it's not the re-console problem)

![2024-06-02_09 04 56](https://github.com/Wilyicaro/Legacy-Minecraft/assets/88715280/1a9928d4-e3bf-4973-85da-323f17d37d3f)

**Comment by Wilyicaro** [comment]
Change the Interface Resolution slider, there is nothing I can do other than change this and give presets with the Auto Resolution option active
