### ISSUE TITLE
The player is unable to switch back to Survival after loading a world created in Survival in Creative

### ISSUE THREAD

**Issue by Daralexen05** [Wilyicaro/Legacy-Minecraft#439]
I briefly switched my survival world to creative to verify if there was an Ocean Monument in my world. After I found a Monument +12K blocks away from Spawn, I exited and saved. However, I was unable to put the world back into Survival. Even when I put "Survival" as my gamemode, the world would still only load in Creative, Adventure, or Spectator. My only solution was to temporarily remove Legacy4J and then open the world to LAN with cheats enabled to go back into Survival.

**Comment by Wilyicaro** [comment]
Well, this is not true under normal conditions, you may be suffering from an incompatibility with some mod
