### ISSUE TITLE
Vanilla recipe book is smaller than inventory

### ISSUE THREAD

**Issue by contrarybaton60** [Wilyicaro/Legacy-Minecraft#44]
![2024-01-22_19 31 32](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/241154dd-e65f-46ec-9e9c-e648903a46da)
![2024-01-22_19 31 37](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/e51d4f1c-821d-4cb2-ab43-eb9dc7a0ee8e)
Self-explanatory, also the Crafting Table UI still has the dark background, I don't know if it's possible to remove it,

**Comment by Wilyicaro** [comment]
As LE doesn't actually have a Recipe Book, I won't change anything else in it, not even its scale, as I will add the LE Crafting Interface, and it's just optional

**Comment by contrarybaton60** [comment]
ah okay, also the statistics and advancements buttons appear in multiplayer servers and the text under the quit game dialog is still the same
![2024-01-22_20 36 43](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/98c34b4f-7b75-4fc5-a842-a990c68b003b)
![2024-01-22_20 37 01](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/c92c1cc4-ca44-4c17-ac97-a7e59161f6b6)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/f1274871-86d1-425a-b9f5-1320b18a3bae)

**Comment by Wilyicaro** [comment]
Why Advancements and Statistics shouldn't appear in multiplayer servers?
And thanks for reporting about the exit game dialog

**Comment by contrarybaton60** [comment]
if your playing a server like hypixel it wouldn't really make sense to have them, but I personally don't mind if you keep them

**Comment by Wilyicaro** [comment]
I understand your point, but it's practically impossible to know if a server is like Hypixel, because there is no real difference for the client between a survival server and a minigames server.
