### ISSUE TITLE
The Leaderboards screen for mob kills and deaths is unable to properly render CEMs

### ISSUE THREAD

**Issue by Daralexen05** [Wilyicaro/Legacy-Minecraft#440]
The title explains it all. I have two CEM packs that revert Zombified Piglins back to Zombie Pigmen and change Piglins and Piglin Brutes to the scrapped Pigman mob. I also have a Fire Emblem resource pack that changes the Blaze to the Vestal from Fire Emblem Echoes (Alex player model with custom texture.) They do not display properly on the Kill and Death counts of the Leaderboard.

![2024-06-04_22 24 01](https://github.com/Wilyicaro/Legacy-Minecraft/assets/144989721/e430a5ee-e086-43a2-b0f2-a7439e3156a7)

**Comment by Wilyicaro** [comment]
This is a compatibility request, it's not a Legacy4J problem, the rendering of entities is done the way vanilla does it, that is, this mod that supports CEM should modify the vanilla rendering method to provide compatibility.

**Comment by Daralexen05** [comment]
> This is a compatibility request, it's not a Legacy4J problem, the rendering of entities is done the way vanilla does it, that is, this mod that supports CEM should modify the vanilla rendering method to provide compatibility.

Thank you, I will report this to Entity Model Features.
