### ISSUE TITLE
Animals do not drop items.

### ISSUE THREAD

**Issue by drakosoldier298** [Wilyicaro/Legacy-Minecraft#441]

**Comment by drakosoldier298** [comment]
I hate github
Version 1.20.6-1.6.7

**Comment by Wilyicaro** [comment]
It's not a Legacy4J problem, it doesn't change the drop of any mob

**Comment by drakosoldier298** [comment]
that means re-console needs to be told it is their problem as they sent me here.

**Comment by Wilyicaro** [comment]
Now that I understand, you generalized by saying that Legacy4J prevented any mob from dropping, but this is only in the Tutorial world, apparently.
Activate the loot gamerule, which for some reason seems to be disabled.

**Comment by drakosoldier298** [comment]
if its DoMobLoot its set to true and is still occurring. its only animals. liek sheep pigs, fish ect,Hostile and neutral mobs drop items.

**Comment by drakosoldier298** [comment]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/30358222/20020de6-2f42-4bcd-9a4b-75d7aa6d58f2)

**Comment by DBTDerpbox** [comment]
what mods are loaded, and what datapacks are loaded?
