### ISSUE TITLE
Map in the tutorial world is level 0 instead of 3

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#442]
Not sure whether this belongs to github or suggestions in discord. The starter map when creating a new world is now level 3 just like on LCE but the map in the tutorial world still creates a level 0 map.
![2024-06-05_20 34 46](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/538d134a-b307-47c4-baff-0fc4e66b9491)

**Comment by Wilyicaro** [comment]
It's because the Tutorial world already has data for the player defined, that is, the changes made to the starter map were not added.
