### ISSUE TITLE
Chest in enchanting area of the tutorial world has blue dye instead of lapis lazuli

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#443]
![2024-06-05_20 38 27](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/8dbf1a71-8896-4e60-9b93-c8733c836bae)
Another world conversion issue similar to #436.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
