### ISSUE TITLE
Changing the gamemode to hardcore doesn't immediately update the difficulty slider

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#444]
If you change the gamemode in the world creation menu to hardcore, the difficulty slider does not change to hard. Clicking "More Options" and then exitting updates it to hard. Creating the world when the slider is not set to hard still creates a world with hard difficulty, so it is only a visual issue. This issue does not allow you to create hardcore worlds with difficulty not set to hard. 

(In the video I am attempting to create a hardcore world with peaceful difficulty but the difficulty is not set to peaceful upon creating the world as expected.)
https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/82015352-a347-4a9f-a5de-8939ce96ac88

**Comment by Wilyicaro** [comment]
I don't understand the problem, this was intentional so as not to have to update the visual value of the difficulty slider unnecessarily, but if there are those who are bothered by this, I will change it

**Comment by bugsbugsbugsLCE** [comment]
Why do you think updating it is unnecessay? This is misleading as it can make you think you are not playing on hard difficulty. In vanilla it updates properly and goes back to what it used to be if you change back to survival or creative.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/bfc18934-7cc0-4335-980e-bd43cbbec2ba
