### ISSUE TITLE
Villager trades are locked when they shouldn't be

### ISSUE THREAD

**Issue by Ello-There** [Wilyicaro/Legacy-Minecraft#445]
I've been trying to trade with some villagers, but their base trades are locked when they shouldn't be. I need some emeralds:(

https://github.com/Wilyicaro/Legacy-Minecraft/assets/171862039/9844bc6a-a3a9-4dc3-b1c4-9ed952b2bb34

**Comment by Wilyicaro** [comment]
This world was probably loaded from a previous version of the mod, I can't do anything more, this bug has already been fixed
