### ISSUE TITLE
Trading with villagers doesn't work 

### ISSUE THREAD

**Issue by jhanna001** [Wilyicaro/Legacy-Minecraft#447]
Issue: I can't trade with villagers on my modded Minecraft server. The only mod I have installed on the server is Legacy4J and Architectury API which are required to run the mod on CurseForge.

It seems like the first trade I make with a villager is the only trade I can continue to make with the villager, my friends have similar problems but it seems almost random when they can and can't trade with villagers, but as I have mentioned it has no issue with the first trade you make, just all trades after that

**Comment by jhanna001** [comment]
Note: I removed the mod and it now works fine so I am sure it is the mod that is the issue

**Comment by BzzzThe18th** [comment]
Yeah there seems to be issues with this. For now if you switch to legacy menu when you go to trade and double click the trade you want it'll work.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
