### ISSUE TITLE
Split mod for crafting system

### ISSUE THREAD

**Issue by SpectralPixel** [Wilyicaro/Legacy-Minecraft#449]
I am currently making a modpack, and wanted to make it controller friendly. The crafting menu is perfectly suited for controllers, and if it were not for the complete overhaul of the game, it would've been a perfect fit.

Is it possible that the legacy crafting menu could be implemented separately? Or could some configuration be added to toggle certain aspects of the mod e.g. the menu overhauls?

**Comment by Wilyicaro** [comment]
It's a good idea, but suggestions need to be made on the Legacy4J Discord server in order to better organize GitHub for _issues_ and incompatibilities only (please note that suggestions prior to the creation of this server will be kept)
