### ISSUE TITLE
Turtle Egg missing from Miscellaneous tab

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#45]
The Turtle Egg is not next to the Sniffer Egg in the Creative Miscellaneous tab. This can be seen in creative_tab_listing.json where minecraft:turtle_egg is misspelled as "minecraft:creturtle_egg".

**Comment by Wilyicaro** [comment]
Thanks for reporting this mistake, it will be fixed in the next update.
