### ISSUE TITLE
Issue with book and quills.

### ISSUE THREAD

**Issue by SeagullMaker** [Wilyicaro/Legacy-Minecraft#452]
My issue is that whenever i use a book and quill, and write on the first page everything works fine, but when i try to type a space on the second page, it will go to the previous page, or make a new page, meaning i cannot make more than one page. My issue is on the fabric version of 1.20.4 mod version 1.6.7, unless im just dumb i hope this is fixed

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
