### ISSUE TITLE
Bug with Villager Trading

### ISSUE THREAD

**Issue by itsmasonbozo** [Wilyicaro/Legacy-Minecraft#454]
I'm playing on a multiplayer survival world with the [Villager Cure Discount Stacking](https://modrinth.com/datapack/villager-cure-discount-stacking) datapack. After trading a few times with a villager, the trading menu for this villager only got messed up. Not sure what to do.
![Screenshot 2024-06-08 222152](https://github.com/Wilyicaro/Legacy-Minecraft/assets/172160952/908e95fa-ce85-41d9-b6c0-21e97d7c3663)

**Comment by Wilyicaro** [comment]
What mods are you using with Legacy4J, besides dependencies? Also, what modloader and version are you using?

**Comment by itsmasonbozo** [comment]
I'm only using Legacy4J and Architectury API on Forge. I'm playing on 1.20.4

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
