### ISSUE TITLE
Selling a lava bucket to a villager gives back an empty bucket

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#456]
If trade with a villager and sell a lava bucket for an emerald, you will get back the empty bucket. This doesn't happen in vanilla. This probably happens because the code for the trading UI is similar to the crafting menu. I am pretty sure that this did not happen a few updates ago.
https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/c6237e99-d3fd-4a67-850e-341077f3072e

https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/8099349f-4d0f-417b-a212-5ab39f8fce45

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
