### ISSUE TITLE
Crafting menu in server doesnt work it forces me to use the old crafting style

### ISSUE THREAD

**Issue by ebanddz** [Wilyicaro/Legacy-Minecraft#459]
doesnt work it forces me to use the old crafting style

**Comment by Wilyicaro** [comment]
If playing on vanilla servers forces you to use Classic Crafting, how did you come to the conclusion that it is an issue, and not a simple limitation?
>If when JEI is not installed on the server side, the function of moving items to the crafting grid is disabled, why expect that a new interface that automates crafting would work?

**Comment by ebanddz** [comment]
so how would could i make that work on my server

**Comment by ebanddz** [comment]
like in the mods area?

**Comment by Wilyicaro** [comment]
yeah, in the mods folder

**Comment by ebanddz** [comment]
would it apply to everyone else in the server or just me

**Comment by Wilyicaro** [comment]
Only if these players are using fabric/forge/neoforge

**Comment by ebanddz** [comment]
everytime i try to load a server with legacy4j in the mods folder it crashes

**Comment by Wilyicaro** [comment]
> Use a fabric/forge/neoforge server and place Legacy4J and its dependencies on it

with the dependencies?

**Comment by Goldenfreddy0703** [comment]
It crashes for me too when i try to access the crafting ui on my server.
