### ISSUE TITLE
Pressing number keys on Creative hotbar slots causes undefined behaviors

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#46]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/6f584aef-603f-4b85-a29d-5489398c7c06)
I was able to change items in the Creative inventory by pressing the number keys on them in my hotbar. This resets upon closing the screen.

**Comment by Wilyicaro** [comment]
This is a bug, that will be fixed in the next update.
