### ISSUE TITLE
Unable to horizontally scroll on an extended crafting menu

### ISSUE THREAD

**Issue by Salt-and-Fries** [Wilyicaro/Legacy-Minecraft#460]
# The User Can't Use the Mouse to Access Extra Recipes
### When a crafting category has more than 12 groups of craftable items, the game hides the extra groups further to the right of the crafting menu. This is not an issue if the user has a controller, since the one-at-a-time movement pushes the entire list of categories over.
_Image 1 - Showing a visual of the extended groups_
![issue2](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/c97f374f-a1ea-4514-907e-fb4731a98aed)

### If the user is playing with a mouse and keyboard, they have no practical way of getting to the last group. They can however use the arrow keys to maneuver over to it, but that is tedious, and gets annoying fast, especially considering the hand must be removed from the mouse to do it. 

_Image 2 - Showing a close-up of the arrow, signifying further groups_
![Issue3](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/9f5693da-16b4-4d58-8672-f36689f63885)

### This appears to only be an issue with the miscellaneous tab in a crafting table. 

_Image 3 - Image of miscellaneous tab_
![Issue4](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/a5fcfeaa-06a3-49c6-beea-5af367ea0f0b)

### It does appear to also be an issue, when vanilla tabs are enabled in the UI settings, and the player crafts without a crafting table

_Image 4 - Vanilla Tabs option in the settings_
![Issue8](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/6c764931-6de1-4d6f-a8e8-5036fb892f83)

_Image 5 - Crafting issue in the blocks tab with Vanilla tabs turned on_ 
![Issue7](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/05b6eb08-421f-463b-87d5-b36807f2d255)

# Extra Bug
### Arrow still appears when show only craftables is turned on

_Image 6 - Yellow arrow stays rendered when there are no further groups_
![Issue1](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/31527f8a-3e5e-4778-8ccc-68a142f0e07d)

# Recommendation
### Could the user be given the option to rebind the in-menu controls?
_Image 7 - Example of in-menu controls_
![Issue6](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81257183/9f5bb576-1f18-4c0b-912d-3e624ace1745)

**Comment by Wilyicaro** [comment]
Added in version 1.7, thanks for reporting.
