### ISSUE TITLE
Autosaving partially continues after disabling

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#462]
When disabling autosave and manually saving at any point afterwards, it will partially continue make new saves. The autosaves will continue showing the icon and will make a new save, but the blocks in the save are reverted to how they were in the previous manual save. Items in the inventory obtained following the manual save will remain in the inventory. Autosaving also continues on a fresh L4J instance, although I can't confirm if blocks remaining from a manual save is an issue there.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39870226/d69740d2-f7b4-4604-9833-fafdce6b154f

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
