### ISSUE TITLE
Combatify mod enlarges and cuts off hotbar when used with legacy4j

### ISSUE THREAD

**Issue by LumiOfFrost** [Wilyicaro/Legacy-Minecraft#463]
To reproduce:
Install Combatify (https://modrinth.com/mod/combatify)
Install Legacy4J
Set hud size to a number over 1

**Comment by Wilyicaro** [comment]
Could you inform the version of Minecraft and the mod loader used? The currently supported versions are very different in code, so there are also different problems.
I would like to say that any change made to the vanilla HUD by another mod is subject to problems, especially if it was not done correctly in my understanding, so I will not leave any issue related to compatibility with this open.
