### ISSUE TITLE
The mod is not compatible with the game clients

### ISSUE THREAD

**Issue by owerset** [Wilyicaro/Legacy-Minecraft#464]
When trying to play on LabyMod, the game crashes
I guess this happens with every client and it's a real shame because nowadays everyone are already using game clients
https://paste.labymod.net/ihilehuxopogoyagijud

**Comment by Lenuilu** [comment]
I.... I don't think a custom client is going to be compatible with a mod that changes the UI in a massive way

**Comment by Wilyicaro** [comment]
Game clients or any mod that changes some interface aren't intended to be supported by Legacy4J
