### ISSUE TITLE
Buttons are not affected when changing interface opacity settings 

### ISSUE THREAD

**Issue by TyTyCameraYT** [Wilyicaro/Legacy-Minecraft#466]
Buttons do become transparent in the title screens, which is what happens in legacy console so thats good, but in gameplay the buttons do not become transparent when the hotbar is. 

![2024-06-13_22 58 39](https://github.com/Wilyicaro/Legacy-Minecraft/assets/171293397/54f5fc80-2688-489b-b805-f334e80e4db4)

**Comment by Wilyicaro** [comment]
Remove Immediately Fast or disable hud batching
