### ISSUE TITLE
Various issues with Dog easter egg

### ISSUE THREAD

**Issue by sunsetbear** [Wilyicaro/Legacy-Minecraft#468]
1. the tick length of a disc is specified in code, to determine for how long music note particles should spawn, for how long to emit a redstone pulse to a comparator, and for how long to let the audio play before forcibly stopping it. This tick length appears to have gone unmodified leading to Dog never actually playing in-game.
2. cat.ogg is in stereo, which means directional panning and positional volume scaling fail completely when the disc is played in-game
3. The bitrate of the file hovers around 100 kpbs, when cat.ogg itself was initially 70kpbs. This leads to filesize bloat especially considering the near double length of the song.

[Here's an ogg file that fixes 2 and 3](https://discord.com/channels/1203542640008892498/1203542640470138907/1251227186250252410) and is also mastered similar to the original cat.ogg instead of being a straight rip of c418's stereo masters- this is important to keep a consistent listening volume in-game. You can fix 1. by doing some math

**Comment by Wilyicaro** [comment]
Thank you for your help with the correction, in fact I didn't even obtain the audio used in the cat music disc, AgentMindStorm provided it to me along with other resources

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
