### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Pawwell1** [Wilyicaro/Legacy-Minecraft#469]
not something to do with physics but with joinning a server, when u join a server, if u hover ur mouse in a specific plaace and click, it cancels the join thingy and returns me to the multiplayer menu, and same thing on controllers, dm me on discord(pawwell124) to understand wat i mean

**Comment by Wilyicaro** [comment]
The disconnect button is still present below the connection screen, as a way for you to disconnect

**Comment by Pawwell1** [comment]
make it appear as a custom btn
