### ISSUE TITLE
tips.json is not reloaded with resource packs

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#47]
Reloading resource packs updates the LANG files but not the tips.json file that controls which loading tips appear. As a result, changing packs which have different loading tips results in translation keys appearing in the box.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/ed7dc46e-5999-455c-ac7f-5e72ab652089)

**Comment by AgentMindStorm** [comment]
Affects 1.3

**Comment by Wilyicaro** [comment]
I think it was fixed in 1.3.2, I didn't tested

**Comment by AgentMindStorm** [comment]
Fixed in 1.3.2. Thank you!
