### ISSUE TITLE
"Created In Creative"

### ISSUE THREAD

**Issue by ironvxz** [Wilyicaro/Legacy-Minecraft#472]
I've been playing this minecraft world for a couple of weeks, never changing the gamemode or anything. When I started using the mod, in the menu, it says, "Created In Creative." It's not like a huge issue or anything, it's just a little nitpick. Is there anything that could've gone wrong?
![Screenshot 2024-06-16 115913](https://github.com/Wilyicaro/Legacy-Minecraft/assets/173000243/b39189d5-230d-4def-9c5d-d53b24e8e009)

**Comment by Wilyicaro** [comment]
Every world with cheats is considered "Created in Creative" in the LE

**Comment by ironvxz** [comment]
I never used cheats or enabled cheats though.

**Comment by Wilyicaro** [comment]
World data says otherwise... (remembering that cheats are the same thing as commands)
