### ISSUE TITLE
Controller not working on macos

### ISSUE THREAD

**Issue by awesomebro983** [Wilyicaro/Legacy-Minecraft#477]
I've tried 2 different types of controller on my M1 MacBook Air, an Xbox Series controller, and an 8bitdo Pro 2, and neither of them worked. I also tried playing in linux, and the controller worked just fine. What about macos could be causing this?

**Comment by Gregu1939** [comment]
Having the same issue

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
