### ISSUE TITLE
Holding the crouch button for too long when exiting an entity will keep you crouching

### ISSUE THREAD

**Issue by Cloud5474** [Wilyicaro/Legacy-Minecraft#478]
https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/d4303dda-927c-4b90-a361-4666ce7e8d8b

**Comment by Cloud5474** [comment]
Also, a similar issue can be found when swimming down and then touching the ground:
https://github.com/Wilyicaro/Legacy-Minecraft/assets/161091467/2fc92587-a1d1-4b7b-8d56-30edc4b5e874

**Comment by Cloud5474** [comment]
Another thing, it doesn't even seem like LCE considers swimming down with the crouch button actually crouching. The crouch animation doesn't apply and there's no paper doll.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
