### ISSUE TITLE
<Contribution-Updated for 1.3.2> Simple Console Aspects packs to include as optional resource packs

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#48]
UPDATE FOR 1.3.2: Console Aspects DEFAULT & CLASSIC now have a corrected biome_overrides.json. This includes the special fog colors in ocean biomes. Removed sound integration other than music as that was turned into a separate contribution.

[Console Aspects DEFAULT.zip](https://github.com/Wilyicaro/Legacy-Minecraft/files/14055619/Console.Aspects.DEFAULT.zip)
[Console Aspects CLASSIC.zip](https://github.com/Wilyicaro/Legacy-Minecraft/files/14055627/Console.Aspects.CLASSIC.zip)

Here are two versions of Console Aspects to include in the pack. DEFAULT is meant to match PS4 Edition 1.95's Default Textures setting. CLASSIC is meant to match PS4 Edition 1.95's Classic Textures setting. CLASSIC must be applied above Programmer Art.

I don't know how you want to package these, but they would be excellent optional additions to the resource packs screen. You are free to rename them with names that make more sense in this mod! You are also free to modify the packs however you want to best fit this mod. HOWEVER, you must not remove the credit to AgentMindStorm in the pack.mcmeta file.

There are minor sound changes related to music and horse sounds. There are major changes related to block, item, and UI textures. There are a few block model changes like spawners, turtle eggs, and cocoa beans. Splashes and loading messages from both Classic Legacy Editions and the updated PS4 Edition are included too.

**Comment by contrarybaton60** [comment]
we (technically) got the first version of console aspects for java! does this have the legacy biome colors?

**Comment by AgentMindStorm** [comment]
Not sure what you mean by Legacy biome colors. Grass and foliage match on Java and Legacy; they only appear darker on Java due to the gamma difference.

Water colors are not in this pack, and neither are potion colors. Both require Colormatic or Vanadium on Fabric, and neither are updated to 1.20.4. However, I do have a separate pack for Bedrock/Legacy water colors called [Environmental Water](https://www.curseforge.com/minecraft/texture-packs/environmental-water)

**Comment by contrarybaton60** [comment]
I meant the water colors, sorry for the confusion, still though, it's still nice to have something similar to console aspects even if the features are limited

**Comment by AgentMindStorm** [comment]
Update: Added 1.3.2 versions of each pack

**Comment by DanielMC101** [comment]
I really feel like it's just best to leave it Java default imo, cuz there's gonna be some people that were prefer java style LCE

**Comment by AgentMindStorm** [comment]
As stated in the post: "**they would be excellent _optional additions_ to the resource packs screen**"

I do not want them added by default either!

**Comment by DanielMC101** [comment]
> As stated in the post: "**they would be excellent _optional additions_ to the resource packs screen**"
> 
> I do not want them added by default either!

I was talking about the water colors

**Comment by AgentMindStorm** [comment]
Oh, thank you for clarifying. That has nothing to with this post as the water colors were added to the mod without any resource packs. You could open another suggestion issue elsewhere.

**Comment by Wilyicaro** [comment]
Thanks for the contribution, added in version 1.3.3.
