### ISSUE TITLE
Map grid in the Re-Console modpack does not match the map grid from Legacy Console Edition

### ISSUE THREAD

**Issue by Delvin4519** [Wilyicaro/Legacy-Minecraft#482]
On Legacy Console Edition, maps are centered at 0,0 which allows tutorial worlds and classic sized worlds to be mapped in a single 1:8 zoom step 3 map.

In the Re-Console modpack for Java, maps instead have -64,-64 at the northwest corner of the map, making it impossible to map the tutorial worlds in a single map, since 4 maps are required to do this job.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/dd310550-ada0-4fac-a3ee-05134cf55cb6)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/4d4c73ca-bb6b-4fd4-be70-304d4c2f6e16)

**Comment by Wilyicaro** [comment]
Unfortunately, suggestions need to be made on the Legacy4J Discord server in order to better organize GitHub for _issues_ and incompatibilities only (please note that suggestions prior to the creation of this server will be kept)
And also, there is already a suggestion like this on the server
