### ISSUE TITLE
Re-Console modpack, Moderner Beta mod fork does not properly generate TU31+ biomes when using 1.12.2/1.17.1 toggles

### ISSUE THREAD

**Issue by Delvin4519** [Wilyicaro/Legacy-Minecraft#483]
Feedback channel for the Re-Console modpack directs issues to be reported here, but this is mainly to do with the fork of the [Modern Beta](https://github.com/BlueStaggo/modern-beta-fabric/tree/1.20.4-er) mod used for the Re-Console modpack, which does not have a way to report bugs. (If you know where I should report this issue, please let me know and I can close this and move it to the proper reporting spot).

The 1.12.2 and 1.17.1 experimental toggles used to generate TU31+ terrain in the re-console modpack has several issues, the temperature zones are all over the place. Hills do not scale properly with the biome size option that can be configured

The biome map on the right comes from using Moderner Beta 1.12.2/1.17.1 and changing biome size from 4 to 2. The biome map left comes from a modded 1.17.1 client where I changed a single line of code to make a numerical value scalable & added a special zoom layer to replicate Mutated biomes from pre 1.12.2 to match LCE (Mutated/Modified biomes use a 0 seed & 0 salt to generate).

TU31 on Legacy Console does not scale biomes between Biome 1:256 and Hills 1:64, but is configurable after TU54.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/cc1df097-a7fa-4c94-ba9e-e06e741de9d4)

How the game should generate biomes:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/07d595a4-e681-47d6-9aee-29764382469f)
From the Re-Console modpack using Modern Beta:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/3308ce40-6e0c-4527-bfe4-1db444d4bdd6)
How it generates on Legacy Console Edition:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/615d512d-46f7-4124-a052-8e5e2f480e76)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/23464599/c411227f-2a69-41c6-b231-9cdf47dbd27a)

**Comment by omo50** [comment]
Re-Console has a page for issues actually. https://github.com/ViolaFlower/Re-Console/issues 
But this is not a proper "issue". You cant expect there to be 100% parity for LCE considering Moderner Beta doesnt go for LCE, rather beta-early release minecraft
