### ISSUE TITLE
Programmer Art breaking menu buttons

### ISSUE THREAD

**Issue by Hornet-Corperation** [Wilyicaro/Legacy-Minecraft#484]
After disabling programmer art it makes the menu buttons all weird
Previously the buttons were outlined in white (i think) but with programmer art turned on and off it changes to a weird mix of the two. I reinstalled the mod with a newer version and the problem persists.

video link: https://drive.google.com/file/d/1sCjXPQPwTu9XBhGKIeOiTwaWBnadtG4h/view?usp=sharing

**Comment by Cjnator38** [comment]
Console Aspects doesn't change the text color to yellow when it changes the button texture. You can work around this by enabling "Force Yellow Text" within the User Interface settings

**Comment by Wilyicaro** [comment]
> Console Aspects doesn't change the text color to yellow when it changes the button texture. You can work around this by enabling "Force Yellow Text" within the User Interface settings

Exactly
