### ISSUE TITLE
BOAT BUG

### ISSUE THREAD

**Issue by moutardx** [Wilyicaro/Legacy-Minecraft#488]
You know in legacy edition when you sneak it's toggle right? when you have to get out of a boat, you have to click the sneak button. but here in legacy4J when i get out of a boat and you have toggle sneak, well you get out, but you sneak which very annoying _**(i know it was patched for flying**_), thisn't a very bad thing when you don't use those but still necessary if you are exploring and more if you are multiplayer

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.

**Comment by moutardx** [comment]
Thanks alot wily, i appreciate your hard work :)
