### ISSUE TITLE
Move things that REALLY SHOULD BE DATA from resources to data

### ISSUE THREAD

**Issue by forkiesassds** [Wilyicaro/Legacy-Minecraft#490]
This is what's currently blocking the mod from being updated to 1.21. Creative inventory data is in resources and not data. Making it impossible to get certain things like enchants which are data-driven

**Comment by Wilyicaro** [comment]
It shouldn't be, and it's not even feasible to do this, if it were done this would greatly limit customization with the mod, I've already resolved this issue of certain registries that are made by the server side not being present when parsing the components json, be patient, the version 1.21 of the mod will be available soon
