### ISSUE TITLE
You cannot click on screenshots in the chat window to open them.

### ISSUE THREAD

**Issue by jgreen76YT** [Wilyicaro/Legacy-Minecraft#492]
In the vanilla Java Edition of Minecraft, when you take a screenshot, you can open the screenshot in the chat window with the link to the screenshot that is shown. However, in Re-Console/Legacy4J, you cannot click on the screenshot's link to open it, causing you to need to go all the way to your screenshots folder which takes extra time. The "screenshot link" i have been talking about can be shown in the attachment below.
![2024-07-05_09 23 46](https://github.com/Wilyicaro/Legacy-Minecraft/assets/73801850/51408942-6fe2-4aac-8461-8ddf1fac9408)

**Comment by Wilyicaro** [comment]
Look, I take screenshots all the time, and in no version did the chat click event stop working, this could be some incompatibility or simply a bad statement

**Comment by Nobody48213** [comment]
> Look, I take screenshots all the time, and in no version did the chat click event stop working, this could be some incompatibility or simply a bad statement

I can’t open them using the chat either
