### ISSUE TITLE
Nether Ambience Doesn't Stop After Leaving Dimension

### ISSUE THREAD

**Issue by Adamoto64** [Wilyicaro/Legacy-Minecraft#493]
A repeated issue I've been having is, after my Nether trips, the world seems a bit more _sinister..._ 
It's because the background wind of the Nether just doesn't stop lol (even when typing this it's still playing on the alt tab lol)
I think it's because the mod constantly plays music to match console, but I think it's interfering with the Nether ambience from stopping.

**Comment by tristann21** [comment]
> I think it's because the mod constantly plays music to match console

Sounds like you're using [re-console](https://github.com/ViolaFlower/Re-Console). iirc Legacy4Java doesn't continually play music. Re-console uses the [Infinite music mod](https://github.com/PlasticStrawActivist/Infinite-music-mod) for their modpack. Have you tried using just Legacy4Java to see if the problem still happens?

**Comment by Adamoto64** [comment]
I'm not playing re-console, just Legacy4J 
I might've been mistaken about the constant music, because that was a "sales pitch" I heard before I got the mod lol
When I'm not busy I'll see if turning off somethings prevents it.

**Comment by tristann21** [comment]
Can confirm, getting the same issue with only Legacy4Java installed. Very eerie!
[latest.log](https://github.com/user-attachments/files/16120970/latest.log)
[Video_2024-07-07_15-19-10.mp4](https://mega.nz/file/SdNGDbZQ#VVb2h9-GRYOdVGTOWnyp5BqJ38S2vr95f9fKP-BrUp4)

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
