### ISSUE TITLE
Legacy4J crashing when trying to join a server

### ISSUE THREAD

**Issue by DrDorf** [Wilyicaro/Legacy-Minecraft#496]
Almost everything else seems to work fine for me, but I cannot even load in to any servers I put in, just straight up crashes before it could even do it. Not entirely sure if it's on my side or anything but I would like to know if it's an easy fix if it is!

**Comment by tristann21** [comment]
> Almost everything else seems to work fine for me, but I cannot even load in to any servers I put in, just straight up crashes before it could even do it. Not entirely sure if it's on my side or anything but I would like to know if it's an easy fix if it is!

may you send a latest log file as a .txt after a crash? Thank You!

**Comment by DrDorf** [comment]
Sure! But I'm not sure how to do that, does it pop up whenever it crashes?

**Comment by DrDorf** [comment]
[curseforgelogs.txt](https://github.com/user-attachments/files/16120839/curseforgelogs.txt) I think this might be it? I was using the curseforge launcher for the mod, if this is not the right log, please let me know where I could possibly find it, I did check my minecraft logs, and it did not have my most recent attempt to join a server with legacy

**Comment by DrDorf** [comment]
[Legacy logs.txt](https://github.com/user-attachments/files/16120849/Legacy.logs.txt)
Okay I think this is the one you actually need, let me know otherwise!

**Comment by tristann21** [comment]
> [curseforgelogs.txt](https://github.com/user-attachments/files/16120839/curseforgelogs.txt) I think this might be it? I was using the curseforge launcher for the mod, if this is not the right log, please let me know where I could possibly find it, I did check my minecraft logs, and it did not have my most recent attempt to join a server with legacy

Those are the logs from CurseForge. For your Minecraft logs, navigate to the `.minecraft` directory, then proceed to the `logs` folder where you will find the `latest.log` file.

The nice thing about CurseForge is they have a button for your modpack(s) which takes you directly to the `.minecraft` folder!

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/154575581/f5126c51-9075-475b-91aa-f271aa872025)


Sending that here would help the devs out a ton!

**Comment by DrDorf** [comment]
Hey I manage to correct myself, I removed that old post and posted and new one with the file called legacy logs, that one should be it!

**Comment by DrDorf** [comment]
Any update on what's causing this?

**Comment by DrDorf** [comment]
Okay so I did a new mod install, and I have been able to connect to some servers, but it crashes after like a minute, I'm assuming that the mod has a lot of issues with server connections for the moment.

**Comment by Wilyicaro** [comment]
There is no problem with connecting to servers in the mod, it works based on the mod loader used
