### ISSUE TITLE
Dying Beds in Console Crafting Bugged

### ISSUE THREAD

**Issue by Adamoto64** [Wilyicaro/Legacy-Minecraft#497]
So, I made some light gray beds and wanted to dye them blue, but when I tried to so, it ate my blue dye and gave me the light gray bed back lol
(for more context for bug testing, i had multiple light gray beds in my inventory, the white beds dyed fine)

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
