### ISSUE TITLE
[Bug/Glitch]game does not open with 1.7 past the 4j studios screen

### ISSUE THREAD

**Issue by HEROBRINEBOT-462** [Wilyicaro/Legacy-Minecraft#498]
### Legacy4J Version

1.20.4-1.7

### Mod Loader Version

fabric (latest)

### Bug/Glitch Occurrence Context

just made github account to report this
also, 1st 1.7 bug report!

### Crash Report

---- Minecraft Crash Report ---- // Don't be sad, have a hug! <3  Time: 2024-07-10 16:12:06 Description: Rendering overlay  java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.class_442) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread. 	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:3325) 	at net.minecraft.class_437.fabric_getRemoveEvent(class_437.java:3333) 	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.remove(ScreenEvents.java:115) 	at net.minecraft.class_310.handler$cnh000$fabric-screen-api-v1$onScreenRemove(class_310.java:14300) 	at net.minecraft.class_310.method_1507(class_310.java:1156) 	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$3(SDLControllerHandler.java:55) 	at net.minecraft.class_1255.method_19537(class_1255.java:87) 	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:53) 	at net.minecraft.class_442.handler$dln000$legacy$added(class_442.java:619) 	at net.minecraft.class_442.method_49589(class_442.java:331) 	at net.minecraft.class_310.method_1507(class_310.java:1174) 	at net.minecraft.class_310.method_49294(class_310.java:860) 	at net.minecraft.class_310.method_49293(class_310.java:1056) 	at net.minecraft.class_156.method_17974(class_156.java:515) 	at net.minecraft.class_310.method_24228(class_310.java:1052) 	at net.minecraft.class_425.method_25394(class_425.java:1088) 	at net.minecraft.class_757.method_3192(class_757.java:920) 	at net.minecraft.class_310.method_1523(class_310.java:1327) 	at net.minecraft.class_310.method_1514(class_310.java:888) 	at net.minecraft.client.main.Main.main(Main.java:265) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:3325) 	at net.minecraft.class_437.fabric_getRemoveEvent(class_437.java:3333) 	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.remove(ScreenEvents.java:115) 	at net.minecraft.class_310.handler$cnh000$fabric-screen-api-v1$onScreenRemove(class_310.java:14300) 	at net.minecraft.class_310.method_1507(class_310.java:1156) 	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$3(SDLControllerHandler.java:55) 	at net.minecraft.class_1255.method_19537(class_1255.java:87) 	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:53) 	at net.minecraft.class_442.handler$dln000$legacy$added(class_442.java:619) 	at net.minecraft.class_442.method_49589(class_442.java:331) 	at net.minecraft.class_310.method_1507(class_310.java:1174) 	at net.minecraft.class_310.method_49294(class_310.java:860) 	at net.minecraft.class_310.method_49293(class_310.java:1056) 	at net.minecraft.class_156.method_17974(class_156.java:515) 	at net.minecraft.class_310.method_24228(class_310.java:1052) 	at net.minecraft.class_425.method_25394(class_425.java:1088)  -- Overlay render details -- Details: 	Overlay name: ~~ERROR~~ NullPointerException: Cannot invoke "Object.getClass()" because the return value of "net.minecraft.class_310.method_18506()" is null Stacktrace: 	at net.minecraft.class_757.method_3192(class_757.java:920) 	at net.minecraft.class_310.method_1523(class_310.java:1327) 	at net.minecraft.class_310.method_1514(class_310.java:888) 	at net.minecraft.client.main.Main.main(Main.java:265) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- System Details -- Details: 	Minecraft Version: 1.20.4 	Minecraft Version ID: 1.20.4 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.11, Azul Systems, Inc. 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc. 	Memory: 298692136 bytes (284 MiB) / 650117120 bytes (620 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 4 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz 	Identifier: Intel64 Family 6 Model 58 Stepping 9 	Microarchitecture: Ivy Bridge (Client) 	Frequency (GHz): 2.59 	Number of physical packages: 1 	Number of physical CPUs: 2 	Number of logical CPUs: 4 	Graphics card #0 name: Intel(R) HD Graphics 4000 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 2112.00 	Graphics card #0 deviceId: 0x0166 	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161 	Memory slot #0 capacity (MB): 4096.00 	Memory slot #0 clockSpeed (GHz): 1.60 	Memory slot #0 type: DDR3 	Memory slot #1 capacity (MB): 4096.00 	Memory slot #1 clockSpeed (GHz): 1.60 	Memory slot #1 type: DDR3 	Virtual memory max (MB): 15828.20 	Virtual memory used (MB): 8956.01 	Swap memory total (MB): 7914.10 	Swap memory used (MB): 586.16 	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M 	Fabric Mods:  		alternate-current: Alternate Current 1.8.0-beta.4 		animatica: Animatica 0.6+1.20 		architectury: Architectury 11.1.17 		ash_api: Ash API 20.4.0 		badoptimizations: BadOptimizations 2.1.1 		balm-fabric: Balm 9.0.9 		bestylewither: BE Style Wither 1.7.0 		betterhurtcam: BetterHurtCam 1.7.0+mc1.20.3 		betterimpaling: Better Impaling 2.0.7 		biome_replacer: Biome Replacer 1.2 		blockswap: Block Swap 5.0.0.0 		bookshelf: Bookshelf 23.0.8 		borderlessmining: Borderless Mining 1.1.9+1.20.2 		bring_decay: Bring Decay 0.0.4 		carpet: Carpet Mod 1.4.128+v231205 		citresewn: CIT Resewn 1.1.4+1.20.4 			citresewn-defaults: CIT Resewn: Defaults 1.1.4+1.20.4 		clientsidenoteblocks: ClientSideNoteblocks 2.7 		cloth-config: Cloth Config v13 13.0.121 			cloth-basic-math: cloth-basic-math 0.6.1 		collective: Collective 7.60 		configurableextramobdrops: Configurable Extra Mob Drops 3.3 		cool_elytra: Cool Elytra 1.5 		cpm: Customizable Player Models 0.6.16c 		customwindowtitle: Custom Window Title 1.2.0 		debugify: Debugify 1.20.4+1.1 		dynamic_fps: Dynamic FPS 3.4.3 		e4mc_minecraft: e4mc 4.0.1 		emuno: EmuNO 1.1.1 		enhancedblockentities: Enhanced Block Entities 0.9.1+1.20.2 			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0 			spruceui: SpruceUI 5.0.3+1.20.2 		entity_model_features: Entity Model Features 2.0.2 		entity_texture_features: Entity Texture Features 6.0.1 			org_apache_httpcomponents_httpmime: httpmime 4.5.10 		entityculling: EntityCulling 1.6.4 		fabric-api: Fabric API 0.97.0+1.20.4 			fabric-api-base: Fabric API Base 0.4.37+78d798af4f 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f 			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f 			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f 			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f 			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f 			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f 			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f 			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f 			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f 			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f 			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f 			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f 			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f 			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f 			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f 			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f 			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f 		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3 		fabricloader: Fabric Loader 0.15.11 			mixinextras: MixinExtras 0.3.5 		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.2 		ferritecore: FerriteCore 6.0.3 		forgeconfigapiport: Forge Config API Port 20.4.3 		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.2-build.52 		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1 		globalpacks: Global Data- & Resourcepacks 1.16.5 		goldenagecombat: Golden Age Combat 20.4.2 		hideexperimentalwarning: Hide Experimental Warning 1.1 		icterine: Icterine 1.3.0 		immediatelyfast: ImmediatelyFast 1.2.15+1.20.4 			net_lenni0451_reflect: Reflect 1.3.3 		indium: Indium 1.0.30+mc1.20.4 		infinite-music: Infinite Music 0.4.0 		item_obliterator: Item Obliterator 2.2.2 		java: OpenJDK 64-Bit Server VM 17 		languagereload: Language Reload 1.6.1+1.20.4 		leashableboats: Leashable Boats 0.0.1-1.20.4 		legacy: Legacy4J 1.7 			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36 		legacy-mipmaps: Legacy Mipmaps 1.1.0 		letmedespawn: Let Me Despawn 1.2.0 		lithium: Lithium 0.12.1 		loadmyresources: Load My Resources 1.0.4 		malilib: MaLiLib 0.18.1 		midnightlib: MidnightLib 1.5.3 		minecraft: Minecraft 1.20.4 		moddetectionpreventer: ModDetectionPreventer 1.2.0 		modelfix: Model Gap Fix 1.14 		modern_beta: Moderner Beta Fabric 6.5+er1.3.1+1.20.4 		modernfix: ModernFix 5.17.0+mc1.20.4 		morestructuresmod: Many More Structures 1.20.4-1.3.0 		mr_beta_nether: Beta Nether 1-V1 		mr_classic_enchantedgoldenapplecrafting: Classic Enchanted Golden Apple Crafting 1.1 		mr_no_moreamethystgeodes: No More Amethyst Geodes 1.0.0 		mr_no_morecopperore: No More Copper Ore 1.0.0 		mr_no_moredeepslate: No More Deepslate 1.0.0 		mr_no_moreglowlichen: No More Glow Lichen 1.0.0 		mr_no_moreruinedportals: No More Ruined Portals 1.0.0 		necronomicon: Necronomicon 1.4.2 		nerb: Not Enough Recipe Book 0.3 		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0 		nochatreports: No Chat Reports 1.20.4-v2.6.1 		noisium: Noisium 2.0.3+mc1.20.2-1.20.4 		nomoreadvancement: nomoreadvancement 0.2 		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.4 		notexturerotations: NoTextureRotations 1.0.1 		oldblockdrops: OldOreDrops 1.0.0 		oldpotions: Old Potions 2.5 			com_electronwill_night-config_core: core 3.6.7 			com_electronwill_night-config_toml: toml 3.6.7 		paperdoll: Paper Doll 20.4.1 		puzzleslib: Puzzles Lib 20.4.43 		servercore: ServerCore 1.5.0+1.20.4 			fabric-permissions-api-v0: fabric-permissions-api 0.3-SNAPSHOT 			org_yaml_snakeyaml: snakeyaml 2.2 			placeholder-api: Placeholder API 2.3.0+1.20.3 			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2 			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2 		skinlayers3d: 3d-Skin-Layers 1.6.4 		sodium: Sodium 0.5.8+mc1.20.4 		sspb: Sodium Shadowy Path Blocks 3.3.0 		threadtweak: ThreadTweak 1.20.4-0.1.2 		tooltipfix: ToolTip Fix 1.1.1-1.20 		transparent: Transparent 20.4.1 		ukulib: ukulib 1.1.2+1.20.4 			com_moandjiezana_toml_toml4j: toml4j 0.7.2 			gs_mclo_java_mclogs-java: mclogs-java 2.1.1 		unsafe-world-random-access-detector: Unsafe World Random Access Detector 1.1.0 		vmp: Very Many Players 0.2.0+beta.7.139 			com_ibm_async_asyncutil: asyncutil 0.1.0 		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.2+1.20.4-fabric 			com_twelvemonkeys_common_common-image: common-image 3.10.0 			com_twelvemonkeys_common_common-io: common-io 3.10.0 			com_twelvemonkeys_common_common-lang: common-lang 3.10.0 			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0 			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0 			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0 			org_quiltmc_parsers_gson: gson 0.2.1 			org_quiltmc_parsers_json: json 0.2.1 		yosbr: YOSBR 0.1.2 		ysns: You Shall Not Spawn! 1.0.5 	Client Crashes Since Restart: 1 	Integrated Server Crashes Since Restart: 0 	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Fabric Screen API (v1) (fabric-screen-api-v1), Legacy4J (legacy)

### What happened wrong?

crashed

**Comment by RoomAlex68** [comment]
The same thing happened with me but on Forge when game does not open with 1.7.1 past the legacy4j logo

**Comment by Wilyicaro** [comment]
I'll close this issue, as no one is having this anymore
