### ISSUE TITLE
Panorama is moving the wrong direction

### ISSUE THREAD

**Issue by DBTDerpbox** [Wilyicaro/Legacy-Minecraft#5]
The menu panorama is not moving the correct direction, in LCE it moves to the right, in the mod its moving to the left

Its also not moving at the correct speed by default

Mod:

https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/48686406-6f43-4977-85d2-659adc7d32e5

LCE:

https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/282834e0-b765-4bae-a203-d933a8e603ee

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it was fixed in 1.1.1.
