### ISSUE TITLE
How to use Tips and Biome overrides?

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#50]
I saw that tips override can be achieved with resource packs, but for biome overrides. How do I override the biomes? I may need to change the water's fog or something like that. Thanks!

**Comment by AgentMindStorm** [comment]
See assets/legacy/biome_overrides.json https://github.com/Wilyicaro/Legacy-Minecraft/tree/master/common/src/main/resources/assets/legacy

**Comment by Wilyicaro** [comment]
You can use as a template for for now the biome_overrides.json and the json files in tip_overrides folder, in the legacy resources folder.
There will be a wiki in the future for this info.
