### ISSUE TITLE
[Bug/Glitch] The Game Crashes On The Create World Screen With Sinytra Connector

### ISSUE THREAD

**Issue by Danmccool** [Wilyicaro/Legacy-Minecraft#500]
### Legacy4J Version

1.20.1-1.7.1

### Mod Loader Version

NeoForge 47.1.106

### Bug/Glitch Occurrence Context

The Bug Happens When You Try To Create A New World

### Crash Report

https://pastebin.com/MkhPnZnU

### What happened wrong?

The Game Crashed In Stead Of Loading The Menu

**Comment by RoomAlex68** [comment]
The same thing happened with me, but the crashes when I get past the legacy4j logo
with sinytra connector and without sinytra connector

**Comment by Danmccool** [comment]
I Hope They Fix The Bug

**Comment by Danmccool** [comment]
@Wilyicaro

**Comment by RoomAlex68** [comment]
The issue happened when I was using Forge 1.20.1 4.7.30

**Comment by Wilyicaro** [comment]
Apparently, there is nothing wrong with Legacy4J, it is just being mentioned in the crash report because its interfaces are literally used to load the world
