### ISSUE TITLE
Lead Entity Visually Vanishes Upon Attaching[Bug/Glitch]

### ISSUE THREAD

**Issue by Adamoto64** [Wilyicaro/Legacy-Minecraft#501]
### Legacy4J Version

1.12-1.7.2

### Mod Loader Version

Fabric Loader 1.15.11

### Bug/Glitch Occurrence Context

I went to lead my horse and the lead appeared for a split second and vanished lol
The lead still functions, but isn't visible

### What happened wrong?

It's supposed to be tethered to the player and mob, obviously

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
