### ISSUE TITLE
Create Components can be pondered out side of inventory [Bug/Glitch]

### ISSUE THREAD

**Issue by Zekrom7000** [Wilyicaro/Legacy-Minecraft#503]
### Legacy4J Version

Forge 1.20.1-1.7.1

### Mod Loader Version

Forge 47.3.0

### Bug/Glitch Occurrence Context

I select Create Component in my hotbar and it allows for pondering when outside of inventory (which is not supposed to occur). makes walking forward quite difficult.

### What happened wrong?

Video of occurrence: https://github.com/user-attachments/assets/6df3d57a-d16c-4b62-8e3c-a82917bb7ff6

**Comment by Wilyicaro** [comment]
It's not Legacy4J's problem if Create uses unsafe methods to perform these functions, it is certainly detecting whether the W key is being pressed every time the tooltip is being obtained
