### ISSUE TITLE
[Bug/Glitch] Buckets of Mobs and Modded Fluid Buckets do not place their respective liquids

### ISSUE THREAD

**Issue by TheEnderGamer** [Wilyicaro/Legacy-Minecraft#504]
### Legacy4J Version

1.20.1-1.7.1, 1.20.4-1.7.2

### Mod Loader Version

Forge 47.3.0, NeoForge 20.4.234

### Bug/Glitch Occurrence Context

I tried to place a bucket containing a modded fluid in Creative and Survival Mode, but it simply does nothing. Same thing happened when I tried to place any buckets from Vanilla Minecraft containing fish. Regular Water, Lava, and Powder Snow Buckets work fine. You can pick up the modded fluids or fish into buckets, but you cannot place them down again.

### What happened wrong?

Fish and modded fluids in buckets are unable to be placed down in Creative or Survival Mode.

**Comment by Wilyicaro** [comment]
Legacy4J doesn't change how any of this works

**Comment by TheEnderGamer** [comment]
I understand that the mod does not change how any of this works, but from what I have seen, this seems to be an issue exclusive to the mod being installed. I have ran Forge 47.3.0 with no mods and with only Architechtury, and this issue is not prevalent, but as soon as the mod is installed, the fluid buckets cannot be placed. This issue also seems to be exclusive to the Forge and NeoForge ports of the mod, and is not prevalent on Fabric.

**Comment by Raysofdoom2665** [comment]
I can confirm this also happens on 1.20.1-1.7.1 with forge 47.3.5, removing Legacy4J fixed the problem.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
