### ISSUE TITLE
[Bug/Glitch] No noise is made when clearing the hotbar in the Creative Mode menu

### ISSUE THREAD

**Issue by TheEnderGamer** [Wilyicaro/Legacy-Minecraft#505]
### Legacy4J Version

1.20.1-1.7.1, 1.20.4-1.7.2, 1.21-1.7.2

### Mod Loader Version

Forge 47.3.0, NeoForge 20.4.234, Fabric 0.15.11

### Bug/Glitch Occurrence Context

Every time I have cleared my hotbar in the Creative Mode menu, no noise has been made. This bug has affected every version of the mod I have played after the 1.7 update, and seems to affect every version of the mod.

### What happened wrong?

Using the "Clear Quick Select" function in the Creative Menu does not make any noise.

**Comment by Wilyicaro** [comment]
This is not a bug, but rather a suggestion, and they should be on the Legacy4J Discord
