### ISSUE TITLE
[Bug/Glitch] Connecting two controllers while using the controller handler SDL3 stops it from recognizing any controllers

### ISSUE THREAD

**Issue by TheEnderGamer** [Wilyicaro/Legacy-Minecraft#506]
### Legacy4J Version

1.20.1-1.7.1, 1.20.4-1.7.2, 1.21-1.7.2

### Mod Loader Version

Forge 47.3.0, NeoForge 20.4.234, Fabric 0.15.11

### Bug/Glitch Occurrence Context

Whenever I connect two controllers to my system when using the SDL3 controller handler, it refuses to recognize any controllers, even after I disconnect my secondary controller. It will automatically do this if two controllers are detected when the game is launched, and you are forced to switch over to using GLFW and to restart the game in order for the controllers to be recognized again. This bug seems to affect every version that has the SDL3 controller handler as an option, and GLFW seems to be unaffected by this bug.

### What happened wrong?

After two controllers are connected to your system, controller handler SDL3 refuses to recognize any controllers until the game is restarted.

**Comment by Wilyicaro** [comment]
I often use 2 controls and switch between them to ensure this works, I believe this is a specific problem in your system, please provide more information if you would like this problem to be resolved

**Comment by TheEnderGamer** [comment]
This problem may be an issue with interaction between Steam Input controls and SDL3, as that is what I am using for my controls in-game, or maybe an issue with the mod running on SteamOS, as that is what I am running the mod on. I don't have a secondary Bluetooth controller, so I am currently unable to test this on Windows. Another detail about this issue is that there is no controller connect or disconnect message, it just stops working. The controls still do work fine for GLFW, however.
