### ISSUE TITLE
Can no longer craft enchanted golden apples

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#507]
The mod used to add the crafting recipe for the enchanted golden apple to match LCE. In 1.7 this has disappeared. Is this intentional? It might have been accidentally removed when adding updating the mod to 1.21, which added new crafting recipes. 
![2024-07-11_22 08 56](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/4377c0d4-5966-42ef-b062-716c1c8b8a74)
![2024-07-11_22 17 19](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/f6685c6d-c2be-405b-89e3-3ac1a11b07e0)

**Comment by bugsbugsbugsLCE** [comment]
Cobweb to string recipe from TU57 is gone too.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
