### ISSUE TITLE
There are no new 1.21 music discs in miscellaneous.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#508]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric loader 1.15.11

### Bug/Glitch Occurrence Context

![image](https://github.com/user-attachments/assets/efac99e9-5b8d-4422-b832-5f23eff59992)

### What happened wrong?

No music. :(

**Comment by DanielMC101** [comment]
Replace the creative json file inside the jar of the mod in assets\legacy 
[creative_tab_listing.json](https://github.com/user-attachments/files/16200794/creative_tab_listing.json)

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
