### ISSUE TITLE
[Bug/Glitch] Cursor snapping breaks at certain frame rates

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#509]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

For some reason, using Sodium with Legacy4J causes the cursor snapping to stop working properly

[Video with Sodium](https://cdn.discordapp.com/attachments/1232836621603438644/1261493684873203722/PXL_20240713_005948394.LS.mp4?ex=6693290b&is=6691d78b&hm=f00353b1e9ce4e2adfed3d5de08eb7299ea7787ea2267e2d664c07486a3f673d&)
[Video without Sodium](https://cdn.discordapp.com/attachments/1232836621603438644/1261493755328991332/PXL_20240713_010226717.LS.mp4?ex=6693291c&is=6691d79c&hm=d28608a217f22171aff24af90a1fc795f2b850c503c42135e759ef704feee7eb&)

### What happened wrong?

Cursor snapping is clearly trying to work, but Sodium somehow causes the cursor to unsnap from an inventory slot

**Comment by natkos21** [comment]
For me it only appears on my Steam Deck. The cursor also seems to have trouble with moving right/down with xaero's world map open

**Comment by Cjnator38** [comment]
Could be a Linux specific issue then? I don't currently have a Windows machine to test on at the moment so I can't really confirm

**Comment by Wilyicaro** [comment]
If it's the Sodium that is somehow causing this, test to see if limiting the FPS stops this from occurring.

**Comment by Cjnator38** [comment]
So it does seem like that's what fixes it. The issue happens when the frame rate is limited to anything above 60 fps (enabling VSync on 60 hz display doesn't fix it)

**Comment by Cjnator38** [comment]
On a bare L4J instance, the issue does technically still occur, but it's a lot less frequent. With Sodium, its pretty much impossible to snap the cursor without using the d-pad

**Comment by natkos21** [comment]
> So it does seem like that's what fixes it. The issue happens when the frame rate is limited to anything above 60 fps (enabling VSync on 60 hz display doesn't fix it)

While that fixes the weird behaviour in xaero's world map, the cursor still struggles in inventory on my Steam deck. I'll test if it also appears on my pc with linux installed. On that same pc with windows it doesn't appear, so maybe it IS linux-specific?

**Comment by JuniperIsSleepy** [comment]
can confirm cursor acts as normal on my windows pc with sodium and l4j at 120hz. Might be linux specific.

**Comment by natkos21** [comment]
Okay, I tested it on my pc, on a live installation of Manjaro. When at 60 fps, the cursor works as intented. But when over or under 60 fps, the cursor suddenly "gives up". So it seems to be 1. a linux specific issue, and 2. a framerate issue. When not at EXACTLY 60 fps, the cursor's snapping breaks. And it only occurs with sodium installed, as said earlier

**Comment by Cjnator38** [comment]
idk if this was mentioned already but the cursor's movement is generally broken at higher frame rates. Also a Linux specific issue

https://github.com/user-attachments/assets/02b1c2b7-7387-4bf3-9470-2570a84b3184

**Comment by Cjnator38** [comment]
here are some more examples using a more recent version of l4j

Here the FPS is uncapped:

https://github.com/user-attachments/assets/e47af408-6bd8-4bd7-8447-d9b78a7c67d0

Here the FPS is capped using VSync only, then 60 fps Max Framerate is added:

https://github.com/user-attachments/assets/06770bfb-1577-4242-973a-9edaf84a9bb4

**Comment by Wilyicaro** [comment]
still happening?

**Comment by Wilyicaro** [comment]
I'll close this issue, as no one updated about the state of this.
