### ISSUE TITLE
The map is very small.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#51]
![2024-01-24_18 08 46](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/6a8b21ab-8a1d-48f3-a3e9-2b49325eb238)
 
I have nothing else to say, but can you please fix it? This is on 1.20.4 Fabric. Thanks again.

**Comment by Wilyicaro** [comment]
This is very strange, it works normally for me in Fabric 1.20.4, are you using any other mods with Legacy4J ?

**Comment by Quartzmaven** [comment]
It's caused by ImmediatelyFast. Try add some workaround/mixin to fix. Thanks.

**Comment by Wilyicaro** [comment]
Fixed in 1.3.1 version
