### ISSUE TITLE
[Bug/Glitch] Crash on startup with "Updating World Icon" mod

### ISSUE THREAD

**Issue by Easyidle123** [Wilyicaro/Legacy-Minecraft#511]
### Legacy4J Version

1.20.1-1.7.1

### Mod Loader Version

Forge 47.3.0

### Bug/Glitch Occurrence Context

Attempting to load a fresh install of the game with only Legacy4J and [Updating World Icon](https://www.curseforge.com/minecraft/mc-mods/updating-world-icon/) installed

### Crash Report

https://mclo.gs/leFeQhJ

### What happened wrong?

The game crashes while loading, and doesn't reach the main menu.

**Comment by Wilyicaro** [comment]
This mod isn't needed, Legacy4J does this when saving the game, certainly the crash is because of this conflict
