### ISSUE TITLE
[Bug/Glitch] Most music stops playing after programmer art is enabled

### ISSUE THREAD

**Issue by agariLMAO** [Wilyicaro/Legacy-Minecraft#512]
### Legacy4J Version

1.20.1-1.7, 1.20.1-1.7.1

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

Noticed it when trying to make a modpack for 1.20.1, I've opened a similar issue to it and it got closed under the assumption that there was nothing wrong. kept experiencing the issue and i found out what the culprit was.

### What happened wrong?

Turns out that whenever programmer art is enabled it causes for no music to play. I do have a recording of it showing the bug in action. https://youtu.be/fMSGLsrVilM

**Comment by Wilyicaro** [comment]
And there's nothing wrong, the resources aren't mine, and I don't take issue with problems caused by resources, which are customizable and don't require any type of knowledge to be able to modify them. Anyone can make a PR to "fix" this, I don't know what AgentMindStorm's intention was when making these changes to the sounds, I believe they were for something about accuracy, but it has a strange behavior

**Comment by agariLMAO** [comment]
> And there's nothing wrong, the resources aren't mine, and I don't take issue with problems caused by resources, which are customizable and don't require any type of knowledge to be able to modify them. Anyone can make a PR to "fix" this, I don't know what AgentMindStorm's intention was when making these changes to the sounds, I believe they were for something about accuracy, but it has a strange behavior

Could you please clarify of how there's nothing wrong with music being muted when programmer art is turned on? While I do agree that it doesn't require much knowledge to "fix" the issue, the reality is that there's is a good percentage of people that don't wanna go through fixing it themselves, either they don't have the time to do it or they just think it's too tedious to do. I know people have their preferences but I bet most people would rather just install and play any mod without having to do trial and error for it to work 100%, but who knows its probably just me..

**Comment by Permdog99** [comment]
> And there's nothing wrong, the resources aren't mine, and I don't take issue with problems caused by resources, which are customizable and don't require any type of knowledge to be able to modify them. Anyone can make a PR to "fix" this, I don't know what AgentMindStorm's intention was when making these changes to the sounds, I believe they were for something about accuracy, but it has a strange behavior

The issue is about Programmer Art, not Console Aspects

**Comment by Cjnator38** [comment]
Happens on 1.20.2-1.7.2 as well. 1.20.4, 1.20.6 and 1.21 don't have this issue

**Comment by Wilyicaro** [comment]
> > And there's nothing wrong, the resources aren't mine, and I don't take issue with problems caused by resources, which are customizable and don't require any type of knowledge to be able to modify them. Anyone can make a PR to "fix" this, I don't know what AgentMindStorm's intention was when making these changes to the sounds, I believe they were for something about accuracy, but it has a strange behavior
> 
> The issue is about Programmer Art, not Console Aspects

I didn't mention Console Aspects at any time, the changes made to Programmer Art were mostly made by AgentMindStorm, I believe they only changed localization audios, and that's why the error
