### ISSUE TITLE
[Bug/Glitch] SDL3 is not handling multiple controllers on Linux.

### ISSUE THREAD

**Issue by Androser420** [Wilyicaro/Legacy-Minecraft#518]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

Connecting 2 or more controllers on Arch Linux seems not to work with the new SDL3 library, I can't confirm whether it works on other distros or not, but it most likely doesn't.
The same issue #506 had been opened before but lacked some logs and further debugging.

Now since it fails on linux, I tried setting up the same environment on my windows 11 vm with gpu passthrough and it worked flawlessly.
Although it works on windows, gaming there is kinda less than ideal because some people either cant pass their GPU to a vm (while also having somewhat worse performance) or they completely switched to linux like me. 

I have provided my crash report at the line where I assume it fails.

### Crash Report

https://mclo.gs/1rLSQay#L471

### What happened wrong?

SDL3 controller library fails to utilize 2+ controllers connected simultaneously whereas with SDL2 it works but is still kinda buggy.

**Comment by Wilyicaro** [comment]
Since there is this another issue, I didn't need to open another one, even if this one has more information, they deal with the same problem

**Comment by Androser420** [comment]
Ah okay thanks for letting me know because i thought it'd be okay to open a new one since that issue was already closed and marked as complete beforehand
