### ISSUE TITLE
[Bug/Glitch] Modded recipes not showing up in crafting GUI

### ISSUE THREAD

**Issue by Raysofdoom2665** [Wilyicaro/Legacy-Minecraft#519]
### Legacy4J Version

1.20.1-1.7.1

### Mod Loader Version

Forge 47.3.5

### Bug/Glitch Occurrence Context

I was testing with some mods that add items, and their recipes are nowhere to be found in the crafting GUI.

### What happened wrong?

In the crafting GUI, no modded recipes.

**Comment by Raysofdoom2665** [comment]
I did read some reading and can show modded recipes by turning on show vanilla tabs, but it doesn't show modded tabs, meaning they all get thrown into the miscellaneous category, making it a nightmare to find the modded recipe I need.

**Comment by Cjnator38** [comment]
It might be because the mod you are using doesn't provide recipes for the recipe book.

**Comment by Wilyicaro** [comment]
Custom recipes should have another crafting type, or added with an integration with Legacy4J
