### ISSUE TITLE
Legacy water colors do not apply in-game by default

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#52]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/512b0795-c58d-46f8-a5e5-97453733f9dd)

I have no resource packs applied. Full mod list:

Minecraft-Legacy-1.20.4-1.3-fabric
architectury-11.0.11-fabric
fabric-api-0.95.1+1.20.4

HOWEVER, applying a custom biome_overrides.json with a resource pack will change the water colors correctly.

**Comment by Wilyicaro** [comment]
I forgot to add the biome_overrides.json archive in 1.20.4 version, it'll be fixed in the next version
