### ISSUE TITLE
[Suggestion] Compat with Shattered World Limits (SWL)

### ISSUE THREAD

**Issue by Raysofdoom2665** [Wilyicaro/Legacy-Minecraft#520]
### Legacy4J Version

any version

### Mod Loader Version

all modloaders

### Bug/Glitch Occurrence Context

So I was testing around with Shattered World Limits, the World Height does get increased via Shattered World Limits, but I noticed that the Superflat Creator still has the 384 block layer level despite having SWL on.

### What happened wrong?

read the Bug/Glitch Occurrence Context.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
