### ISSUE TITLE
fullscreen resolution text not appearing correctly

### ISSUE THREAD

**Issue by brujyeah** [Wilyicaro/Legacy-Minecraft#521]
### Legacy4J Version

1.20.1

### Bug/Glitch Occurrence Context

![image](https://github.com/user-attachments/assets/3ecfd94d-51af-4c9c-a61d-62fec8967baa)

### What happened wrong?

what the title says

**Comment by Wilyicaro** [comment]
There is no information about the context in which this occurs, such as the OS, not even the screen resolution. 
I would like to say that even with this information the only thing that can be done is to change the Interface Resolution, if a correction is made it will only be applied to Auto Resolution, and will have the same effect

**Comment by Wilyicaro** [comment]
Thanks for reporting, fixed in version 1.20.1-1.7.3
