### ISSUE TITLE
Nintendo Switch Pro Controller Connected But not Working When I using macos Sonoma

### ISSUE THREAD

**Issue by kalebpikachu10** [Wilyicaro/Legacy-Minecraft#522]
https://github.com/user-attachments/assets/547075cb-f2de-4807-a9e7-05b4e2cd8722

here video proof of the issue also it's still doesn't when i update your mod to the latest version.

**Comment by tristann21** [comment]
> IMG_0045.mp4
> 
> here video proof of the issue also it's still doesn't when i update your mod to the latest version.

Try this:

Go to Help & Options -> Controls -> Controller -> And change your controller handler, which is the second slider from the top. It might ask you to download SDL natives or whatever it's called, press OK to do that. 

If it's already on SDL, try using GLFW for the controller handler, and see if that fixes the issue. I'm not sure if changing this setting requires a restart for the game but I don't think so.

Also if it helps, William made a guide on how to download and setup the SDL2 framework on MacOS: https://github.com/contrarybaton60/Williams-Console/wiki/Running-Legacy4J-on-MacOS

**Comment by kalebpikachu10** [comment]
> > IMG_0045.mp4
> > here video proof of the issue also it's still doesn't when i update your mod to the latest version.
> 
> Try this:
> 
> Go to Help & Options -> Controls -> Controller -> And change your controller handler, which is the second slider from the top. It might ask you to download SDL natives or whatever it's called, press OK to do that.
> 
> If it's already on SDL, try using GLFW for the controller handler, and see if that fixes the issue. I'm not sure if changing this setting requires a restart for the game but I don't think so.
> 
> Also if it helps, William made a guide on how to download and setup the SDL2 framework on MacOS: https://github.com/contrarybaton60/Williams-Console/wiki/Running-Legacy4J-on-MacOS

I try and it works thanks for your help.
