### ISSUE TITLE
[Bug/Glitch] World Host integration issues

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#523]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.16.0

### Bug/Glitch Occurrence Context

I've done a bit of testing and I've found a couple issues with the current implementation of World Host's features in Legacy4J:
- "Critical error in WH recv thread" error on host every time player tries to join through the "[Player] went online" toast notification. The joining player will time out each time.
[Log (Player joins at 02:20)](https://mclo.gs/Y5M5soQ#L358)
![image](https://github.com/user-attachments/assets/d04afb54-1b66-4e9b-aa6b-165fb8e7a1f2)

- Game invites appearing as "[Player] added you back as a friend" toast notification.

https://github.com/user-attachments/assets/17c36da0-1e0b-4448-a803-4c838c038761
- No access to an equivalent UI for the Friends tab in the vanilla Multiplayer menu. This tab is the only way to join friends with the standard Java Edition UI.
- Friends can only be added when in a world if Mod Menu isn't installed.

These issues were present in an instance of Legacy4J with Fabric API, Mod Menu + Placeholder API, and World Host. Testing on a 1.21 instance with Fabric Loader 0.16.0 and World Host only, none of the connection issues are present and all connections appear to be successful.

I'll open an issue on the World Host repo as well

### What happened wrong?

In it's current state, using World Host doesn't seem to work with Legacy4J, but does in a standard 1.21 Fabric instance

**Comment by Wilyicaro** [comment]
I've seen many people being able to play normally with World Host installed (disregarding connection problems, of course), online friends' worlds appearing in the Join tab (which is equivalent to online friends in the "vanilla" Multiplayer interface) and everything, saying that not working in its current state is a bit of an exaggeration. 
Invitations made by Legacy4J are not actually _invitations_ as there is no such function in World Host. 
And thanks for suggesting being able to access the friends menu (denoting it as a problem), but I've seen a lot of talk about this, I thought it would be almost useless to add a friend without having an open world. Honestly, I don't want to improve this too much, I would like to make my own implementation of a friend system and world hosting system

**Comment by Cjnator38** [comment]
> Honestly, I don't want to improve this too much, I would like to make my own implementation of a friend system and world hosting system

I've also been hearing a lot of people complain about their difficulties trying to use World Host with L4J, so I think it's exciting to know that an in-house solution is a possibility
