### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by NYCWalIcrawler** [Wilyicaro/Legacy-Minecraft#524]
### Legacy4J Version

1.21 - 1.7

### Mod Loader Version

Fabric 0.100.7 1.21

### Bug/Glitch Occurrence Context

View bobbing stops working when Shaders are enabled through Iris

### What happened wrong?

The view bobbing would stop working if i turned on shaders, making the game seem like i was always in creative flying in third person and just look off in first.

**Comment by Wilyicaro** [comment]
This is known, and is unfixable in my part without removing the Flying View Rolling
