### ISSUE TITLE
[Bug] Water filled cauldrons immovable

### ISSUE THREAD

**Issue by AllanAxolotls** [Wilyicaro/Legacy-Minecraft#525]
### Legacy4J Version

1.20.4 1.7.2

### Bug/Glitch Occurrence Context

water_cauldron is immovable by pistons but should be able to move. This bug breaks a lot of redstone.

### What happened wrong?

the water_cauldron should move when a piston tries pushing it, but it acts like any other immovable block which it shouldn’t

**Comment by Wilyicaro** [comment]
Block entities in the JE are immovable
