### ISSUE TITLE
[Bug/Glitch] Issues when autosave is disabled

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#526]
### Legacy4J Version

1.21-1.7.2, 1.20.6-1.7.2

### Mod Loader Version

Fabric Loader 0.16.0 (1.21), 0.15.11 (1.20.6)

### Bug/Glitch Occurrence Context

Legacy4J's manual saving implementation seems to have a couple bothersome and potentially damaging issues

1. Saving and entering any world (including the world that was saves) too quickly can cause a chunks to get misplaced. Amount of chunks affected could be small, but most instances can fill up most of the log file with errors like "`Chunk file at [-32, 17] is in the wrong location; relocating.`"
Logs from test L4J 1.20.6-1.7.2 instance:
[Before relaunch](https://mclo.gs/51yTe5X)
[After relaunch](https://mclo.gs/EWJUaan)
Images from Re-Console 0.5.7:
![image](https://github.com/user-attachments/assets/52391c26-18cb-4b30-a711-22f3279c64c3)
![image](https://github.com/user-attachments/assets/9b8afda4-4227-4998-9cbf-76144f9585d5)

2. Tamed animals can get deleted when manually saving and reloading the game (might also happen when simply reopening the world)

https://github.com/user-attachments/assets/4cb46231-6d69-414e-b20d-3f408c854323

3. Deleting a world does not work if the previous world save was done with autosave disabled in the current game session. You can only delete the save by exiting the game and deleting through the saves folder, or restarting the game and deleting without loading the world.

4. Exit and Save => Exit Game causes the following to show up in logs:
```[IO-Worker-3/ERROR]: Cound not schedule mailbox
java.util.concurrent.RejectedExecutionException: Task IOWorker-chunk 2 false rejected from java.util.concurrent.ThreadPoolExecutor@7d7cac8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 59728]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[?:?]
	at net.minecraft.class_3846.method_16908(class_3846.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
This might signal that the game is still trying to use ThreadedAnvilChunkStorage, but can't since it's disabled. I don't entirely know how saving works in vanilla, but this might also explain why some entities aren't saved

### What happened wrong?

Manually saving can sometimes cause chunks to be misplaced, tamed animals to be erased, and could prevent intentional save deletion

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
