### ISSUE TITLE
[Bug/Glitch] Incompatible with Fabulously Optimized/Remove Reloading Screen

### ISSUE THREAD

**Issue by pparmy** [Wilyicaro/Legacy-Minecraft#527]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

,,  when trying to add Legacy4J to the beta6 instance of Fabulously Optimized, the  error below is supplied. removing Remove Reloading Screen only leads to more errors which i can supply if of help

### Crash Report

Incompatible mods found! net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other! A potential solution has been determined, this may resolve your problem: 	 - Replace mod 'Legacy4J' (legacy) 1.7.2 with any version that is compatible with: 		 - rrls 5.0.1+mc1.21-fabric More details: 	 - Mod 'Legacy4J' (legacy) 1.7.2 is incompatible with any version of mod 'Remove Reloading Screen' (rrls), but a matching version is present: 5.0.1+mc1.21-fabric! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

### What happened wrong?

mod incompatibility that persists after removal of Remove Reloading Screen(?)

**Comment by Wilyicaro** [comment]
Legacy4J won't be compatible with this mod, as it changes the Loading Overlay to be similar to LE

**Comment by Wilyicaro** [comment]
The last crash is unrelated with this mod and Sodium Extras, it's caused by Puzzle.
It'll be fixed in the next mod version. (1.7.3)
