### ISSUE TITLE
[Bug/Glitch] Hotbar has black line under selected slot while using any non-default resource pack

### ISSUE THREAD

**Issue by RedRain0o0** [Wilyicaro/Legacy-Minecraft#529]
### Legacy4J Version

1.XX-1.7.2

### Mod Loader Version

Any

### Bug/Glitch Occurrence Context

While using a resource pack that modifies `assets/minecraft/textures/gui/sprites/hud/hotbar_selection.png`, a transparent black bar appears at the bottom. I assume this is due to a sub-optimal fix for the bottom of the selection texture not existing normally. Below are examples with Vanilla, Fallout, Faithful 32x, and Fantasy
![Vanilla](https://github.com/user-attachments/assets/3c3e4442-06a0-4efb-a4d3-a6b8d42da139)
![Fallout](https://github.com/user-attachments/assets/ccf08f79-e460-4a52-bbf5-d94682929af2)
![Faithful 32x](https://github.com/user-attachments/assets/ddbe7165-e2fd-4101-abf8-63c7735f86cd)
![Fantasy](https://github.com/user-attachments/assets/bc242f24-0d7c-4fcc-9d50-15dee1bd56fb)

### What happened wrong?

A black bar is rendered below the selected hotbar slot when there shouldn't be anything

**Comment by Wilyicaro** [comment]
This isn't a bug, it's for compatibility with resource packs that modify the hotbar selection sprite from vanilla, that have 23 pixels height for some reason, and the one from L4J that have 24, but only the last line is used, so it doesn't look completely weird with a totally different hotbar texture

**Comment by thedarkcave215** [comment]
Is there any workaround for this? On certain packs it can look very intrusive
