### ISSUE TITLE
Water transparency setting does not work correctly

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#53]
The water transparency setting is meant to match the same setting on Bedrock. However, on Bedrock, the water textures are solid instead of transparent, so their alpha is 255 * 0.8 = 204. However, since the Java water textures are semitransparent, their transparency is 180 * 0.8 = 144, creating overly transparent water.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/c660e5e3-5426-4b8a-87cc-ac415a3e75bb)

To solve this, water textures should be raised to 255 alpha before applying the water_transparency value. If the solution is just replacing the water textures themselves, this will break compatibility with other resource packs, so the "flattening alpha" solution is better.

Here I've used a resource pack to demonstrate how this proposed fix would look. It makes oceans look much more natural.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/27996d0e-31de-46ce-a747-9faef58911b3)

**Comment by Wilyicaro** [comment]
Yes, I know that, but when I noticed it was late, I extracted the water texture from last xbox 360 update, and it was very ugly, and I doesn't used it.  But, saying that the water transparency setting doesn't work correctly is a bit of an exaggeration, because it's simply the texture, when I saw that I actually got scared lol

**Comment by AgentMindStorm** [comment]
Well it's not just the texture, that's the thing. Although the fix you added in 1.3.1 fixes the default water, any texture pack applied above the default resources will have water that looks too transparent. That's why I suggested raising the alpha value of all water textures to 255 before applying the water_transparency changes.

**Comment by Wilyicaro** [comment]
Unfortunately, increasing the alpha value of the water texture is not simple, because to do this I would probably have to create a custom Render Type, which removes the transparency of the original texture, but implies changing the rendering of all fluids, and breaks compatibility with many mods

**Comment by AgentMindStorm** [comment]
Oh, I see. That is unfortunate. Thank you for your responses and for your amazing work on this mod. I know I've been spamming you with bug reports and I apologize. I have just been enjoying playing the game with the Legacy visuals and menus so much! It is incredible what you've achieved in such little time.

**Comment by Wilyicaro** [comment]
You're welcome! 
You helped me a lot with all these issues and contributions
