### ISSUE TITLE
[Bug/Glitch] Broken controllers

### ISSUE THREAD

**Issue by Opoodoop** [Wilyicaro/Legacy-Minecraft#531]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric 0.16.0

### Bug/Glitch Occurrence Context

When 2 or more controllers are connected at the same time.

### Crash Report

[11:35:45] [Timer-1/ERROR]: Uncaught exception in thread "Timer-1" java.lang.IllegalArgumentException: Argument value 0x200000001 exceeds native capacity (4 bytes) mask=0xffffffff00000000 	at com.sun.jna.IntegerType.setValue(IntegerType.java:112) ~[jna-5.14.0.jar:?] 	at com.sun.jna.IntegerType.<init>(IntegerType.java:69) ~[jna-5.14.0.jar:?] 	at dev.isxander.sdl3java.api.joystick.SDL_JoystickID.<init>(SDL_JoystickID.java:25) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] 	at dev.isxander.sdl3java.api.gamepad.SdlGamepad.SDL_GetGamepads(SdlGamepad.java:58) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] 	at wily.legacy.client.controller.SDLControllerHandler.isValidController(SDLControllerHandler.java:183) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] 	at wily.legacy.client.controller.ControllerManager$1.run(ControllerManager.java:63) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?] 	at java.base/java.util.TimerThread.run(Timer.java:516) ~[?:?]

### What happened wrong?

all controller support breaks when i plug in a second controller and does not work again until i restart the game. keyboard and mouse still works afterwards.

**Comment by Dragon-Mom** [comment]
Same issue here, have been unable to get any input

**Comment by tristann21** [comment]
> ### Legacy4J Version
> 1.21-1.7.2
> 
> ### Mod Loader Version
> Fabric 0.16.0
> 
> ### Bug/Glitch Occurrence Context
> When 2 or more controllers are connected at the same time.
> 
> ### Crash Report
> [11:35:45] [Timer-1/ERROR]: Uncaught exception in thread "Timer-1" java.lang.IllegalArgumentException: Argument value 0x200000001 exceeds native capacity (4 bytes) mask=0xffffffff00000000 at com.sun.jna.IntegerType.setValue(IntegerType.java:112) ~[jna-5.14.0.jar:?] at com.sun.jna.IntegerType.(IntegerType.java:69) ~[jna-5.14.0.jar:?] at dev.isxander.sdl3java.api.joystick.SDL_JoystickID.(SDL_JoystickID.java:25) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] at dev.isxander.sdl3java.api.gamepad.SdlGamepad.SDL_GetGamepads(SdlGamepad.java:58) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] at wily.legacy.client.controller.SDLControllerHandler.isValidController(SDLControllerHandler.java:183) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] at wily.legacy.client.controller.ControllerManager$1.run(ControllerManager.java:63) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] at java.base/java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?] at java.base/java.util.TimerThread.run(Timer.java:516) ~[?:?]
> 
> ### What happened wrong?
> all controller support breaks when i plug in a second controller and does not work again until i restart the game. keyboard and mouse still works afterwards.

Until it gets fixed, have you tried using GLFW as the controller handler? it can be a potential work around. Try changing it before you plug in your second controller.

Help & Options -> Controls -> Controller -> Controller Handler slider (second or third from the top)

**Comment by Opoodoop** [comment]
> Until it gets fixed, have you tried using GLFW as the controller handler? it can be a potential work around. Try changing it before you plug in your second controller.
> 
> Help & Options -> Controls -> Controller -> Controller Handler slider (second or third from the top)

I haven't used this mod since as I was only testing out the mod, but I might try it again as you said

**Comment by Dragon-Mom** [comment]
> > ### Legacy4J Version
> > 1.21-1.7.2
> > ### Mod Loader Version
> > Fabric 0.16.0
> > ### Bug/Glitch Occurrence Context
> > When 2 or more controllers are connected at the same time.
> > ### Crash Report
> > [11:35:45] [Timer-1/ERROR]: Uncaught exception in thread "Timer-1" java.lang.IllegalArgumentException: Argument value 0x200000001 exceeds native capacity (4 bytes) mask=0xffffffff00000000 at com.sun.jna.IntegerType.setValue(IntegerType.java:112) ~[jna-5.14.0.jar:?] at com.sun.jna.IntegerType.(IntegerType.java:69) ~[jna-5.14.0.jar:?] at dev.isxander.sdl3java.api.joystick.SDL_JoystickID.(SDL_JoystickID.java:25) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] at dev.isxander.sdl3java.api.gamepad.SdlGamepad.SDL_GetGamepads(SdlGamepad.java:58) ~[dev_isxander_libsdl4j-3.693c75e-36-b73680dfff8078a4.jar:?] at wily.legacy.client.controller.SDLControllerHandler.isValidController(SDLControllerHandler.java:183) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] at wily.legacy.client.controller.ControllerManager$1.run(ControllerManager.java:63) ~[Legacy4J-1.21-1.7.2-fabric.jar:?] at java.base/java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?] at java.base/java.util.TimerThread.run(Timer.java:516) ~[?:?]
> > ### What happened wrong?
> > all controller support breaks when i plug in a second controller and does not work again until i restart the game. keyboard and mouse still works afterwards.
> 
> Until it gets fixed, have you tried using GLFW as the controller handler? it can be a potential work around. Try changing it before you plug in your second controller.
> 
> Help & Options -> Controls -> Controller -> Controller Handler slider (second or third from the top)

I have tried this before and it did not work however I didn't try restarting afterwards so I will have to try that next

**Comment by tristann21** [comment]
@Opoodoop @Dragon-Mom did it work?

**Comment by Dragon-Mom** [comment]
> @Opoodoop @Dragon-Mom did it work?

After restarting with GLFW as the handler and changing the controller manually to my PS5 controller it did work yes, thank you 😄
