### ISSUE TITLE
[Bug/Glitch] No splash

### ISSUE THREAD

**Issue by pewf** [Wilyicaro/Legacy-Minecraft#532]
### Legacy4J Version

1.20.4-1.7.2

### Mod Loader Version

Fabric 0.15.11

### Bug/Glitch Occurrence Context

Load up the game using minecraft 1.20.4, there's no splash text

### What happened wrong?

In the render part of the TitleScreenMixin, the splash is null so it skips over rendering. The splash being null should be the issue

**Comment by Cjnator38** [comment]
afaik this has been fixed in the next update

**Comment by pewf** [comment]
when is the fix coming

**Comment by pewf** [comment]
Oi. When is the fix coming @Wilyicaro

**Comment by omo50** [comment]
> Oi. When is the fix coming @Wilyicaro

youd be better off being patient instead of demanding stuff. stop being entitled

**Comment by Permdog99** [comment]
> Oi. When is the fix coming @Wilyicaro

No worries, this will be fixed in 1.7.3

**Comment by pewf** [comment]
> > Oi. When is the fix coming @Wilyicaro
> 
> youd be better off being patient instead of demanding stuff. stop being entitled

i wasnt demanding anything i was asking a question. a demand would be more like "HEY RELEASE THE FIX NOW!"
