### ISSUE TITLE
[Bug/Glitch] Chat bug issue on 1.20.4

### ISSUE THREAD

**Issue by Deathlife23** [Wilyicaro/Legacy-Minecraft#534]
### Legacy4J Version

1.20.4-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

![image](https://github.com/user-attachments/assets/c73762ee-36ad-493b-bbd3-6eac3e35c20c)

### What happened wrong?

The positioning is wrong and incorrect, thus causing this issue

**Comment by Cjnator38** [comment]
Issue is 1.20.4 specific, so 1.20.1, 1.20.6 and 1.21 aren't affected

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
