### ISSUE TITLE
The Controller compatibilities dose not work the only thing that works are the right and left trigger

### ISSUE THREAD

**Issue by Gonnulf** [Wilyicaro/Legacy-Minecraft#535]
### Legacy4J Version

1.20.4

### Mod Loader Version

Current version

### Bug/Glitch Occurrence Context

The Controller compatibilities dose not work the only thing that works are the right and left trigger

### What happened wrong?

The Controller compatibilities dose not work the only thing that works are the right and left trigger

**Comment by Wilyicaro** [comment]
There is no way I can help you without you informing your system, its version, if you have Steam installed or any other software that interferes with the controller input.
And it is incorrect to say that controller support "dose not work", for most people it works fine, your case is an exception
