### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by W0jtini** [Wilyicaro/Legacy-Minecraft#537]
### Legacy4J Version

1.20.1

### Mod Loader Version

Fabric 0.15.6

### Bug/Glitch Occurrence Context

I added the mod, And it crashes and gives me out an error. Is it my problem or the mods?

### Crash Report

https://pastebin.com/hQDdVuPT

### What happened wrong?

I Opened the game and it crashes.

**Comment by Wilyicaro** [comment]
This is certainly because of a custom launcher

**Comment by TheAwesome98-Real** [comment]
i don't think so, it looks like an incompatibility between wurst (the steal buttons, i think) and legacy4j (which highly modifies all guis). what happens if you try to open the game with wurst disabled?
