### ISSUE TITLE
[Bug/Glitch] Border nametags is not rendering on entity blocks.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#538]
### Legacy4J Version

1.21-1.7.2 

### Mod Loader Version

Fabric loader 0.16.0

### Bug/Glitch Occurrence Context

![image](https://github.com/user-attachments/assets/8db5fb7e-9a6f-4344-b996-ae41accbc817)

![image](https://github.com/user-attachments/assets/b806d798-cb22-4a49-a138-218b1e213b66)

![image](https://github.com/user-attachments/assets/64aed9d3-2ec8-42e6-a345-4914cbc8fd9d)

(I'm not using Iris mod, so it's fully minecraft render.)

### What happened wrong?

Border Nametags just disappears on entity's(?) blocks.

**Comment by Wilyicaro** [comment]
This is a vanilla rendering issue, not a Legacy4J one, if they fix this it will be in Legacy4J as well.
(you can see that not only the border doesn't render, but the background doesn't either)
