### ISSUE TITLE
[Bug/Glitch] creative menu does not act like console edition did

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Wilyicaro/Legacy-Minecraft#539]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Quilt Loader 0.26.3

### Bug/Glitch Occurrence Context

gamepad usage in creative inventory

### What happened wrong?

if you open the creative inventory:
- if you're holding an item in the cursor and close the inventory, the item is not deleted
- if you press west to clear the quick select while hovering an item, it picks up one, which is inconsistent with the button hint. if you are holding an item, it clears the quick select then places it back down.
- the "What's this?" hint overlaps the creative inventory

**Comment by Wilyicaro** [comment]
This is a suggestion, not an issue, and no, I will not remove features from vanilla just to have 100% parity with LE.

**Comment by TheAwesome98-Real** [comment]
what feature would you be removing? that doesn't make sense

**Comment by Wilyicaro** [comment]
> what feature would you be removing? that doesn't make sense

You want it to work identical to LE, right? Obviously if it's identical, there won't be the ability to place 1 item or take half

**Comment by TheAwesome98-Real** [comment]
i didn't want you to remove it, i wanted you to not make the button hint incorrect for the action it performs
