### ISSUE TITLE
(Question) Do you plan on making a discord server for this mod?

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#54]
I think it would be nice and could potentially be nice to get legacy console community involved.

**Comment by AgentMindStorm** [comment]
Please avoid creating a Discord server for this mod. There is already a Discord server about Legacy Console research and development which has a section for #java-edition. https://discord.gg/5WqYCMfN

Additionally, hiding issue information behind a Discord server makes it impossible for users to use search engines to find and report issues. Github is a better location for that sort of thing!

**Comment by SpringDoesStuff** [comment]
Nah make a Discord server, i don't know what the other dude is yapping about but i shouldn't have to be forced somewhere else to see updates for this mod and ONLY this mod, Github is a better place for reporting issues yes, sure but Discord is a better place for catering a community, and honestly that's all i want.

**Comment by zqvb** [comment]
w spring, i vouch

**Comment by Wilyicaro** [comment]
I was planning make a Discord server, more for suggestions and questions about the mod than other things, probably I'll can do this after fixing the actual issues
