### ISSUE TITLE
[Bug/Glitch] Menu SFX

### ISSUE THREAD

**Issue by TheSmokeinator** [Wilyicaro/Legacy-Minecraft#541]
### Legacy4J Version

Version 1.20.2

### Mod Loader Version

Curseforge

### Bug/Glitch Occurrence Context

in the menu, when clicking a button, it makes the modern click sound. is that a bug, or is it missing the old .ogg file?

### What happened wrong?

There is an old sound effect for a menu click, and this mod is missing it

**Comment by Cjnator38** [comment]
Did you check if you had mod resources above the Default resources?

**Comment by Wilyicaro** [comment]
As Cjnator38 said, you need to have the mod resources above the vanilla resources for everything to work as it should
