### ISSUE TITLE
[Bug/Glitch] Cannot type properly in books using keyboard

### ISSUE THREAD

**Issue by jazziejazzgirl** [Wilyicaro/Legacy-Minecraft#542]
### Legacy4J Version

1.7.2

### Mod Loader Version

fabric loader 0.16.0

### Bug/Glitch Occurrence Context

1. get book and quill item
2. typing the spacebar keeps opening up the keyboard screen. i dont know how to turn this off if its even an option
3. can't type normally

also i cant sign my name when im finished, i have to press tab three times to be able to type anything

### What happened wrong?

typing spaces is impossible

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
