### ISSUE TITLE
[Glitch] Server slows down somehow when mod is installed.

### ISSUE THREAD

**Issue by Ivanoshechka** [Wilyicaro/Legacy-Minecraft#543]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric loader 0.16.0

### Bug/Glitch Occurrence Context

 When the mod is installed on the server, the server itself begins to lag/ping a lot. But this for people who just a too away from the host. (Me from Russia to Belarussia host.)
 Yeah, it's lag with Radmin Vpn. But without mod installed - everything so much better and fine. 

### What happened wrong?

 I made a 4 minute [video](https://youtu.be/TBzrTaew8kk) to demonstrate this issue!

[(Plz watch if you can.)](https://youtu.be/TBzrTaew8kk)

**Comment by Wilyicaro** [comment]
Could you help me with this issue?
If you can, test version 1.6.7 of the mod to see if this happens (in this case you would have to make a backup of the server in 1.20.6), so I would already know the solution for this

**Comment by Ivanoshechka** [comment]
So. I create a new fabric server on 1.20.6. Put l4j, fabric api, and that depend mod + [wing's](https://modrinth.com/modpack/wing-server) modpack.
Started with server.properties from 1.21 server.

I log in and it seems to situation is better, but i still have ping spikes while playing (mostly when i flying with elytra). I can interact with world immediately and i didn't get shulker lag when just opening them. 

[There](https://youtu.be/2AN8O2PCySQ) a 3 minute non-cut video of demonstration. 

We tried it without mod, and situation is just better, i don't get 200-300 ping when just flying/playing.

**Comment by Wilyicaro** [comment]
Could you show footage of you flying in vanilla in the same way?
I think it's very unlikely to have anything related to Legacy4J in versions <=1.6.7, since there is nothing in these versions that could cause server slowdowns

**Comment by Ivanoshechka** [comment]
Hmm. Maybe you right. Because in one moment, without mod, when i teleported to 30000000 cords i get 700~ ping. (It's 101% is radmin now.

But [there](https://youtu.be/VZ1Qlc2Dx_4) i just flying without mod.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
