### ISSUE TITLE
[Bug/Glitch] Non-legacy client can't enter server with mod installed

### ISSUE THREAD

**Issue by grayairr** [Wilyicaro/Legacy-Minecraft#545]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

Tried to join a server with the Legacy4J mod installed, can't enter because the mod isn't installed on my client.

![image](https://github.com/user-attachments/assets/edca9510-bb08-4df4-9a68-ecf4a6b2c2b0)

### What happened wrong?

The server, on join, errors out, saying that some registry entries are unknown to the client.

**Comment by JuniperIsSleepy** [comment]
Use RegSyncFix on Modrinth to get around this. Beware some jank may occur.
