### ISSUE TITLE
[Bug/Glitch] Game is crashing after the 4J logo - Fabric 1.21

### ISSUE THREAD

**Issue by nonflyingclouds99** [Wilyicaro/Legacy-Minecraft#547]
### Legacy4J Version

1.21-1.7-fabric

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

1. Open Minecraft
2. Logos appearing normally (They are in an infinite loop but I don't know if this is normal)
3. Click on the screen to skip
4. The game closes

### Crash Report

https://pastebin.com/Eb88mY93

### What happened wrong?

I can't play the Legacy4J mod because my game is simply crashing after the logos appear in an infinite loop. I tried to solve this using the old versions of the mod but none of them actually worked, I didn't try to compare the logs of each version of the mod to see if they were the same.

Seeing now I forgot to add the Architectury API, but even after adding it my Minecraft continues to close the same way as before

**Comment by Wilyicaro** [comment]
#498
