### ISSUE TITLE
Game display bug [Bug/Glitch]

### ISSUE THREAD

**Issue by R27etro** [Wilyicaro/Legacy-Minecraft#549]
### Legacy4J Version

0.7.3+mc1.21

### Mod Loader Version

fabric 0.16.0

### Bug/Glitch Occurrence Context

I do not know how to describe it but the game seems not to be updating the display for whatever reason I can't find out why the game is still interactable and hides the cursor from the whole display  game never crashed

https://youtu.be/yIz-nKyCoekI 

### Crash Report

https://pastebin.com/gvyZjATp

### What happened wrong?

no clue display frozen

**Comment by Wilyicaro** [comment]
Since you are using the [Re-Console](https://github.com/ViolaFlower/Re-Console) modpack, you should make this issue in its repository, I can't help you much with this as it is certainly a specific incompatibility, and no log was provided
