### ISSUE TITLE
(Some Bugs!) Check Below! 

### ISSUE THREAD

**Issue by SpringDoesStuff** [Wilyicaro/Legacy-Minecraft#55]
Interface Opacity also Affects host options, not sure if this is intended but it's strange looking, maybe there should be 2 options for hotbar and for host options?

Using any world generation mods that add extra biomes ETC seems to cause the game to crash, for example I used the mod gipples gallore and tried to create a world using the Legacy4J mod and it displayed the option to Quit or Go back to Title on this bugged Dirt screen, I removed the Legacy4J mod and proceeded to generate the world with the same mods and it generated fine, only after i had done that i added back Legacy4J and I could play the world I created without it, without issues, but I cannot seem to generate worlds when using the mod itself.

Using Port numbers higher than 5 numbers causes the game to crash, which shouldn't be possible given that it doesn't allow you to go higher? but i previously had gotten a crash related to that and the port number exceeded the amount I should have been able to input, although I did try and reproduce this issue and I couldn't so maybe it was one off.

Overall very happy with progress!!!

oh also, for the nametag colors and borders I do think you should make the color borders a little thicker as it seems the border is very thin compared to the actual console countparts.

**Comment by Wilyicaro** [comment]
Firstly, thanks for all these reports.
The interface opacity affects Host Options too, at least in the last xbox 360 edition update, the same for the border, it is very thin in the latest updates.
About the biomes and the port numbers, I'll test it more, but I think that the number limit affects only the Create World Screen

**Comment by Wilyicaro** [comment]
Partially fixed in version 1.3.3, I didn't test the biomes issues.

**Comment by Wilyicaro** [comment]
I'll close this issue, as I tested with the mentioned "biomes" mod, and it's working normally.
