### ISSUE TITLE
[Bug/Glitch] Crash on Launch

### ISSUE THREAD

**Issue by jgreen76YT** [Wilyicaro/Legacy-Minecraft#550]
### Legacy4J Version

1.21-1.7.2-Fabric

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

I run Legacy4J on the modrinth app on fabric 0.15.11 with all dependencies i need + the adrenaline optimization mods and my game crashes on start.

### Crash Report

https://pastebin.com/JWzkwTZK

### What happened wrong?

Crashed on start using modrinth app.

**Comment by Wilyicaro** [comment]
Reset your ImmediatelyFast config, or disable experimental hud batching
