### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by SollaxxScape** [Wilyicaro/Legacy-Minecraft#551]
### Legacy4J Version

1.20.4

### Mod Loader Version

Forge

### Bug/Glitch Occurrence Context

So i was just playing minecraft then suddenly the game crashed
and i cannot start the game again
I HAVE NO OTHER MODS INSTALLED besides legacy4J.

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 296900480 bytes (283 MiB) / 805306368 bytes (768 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f0a
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24366.74
	Virtual memory used (MB): 16318.29
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: Forge 1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2+13
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.70, NVIDIA Corporation
	Window size: 1280x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 9/9 chunks
	Resource Packs: 
	Current Language: en_US
	Locale: en_GB
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
	ModLauncher: 10.1.2
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@49
		javafml@49.1.0
	Mod List: 
		forge-1.20.4-49.1.0-client.jar                    |Minecraft                     |minecraft                     |1.20.4              |ENQUEUE_IM|Manifest: NOSIGNATURE
		OldCombatMod_1.20.X.jar                           |Old Combat Mod                |old_combat_mod                |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		Legacy4J-1.20.4-1.7.2-forge.jar                   |Legacy4J                      |legacy                        |1.7.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.20.4-49.1.0-universal.jar                 |Forge                         |forge                         |49.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.3.0.jar                           |WorldEdit                     |worldedit                     |7.3.0+6678-55745ad  |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-11.1.17-minecraftforge.jar           |Architectury                  |architectury                  |11.1.17             |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: d7d815ab-3647-4639-81b1-f450b3b8721a
	FML: 0.0
	Forge: net.minecraftforge:49.1.0

### What happened wrong?

crash

**Comment by TheAwesome98-Real** [comment]
this is not a crash log, and you haven't formatted it properly. please just use mclo.gs

**Comment by Wilyicaro** [comment]
This issue was made incorrectly, the crash report should have been posted in the correct place, and to make matters worse, there is nothing indicating a crash in this log
