### ISSUE TITLE
[Bug/Glitch] "play" button still shows in the level list

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Wilyicaro/Legacy-Minecraft#552]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Quilt Loader 0.26.3

### Bug/Glitch Occurrence Context

level list

### What happened wrong?

this
![level icon](https://github.com/user-attachments/assets/334ec46d-a9bc-409a-b1c4-b674ab822942)

**Comment by Wilyicaro** [comment]
Don't conclude that something is a bug without being sure, this is obviously intentional, the interface has been redone, nothing has been kept the same as vanilla

**Comment by TheAwesome98-Real** [comment]
> this is obviously intentional

this is not obvious at all. this looks like a mistake to most players. it doesn't make sense why you would include this

**Comment by Wilyicaro** [comment]
> > this is obviously intentional
> 
> this is not obvious at all. this looks like a mistake to most players. it doesn't make sense why you would include this

This is for a few reasons: it only appears while hovering and serves to show that you don't need to click the button again to perform the action, which is totally appropriate since in LE there was no way to use the cursor on this screen, so I have the possibility of including this without saying that it is not accurate with the LE.
I would like to know which players think this is a mistake, you are the first one I have seen talking about this, even with a server with almost 4k users

**Comment by TheAwesome98-Real** [comment]
> even with a server with almost 4k users

oh i wonder why if you require people to join it to request anything that isn't explicitly a bug (like parity fixes or feature requests)

**Comment by Wilyicaro** [comment]
> > even with a server with almost 4k users
> 
> oh i wonder why if you require people to join it to request anything that isn't explicitly a bug (like parity fixes or feature requests)

It's to keep the Issues organized for really important things, like incompatibilities and bugs, if there wasn't a server it would certainly be unfeasible to keep the issues with a bunch of suggestions in between

**Comment by TheAwesome98-Real** [comment]
isn't that what tags are for

**Comment by Wilyicaro** [comment]
> isn't that what tags are for

It wouldn't be useful, the number of suggestions is much greater than the number of issues and incompatibilities, in addition to the fact that the Legacy4J server already has tags that are more suitable for suggestions
