### ISSUE TITLE
[Bug/Glitch] Items in hotbar don't dim along with interface opacity

### ISSUE THREAD

**Issue by thedarkcave215** [Wilyicaro/Legacy-Minecraft#553]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.16.0

### Bug/Glitch Occurrence Context

I've been playing the mod using the Re-Console modpack on Modrinth.

### What happened wrong?

The items in the hotbar don't correctly dim along with the hotbar. I've attached a screenshot of the issue.
![opacity_legacy4j](https://github.com/user-attachments/assets/fa00b122-e68b-4db5-a00f-860e52f24db9)
Below is a screenshot from the Xbox 360 Edition, showing what the items should look like.
![opacity_xbox](https://github.com/user-attachments/assets/6b79577b-4c7e-472a-bded-bc9b1accb121)

**Comment by JuniperIsSleepy** [comment]
disable hud_batching in the immediatelyfast config file

**Comment by JuniperIsSleepy** [comment]
It’s not a bug so much as it is a result of how the optimization method works
