### ISSUE TITLE
[Bug/Glitch] Enchanting Table UI visual bug

### ISSUE THREAD

**Issue by Scruufy** [Wilyicaro/Legacy-Minecraft#554]
### Legacy4J Version

1.20.1

### Mod Loader Version

NeoForge Version 47.1.106

### Bug/Glitch Occurrence Context

im not exactly sure how this is happening but i have this visual bug with the enchanting table
![2024-08-10_01 41 46](https://github.com/user-attachments/assets/d0935d26-4591-4d0c-87bf-7ef1765615bf)

### What happened wrong?

im very familar with the black and pink textures of doom, the enchanting table still functions, but its extremely annoying

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
