### ISSUE TITLE
Question about 1.19.2

### ISSUE THREAD

**Issue by Fel1c** [Wilyicaro/Legacy-Minecraft#556]
Is a 1.19.2 build planned or can it not be done?

**Comment by Wilyicaro** [comment]
Nope, this port is not planned, but anything can be done, the question is how much it is wanted

**Comment by Fel1c** [comment]
It Would be cool if a 1.19.2 Port would be made

**Comment by LuigiGamerYT14** [comment]
Well im a 1.19.2 so might be cool
