### ISSUE TITLE
Older Versions

### ISSUE THREAD

**Issue by Lartsima** [Wilyicaro/Legacy-Minecraft#557]
Can you please add older versions? I don't really want basalt and amethyst in my world because then it's just bedrock edition.

**Comment by RedRain0o0** [comment]
This is for issues, not suggestions. Also, there are no plans for backports beyond what already exists. you can use other mods/datapacks to remove newer features

**Comment by Lartsima** [comment]
Oh ok

wt., 13 sie 2024, 17:34 użytkownik RedRain0o0 ***@***.***>
napisał:
