### ISSUE TITLE
[Bug/Glitch] World save corruption and data rollbacks

### ISSUE THREAD

**Issue by Narrowlegacy87** [Wilyicaro/Legacy-Minecraft#558]
Version : 1.21-1.7.2
Loader : Fabric

I could be playing for like a minute or two and then after a bit I break a block and notice it doesn't drop anything, then I look at the mobs and the'yre all standing still. Attempting to save does nothing even with autosave and then when I click "exit world" it softlocks me in the exiting world screen til I kill process and then load the instance up again to see I've been rolled back. Its gotten so bad I can't even get 20 seconds into my world without the game doing this. I've tried my world without legacy4j and its just a legacy4j issue. I have footage of this as well and literally have no idea what could be causing it

Video : 

https://github.com/user-attachments/assets/0ea9e3bc-9559-47dc-a8d2-b6bbf55ec89e

Only other mods : 
3d skin layers
Appleskin
Enhanced block entitites
Entity Model Features
EntityCulling
Mod Menu
Modern Beta
Mouse Tweaks
No Telemetry
Architectury
Cloth Config
Fabric API

(IT STILL DOES THIS EVEN IF IT IS THE ONLY MOD INSTALLED, IT WORKS FINE WITHOUT LEGACY4J)

**Comment by JuniperIsSleepy** [comment]
Make sure autosave is on, and that minecraft has more ram dedicated to it. Hoping this will be fixex next update

**Comment by Narrowlegacy87** [comment]
> Make sure autosave is on, and that minecraft has more ram dedicated to it. Hoping this will be fixex next update

tried that, autosave actually DISABLES ITSELF and I have like 10gb of ram allocated so its not that, without the mod installed saving works fine so this is a bug that is actually making playing with the mod impossible

**Comment by Narrowlegacy87** [comment]
I would also like to add that the vines you'd get from the jungle biome are literally invisible in the hotbar, its not that they blend in I mean the texture isn't in the hotbar

**Comment by Wilyicaro** [comment]
Everything is stated in #526
