### ISSUE TITLE
[Bug/Glitch] GUI glitches

### ISSUE THREAD

**Issue by Pancakeman1873** [Wilyicaro/Legacy-Minecraft#559]
### Legacy4J Version

1.20.1

### Mod Loader Version

Fabtic Loader 0.15.11

### Bug/Glitch Occurrence Context

The craft GUI opens even when the pause menu is open.

https://github.com/user-attachments/assets/8b1f0541-2597-4099-9916-425727a75c0f

### What happened wrong?

I have assigned craft on the cross keys, which makes it difficult to navigate the menus.
This problem did not occur in 1.21.
(I used a translator so the text may be wrong.)

**Comment by Wilyicaro** [comment]
Not a problem with Legacy4J, it's certainly an external program, like Steam, that is remapping some buttons.

**Comment by Pancakeman1873** [comment]
PCに詳しくないのでわからないのですが、おそらく外部プログラムは起動していないと思うのですが...。
有線のxbox oneコントローラー、Prism Launcher、legacy4Jのみをインストールしたブート構成で遭遇しました。
的外れだったらごめんなさい。

**Comment by Pancakeman1873** [comment]
I don't know, I'm not familiar with PCs, but I'm probably not running any external programs...
I encountered this with a wired xbox one controller, Prism Launcher, and a boot configuration with only legacy4J installed.
Sorry if I'm missing the point.
