### ISSUE TITLE
There's a character limit when typing the server address.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#56]
I was installing World Host mod, I open the LAN, sent the public temporary IP to allow users to join. But the problem is, the server address doesn't fit and they can't join because of the character limit. Also for some reason, the LAN port is limited to "3" instead of 5.

**Steps to Host:**
1. Host singleplayer world.
2. /worldhost ip - it should have the jemnetworks link
3. Send the address to a friend.

**Steps from Host:**
1. "Play Game"
2. Go to the "Join" tab
3. Add Server
4. Paste the link.

**Comment by Wilyicaro** [comment]
Fixed in 1.3.3 version, thanks for reporting.
