### ISSUE TITLE
[Bug/Glitch] Using Joystick to look around doesnt progress the `Look around` tutorial tip

### ISSUE THREAD

**Issue by RedRain0o0** [Wilyicaro/Legacy-Minecraft#560]
### Legacy4J Version

1.XX-1.7.2

### Mod Loader Version

Any (assumedly)

### Bug/Glitch Occurrence Context

When creating a world and getting the `Look around` tip it doesn't accept Joystick look for progress
![image](https://github.com/user-attachments/assets/ce1747f6-b3a4-41a9-9813-0461ad0ca631)

### What happened wrong?

Looking around with joystick doesn't progress the `Look around` tutorial

**Comment by Wilyicaro** [comment]
Well, it's clear that this tutorial is only for the mouse, and that almost nothing has been changed in relation to the vanilla, this will only change when a function for the tutorial world is added
