### ISSUE TITLE
[Bug/Glitch] "Display HUD" option does not hide the "new recipies unlocked" popup

### ISSUE THREAD

**Issue by jan-sonki** [Wilyicaro/Legacy-Minecraft#562]
### Legacy4J Version

1.7.2

### Mod Loader Version

Fabric Loader 0.16.0

### Bug/Glitch Occurrence Context

Go to Settings > User Interface > "Display HUD" and set it to "off". Unlock new recipes so the popup shows up.

### What happened wrong?

![image](https://github.com/user-attachments/assets/8fbb5314-bf60-4083-ab96-91b594dc4e6e)
Apon turning on the "Display HUD" option, it does not hide the "New recipes unlocked" popup.

**Comment by Wilyicaro** [comment]
![image](https://github.com/user-attachments/assets/f4845591-9e03-4769-97a5-7232a64d3d90)
this happens in the LE too, the toasts were visible even with the Display HUD disabled
