### ISSUE TITLE
[Bug/Glitch] Crouch state saves when exiting without saving 

### ISSUE THREAD

**Issue by dragonplus8** [Wilyicaro/Legacy-Minecraft#563]
### Legacy4J Version

1.21.0 -1.7.2

### Mod Loader Version

Fabric 0.16.0 

### Bug/Glitch Occurrence Context

This is incredibly minor, but if you exit a world without saving the game the game will still save if you were crouching or not  

### What happened wrong?

The game should not save the crouching state when exiting without saving

**Comment by Wilyicaro** [comment]
This is part of #526
