### ISSUE TITLE
How do I help translate to Japanese?

### ISSUE THREAD

**Issue by Keitan924111** [Wilyicaro/Legacy-Minecraft#564]
I would like to help translate this project into Japanese. How can I do that?

**Comment by Wilyicaro** [comment]
Feel free to contribute, you can make a Pull Request with the Japanese translation
You can base from the default translation:
https://github.com/Wilyicaro/Legacy-Minecraft/blob/1.20.4/common/src/main/resources/assets/legacy/lang/en_us.json
