### ISSUE TITLE
[Bug] Does not exit properly when game is closed in menu in multimc offline mode

### ISSUE THREAD

**Issue by MunBus** [Wilyicaro/Legacy-Minecraft#566]
### Legacy4J Version

1.21.1 - 1.7.2

### Mod Loader Version

Fabric Loader - 0.15.11

### Bug/Glitch Occurrence Context

Can save game when used exit with saving but not close window. Have to force quit. Worked when in regular mode

### Crash Report

pastebin.com/2ZYnwcZKMy

### What happened wrong?

Did not exit app stuck on exiting game does not close window.

**Comment by MrMeowboots** [comment]
I have this same issue. When exiting my game wont close and will get stuck on this screen, am using 1.20.4 Fabric
![error](https://github.com/user-attachments/assets/407f4b20-927e-45a3-aa46-a2a09e1cb71e)

**Comment by Wilyicaro** [comment]
This isn't caused by Legacy4J, it's a Prism Launcher issue, I'm having this without L4J installed
