### ISSUE TITLE
[Bug/Glitch] The game crashes when a Litematica schematic is loaded into a world

### ISSUE THREAD

**Issue by Daralexen05** [Wilyicaro/Legacy-Minecraft#567]
### Legacy4J Version

1.20.4-1.6.7+fabric

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

[crash-2024-08-20_19.02.56-client.txt](https://github.com/user-attachments/files/16684004/crash-2024-08-20_19.02.56-client.txt)
Crash log.
The problem states itself in the title. I want to rebuild the TU7-TU9 Tutorial World castle in my main survival world. I made a schematic of it using Litematica, but the game crashes when I load the schematic into the world. I went to the Litematica Github, and I found an issue similar to mine. The issue states that Legacy4J is responsible for the crash/incompatibility. https://github.com/maruohon/litematica/issues/853

### What happened wrong?

The game crashes when a Litematica schematic is loaded into the world with Legacy4J installed/enabled.

**Comment by Wilyicaro** [comment]
this was fixed in version 1.7
