### ISSUE TITLE
[Bug/Glitch] Credits do not use `legacy:textures/gui/title/minecraft.png`

### ISSUE THREAD

**Issue by RedRain0o0** [Wilyicaro/Legacy-Minecraft#568]
### Legacy4J Version

1.XX 1.7.3

### Mod Loader Version

Any (assumedly)

### Bug/Glitch Occurrence Context

Going into the exit portal and getting the credits uses the wrong texture

### What happened wrong?

![image](https://github.com/user-attachments/assets/97d05706-2373-4d0f-85e6-cfb6101b7d82)
I was testing Fallout Mash-up Pack and i noticed that the end poem screen doesnt use `legacy:textures/gui/title/minecraft.png`

**Comment by Wilyicaro** [comment]
This isn't a bug, the credits just weren't changed, so they're the same from vanilla
