### ISSUE TITLE
[Bug/Glitch] when the client has Fabric API, Legacy4J MUST be installed to connect to the server.

### ISSUE THREAD

**Issue by dude98** [Wilyicaro/Legacy-Minecraft#569]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric 0.16.0

### Bug/Glitch Occurrence Context

i was testing to see why i kept getting "registry entries unknown to this client" when trying to connect to a legacy4j lan server, and through toggling mods on one at a time found that Fabric API force disconnects you if you don't have Legacy4J installed on the client. i do not know how to disable this, but it makes me unable to join a server with any client tweaks (shaders as an example) unless i installed Legacy4J, making the regular minecraft pause and main menu screens unusable and forces the people who want to play on the server to either completely uninstall fabric (since all the mods need fabric API) or use Legacy4J, which would bother some people.

### What happened wrong?

i'm putting how to reproduce it here:
1. start an instance with just Legacy4J (and its dependencies) installed and make a lan world
2. start another instance with just fabric and the fabric API installed and try to connect to the server
3. the instance gets disconnected with a unknown registry entries error.

if it's possible to fix this on your end please do so, and if it's not please either bring it to someone who can. i'm guessing since other mods also can make this screen show up it's a fabric API thing specifically, but idk how to disable this forced disconnect.

**Comment by Wilyicaro** [comment]
As you said, this is a "problem" with the Fabric API, not with Legacy4J, there is nothing to be done as long as Legacy4J's target is accuracy, which cannot be achieved without adding registries
But you can use this mod: https://modrinth.com/mod/regsyncfix
