### ISSUE TITLE
Suggestion for mod crafting

### ISSUE THREAD

**Issue by BasicAcorn99** [Wilyicaro/Legacy-Minecraft#570]
So basically I think you should be able to craft mod items in the legacy crafting menu, maybe there can be a setting in the settings to enable a tab in the crafting menu that lets you craft all mod items and sorted by mod.

**Comment by Wilyicaro** [comment]
Firstly, suggestions aren't intended to be done here, but in [Legacy4J Discord](https://discord.gg/CVas58uPyb) server
Also, you can craft mod items in the Legacy Crafting Interface, just enable Display Vanilla Tabs in User interface section
