### ISSUE TITLE
[Contribution] Replace Mojang Loading Screen

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#58]
Pick which one here is best for you... I am removing Drippy Loading Screen. This one is important. Thanks.

Switch/3DS
![Switch-style background](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/aefa458f-d14b-43ae-ab89-1d7b2d65eb47)

Xbox 360
![X360-style background](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/0169f652-8b67-4d7d-87df-86e59348421a)

Playstation
![psstylebackground](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/6fae8b60-3a34-40e4-934c-d97e7dce4c1a)

Playstation (Alt)
![alt](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/f6a395d7-0909-4b18-bbe7-8432dbb72bf2)

**Comment by SpringDoesStuff** [comment]
PLEASE

**Comment by Quartzmaven** [comment]
...or optionally, add a path where to customize a loading screen.

**Comment by Quartzmaven** [comment]
There is, but it needs a mod.

https://modrinth.com/mod/rrls
