### ISSUE TITLE
[Bug/Glitch] Cursor not picking up items in inventory menus at random times

### ISSUE THREAD

**Issue by RugerPug** [Wilyicaro/Legacy-Minecraft#582]
### Legacy4J Version

1.21

### Mod Loader Version

Fabric

### Bug/Glitch Occurrence Context

Having this issue where whenever I try to pick up an item in my inventory or any sort of menu, it's stuck on the cursor for a random amount of time. It will not let me place it down anywhere at this time. After a few seconds of being confused, it then allows me to place it somewhere. I've done a multitude of mouse tests and my mouse does not seem to be the issue

### What happened wrong?

https://github.com/user-attachments/assets/ca31246c-2146-4f6a-89be-2b8284171e7d

**Comment by Wilyicaro** [comment]
Legacy4J does not make any changes to the movement of the cursor with the mouse, if there is a problem it is not caused by it
