### ISSUE TITLE
[Bug/Glitch] Crush, help me plz

### ISSUE THREAD

**Issue by OneWorldStudio** [Wilyicaro/Legacy-Minecraft#584]
### Legacy4J Version

Legacy4J [Fabric] 1.20.1-1.7.3

### Mod Loader Version

Fabric 0.16.2

### Bug/Glitch Occurrence Context

[crash-2024-09-04_21.50.08-client.txt](https://github.com/user-attachments/files/16875614/crash-2024-09-04_21.50.08-client.txt)

### What happened wrong?

Crash

**Comment by Wilyicaro** [comment]
I think I already helped u in the Discord

**Comment by OneWorldStudio** [comment]
> Я думаю, я уже помог тебе в Discord.

Yeah
