### ISSUE TITLE
[Crash] Legacy4J client start-up phase

### ISSUE THREAD

**Issue by Cixon** [Wilyicaro/Legacy-Minecraft#585]
### Legacy4J Version

1.21-1.7.3-neoforge

### Mod Loader Version

1.21.1 - 21.1.35 - Neoforge

### Bug/Glitch Occurrence Context

Crash on startup, something to do with GUI overlay.

### LINE 10829
[debug.log](https://github.com/user-attachments/files/16882460/debug.log)

### Crash Report

https://gist.github.com/Cixon/df5115f7eb6d45dfb5981324d62f13ae

### What happened wrong?

Cannot launch client. Title.

**Comment by Scruufy** [comment]
i am having this problem with the 1.7.3 version aswell on forge

**Comment by Cixon** [comment]
> > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly

Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro

**Comment by Wilyicaro** [comment]
> > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> 
> Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro

downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta

**Comment by Cixon** [comment]
well I guess we'll need support for newer NeoForge versions which will be time consuming to fix, I still do appreciate all your efforts @Wilyicaro !

**Comment by jadenquinn** [comment]
> > > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> > 
> > 
> > Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro
> 
> downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta

![image](https://github.com/user-attachments/assets/67ec1ad0-2179-4f65-92bc-eec3d1a7bcc9)

**Comment by jadenquinn** [comment]
It doesn't even work on current 1.21! Maybe put that in the description of your mod. That's a fatal issue.

**Comment by jadenquinn** [comment]
> > > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> > 
> > 
> > Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro
> 
> downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta

This doesn't even work

**Comment by Cixon** [comment]
Please have patience. I understand it’s frustrating but I was advised  a fix was made from a lead tester in the discord community (Stevee); all NeoForge users are waiting.

How did @Wilyicaro fix it? Idk, I’d hope that L4J was at least updated to the newer NeoForge versions though. A update is coming soon.

**Comment by omo50** [comment]
> Please have patience. I understand it’s frustrating but I was advised a fix was made from a lead tester in the discord community (Stevee); all NeoForge users are waiting.
> 
> How did @Wilyicaro fix it? Idk, I’d hope that L4J was at least updated to the newer NeoForge versions though. A update is coming soon.

in all reality this should be a hotfix and not a "waiting for the next update" thing. a whole loader not working on any 1.21.x version is a massive oversight

**Comment by JuniperIsSleepy** [comment]
This is true, neoforge could simply be placed onto “1.7.3_1” or “1.7.3.1” or something temporarily

**Comment by omo50** [comment]
> This is true, neoforge could simply be placed onto “1.7.3_1” or “1.7.3.1” or something temporarily

it should, something like this should have been patched almost immediately IMO

**Comment by Cixon** [comment]
> > This is true, neoforge could simply be placed onto “1.7.3_1” or “1.7.3.1” or something temporarily
> 
> it should, something like this should have been patched almost immediately IMO

I agree but from what I heard, NeoForge apparently made significant changes that inhibited compatibility for L4J which sounds like a rewrite is required? I could be wrong

**Comment by omo50** [comment]
> > > This is true, neoforge could simply be placed onto “1.7.3_1” or “1.7.3.1” or something temporarily
> > 
> > 
> > it should, something like this should have been patched almost immediately IMO
> 
> I agree but from what I heard, NeoForge apparently made significant changes that inhibited compatibility for L4J which sounds like a rewrite is required? I could be wrong

considering it crashes on like every version of neoforge or boots into a black screen, it just most likely wasnt tested for some reason. 1.7.3 on neoforge should be taken down due to the fact it is non functional though

**Comment by jadenquinn** [comment]
> Please have patience. I understand it’s frustrating but I was advised a fix was made from a lead tester in the discord community (Stevee); all NeoForge users are waiting.
> 
> How did @Wilyicaro fix it? Idk, I’d hope that L4J was at least updated to the newer NeoForge versions though. A update is coming soon.

NeoForge screwed up? Ah.

**Comment by Cixon** [comment]
> > Please have patience. I understand it’s frustrating but I was advised a fix was made from a lead tester in the discord community (Stevee); all NeoForge users are waiting.
> > How did @Wilyicaro fix it? Idk, I’d hope that L4J was at least updated to the newer NeoForge versions though. A update is coming soon.
> 
> NeoForge screwed up? Ah. He didn't fix it. He just told them to downgrade their MC version by 1 and use an old version of NeoForge, which doesn't fix anything.

Probably because the update for the fix isn’t out yet…like I said. Lol.

**Comment by Wilyicaro** [comment]
It's clearly supposed to work in this version, just look at the version that the 1.21 build for NeoForge is made in, you can clone this repository yourself and test, if it doesn't work even downgrading this is some other conflict

> > > > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> > > 
> > > 
> > > Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro
> > 
> > 
> > downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta
> 
> This doesn't work. There is no "-beta" one. Only 57. Crashes anyway. Doesn't work on 54 either. Same crash on all tests.
> 
> https://paste.ee/p/vqq7D
> 
> UPDATE: Dammit. I had to scroll all the way down to find that version, this is one crusty old version then. CRASHES ANYWAY!? https://paste.ee/p/q9JbI

It's clearly supposed to work in this version, just look at the version that the 1.21 build for NeoForge is made in, you can clone this repository yourself and test, if it doesn't work even downgrading this is some other conflict

**Comment by jadenquinn** [comment]
> > > > > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> > > > 
> > > > 
> > > > Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro
> > > 
> > > 
> > > downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta
> > 
> > 
> > This doesn't work. There is no "-beta" one. Only 57. Crashes anyway. Doesn't work on 54 either. Same crash on all tests.
> > https://paste.ee/p/vqq7D
> > UPDATE: Dammit. I had to scroll all the way down to find that version, this is one crusty old version then. CRASHES ANYWAY!? https://paste.ee/p/q9JbI
> 
> It's clearly supposed to work in this version, just look at the version that the 1.21 build for NeoForge is made in, you can clone this repository yourself and test, if it doesn't work even downgrading this is some other conflict

And it doesn't work.

**Comment by Wilyicaro** [comment]
> > This is true, neoforge could simply be placed onto “1.7.3_1” or “1.7.3.1” or something temporarily
> 
> it should, something like this should have been patched almost immediately IMO

At the time this issue was discovered I was already developing the next version, obviously I wasn't going to do a hotfix with incomplete features, and besides, I didn't imagine there would be changes to the modloader mapping, especially when it comes to 1.21.1 which there were almost no changes

**Comment by Cixon** [comment]
> 
> And it doesn't work. I agree with your premise, it CLEARLY is supposed to work, but it doesn't. All I did was install your mod and NeoForge, it can't be conflicting with another mod.

L4J was built on an old version of NeoForge which blocks the ability to use other mods. Suggesting a downgrade is obsolete as many that use L4J have other mods and doing this didn’t really fix anything at hand. Nearly all NeoForge developers moved to 21.0.160. If @Wilyicaro can update L4J to a more recent version such as something in Early August or something, it will fix all these issues at hand especially with the mapping accommodations.

**Comment by Wilyicaro** [comment]
> > > > > > > Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
> > > > > 
> > > > > 
> > > > > Is there a workaround for this or will NeoForge remain usable until a fix is provided? @Wilyicaro
> > > > 
> > > > 
> > > > downgrade ur NeoForge and Minecraft versions to 1.21-21.0.57-beta
> > > 
> > > 
> > > This doesn't work. There is no "-beta" one. Only 57. Crashes anyway. Doesn't work on 54 either. Same crash on all tests.
> > > https://paste.ee/p/vqq7D
> > > UPDATE: Dammit. I had to scroll all the way down to find that version, this is one crusty old version then. CRASHES ANYWAY!? https://paste.ee/p/q9JbI
> > 
> > 
> > It's clearly supposed to work in this version, just look at the version that the 1.21 build for NeoForge is made in, you can clone this repository yourself and test, if it doesn't work even downgrading this is some other conflict
> 
> And it doesn't work. I agree with your premise, it CLEARLY is supposed to work, but it doesn't. All I did was install your mod and NeoForge, it can't be conflicting with another mod.

I tested it now, it really isn't working on a common launcher, but it's easy to fix by editing the accesstransformer, I didn't imagine that the development environment would have any difference in relation to this, but thanks for testing this

**Comment by Wilyicaro** [comment]
> > And it doesn't work. I agree with your premise, it CLEARLY is supposed to work, but it doesn't. All I did was install your mod and NeoForge, it can't be conflicting with another mod.
> 
> L4J was built on an old version of NeoForge which blocks the ability to use other mods. Suggesting a downgrade is obsolete as many that use L4J have other mods and doing this didn’t really fix anything at hand. Nearly all NeoForge developers moved to 21.0.160. If @Wilyicaro can update L4J to a more recent version such as something in Early August or something, it will fix all these issues at hand especially with the mapping accommodations.

The new version will be available soon

**Comment by Wilyicaro** [comment]
_I closed the issue by accident_

**Comment by jadenquinn** [comment]
XD

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.4, thanks for reporting.

**Comment by jadenquinn** [comment]
> Fixed in version 1.7.4, thanks for reporting.

No it's not https://private-user-images.githubusercontent.com/13245331/371813386-21e221fb-cd55-4a11-bffb-ccd1453ea310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjkyMzMsIm5iZiI6MTcyNzU2ODkzMywicGF0aCI6Ii8xMzI0NTMzMS8zNzE4MTMzODYtMjFlMjIxZmItY2Q1NS00YTExLWJmZmItY2NkMTQ1M2VhMzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAwMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNWIwNjdhNGU2ODU1ZjFhNzlhOTFhNTBmMDFkMzRhM2QxNTJmZmNhY2E0N2QzZDdhOWRiYTI1MjlhNTY5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._D_ZpdUNcpdBcuhZ73WOAN6LlwWkgHxcColja-yJKyI

**Comment by jadenquinn** [comment]
You might have fixed one issue, but created another that still makes the game not launch.

**Comment by Wilyicaro** [comment]
> You might have fixed one issue, but created another that still makes the game not launch. It works with Forge, no idea wtf NeoForge's problem is.

It's working, and ur link isn't working (certainly it's a crash report), it's even being used in modpacks

**Comment by Wilyicaro** [comment]
I can't say for sure, but I believe you are using an old version of NeoForge, if indeed a new problem has been created, if it is 1.21.1 any version should work
