### ISSUE TITLE
[Bug/Glitch] Black Screen on Bootup for NeoForge 1.21.1

### ISSUE THREAD

**Issue by omo50** [Wilyicaro/Legacy-Minecraft#586]
### Legacy4J Version

1.7.3

### Mod Loader Version

21.1.42

### Bug/Glitch Occurrence Context

Installing Legacy4J for NeoForge just boots into a black screen, rendering the game entirely unplayable
![image](https://github.com/user-attachments/assets/42a97d38-ad73-4cb7-8bd4-adffccf192f3)
Notably doesn't crash. Just is a black screen

### Crash Report

Log: https://mclo.gs/20H3NV4

### What happened wrong?

the game boots into a black screen

**Comment by omo50** [comment]
potentially related to #585 aswell

**Comment by Wilyicaro** [comment]
> potentially related to #585 aswell

This is exactly the same issue

**Comment by omo50** [comment]
> > potentially related to #585 aswell
> 
> This is exactly the same issue

you sure? It doesn't crash, it simply boots into a completely black screen.

**Comment by Wilyicaro** [comment]
> > > potentially related to #585 aswell
> > 
> > 
> > This is exactly the same issue
> 
> you sure? It doesn't crash, it simply boots into a completely black screen.

Yeah, the NeoForge version is broken cuz of changes in some update of the mod loader, both report the same problem, the only difference is that as Cixon's advances in the initialization the crash occurs because it did not initialize correctly
