### ISSUE TITLE
Moving items using number keys or offhand key no longer plays a sound

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#587]
If you move items around in the inventory using the number keys or the offhand key, it no longer makes the minecraft:ui.button.click sound like it used to. The same thing applies when you let go of a mouse button after dragging the cursor to distribute or copy items. (That may be intentional?)

https://github.com/user-attachments/assets/f54e12d0-4713-47f5-a8a2-301c039968d5

**Comment by Wilyicaro** [comment]
This is intentional, the _click_ sound was previously being played on every slot action, simulated or not
