### ISSUE TITLE
Snow golems and player-created iron golems become completely immune to damage when setting the playerVsPlayer to false

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#588]
If you set the playerVsPlayer gamerule to false, it's supposed to make you unable to attack tamed mobs and player created iron golems and snow golems too, which works just fine, however snow golems and player-created iron golems become completely immune to damage, when it is only supposed to make them immune to melee attacks from players. (They can survive lava etc., just anything.) For wolves, horses etc. it works correclty as they do not become immune to any damage.

https://github.com/user-attachments/assets/47fe85fa-aae6-4b7a-b88d-4213c0610efc

https://github.com/user-attachments/assets/5c7584de-49ba-47da-acdf-7890bb74d99d

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.4, thanks for reporting.
