### ISSUE TITLE
Game does not want to launch with one or more mods added with legacy4j in the mods folder

### ISSUE THREAD

**Issue by LOLOXHD** [Wilyicaro/Legacy-Minecraft#589]
Hi there.

I usually don't visit GitHub that often, but I figured, that maybe anyone could help me with this issue.

I have some mods in my mods folder, that usually work fine with every other mod, but I can't get the game to launch with all of those mods. I've tried using only architectury, fabric api, modmenu and legacy4j together and it worked. Somehow, maybe some mod(s) could cause a conflict.

I attached a screenshot with my mods, the latest.log file and if you want to try this yourself, then I've attached a link to my whole mods folder in a zip file.

[latest.log](https://github.com/user-attachments/files/16922432/latest.log)
[Mods.zip](https://www.mediafire.com/file/u898wdq768sweqw/mods.zip/file)

![mods.png](https://github.com/user-attachments/assets/d6a7a1a9-d7e0-49c9-9b12-3926c14645a6)

**Comment by Wilyicaro** [comment]
Remove CleanCut mod
