### ISSUE TITLE
[Bug/Glitch] Classic Crafting item output renders above created item

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#591]
### Legacy4J Version

1.21-1.7.3

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

When Classic Crafting is enabled, the output item is rendered below the created item.
![Re-Console 0.8.0 Beta 8](https://github.com/user-attachments/assets/5fa1a74d-4e6d-4a9d-a7f4-76e7ef597ed8)
![Legacy4J Standalone](https://github.com/user-attachments/assets/b6fbfc77-237e-49ce-85b0-39f7e871f5b6)

### What happened wrong?

The created item should render above the crafting interface's output item.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5.2444.0, thanks for reporting.
