### ISSUE TITLE
[Bug/Glitch] Tutorial Toast crashes the game in world

### ISSUE THREAD

**Issue by Scruufy** [Wilyicaro/Legacy-Minecraft#592]
### Legacy4J Version

1.20.1 1.7.3

### Mod Loader Version

fabric 0.16.5

### Bug/Glitch Occurrence Context

this happens a few seconds after a world load up

### Crash Report

---- Minecraft Crash Report ---- // Daisy, daisy...  Time: 2024-09-10 18:19:16 Description: Unexpected error  java.lang.RuntimeException: Mixin transformation of net.minecraft.class_372 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) 	at net.minecraft.class_1151.method_4899(class_1151.java:89) 	at net.minecraft.class_1156.method_4917(class_1156.java:99) 	at net.minecraft.class_310.method_1574(class_310.java:1925) 	at net.minecraft.class_310.method_1523(class_310.java:1181) 	at net.minecraft.class_310.method_1514(class_310.java:802) 	at net.minecraft.client.main.Main.main(Main.java:250) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) 	... 13 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector render(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIII)V in legacy-common.mixins.json:TutorialToastMixin from mod legacy failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Legacy4J-common-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 16 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) 	at net.minecraft.class_1151.method_4899(class_1151.java:89) 	at net.minecraft.class_1156.method_4917(class_1156.java:99)  -- Affected level -- Details: 	All players: 1 total; [class_746['Scruufy'/306, l='ClientLevel', x=5.22, y=73.00, z=0.78]] 	Chunk stats: 1024, 543 	Level dimension: minecraft:overworld 	Level spawn location: World: (0,74,0), Section: (at 0,10,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 87 game time, 87 day time 	Server brand: fabric 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.class_638.method_8538(class_638.java:458) 	at net.minecraft.class_310.method_1587(class_310.java:2406) 	at net.minecraft.class_310.method_1514(class_310.java:826) 	at net.minecraft.client.main.Main.main(Main.java:250) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: vanilla, fabric, programmer_art, file/bonus_cobblemon_textures_v1-1.5.zip, file/Retro Apricot Leaves, file/Old Lang.zip, file/MissingMon_v3.0 [METALIC MADNESS].zip, file/Mismagius shiny fix by KomiTheGhost.zip, file/Kale's Collection [v1.7].zip, file/Jacturne.zip, file/GG&T Pack.zip, file/FreshMotion[V.0.2](Cobblemon).zip, file/E19 Cobblemon Minimap Icons.zip, file/Cobble-Remodels_v5.1 (2).zip  -- Cobblemon -- Details: 	Version: 1.5.2 	Is Snapshot: false 	Git Commit: df8f078 (https://gitlab.com/cable-mc/cobblemon/-/commit/df8f078d13702ab9a000438910b822ceffbb2248) 	Branch: HEAD  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 2129904032 bytes (2031 MiB) / 4026531840 bytes (3840 MiB) up to 10200547328 bytes (9728 MiB) 	CPUs: 16 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 9 5900HX with Radeon Graphics         	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0 	Microarchitecture: Zen 3 	Frequency (GHz): 3.29 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 16 	Graphics card #0 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x25a0 	Graphics card #0 versionInfo: DriverVersion=32.0.15.5612 	Graphics card #1 name: AMD Radeon(TM) Graphics 	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #1 VRAM (MB): 512.00 	Graphics card #1 deviceId: 0x1638 	Graphics card #1 versionInfo: DriverVersion=30.0.13002.19003 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 35230.75 	Virtual memory used (MB): 22477.77 	Swap memory total (MB): 19456.00 	Swap memory used (MB): 1579.96 	JVM Flags: 10 total; -Xmx9728M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M 	Fabric Mods:  		accurateblockplacement: Accurate Block Placement 1.2.1 		amplified_nether: Amplified Nether 1.2.5 		appleskin: AppleSkin 2.5.1+mc1.20 		architectury: Architectury 9.2.14 		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3 			org_reflections_reflections: reflections 0.10.2 		birds-boids: Birds Boids 1.1.0 		boids: Boids 1.2.2 			blue_endless_jankson: jankson 1.2.3 		borderlessmining: Borderless Mining 1.1.8+1.20.1 		botania: Botania 1.20.1-446-FABRIC 			fiber: fiber 0.23.0-2 			reach-entity-attributes: Reach Entity Attributes 2.4.0 			step-height-entity-attribute: Step Height Entity Attribute 1.2.0 		carryon: Carry On 2.1.2.7 		cicada: CICADA 0.8.3+1.20.1 		cloth-config: Cloth Config v11 11.1.118 			cloth-basic-math: cloth-basic-math 0.6.1 		cobbledollars: CobbleDollars 1.3.2+1.20.1 		cobblemon: Cobblemon 1.5.2+1.20.1 		cobblemon-ui-tweaks: Cobblemon UI Tweaks 1.0.6 		cobblemon_spawn_notification: Cobblemon Spawn Notification 1.5-fabric-1.0.0 		cobblemonintegrations: Cobblemon Integrations 1.0.6 		cobblemonridingfabric: Cobblemon Riding Fabric 1.2.5 		collective: Collective 7.84 		constantmusic: Constant Music 1.0.1 			com_moandjiezana_toml_toml4j: toml4j 0.7.2 		continents: Continents 1.1.5 		copperandtuffbackport: CopperandTuffBackport 1.2 		create: Create 0.5.1-d-build.1161+mc1.20.1 			com_google_code_findbugs_jsr305: jsr305 3.0.2 			flywheel: Flywheel 0.6.10 			milk: Milk Lib 1.2.60 				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2 			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20 			porting_lib_base: Porting Lib Base 2.1.1127+1.20 				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20 				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20 			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20 			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20 				mm: Manningham Mills 2.3 			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20 				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20 			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20 			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20 			porting_lib_models: Porting Lib Models 2.1.1127+1.20 			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20 			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20 				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20 				porting_lib_common: Porting Lib Common 2.1.1127+1.20 				porting_lib_core: Porting Lib Core 2.1.1127+1.20 				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20 				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20 			porting_lib_tags: Porting Lib Tags 3.0 			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20 			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20 			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1 				porting_lib_data: Porting Lib Data 2.1.1090+1.20 				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20 					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20 		deeperdarker: Deeper and Darker 1.3.2 			customportalapi: Custom Portal Api 0.0.1-beta64-1.20 		disenchanter: Disenchanter 0.1.8+1.20 		doubledoors: Double Doors 5.9 		entity_model_features: Entity Model Features 2.2.4 		entity_texture_features: Entity Texture Features 6.2.3 			org_apache_httpcomponents_httpmime: httpmime 4.5.10 		entityculling: EntityCulling 1.7.0 		fabric-api: Fabric API 0.92.2+1.20.1 			fabric-api-base: Fabric API Base 0.4.31+1802ada577 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577 			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577 			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77 			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577 			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377 			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577 			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577 			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577 			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677 			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577 			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577 			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577 			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577 		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1 			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3 			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1 		fabricloader: Fabric Loader 0.16.5 			mixinextras: MixinExtras 0.4.1 		fallingleaves: Falling Leaves 1.15.6 		forgeconfigapiport: Forge Config API Port 8.0.0 		fwaystones: Fabric Waystones 3.3.2+mc1.20.1 		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric 			com_electronwill_night-config_core: core 3.6.5 			com_electronwill_night-config_toml: toml 3.6.5 		gravels_extended_battles: Gravel's Extended Battles 1.4.0 		here-be-no-dragons: Here be no Dragons! 1.0.0 		immediatelyfast: ImmediatelyFast 1.2.21+1.20.4 			net_lenni0451_reflect: Reflect 1.3.4 		immersive_paintings: Immersive Paintings 0.6.7+1.20.1 		indium: Indium 1.0.34+mc1.20.1 		inmis: Inmis 2.7.2-1.20.1 			omega-config: OmegaConfig 1.2.3-1.18.1 		inmisaddon: InmisAddon 1.0.4 		ironchest: Iron Chests 2.0.2 			libgui: LibGui 8.1.1+1.20.1 				jankson: Jankson 6.0.0+j1.2.3 				libninepatch: LibNinePatch 1.2.0 		jade: Jade 11.11.0+fabric 		java: OpenJDK 64-Bit Server VM 17 		legacy: Legacy4J 1.7.3 			dev_isxander_libsdl4j: libsdl4j 3.6896c4c-38 		loadmychunks: Load My Chunks 1.0.6-hf2 		lootr: Lootr 0.7.34.84 		magnumtorch: Magnum Torch 8.0.2 		megamons: Ascension Megamons 1.5.0+1.20.1-forge+fabric-75b66fa 		memoryleakfix: Memory Leak Fix 1.1.5 		midnightlib: MidnightLib 1.4.1 		minecraft: Minecraft 1.20.1 		modelfix: Model Gap Fix 1.15 		modernfix: ModernFix 5.19.4+mc1.20.1 		modmenu: Mod Menu 7.2.2 		more_cobblemon_tweaks: MoreCobblemonTweaks 0.5.1 		niftycarts: NiftyCarts 20.1.3 		notenoughanimations: NotEnoughAnimations 1.7.6 		owo: oωo 0.11.2+1.20 		paintings_backport: 1.21 Paintings backport 2.0.0 		particular: Particular 1.1.1 		patchouli: Patchouli 1.20.1-84-FABRIC 		puzzleslib: Puzzles Lib 8.1.23 			puzzlesaccessapi: Puzzles Access Api 8.0.7 		recast: Recast 3.5 		remove_sword_attack_cooldown: RemoveSwordAttackCooldown 1.0.7-[1.14+] 		showmeyourskin: Show Me Your Skin! 1.9.0+1.20 			cardinal-components-base: Cardinal Components API (base) 5.2.1 			cardinal-components-entity: Cardinal Components API (entities) 5.2.1 		sit: Sit 1.20.1-27 		skinlayers3d: 3d-Skin-Layers 1.6.7 		sodium: Sodium 0.5.11+mc1.20.1 		sodiumextras: Sodium Extras 1.0.1 		sushi_bar: Sushi Bar 0.2.2+1.20 			com_moulberry_mixinconstraints: mixinconstraints 1.0.1 		treeharvester: Tree Harvester 9.1 		trinkets: Trinkets 3.7.2 		yungsapi: YUNG's API 1.20-Fabric-4.0.5 			org_javassist_javassist: javassist 3.29.2-GA 	Flywheel Backend: GL33 Instanced Arrays 	Launched Version: 1.20.1 	Backend library: LWJGL version 3.3.1 SNAPSHOT 	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation 	Window size: 1920x1080 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Type: Integrated Server (map_client.txt) 	Graphics mode: fancy 	Resource Packs: vanilla, fabric, programmer_art, file/bonus_cobblemon_textures_v1-1.5.zip, file/Retro Apricot Leaves, file/Old Lang.zip, file/MissingMon_v3.0 [METALIC MADNESS].zip, file/Mismagius shiny fix by KomiTheGhost.zip, file/Kale's Collection [v1.7].zip, file/Jacturne.zip, file/GG&T Pack.zip, file/FreshMotion[V.0.2](Cobblemon).zip, file/E19 Cobblemon Minimap Icons.zip, file/Cobble-Remodels_v5.1 (2).zip 	Current Language: en_us 	CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics  	Server Running: true 	Player Count: 1 / 8; [class_3222['Scruufy'/306, l='ServerLevel[New World]', x=5.22, y=73.00, z=0.78]] 	Data Packs: vanilla, fabric, Cobble-Remodels_v5.1 (2).zip, Cobblemon_-_Hisuian_Forms_-_Decidueye_Release.zip (incompatible), Fossil_Hybrids!BETA 1.01.zip, FreshMotion[V.0.2](Cobblemon).zip, GG&T Pack.zip, Jacturne.zip, Kale's Collection [v1.7].zip, Kazerio's Radiant Forms v0.1.zip, MissingMon_v3.0 [METALIC MADNESS].zip, bonus_cobblemon_textures_v1-1.5.zip 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Stable

### What happened wrong?

the game crashes due to the tutorial toast.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.4, thanks for reporting.
