### ISSUE TITLE
[Bug/Glitch] Pottery Sherds have broken tips

### ISSUE THREAD

**Issue by Ch1216** [Wilyicaro/Legacy-Minecraft#593]
### Legacy4J Version

1.21-1.8.3

### Mod Loader Version

Fabric Loader 0.16.4

### Bug/Glitch Occurrence Context

Pottery Sherds do not have their tips displayed when the "What's This" button is pressed

### What happened wrong?

There is a tip for "pottery_sherd" in the en_us.json file, so I suspect the reason for them not showing up is there being no pottery sherd tip override

**Comment by Wilyicaro** [comment]
Thank you for listing these non-existent tips, but you are essentially asking for a feature, this is definitely not a bug or a glitch, and for that you should make a suggestion on the[ Legacy4J Discord server](https://discord.gg/CVas58uPyb)
Also, you can make a Pull Request with these overrides if you can 
Ps: version 1.21-1.8.3 doesn't exist yet lol
