### ISSUE TITLE
[Bug/Glitch] Missing Mob Tips from 1.20-1.21

### ISSUE THREAD

**Issue by Ch1216** [Wilyicaro/Legacy-Minecraft#594]
### Legacy4J Version

1.21-1.8.3

### Mod Loader Version

Fabric Loader 0.16.4

### Bug/Glitch Occurrence Context

There are missing tips for the following mobs:
(1.20)
Armadillos
Camels
Sniffer
(1.20.5)
Armadillos
(1.21)
Bogged
Breeze

### What happened wrong?

Tips dont show up for these mobs when they are looked at

**Comment by Wilyicaro** [comment]
#593
