### ISSUE TITLE
[Bug/Glitch] Missing Item Tips from 1.20.5

### ISSUE THREAD

**Issue by Ch1216** [Wilyicaro/Legacy-Minecraft#595]
### Legacy4J Version

1.21-1.8.3

### Mod Loader Version

Fabric Loader 0.16.4

### Bug/Glitch Occurrence Context

1.20.5, also called the Armored Paws dropped added armadillos, armadillos scutes and wolf armor, it also renamed turtle's scute from just being scute to turtle scute
There are missing tips for the following items:
Armadillo Scute
Wolf Armor
Turtle Scute

### What happened wrong?

When pressing the "What's This" key over the mentioned items, no tips show up

**Comment by Wilyicaro** [comment]
Thank you for listing these non-existent tips, but you are essentially asking for a feature, this is definitely not a bug or a glitch, and for that you should make a suggestion on the [Legacy4J Discord server](https://discord.gg/CVas58uPyb
Also, you can make a Pull Request with these overrides if you can 
Ps: version 1.21-1.8.3 doesn't exist, lol
