### ISSUE TITLE
suggestion  1.13 or 1.12.

### ISSUE THREAD

**Issue by fluffdruff** [Wilyicaro/Legacy-Minecraft#596]
### Legacy4J Version

123

### Bug/Glitch Occurrence Context

i would love a backport to older versions such as 1.13 or 1.12. idk if that's too difficult but i would love to play console Minecraft on console versions.

### What happened wrong?

thanks

**Comment by Wilyicaro** [comment]
Suggestions should not be made here, but rather on the Legacy4J Discord server, and currently no backports are planned
