### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by FR00TP3NCH** [Wilyicaro/Legacy-Minecraft#597]
### Legacy4J Version

1.20.1 1.7.3

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

Game randomly crashes while opening GUI because of Legacy4j

### Crash Report

https://pastebin.com/Ji41ivJx

### What happened wrong?

Yeah, I have no idea what's wrong with it. It just crashes sometimes when a GUI is opened.

**Comment by FR00TP3NCH** [comment]
Just found out that it's not because of the GUI, my stupid ass didn't read the crash report. It seems like its a bug with autosaving or something.

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.4, thanks for reporting.
