### ISSUE TITLE
[Bug/Glitch] Modded items in Crafting Tab Listing do not show up in game.

### ISSUE THREAD

**Issue by vos6434** [Wilyicaro/Legacy-Minecraft#598]
### Legacy4J Version

1.20.1-1.7.3

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

I have attempted to add create mod items to a custom crafting tab using a resourcepack with a crafting_tab_listing.json.

### What happened wrong?

Modded items in crafting_tab_listing.json do not show up in game.

The json file tab configuration
![json](https://github.com/user-attachments/assets/7eb308ff-1b00-43c9-8295-0374e08d5dee)

In game screenshot of the issue
![ingame](https://github.com/user-attachments/assets/47cc1618-ce3b-435e-9ad9-61671a72fd78)

As you can see the minecart from the json gets shown but create mod items do not.

**Comment by Wilyicaro** [comment]
u have to put the name of the recipe, not of the "modded item"
