### ISSUE TITLE
<Suggestion> Logical Game Rule Order

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#60]
The Create/Edit World screen is difficult to use because the game rules are ordered alphabetically. Here is a proposed re-ordering to make it easier to use and closer to Legacy.

Here is the general organization idea: World Options covers block movement, Experiments, and Data Packs. Game Options should be sorted as:

General layout principle:

Host Privileges
Time Options (like Daylight Cycle)
Player Options (like Keep Inventory)
Mob Options (like Mob Griefing)
Block Options (like Tile Drops)
Global Options (like Announce Advancements)
Technical Options (like Random Tick Speed and Spawn Radius)
Command Options (like Log Admin Commands)

With this in mind, here is my re-ordering for ease of use:

**World Options (After Customize Button):**

Experiments
Data Packs
Trust Players
Fire Spreads
Vines Spread
Water Source Conversion
Lava Source Conversion

**Game Options**

Host Privileges
Daylight Cycle
Weather Cycle
Keep Inventory
Limited Crafting
Immediate Respawn
Natural Regeneration
Drowning Damage
Fall Damage
Fire Damage
Freezing Damage
Mob Spawning
Phantom Spawning
Pillager Patrols
Disable Raids
Wandering Trader Spawning
Warden Spawning
Mob Griefing
Universal Anger
Forgive Dead Players
Mob Loot
Entity Cramming Limit
Entity Loot
Tile Drops
Block Explosion Drop Decay
TNT Explosion Drop Decay
Mob Explosion Drop Decay
Projectiles Break Blocks
Snow Accumulation Height
Death Messages
Sleep Percentage
Respawn Radius
Random Tick Speed
Announce Advancements
Global Sound Events
Global Map Player Icon
Survival Nether Portal Delay
Creative Nether Portal Delay
Disable Elytra Movement Check
Spectators Generate Chunks
Reduced Debug Information
Log Admin Commands
Command Feedback
Command Block Output
Command Modification Block Limit
Command Chain Limit
Command Context Limit (please capitalize "Limit" in this gamerule in en_us)

**Comment by Wilyicaro** [comment]
Partially added in version 1.3.3

**Comment by Wilyicaro** [comment]
Added in version 1.4.1, not quite in the order and categories you wanted, unfortunately, as compatibility with other mods game rules should be in mind.
