### ISSUE TITLE
[Bug/Glitch] Crash when loading title screen

### ISSUE THREAD

**Issue by jadenquinn** [Wilyicaro/Legacy-Minecraft#600]
### Legacy4J Version

1.12.1

### Mod Loader Version

NeoForge 21.1.56

### Bug/Glitch Occurrence Context

First time using the mod, and it doesn't even work once. All I did was make a new instance with MultiMC, install NeoForge, add the mod, and launch.

### Crash Report

https://paste.ee/p/IIREm

### What happened wrong?

Everything.

**Comment by jadenquinn** [comment]
A video of it crashing, and also when it crashes: https://youtu.be/-tQck-Fqp_s

**Comment by Wilyicaro** [comment]
#585

**Comment by jadenquinn** [comment]
Crashes anyway using 57-beta - https://paste.ee/p/q9JbI
