### ISSUE TITLE
[Bug/Glitch] Game crashes after creating/opening a world

### ISSUE THREAD

**Issue by amonguslover876** [Wilyicaro/Legacy-Minecraft#601]
### Legacy4J Version

1.20.1-1.7.3

### Mod Loader Version

Forge 47.3.10

### Bug/Glitch Occurrence Context

When i tried to create or open a world, it would sometimes work for a few seconds, then it displayed "saving world" screen, then it crashed

### Crash Report

https://pastebin.com/M0aygN0G

### What happened wrong?

Game crashes when i create or open a world
The error shown is as follows:

The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Exit Code: 255

Also I am not using any other mods or resource packs

**Comment by Wilyicaro** [comment]
#592
