### ISSUE TITLE
[Bug/Glitch] can't scroll on custom assortments

### ISSUE THREAD

**Issue by SpringierTrain** [Wilyicaro/Legacy-Minecraft#603]
### Legacy4J Version

1.20.4-1.7.4

### Mod Loader Version

0.15.11

### Bug/Glitch Occurrence Context

![image](https://github.com/user-attachments/assets/d30cf285-11fb-4e78-bd42-f747c2b97c27)

There are no options to scroll down the description. However, the built-in assortments work fine, weirdly enough.
 
Attached below is my custom assortment's json.

```
{
  "description": {
    "translate": "Welcome to the Wasteland! Celebrate the Fallout® series in Minecraft by cracking open this Vault containing 44 unique skins, custom textures, re-skinned mobs, a special post-apocalyptic map, original Fallout soundtrack compilation and a Pip-Boy inspired UI."
  },
  "packs": [
    "vanilla",
    "programmer_art",
    "fabric",
    "file/Legacy Extended 2.12",
    "file/OldHorseModel_1_21_V2_0_2.zip",
    "file/Legacy-Skin-Packs-1.1.1-fixed",
    "file/Classic Villages (Gravel Paths)",
    "file/Legacy-Projects-Skins-v0.1.1",
    "file/FalloutMash-upPack"
  ],
  "id": "template_assort",
  "name": "Fallout"
}
```

### Crash Report

didnt crash

### What happened wrong?

i cant scroll down the description of my custom assortment

**Comment by Wilyicaro** [comment]
Your description is wrong, the `translate` entry is for translation keys, u should replace it with `text` or use a correct translation key

**Comment by SpringierTrain** [comment]
i try making it "description": <description> and replacing the translate key with text and that didnt work either

**Comment by Wilyicaro** [comment]
![image](https://github.com/user-attachments/assets/7150ecd3-3bcc-4619-b462-34b69a1e3d03)
I didn't change anything in this new version...

**Comment by Wilyicaro** [comment]
maybe some conflict?
