### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by FR00TP3NCH** [Wilyicaro/Legacy-Minecraft#604]
### Legacy4J Version

1.20.4 1.7.4

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

When changing the User Interface the GUI icons break
![2024-09-21_19 03 52](https://github.com/user-attachments/assets/e7a1d457-d630-4235-83bc-599d82884f54)
![2024-09-21_19 08 06](https://github.com/user-attachments/assets/af45e1fd-74e0-4609-8ba9-b18c16480416)

### Crash Report

No crash report

### What happened wrong?

Yeah, the things just bugged for some reason.

**Comment by FR00TP3NCH** [comment]
I should have explained more, when I disabled Auto Resolution it just broke the crosshair and icons,

**Comment by Wilyicaro** [comment]
These are artifacts, and they occur precisely because of changes in resolution, there is no way to correct them.
