### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by SpacePizzazzisda1** [Wilyicaro/Legacy-Minecraft#605]
### Legacy4J Version

1.20.1-1.21.1 -1.7.4+fabric

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

Whenever I open a already created world in this version it gets stuck in this screen
![Screenshot 2024-09-21 192007](https://github.com/user-attachments/assets/d4ae310b-f155-4236-a270-f17d557cb1cb)

### What happened wrong?

Can't Open already created world in this version get stuck in this screen
![Screenshot 2024-09-21 192007](https://github.com/user-attachments/assets/f97b6178-c798-4dde-b7af-b7f8bd7d4311)

**Comment by Wilyicaro** [comment]
#599

**Comment by Wilyicaro** [comment]
you should share the log in the original issue, to help find this conflict cause
