### ISSUE TITLE
[Bug/Glitch] Resource Assorts still not save positions / Original click sound bug until loading Resource Assorts again

### ISSUE THREAD

**Issue by Bubasauro95** [Wilyicaro/Legacy-Minecraft#606]
### Legacy4J Version

1.21

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

When opening Legacy4J (even after update 1.7.4), when you click, the original clicking sound plays when clicking unlike the LCE one. 

On the Resource Assorts menu, after changing some resource packs, the position doesn't save. Only inside a world, after doing this again, the positions and the resource packs you selected starts working and the right click sound starts to play again. 

The original clicking sound starts playing again after you leave the world.

https://github.com/user-attachments/assets/17986a70-f727-4650-8467-bb51b53570b7

List of the mods on this modpack:
AppleSkin
Architectury
Balm
Cloth Config v15
Collective
Configuration
Entity Model Feature
Entity Texture Feature
Fabric API
FallingTree
HUD Coordinates
Jade
Legacy4J
MaLiLib
NetherPortalFix
Simple Discord Rich Presence
Sodium
Tax Free Levels
Your Items Are Safe

(if some library are causing the bug, my bad, they are maybe ghost libraries for some mods i've already removed)

### What happened wrong?

Resource Assorts doesn't save positions and the wrong clicking sound plays if you don't change the Resource Assorts

**Comment by Wilyicaro** [comment]
It's clearly saving the order, just the Legacy Waters resource pack isn't compatible with Sodium

**Comment by Wilyicaro** [comment]
And about the click sound, item sizes and other things, u have to use the fabric resources above the Minecraft resources

**Comment by Wilyicaro** [comment]
And I also see that you are using Direct Save Load, using this the Resource Assorts chosen in the world will not be loaded
