### ISSUE TITLE
Cannot open existing worlds

### ISSUE THREAD

**Issue by Jacob450** [Wilyicaro/Legacy-Minecraft#609]
### Legacy4J Version

1.20.4-1.7.4

### Mod Loader Version

fabric-api-0.97.2+1.20.4

### Bug/Glitch Occurrence Context

When trying to open an existing world the game will be stuck on a continuous loading screen.

### What happened wrong?

When trying to open an existing world the game will be stuck on a continuous loading screen.

**Comment by Wilyicaro** [comment]
Remove the Legacy Waters resource pack from your selected resource assort

**Comment by Wilyicaro** [comment]
Also see: #599
