### ISSUE TITLE
<Suggestion> Improved Resource Packs Screen

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#61]
Although the screen in the mod is Legacy-accurate, it is much more difficult to use because Legacy's menu was made for selecting only one pack at a time. It is also not possible to re-order packs with the current menu.

I suggest doing something similar to the Legacy Console UI pack by CrisXolt for Bedrock. It has a resource packs screen based on the old select world screen from Console Edition.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/47bba132-f0b9-473b-921b-06e82f5cbbae)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/4a4aeb32-5e2c-4bad-9480-f43022fe4842)

It is very similar to the old select world screen:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/58c5df9a-a34d-4261-ac1d-e589e50aea71)

This screen allows you to view all the packs you have more easily than the one in this mod currently.

**Comment by Wilyicaro** [comment]
I was planning this, so much so that if you click and hold shift in the actual resource pack selector, the JE Resource Pack Selection screen will open.

**Comment by AgentMindStorm** [comment]
Great to hear!

**Comment by Wilyicaro** [comment]
Thanks for suggesting, added in version 1.3.3
