### ISSUE TITLE
[Bug] [Minor] Controller input not recognized with Fishing Overhaul's Mini-game

### ISSUE THREAD

**Issue by Cixon** [Wilyicaro/Legacy-Minecraft#610]
### Legacy4J Version

Legacy4J-1.21-1.7.4-neoforge

### Mod Loader Version

NeoForge - 21.1.57

### Bug/Glitch Occurrence Context

Trigger button to retract fishing rod not recognized when Fishing Overhaul's Mini-game is prompted.
See more details below.

### Crash Report

n/a

### Input not recognized - Suppose to work like this:

https://youtu.be/J9Zpsntan_8?si=s3_aGvymy88TjVHa&t=8

Source: https://github.com/pitbox46/FishingOverhaul

Mod-page: https://www.curseforge.com/minecraft/mc-mods/fishing-overhaul

**Comment by Wilyicaro** [comment]
This is a specific compatibility request, not a bug, as in this mod the fishing is done through a screen, and key mappings are only consumed when there is no screen, having to be manually checked on the screen for the controller and keyboard

**Comment by Cixon** [comment]
> This is a specific compatibility request, not a bug, as in this mod the fishing is done through a screen, and key mappings are only consumed when there is no screen, having to be manually checked on the screen for the controller and keyboard

Suggested via discord #💡legacy 4J thread, thanks.
