### ISSUE TITLE
[Bug/Glitch] Replay Mod UI bugs out on UI scales outside 720p

### ISSUE THREAD

**Issue by MarGar12** [Wilyicaro/Legacy-Minecraft#612]
### Legacy4J Version

1.7.4

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

Buttons and other UI elements don't show up and the Replay Viewer menu is completely glitched. Here are some screenshots:

Pause Recording and Stop/Play Recording button out of place in 720p
![image](https://github.com/user-attachments/assets/ef0bf891-9f8c-4ff3-ac57-b217c22e5073)

Pause Recording and Stop/Play Recording button not showing up in 1080p
![image](https://github.com/user-attachments/assets/48f1ebc6-3c86-4c9e-b6f4-3665e1c53243)

Broken Replay Viewer menu in 1080p
![image](https://github.com/user-attachments/assets/e3c1fd60-4f00-4243-a668-3b3fda3c2517)

The save replay dialog also doesn't show up on resolutions outside the ui scale of 720p.

### What happened wrong?

Replay Mod UI does not show up in resolutions specifically outside the 720p/768p ui scale. The Pause Recording and Stop/Start Recording button is also out of place and the replays menu ui is completely glitched outside 720p/768p.

**Comment by Wilyicaro** [comment]
#540
