### ISSUE TITLE
why are you limiting chunk distance to 12

### ISSUE THREAD

**Issue by midvightmirage** [Wilyicaro/Legacy-Minecraft#614]
### Legacy4J Version

1.21

### Mod Loader Version

Fabric

### Bug/Glitch Occurrence Context

you limit chunk distance to 12
also why is there no other place that is more fitting where i can say this
only this here

### What happened wrong?

why are you limiting chunk distance to 12

**Comment by midvightmirage** [comment]
dit it serriously make a new issue
god i hate github

**Comment by Wilyicaro** [comment]
L4J doesn't limit the chunk distance
