### ISSUE TITLE
Controller support is broken

### ISSUE THREAD

**Issue by jadenquinn** [Wilyicaro/Legacy-Minecraft#615]
I'm on a Mac, and that's probably why. Still a problem. All you gotta do is take the library that's included in one of the other mods that DOES work on the Mac, like Controlify, and bam, it should work on the Mac.

Sorry for not using the issue template, that's broken on the iOS GitHub app.

**Comment by Wilyicaro** [comment]
It's using the same library as the Controlify, just download the SDL Controller Handler

**Comment by Shane-King** [comment]
I don't understand how to fix it is it a mod loader issue or like I am using the latest version of Mac OS on my m1 Mac and it still don't work out of the box and have no idea how to fix it

**Comment by Shane-King** [comment]
I don't even know how use or even download the sdl

> Does using the SDL controller handler fix anything?

**Comment by Shane-King** [comment]
> > I don't even know how use or even download the sdl
> > > Does using the SDL controller handler fix anything?
> 
> Find the controller settings ingame and change GLFW handler to SDL3, there should be a slider

ohh I thx so much

**Comment by Wilyicaro** [comment]
I'll certainly set the SDL 3 Controller Handler as default in Mac OS too
