### ISSUE TITLE
[mod-incompat] Legacy 4J x Moonrise

### ISSUE THREAD

**Issue by Cixon** [Wilyicaro/Legacy-Minecraft#616]
### Legacy4J Version

1.21-1.7.4

### Mod Loader Version

NeoForge: 21.1.59

### Bug/Glitch Occurrence Context

Mixin incompatibility with Moonrise. Developer provided a pseudo-code fix for you to look into.

See comment for initial ticket here:
https://github.com/Tuinity/Moonrise/issues/39#issuecomment-2384772100

### Crash Report

nah.

### What happened wrong?

Title.

**Comment by Wilyicaro** [comment]
> You could bundle MixinExtras in Forge, allowing you to use MixinExtras freely

This should work too, but it's not ideal, I think just injecting before and after the `collide` method call in `move` will be better

**Comment by Cixon** [comment]
wish to see a patch soon 🤞

**Comment by Wilyicaro** [comment]
I already fixed it in dev builds, but as I'm working on other project I wouldn't expect to see it very soon

**Comment by Cixon** [comment]
> I already fixed it in dev builds, but as I'm working on other project I wouldn't expect to see it very soon

Gotcha. Thanks!

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5.2444.0, thanks for reporting
