### ISSUE TITLE
[Bug/Glitch] Crash when rendering username

### ISSUE THREAD

**Issue by Jab125** [Wilyicaro/Legacy-Minecraft#617]
### Legacy4J Version

1.21-0.7.4

### Mod Loader Version

Fabric Loader 0.16.5

### Bug/Glitch Occurrence Context

When signing in and entering the encryption password

### Crash Report

https://gist.github.com/Jab125/66c820b9e7b1441f3ffd12ec01758c5f

### What happened wrong?

Game crash

### Code Analysis

`mc.getUser()` can in fact be null, which would cause a game crash when trying to call `getUsername()`.
https://github.com/Wilyicaro/Legacy-Minecraft/blob/119382dbbc00f7fd4967a336893f371122436724/common/src/main/java/wily/legacy/util/ScreenUtil.java#L118

### Potential Solution

Right above the problematic line, add:
```java
if (mc.getUser() == null) return;
```
so if `mc.getUser()` ends up being `null`, simply not rendering the username at all.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5.2444.0, thanks for reporting.
