### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by Ghostblackout** [Wilyicaro/Legacy-Minecraft#618]
### Legacy4J Version

1.20.1-1.7.4

### Mod Loader Version

0.16.5

### Bug/Glitch Occurrence Context

I need help my xbox controller 360 is not working on my pc that runs arch linux but when I use it on my pc it works fine in minecraft

### What happened wrong?

I cant use my xbox controller 360 on linux

**Comment by Wilyicaro** [comment]
It should work correctly, but it's not related to L4J, it's certainly the absence of the driver for that controller.
