### ISSUE TITLE
[Bug/Glitch] [Forge] Controller Configurations Not Saving

### ISSUE THREAD

**Issue by Vintage-kun** [Wilyicaro/Legacy-Minecraft#619]
### Legacy4J Version

1.20.1 1.74

### Mod Loader Version

Forge 47.3.0

### Bug/Glitch Occurrence Context

Controller configurations not saving.

### What happened wrong?

When changing the controller button mappings and exiting the game, after reopening the game all the button remaps return to their default state. This seems to only happen with Forge, as Fabric works just fine. 

I've tried different versions of Legacy4J, Forge, and disabling all other mods, but the issue still persists.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5, thanks for reporting.
