### ISSUE TITLE
[Bug/Glitch] Certain mods aren't compatible with Legacy4J

### ISSUE THREAD

**Issue by nenamoree9** [Wilyicaro/Legacy-Minecraft#621]
### Legacy4J Version

1.21-1.7.4

### Mod Loader Version

Fabric Loader 0.16.7

### Bug/Glitch Occurrence Context

Certain mods won't play nicely with Legacy4J and when you try to launch Minecraft, the game crashes or fails to load.

My mods list:
3d-Skin-Layers
AmbientSounds
Animatica
AppleSkin
Better Ping Display
Better Statistics Screen
BetterF3
Bobby
CalcMod
Cardinal Components API
Carpet Mod
Celestial
CICADA
CIT Resewn
clearsky
Cloth Config v15
Configured
Controlling
CreativeCore
Damage Numbers
Debugify
Detail Armor Bar
Dynamic Crosshair
Dynamic FPS
Easy Shulker Boxes
EffectTimerPlus
EMI
Enchanted Vertical Slabs
Enhanced Block Entities
Entity Model Features
Entity Sound Features
Entity Texture Features
ExtraSounds Next
Fabric API 0.102.0+1.21
Fabric Language Kotlin
Fabric Tailor
FerriteCore
Footprint Particle
Footprint Particles
Forge Config API Port
Freecam (Modrinth Edition)
GeckoLib 4
GlitchCore
Held Item Info
Highlighter
Human Reborn
Iceberg
... more

My launcher is Prism Launcher

### Crash Report

https://mclo.gs/mMMIi8j

### What happened wrong?

The game crashes while trying to start up

**Comment by Wilyicaro** [comment]
Remove Carpet Mod, Legacy4J already adds accurate pushable block entities
