### ISSUE TITLE
[Bug/Glitch] Java Runtime crashes when switching to keyboard input

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#622]
### Legacy4J Version

1.21-1.7.4

### Mod Loader Version

Fabric Loader 0.16.2

### Bug/Glitch Occurrence Context

More often than not, pressing a key on the keyboard after using controller input crashes JRE.

https://github.com/user-attachments/assets/baff4a17-02c3-4189-ac5a-5151486db9b9

### Crash Report

https://mclo.gs/n0ycGtX

### What happened wrong?

Pressing any key on the keyboard after using controller input for a bit causes a JRE crash

**Comment by Wilyicaro** [comment]
This isn't directly related to the controller input itself, but it's related to the used Java installation on ur system
These occurrences started from 1.7.3 (this has never happened to me, even though I forced the probable reasons), the real reason isn't known, but they can be fixed if you use a different Java installation.

**Comment by Cjnator38** [comment]
> This isn't directly related to the keyboard input itself, but it's related to the used Java installation on ur system These occurrences started from 1.7.3 (this has never happened to me, even though I forced the probable reasons), the real reason isn't known, but they can be fixed if you use a different Java installation.

For me, it doesn't seem like an issue with the Java install, but rather an issue with a mod used in both Re-Console and Legacy Remade. I've had these crashes with all the versions of Java 21 I have on my system (Eclipse Adoptium, GraalVM, and the runtime provided by the official Minecraft Launcher), and on a bare Legacy4J instance, crashes are a lot less frequent.
