### ISSUE TITLE
[Bug/Glitch] Mod Incompatibility with Tectonic (Stuck on infinite loading screen)

### ISSUE THREAD

**Issue by Cooluy592** [Wilyicaro/Legacy-Minecraft#623]
### Legacy4J Version

1.20.1

### Mod Loader Version

Fabric 0.92.2 + 1.20.1

### Bug/Glitch Occurrence Context

You are able to create the world but once you rejoin it you can't rejoin it. I belive it have something with the experimental features pop-up but I may be wrong.

### What happened wrong?

Wasn't able to load into a minecraft world with tectonic when rejoining after creation

**Comment by Wilyicaro** [comment]
#599
