### ISSUE TITLE
[Bug/Glitch] Game crashes when making a Template

### ISSUE THREAD

**Issue by RedRain0o0** [Wilyicaro/Legacy-Minecraft#624]
### Legacy4J Version

1.21.1 - 1.7.4

### Mod Loader Version

Fabric Loader  - 0.16.7

### Bug/Glitch Occurrence Context

I'm trying to set up a World Template for Festive and it keeps crashing whenever I attempt to load it

### Crash Report

https://mclo.gs/xWYvRvo

### What happened wrong?

Whenever I attempt to load the world as a folder from `.minecraft/saves` it will load just fine, but attempting to load the exact same world from an `.mcsave` will just crash the game citing "no `level.dat` in `current-world/Festive`"
The `.mcsave` can be found [here](https://github.com/RedRain0o0/LCE-Resources/blob/festive/festive.mcsave)

**Comment by Wilyicaro** [comment]
The `.zip` file being used is certainly invalid as there is no file in the world to be read, it's certainly a `.rar` file (which isn't supported), and since winrar supports opening this type of file even renamed to `.zip` it's easy to confuse
