### ISSUE TITLE
[Bug/Glitch] FOV is not present in the latest beta

### ISSUE THREAD

**Issue by Tarfist** [Wilyicaro/Legacy-Minecraft#625]
### Legacy4J Version

Beta 1.21-1.7.5.2444.1

### Mod Loader Version

Fabric 0.16.7

### Bug/Glitch Occurrence Context

FOV is not present in any of the menus like in the previous version, aka 1.20.2-1.7.4 [Stable].

I know that this update has come in two parts [Starting from Oct 31, to Nov 1], And i do get how this could've been a mistake, like forgot to put back FOV option after improving the whole settings section.

### What happened wrong?

FOV option [aka] slider is now present in any of the settings menu.

**Comment by Wilyicaro** [comment]
Open the `Graphics` section and press `Show Advanced Options`
