### ISSUE TITLE
[Crash] Server Environment not supported

### ISSUE THREAD

**Issue by Cixon** [Wilyicaro/Legacy-Minecraft#626]
### Legacy4J Version

Legacy4J-1.21-1.7.5.2444.3 | commit 3f3bda4c0096338fe7852909cec476abf84219a9

### Mod Loader Version

NeoForge - 1.21.1 | 21.1.73

### Bug/Glitch Occurrence Context

# Unable to launch a NeoForge server.

Install NeoForge server environment:
https://projects.neoforged.net/neoforged/neoforge

![2024-11-02 22_15_48-Greenshot](https://github.com/user-attachments/assets/9ee3a5c1-e14b-4efa-9369-7eef9040b1bc)

Install NeoForge Legacy 4J [1.21-1.7.5.2444.3](https://modrinth.com/mod/legacy4j/version/1.21-1.7.5.2444.3+neoforge)

### Crash Report

N/A - not provided.

# What happened wrong?

Server won't launch. 

## Latest.log:
[latest.log](https://github.com/user-attachments/files/17609096/latest.log)

**Comment by Cixon** [comment]
## Additional context from Console:

https://gist.github.com/Cixon/d120819b1adeb18b4cd82fbedc006726

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5.2444.4, thanks for reporting.
