### ISSUE TITLE
[Bug/Glitch] Contents of a container item(in this case, Sophisticated Backpacks' normal to copper backpack) are not carried over when upgrading via legacy crafting

### ISSUE THREAD

**Issue by AdrianneAlojado** [Wilyicaro/Legacy-Minecraft#627]
### Legacy4J Version

1.21-1.7.5.2444.3 (mightve been a problem for older versions?)

### Mod Loader Version

Neoforge 21.1.72

### Bug/Glitch Occurrence Context

When using a resource pack that allows for crafting recipes of a modded item, there is a now a way to upgrade your item to another tier, however when it comes to items that allow you store other items, there is a problem.

### What happened wrong?

The contents of an upgraded container item like a normal backpack to a copper backpack does not carry over.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5.2444.4, thanks for reporting.
