### ISSUE TITLE
<Suggestion> Add thicker Legacy fog

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#63]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/f91b7450-8fcb-4c52-ac87-ea9cc4135627)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/ede16a05-8a40-4536-a995-9a5c6ccb4544)

Screenshots are from Wii U Edition.

Legacy fog is similar to beta fog in its intensity with distance. I was able to approximate this look in Console Aspects by starting Overworld fog at 40% of render distance and ending it at 90% (meaning the chunks between 90 and 100 were fully shrouded in fog). End fog is even more intense, starting at the player (0% of render distance) and ending at 80%.

**Comment by Quartzmaven** [comment]
There's a problem with the End fog with Sodium installed. It's a gray fog now, it's bad... Not a related Legacy4J issue.
![2024-01-25_18 25 14](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81502335/38bfd8f1-b9b7-4f09-a690-f30ae261493a)

**Comment by Wilyicaro** [comment]
Finally added in version 1.5, thanks for reporting
