### ISSUE TITLE
[Bug/Glitch] Map grid bugged out on worlds created before L4J 1.7.3

### ISSUE THREAD

**Issue by NYCWalIcrawler** [Wilyicaro/Legacy-Minecraft#630]
### Legacy4J Version

1.7.3

### Mod Loader Version

Fabric Loader 0.16 (Legacy Remade)

### Bug/Glitch Occurrence Context

Basically the issue is that on my older world created far before the LCE map grid change introduced in 1.7.3 (where 0,0 is centered rather than a corner) any maps i generate will generate in a different area (i.e. if i'm in the bottom left corner of where a map should be, a map will be created to the left of where it should be)

The issue isnt present in any other saves, not even a duplicate copy of my world seed made after the update. If I could atleast get help with maybe fixing my world's maps it'd be appreciated

### What happened wrong?

The maps generated at 3/4 size (LCE map size) only generate the actual area your in if your in a specific part of the map on older saves / saves made outside of l4j

**Comment by Wilyicaro** [comment]
I can't do anything, this change is only valid for new/unlocked maps

**Comment by NYCWalIcrawler** [comment]
After some testing i'm pretty sure the issue is that the smaller default map sizes (i.e. the ones crafted in survival) for some reason snap to the grid in a weird way. Maybe there could be a way to get the lce grid maps in survival crafting?
