### ISSUE TITLE
[Bug/Glitch] 

### ISSUE THREAD

**Issue by AdrianneAlojado** [Wilyicaro/Legacy-Minecraft#631]
### Legacy4J Version

1.21-1.7.5.2444.8

### Mod Loader Version

Neoforge 21.1.72

### Bug/Glitch Occurrence Context

On the 1.21 bleeding edge version of Aether from CircleCI, you can have gloves (whether if its in the Aether's menu or the Accessories menu and it would be visible, however with Legacy4J's new swimming animation in the first person...

### What happened wrong?

Glove stays in the same position, but the arm is still swimming.

**Comment by Wilyicaro** [comment]
This isn't a L4J problem, the swimming animation is practically a disabled vanilla feature
