### ISSUE TITLE
[Bug/Glitch]After dying in hardcore, it allows you to exit without saving.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#632]
### Legacy4J Version

1.20.1 - 1.21

### Bug/Glitch Occurrence Context

https://github.com/user-attachments/assets/cce22156-a387-41d3-a41f-91204508476d

### What happened wrong?

I feel like this actually worked in the previous versions of exiting without having an option of not saving after dying in hardcore.

**Comment by Wilyicaro** [comment]
It was never a thing in L4J, but it'll be considered
