### ISSUE TITLE
[Suggestion] overstacked items show as "##+"

### ISSUE THREAD

**Issue by nenamoree9** [Wilyicaro/Legacy-Minecraft#634]
In TU14, overstacked items were changed to display as "##+". For example, if an item is stacked over 99, it shows as "99+". If an item is stacked over 64, it shows as "64+". Also make overstacked items obtainable via /give.

Command syntax:

/give nenamoree9 oak_planks[minecraft:max_stack_size=99] 100
![screenshot5](https://github.com/user-attachments/assets/5a2da7aa-97e1-463c-ab33-fabeac83bc19)

Image is from CoolguyJommy's video

**Comment by Wilyicaro** [comment]
Added in 1.7.5, thanks for suggesting.
