### ISSUE TITLE
Items in bundles are rendered offset in the item tooltip

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#636]
![2024-11-15_20 25 04](https://github.com/user-attachments/assets/be36d7bb-f381-49e9-903d-da46bd3d172b)
![2024-11-15_20 25 07](https://github.com/user-attachments/assets/0093e24a-3511-4faf-8a4c-e2cfafce82ff)
![2024-11-15_20 25 11](https://github.com/user-attachments/assets/6a4c8b66-3c9d-417a-9773-515f6ec11b52)

**Comment by Wilyicaro** [comment]
Which version are you using?

**Comment by Wilyicaro** [comment]
Make sure to always test with the latest beta.

**Comment by bugsbugsbugsLCE** [comment]
I am using 1.7.5.2444.0.

**Comment by bugsbugsbugsLCE** [comment]
Hmm, this doesn't occur in 1.7.5.2444.9. You can close this then.

**Comment by Wilyicaro** [comment]
A lot changed since .0
