### ISSUE TITLE
[Bug/Glitch] Polytone no longer works with L4J

### ISSUE THREAD

**Issue by FR00TP3NCH** [Wilyicaro/Legacy-Minecraft#637]
### Legacy4J Version

1.21-1.7.5.2444.9+fabric

### Mod Loader Version

Fabric Loader 0.16.9

### Bug/Glitch Occurrence Context

Legacy4J Crashes when I use Polytone on its latest version.

### Crash Report

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'legacy' at 'wily.legacy.fabric.Legacy4JFabricClient'! at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) at knot//net.minecraft.class_310.<init>(class_310.java:477) at knot//net.minecraft.client.main.Main.main(Main.java:239) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4895 failed at knot//net.minecraft.class_3929.<clinit>(class_3929.java:100) at knot//wily.legacy.Legacy4JClient.registerScreen(Legacy4JClient.java:406) at knot//wily.legacy.fabric.Legacy4JFabricClient.onInitializeClient(Legacy4JFabricClient.java:54) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ... 6 more Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4895 failed at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ... 10 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ... 14 more Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [polytone-common.mixins.json:SmithingScreenMixin from mod polytone] from phase [DEFAULT] in config [polytone-common.mixins.json] FAILED during APPLY at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ... 17 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_4895::modifyRenderEntityX with priority 1000 cannot inject into net/minecraft/class_4895::method_2389(Lnet/minecraft/class_332;FII)V merged by wily.legacy.mixin.SmithingScreenMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> polytone-common.mixins.json:SmithingScreenMixin from mod polytone -> Prepare Injections -> modify$din000$polytone$modifyRenderEntityX(F)F -> Prepare -> -> { target: method_2389(Lnet/minecraft/class_332;FII)V }] at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312) at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ... 17 more

### What happened wrong?

I honestly have no idea.

**Comment by Wilyicaro** [comment]
Not only in the beta version, this is a problem of a polystone update

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5, thanks for reporting.
