### ISSUE TITLE
[Bug/Glitch] Crashes the game when clicking play button with world host mod.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#638]
### Legacy4J Version

1.21-1.7.5.2444.9

### Mod Loader Version

Fabric, and NeoForge

### Bug/Glitch Occurrence Context

Crashes the game when clicking play button with world host mod.

### Crash Report

https://mclo.gs/Yddb3rw https://mclo.gs/AtCXUYi

### What happened wrong?

Basically, whenever you click play button it crashes the game.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5, thanks for reporting.
