### ISSUE TITLE
[Bug/Glitch] Creating a new world on 1.7.4 causes a java.nio.file.DirectoryNotEmptyException error causing infinite loading

### ISSUE THREAD

**Issue by samiscool51** [Wilyicaro/Legacy-Minecraft#639]
### Legacy4J Version

1.20.4-1.7.4

### Mod Loader Version

Forge 49.1.0

### Bug/Glitch Occurrence Context

When creating a new world, the game fails to create the world due to java.nio.file.DirectoryNotEmptyException
however, there is no world called "New World" within my saves folder.
i created a brand new instance so there shouldn't be any existing saves.
checking the save folder shows no folder named "New World" and creating a folder called "New World" then deleting it does not solve the problem.
i also tried naming the world something different (in this case "New Worldx") to only receive the same result.
i am running on a supported java version: Java 17.0.8
I am running on Windows 10 LTSC (build 1809) and i cannot confirm if the bug exists on other platforms but judging by no other reports, it may be a issue unique Windows 10 LTSC. (or a general windows 10 issue)
Creating a world without the mod works as intended.
Loading an existing world with the mod works as intended.

### Crash Report

https://mclo.gs/FF61Mmp

### What happened wrong?

Went to create world.
Infinite loading screen when creating the world, log says an error as occurred.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5, thanks for reporting.
