### ISSUE TITLE
<Contribution> Add Pink End Crystal Beams from Legacy

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#64]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/62aafea9-c1f5-42e1-ac61-9cdadc9fe5f7)

Extracted Texture:

![end_crystal_beam](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/d7591413-e06f-47c2-a5b2-11dd20641ff7)

Here is the texture for textures/entity/end_crystal. However, End Crystal beams do not support semitransparent pixels by default on Java, so you may have to change it to allow those pixels like the Slime.

**Comment by Wilyicaro** [comment]
Added in version 1.3.3.
