### ISSUE TITLE
[Bug/Glitch] The game crashes when conflicted with OptiFine

### ISSUE THREAD

**Issue by hinienbaomao** [Wilyicaro/Legacy-Minecraft#643]
### Legacy4J Version

1.21-1.7.4

### Mod Loader Version

Forge 52.0.28

### Bug/Glitch Occurrence Context

Whenever i use Legacy4J with Optifine on 1.21.1, the game always crashes.
I tried installing SDL2 and it doesnt do anything either
![image](https://github.com/user-attachments/assets/9ee1bdd0-494f-4157-bf96-8dba98717e2a)

### Crash Report

https://mclo.gs/UBM2liv

### What happened wrong?

MC just crashes whenever i use Legacy4J with OptiFine

**Comment by Wilyicaro** [comment]
#629
