### ISSUE TITLE
[Bug/Glitch] Legacy4J and L_ender's Cataclysm major incompatibility 

### ISSUE THREAD

**Issue by mynayas** [Wilyicaro/Legacy-Minecraft#645]
### Legacy4J Version

1.20.1-1.7.4

### Mod Loader Version

Forge - 47.3.12 (should happen to any version supporting the current legacy4j and L_ender's Cataclysm versions)

### Bug/Glitch Occurrence Context

i was testing how bosses from L_ender's Cataclysm played with reconsole, and when i was fighting ignis, he used an inescapable attack that crashed the game the second he released me. which seems to be caused from legacy4j.

https://github.com/user-attachments/assets/4b0fdee0-d741-4a9a-b9c7-7aa25dfcd48f

![image](https://github.com/user-attachments/assets/37c57f73-b206-4500-9a77-012cecd5141a)

### Crash Report

https://pastebin.com/W7NR8UbU

### What happened wrong?

The Game Crashes when any boss from "L_ender's Cataclysm" hits a player with an inescapable attack, and then get's freed. you only need to download legacy4j and L_ender's Cataclysm, fight any boss with an inescapable attack in survival, in this example it's ignis, and get him to do the stab attack and hang you up. when he releases you, the game instantly crashes. (this is probably due to the release animation being unable to load. but i can't confirm.)

**Comment by Wilyicaro** [comment]
This isn't related _to the release animation being unable to load_, this is a ncompatibility with the vehicle camera movement, it's simply to fix

**Comment by Wilyicaro** [comment]
Fixed in 1.7.5, thanks for reporting.
