### ISSUE TITLE
[Bug/Glitch] Can't take book from a Lectern

### ISSUE THREAD

**Issue by SnowyBoi64** [Wilyicaro/Legacy-Minecraft#648]
### Legacy4J Version

Legacy4J-1.21-1.7.5.2444.9

### Mod Loader Version

Fabric Loader 0.16.9

### Bug/Glitch Occurrence Context

Vanilla
![image](https://github.com/user-attachments/assets/45f3f676-79d3-4ec0-b23f-9576b476a536)

Legacy4J
![image](https://github.com/user-attachments/assets/0b773035-3f24-4f4c-8e8f-2be776e22647)

### What happened wrong?

I'm not sure how it was on PS4 Edition, but in Legacy4J there is a lack of a 'Take Book' option for the lectern. This makes it so you can only get the book back by breaking the lectern.
If this is intentional and how it was in PS4 Edition, it would be nice to gain the ability to take books off lecterns.

**Comment by Wilyicaro** [comment]
This isn't present in PS4 Edition, so it's not a bug, but I won't remove a feature from vanilla, so this will be added.

**Comment by Wilyicaro** [comment]
Added in 1.7.5-rc5
