### ISSUE TITLE
[Bug/Glitch] Missing Smithing Table Sprites

### ISSUE THREAD

**Issue by BrandonItaly** [Wilyicaro/Legacy-Minecraft#649]
### Legacy4J Version

1.21.4-1.7.5-rc5

### Bug/Glitch Occurrence Context

The sprites in the Smithing Table are missing. I presume this is because the location of the sprites moved in 1.21.4

### What happened wrong?

![image](https://github.com/user-attachments/assets/19240b0f-efb8-401f-ad0d-6ca70ca87971)

**Comment by Wilyicaro** [comment]
Thanks for reporting, you're correct, it was related to the slot sprites being finally moved from the block/item atlas to gui atlas.
This will be fixed in 1.21.4-1.7.5-rc6
