### ISSUE TITLE
<Contribution> UI Sounds, Horse Ambient Sound, Skeleton Sounds, Levelup Sound, Cat Music Disc Easter Egg

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#65]
[assets.zip](https://github.com/Wilyicaro/Legacy-Minecraft/files/14054474/assets.zip)

Here are sound assets to include in the base pack. These are exclusive to Legacy.

Full List:

- All ui sounds from Legacy with their original names hooked up as
  - ui.press (clicking a button)
  - ui.focus (moving tabs/selection)
  - ui.back (leaving a menu)
  - ui.scroll (NOT IN MOD YET, for scrolling in the Creative menu)
  - ui.craft (NOT IN MOD YET, for crafting an item successfully)
  - ui.craft_fail (NOT IN MOD YET, for trying to craft an item you don't have the materials for)
- Horse ambient sound "idle4" (a whinny)
- Cat music disc plays Dog at the end
- Fancier level-up sound
- Old skeleton sounds (never updated; intentional)

**Comment by Quartzmaven** [comment]
You're missing something the other 2:
- Air Punching sound
- Fall damage sound

Also note, the press, focus, and back sounds are kinda quiet.

**Comment by AgentMindStorm** [comment]
About your reply

1.) This cannot be added with just a resource pack. It also uses the existing attack.nodamage sound so a resource pack can't do much..
2.) Fall damage sounds on Legacy were updated to match Java and Bedrock before it was discontinued. I have the extracted Wii U Edition files to compare to.
3.) These UI sounds were extracted directly from Legacy in WAV format and converted to OGG. VLC and other media players don't play them very well for some reason, but they sound normal in-game.

**Comment by Quartzmaven** [comment]
I know both of them can't be added in a resource pack, but it should be inside the mod.

**Comment by AgentMindStorm** [comment]
Yes, but that should be a separate report then. This contribution is specifically a list of resource pack assets to add to the base resource pack.

**Comment by Wilyicaro** [comment]
Thanks for the assets, they were added in version 1.3.3, some sounds will be used in the future. (Crafting Interface)
