### ISSUE TITLE
[Bug/Glitch]Villager GUI

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#650]
### Legacy4J Version

1.21.4

### Mod Loader Version

Fabric

### Bug/Glitch Occurrence Context

So it seems like whenever you do a trade with a villager, the GUI bugs out.

### What happened wrong?

So it seems like whenever you do a trade with villager, it bugs out
![2024-12-28_13 13 38](https://github.com/user-attachments/assets/b768102e-1991-4f59-a74f-d47fba97c5eb)

**Comment by Wilyicaro** [comment]
Well, we discussed this on Discord so I'll close this issue

**Comment by Titzi2904** [comment]
I am having the same issue and don't know how to resolve it...

**Comment by Cjnator38** [comment]
> I am having the same issue and don't know how to resolve it...

This bug should be resolved in the next version of Legacy4J
