### ISSUE TITLE
[Bug/Glitch] Vehicle Camera Rotation doesn't work on 1.21.3/1.21.4

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#651]
### Legacy4J Version

1.21.3-1.7.7, 1.21.4-1.7.7

### Mod Loader Version

Fabric Loader 0.16.9

### Bug/Glitch Occurrence Context

Vehicle Camera Rotation no longer works on 1.21.3 or 1.21.4, possibly due to changes made for the "Minecart Improvements" experiment

### What happened wrong?

Camera does not rotate when "Vehicle Camera Rotation" is enabled on 1.21.3 and 1.21.4

**Comment by Wilyicaro** [comment]
It's working, but not on minecarts, as vanilla added this to the game

**Comment by Wilyicaro** [comment]
The vanilla option was added below the L4J option lol

**Comment by Cjnator38** [comment]
That option only works in worlds with the "Minecart Improvements" datapack enabled, unfortunately

**Comment by Cjnator38** [comment]
i wonder if the issues channel still works :sob:

**Comment by lunakittyyy** [comment]
Hi chat

**Comment by t3rav0lt** [comment]
BRING BACK LEGACY REBORN!!!!!!11111

 /s

**Comment by JuniperIsSleepy** [comment]
the vc is pretty funny

**Comment by Cjnator38** [comment]
i didn't make it in time :(

**Comment by t3rav0lt** [comment]
womp womp

**Comment by t3rav0lt** [comment]
1.8.9 port when

**Comment by lunakittyyy** [comment]
beta 1.6 port when

**Comment by WonkaCCS** [comment]
You guys suck. I hate how you say you're going on a hiatus as a way to make us not think you're abandoning us when you really are. You should be ashamed of this.

**Comment by t3rav0lt** [comment]
Bugrock port when

**Comment by omo50** [comment]
re-console will still receive updates for those wondering

**Comment by Cjnator38** [comment]
> Bugrock port when

didn't that already happen

**Comment by lunakittyyy** [comment]
> You guys suck. I hate how you say you're going on a hiatus as a way to make us not think you're abandoning us when you really are. You should be ashamed of this.

i dont think its quite that far but I am worried this hiatus will be very long
the license changing isnt that great either but you can just fork from before the change occured

**Comment by t3rav0lt** [comment]
> > Bugrock port when
> 
> didn't that already happen

Best we've got is this
https://www.mcbedrock.com/community/16x16/vanilla-deluxe-project-4jd-ui/#post-30269

**Comment by WonkaCCS** [comment]
The fact I got muted just now just for speaking out about your shady doings is disgusting.

**Comment by t3rav0lt** [comment]
> re-console will still receive updates for those wondering

[https://media.tenor.com/tGsUGE2tMdMAAAAM/yippee.gif](url)

**Comment by ParkerTCK** [comment]
i had to reset my password to talk here
is this our new general

**Comment by lunakittyyy** [comment]
idk

**Comment by Cjnator38** [comment]
l4j 1.8.9 when

**Comment by WonkaCCS** [comment]
GUYS ANYONE WHO BOOSTED THE SERVER, REMOVE YOUR BOOSTS THEY DON'T DESERVE IT.

**Comment by JuniperIsSleepy** [comment]
source: crack pipe

> GUYS ANYONE WHO BOOSTED THE SERVER, REMOVE YOUR BOOSTS THEY DON'T DESERVE IT.

**Comment by t3rav0lt** [comment]
L4J 1.6.4 prot???111?

**Comment by ParkerTCK** [comment]
l4j 1.2.4 port when

**Comment by WonkaCCS** [comment]
They literally don't deserve it. They aren't being clear, they're saying they're leaving it on a hiatus when they're just abandoning and telling us that so that we don't get mad.

**Comment by Cjnator38** [comment]
je port for lce when

**Comment by DexrnZacAttack** [comment]
l4j 1.2.4.1 port???? Terraria confirmed????

**Comment by lunakittyyy** [comment]
**Wilyicaro** locked as **too heated** and limited conversation to collaborators

**Comment by Cjnator38** [comment]
there goes the webhook

**Comment by ParkerTCK** [comment]
whar

**Comment by omo50** [comment]
when will legacy4j be coming to the wii u

**Comment by Cjnator38** [comment]
tomorrow!!!

**Comment by WonkaCCS** [comment]
This is lame, they couldn't even leave us somewhere to chat on discord.

**Comment by ParkerTCK** [comment]
the issues channel is lagging behind so far

**Comment by WonkaCCS** [comment]
Ikr

**Comment by omo50** [comment]
> tomorrow!!!

winner!

**Comment by ParkerTCK** [comment]
yea they shouldve left us a singular channel
when is someone making a fan server fr

**Comment by Cjnator38** [comment]
i think wily disabled the webhook now that we're using this github issue as a fallback :sob:

**Comment by WonkaCCS** [comment]
https://discord.gg/Jmz8kR8t

**Comment by ParkerTCK** [comment]
NOOO

**Comment by Cjnator38** [comment]
l4j server is no more

**Comment by ParkerTCK** [comment]
was i the last one to get a message on there or is my discord broken

**Comment by lunakittyyy** [comment]
i got the last one in wordle :3

**Comment by WonkaCCS** [comment]
i think so

**Comment by DexrnZacAttack** [comment]
so who enjoyed the terraria "gameplay" that I was streaming in VC?

**Comment by WonkaCCS** [comment]
https://discord.gg/Jmz8kR8t guys let's chat here this is too slow

**Comment by ParkerTCK** [comment]
yea what they said

**Comment by WonkaCCS** [comment]
The person who boosted the server is absolutely braindead

**Comment by omo50** [comment]
https://discord.gg/kqCS2e6x heres the re-console server invite for those who care

**Comment by WonkaCCS** [comment]
MAKE LEGACY4J GREAT AGAIN!!!

**Comment by Wilyicaro** [comment]
> You guys suck. I hate how you say you're going on a hiatus as a way to make us not think you're abandoning us when you really are. You should be ashamed of this.
We have our own lives, which from the moment they started to be really affected by the development of the mod we started to think about this pause (we don't use the term hiatus anywhere), this decision wasn't easy for anyone, we had to make it at the last minute.
This mod was made with love, from fan to fan, it's a dream that I always wanted and I achieved, I can't have any kind of regret for having done this and still have this whole community, making sure that any kind of hate towards us doesn't affect us.

**Comment by WonkaCCS** [comment]
MAKE LEGACY 4J GREAT AGAIN!!!

**Comment by ParkerTCK** [comment]
it would be really funny if you left one voice channel open in the server
