### ISSUE TITLE
Hand rotates by 180° when sneaking while gliding and holding an item instead of when not holding an item

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#652]
If you sneak while gliding with an eltra, it's supposed to rotate your arm by 180° degree when not holding an item in the mainhand but in the latest version it is the other around. It only rotates by 180° when holding an item
https://github.com/user-attachments/assets/4cd2fa7a-bff7-4a94-9694-caa9d0815083

**Comment by Wilyicaro** [comment]
Fixed in 1.7.9, thanks for reporting.
