### ISSUE TITLE
[Bug/Glitch] Furnace Arrow Texture Broken While Cooking

### ISSUE THREAD

**Issue by CubeCube65** [Wilyicaro/Legacy-Minecraft#653]
### Legacy4J Version

1.20.1 1.7.9

### Mod Loader Version

Forge 47.3.22

### Bug/Glitch Occurrence Context

The Arrow for when the Furnace is cooking is not working properly
![Texture Bug](https://github.com/user-attachments/assets/52ce3c37-5aca-4507-8468-60e4ffa6223c)

### What happened wrong?

Their might be a problem happening with the textures or something.

**Comment by Wilyicaro** [comment]
Fixed in 1.7.10, thanks for reporting
