### ISSUE TITLE
do you guys do trick or treating

### ISSUE THREAD

**Issue by cackle4524** [Wilyicaro/Legacy-Minecraft#654]
### Legacy4J Version

trick or treating

### Mod Loader Version

trick or treating

### Bug/Glitch Occurrence Context

do you guys do trick or treating

### Crash Report

trick or treating

### What happened wrong?

trick or treating

**Comment by cackle4524** [comment]
do you guys do trick or treating

**Comment by Wilyicaro** [comment]
maybe
