### ISSUE TITLE
<Suggestion> Retake world icon every time the world is exited with "Exit and Save"

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#66]
The Legacy world icon changed every time you exited and saved your world. Java only takes the icon once and saves it forever. Is it possible to change that behavior?

**Comment by Wilyicaro** [comment]
It's possible, probably in the next version I'll add this feature

**Comment by Wilyicaro** [comment]
Added in 1.4.1 version, thanks for suggesting!
