### ISSUE TITLE
Picking up an item that goes into the extended inventory (not the hotbar) in Creative adds item to Creative menu

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#67]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/8c02db13-0eb9-4a97-90a0-6f1acb364d14)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/6acf91bc-bc14-41cb-9ba5-c923cbc4db78)

Picking up an item in Creative Mode that does not enter the hotbar has a chance to put it into the Creative inventory next time it is opened. As seen in the above screenshots, picking up a Bamboo Door and a Dripstone Block with a full hotbar changed two items in the Creative inventory to those two.

**Comment by Wilyicaro** [comment]
Thanks for reporting, fixed in 1.3.3 version
