### ISSUE TITLE
Atempting to save with the c2me mod causes crash (fabric 1.20.4)

### ISSUE THREAD

**Issue by asweqr** [Wilyicaro/Legacy-Minecraft#68]
simply putting c2me and leagcy4j and its dependencys together and attempting to save causes the game to crash

mods used

c2me-fabric-mc1.20.4-0.2.0+alpha.11.40
Minecraft-Legacy-1.20.4-1.3.2-fabric
fabric-api-0.95.1+1.20.4
architectury-11.0.11-fabric

c2me link
https://modrinth.com/mod/c2me-fabric

logs
[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/14061507/latest.log)

[crash-2024-01-26_20.22.24-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14061510/crash-2024-01-26_20.22.24-client.txt)

**Comment by Wilyicaro** [comment]
Unfortunately, this incompatibility is necessary, mainly for modifications to the loading screen.
