### ISSUE TITLE
"Force-close-loading-screen" mod causes crash on startup with legacy4j (Fabric 1.20.4)

### ISSUE THREAD

**Issue by asweqr** [Wilyicaro/Legacy-Minecraft#69]
simply putting Force-close-loading-screen and legacy4j with its dependencys and booting minecraft up will cause a crash

mods used

Minecraft-Legacy-1.20.4-1.3.2-fabric
fabric-api-0.95.1+1.20.4
architectury-11.0.11-fabric
forcecloseloadingscreen-2.2.0

Force-close-loading-screen link

https://modrinth.com/mod/forcecloseworldloadingscreen

logs

[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/14061658/latest.log)

crash log failed to generate

**Comment by Wilyicaro** [comment]
Unfortunately, this incompatibility is necessary, mainly for modifications to the loading screen.
