### ISSUE TITLE
hud gets smaller with do a barrel roll mod 

### ISSUE THREAD

**Issue by BestChoripans** [Wilyicaro/Legacy-Minecraft#70]
i was trying to use the mod do a barrel roll once playing i noticed that the hud is smaller and stays in the upper left corner this happens in the 1.20.2 and 1.20.4 versions of fabric

![2024-01-26_13 36 59](https://github.com/Wilyicaro/Legacy-Minecraft/assets/134541919/bbb90168-6d58-4d69-9593-b7f1fee5ba0a)

mods folder:
![imagen](https://github.com/Wilyicaro/Legacy-Minecraft/assets/134541919/d83c914d-64ea-445d-b976-e2488d61816d)

**Comment by Quartzmaven** [comment]
Same thing goes for "Cool Elytra", cus it's a fork of Do A Barrel Roll.

**Comment by Wilyicaro** [comment]
Fixed in 1.3.3 version
