### ISSUE TITLE
hints being rendered on screen cause massive frame drops on low end machines (Fabric 1.20.4)

### ISSUE THREAD

**Issue by asweqr** [Wilyicaro/Legacy-Minecraft#71]
on low end machines when a hint is being rendered it can cause massive frame drops for me i went from 45 fps to an average of 15 fps when a hint is being rendered as soon as the hint goes away i go back up to 45 fps

mods used

fabric-api-0.95.1+1.20.4
architectury-11.0.11-fabric
Minecraft-Legacy-1.20.4-1.3.2-fabric

**Comment by Wilyicaro** [comment]
Unfortunately due to JE's unoptimized transparency and high tiles usage for better fidelity with LE there will be performance issues, the tips/hints are nothing special for this massive frame drop, and probably JE's toast system animations and constant checks may play some part in this.
