### ISSUE TITLE
Elytra sneaking pose arm position inaccurate

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#72]
Screenshot from Legacy4J:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/ad5ce933-fe09-41ca-835d-079ae0d6614b)

Screenshot from Wii U Edition:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/40ef55e0-2134-428c-9aae-d0b7332b0dd5)

The arm should go a full 180 degrees when sneaking while gliding. Additionally, the arm should return to its normal position if the player holds an item. The pose on Legacy only occurs while holding nothing.

**Comment by Wilyicaro** [comment]
Fixed in 1.3.3 version
