### ISSUE TITLE
<Suggestion> More frequent music

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#73]
Music on Legacy Console Edition played more frequently than Java. On Legacy, there were only 20-60 seconds (400-1200 ticks) between the end of one song and the start of another. This delay should apply to all dimensions, survival, and creative. The main menu music plays constantly like Java Edition.

**Comment by Wilyicaro** [comment]
Thanks for suggesting, added in 1.3.3 version.
