### ISSUE TITLE
<Suggestion> Hold jump to go up while flying with the elytra in Creative

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#74]
On Legacy, holding the jump button while flying with the elytra in Creative moved the player upward at the same speed as typical Creative flight. *Do not match the way Bedrock does it with momentum.* The elytra gains no vertical momentum on Legacy; the player moves up at a constant rate.

**Comment by Wilyicaro** [comment]
Added in 1.3.3 version
