### ISSUE TITLE
Item sizes in slots do not match Console Edition

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#75]
Legacy4J already has this partially implemented, but it is not fully accurate. 2D items in slots on Legacy generally do not fill the entire slot space. In this mod, item size in slot is currently is separated by Creative tab. In Legacy, there is a short list of items that fill the whole slot. The rest don't:

List of "Large Items"

- All Swords
- All Pickaxes
- All Shovels
- All Axes
- All Hoes
- Bow
- Crossbow
- Fishing Rod
- Carrot on a Stick (and Warped Fungus on a Stick)

Screenshot from Legacy4J:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/8dae74e3-bd6b-4c70-80eb-e5b11c4785d9)

Screenshot from Wii U Edition:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/4e695b8e-5f7a-47c5-8ab6-41c8c0080ad4)

Addendum: I don't want to overwhelm you with bug reports and suggestions. Please tell me if I'm spamming too much. I am not expecting that you fix all these immediately or prioritize them any more than your original plans. These are just extra things I noticed that you could work on someday if you want to. This mod is AMAZING and I'm very excited to see it in the future!

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, I think it was fixed in 1.3.3 version, the "hardcoded" item size changes have been removed, now only the models were modified
