### ISSUE TITLE
Disable "Legacy4J Water Resources" by default.

### ISSUE THREAD

**Issue by Quartzmaven** [Wilyicaro/Legacy-Minecraft#78]
Even though it says it will automatically disable when Sodium/Rubenium is installed. But when I export the modpack to Modrinth's mrpack format then import over PrismLauncher, it forces the resource pack to enable by default thinking that Sodium isn't installed. The resource pack is known for causing the water to look opaque and have messy biome blending due to Sodium. Here are the steps:

**Steps reproduced:**
1. Open Prism Launcher
2. Play modpack (contains only the mod and it's dependencies)
3. Go to Help & Options -> Settings -> Graphics -> Resource Pack
4. Disable "Legacy4J Water Resources"
5. Exit the game.
6. Export modpack as Modrinth format (only the mod and it's dependencies checked)
7. Import the modpack that was exported
8. Play the exported modpack
9. Go to Help & Options -> Settings -> Graphics -> Resource Pack
10. As you can see the "Legacy4J Water Resources" is still enabled by default.

If anything here finds you confusing, let me know. Thanks.

Also, another problem, shift-clicking on the Resource Pack text crashes the game.

**Comment by Wilyicaro** [comment]
It's working normally for me, at least in Fabric API 0.95.3, Legacy Waters is auto-removed every time I select it with sodium or rubidium installed.
I can't see this shift-clicking problem, could you elaborate further?

**Comment by Quartzmaven** [comment]
I meant opening the Vanilla Resource Packs screen by shift + left click.

**Comment by Quartzmaven** [comment]
This is the exact problem I had:
https://github.com/Wilyicaro/Legacy-Minecraft/issues/82

**Comment by Quartzmaven** [comment]
I managed to fix in the worst way possible by forcing the resourcepack to be incompatible, that way when I install the modpack, it should be forced to be disabled, so it's good now.

`incompatibleResourcePacks:["legacy:legacy_waters_resourcepacks/legacy_waters"]`
