### ISSUE TITLE
The GUI menus like inventory, interface etc scaling could be bit more better. When playing on 1080p screen at 4 GUI scaling, it's a bit small compared to how it is on Console Edition versions of Minecraft

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#79]
![ConsoleEditionGUI2](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/7fd112bc-e20c-42a1-9c43-7824a41602cb)
![ConsoleEditionGUI](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/614f2c5e-7ced-4d69-ba89-2c5d367b9052)
![ConsoleEditionGUI3](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/4b51e95b-ca26-49f6-be71-775c6ddf588a)
![consoleeditionGUI4](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/09519043-95e9-4b98-8a41-50b02672ed8e)
![2024-02-01_11 14 10](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/7533638e-ac8b-401d-99c3-ea8a3a08d14c)
![2024-02-01_11 45 38](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/d3e83d45-3837-4770-8ce4-9fa00d791053)
![2024-02-01_11 15 01](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/e198cc1d-a2bb-4a07-93a7-0312b40954a9)
![2024-02-01_11 21 20](https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/a4c3fb9f-e187-41e6-a4c8-cee7d8897970)

**Comment by Wilyicaro** [comment]
Unfortunately, to improve this, it's probably necessary to remove GUI Scale option from the game, as the LE doesn't have that option or other way of changing all the screen scale

**Comment by DanielMC101** [comment]
> Unfortunately, to improve this, it's probably necessary to remove GUI Scale option from the game, as the LE doesn't have that option or other way of changing all the screen scale

Oh, so you can't really just manually make the GUI menus bit more bigger besides the HUD?

**Comment by DanielMC101** [comment]
> Unfortunately, to improve this, it's probably necessary to remove GUI Scale option from the game, as the LE doesn't have that option or other way of changing all the screen scale

Also, I remember before the 1.2 update the GUI size when set on auto was perfect size, can you maybe revert it to that while keeping the HUD size separate?

**Comment by Wilyicaro** [comment]
Probably, I can improve the vanilla GUI scaling system to be more accurate when set to AUTO at all resolutions, because when I was playing in 1440p the GUI scale was a lot bigger than in LE, and there was no 1:1 accurate GUI scale setting

**Comment by DanielMC101** [comment]
> Probably, I can improve the vanilla GUI scaling system to be more accurate when set to AUTO at all resolutions, because when I was playing in 1440p (edit: before 1.2) the GUI scale was a lot bigger than in LE, and there was no 1:1 accurate GUI scale setting

Oh yeah and don't forget the paper doll thing, it's also part of GUI I think
