### ISSUE TITLE
Global audio slider is missing

### ISSUE THREAD

**Issue by DBTDerpbox** [Wilyicaro/Legacy-Minecraft#8]
The Sound menu is missing the slider to change the master volume of the game

Mod:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/2be47b74-5340-4fa0-9553-2c003001e685)

Vanilla:

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/65347035/33222c6d-7d1e-4803-9bfb-73786d4d57bd)

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it was fixed in 1.1.2 version
