### ISSUE TITLE
Stopping before finishing eating something removes interpolation on next animation

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#80]
The eating animation in 1.3.3 (very nice, by the way) only interpolates the first time you eat something. If you eat a piece of food part of the way and then stop, the arm will jump into position immediately when you start eating again. It does not smoothly transition every time.

**Comment by DanielMC101** [comment]
yea. eating animation def isn't really accurate

**Comment by Wilyicaro** [comment]
Fixed in version 1.4, thanks for reporting.
