### ISSUE TITLE
<suggestion>  LE widget highlight texture as a seprate resource pack

### ISSUE THREAD

**Issue by contrarybaton60** [Wilyicaro/Legacy-Minecraft#81]
![2024-02-01_18 39 22](https://github.com/Wilyicaro/Legacy-Minecraft/assets/110365948/2035a9cf-0cab-4869-976a-5a3152852b19)
I really like the way you added this feature when using programmer art, but is there's a way to have this as by itself? I prefer using the default textures

**Comment by Wilyicaro** [comment]
Added in version 1.4 in the Console Aspects resource pack, and a "Force Yellow Text" option in User Interface section.

**Comment by contrarybaton60** [comment]
thanks!
