### ISSUE TITLE
Cannot close inventory using inventory keybind

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#83]
In Creative Mode, there is a separate keybind to open the player inventory instead of the Creative inventory. However, you cannot press this separate keybind to close the player inventory. Ideally, you could use both E or I (or the rebound equivalnet) to close any inventory screen.

**Comment by Wilyicaro** [comment]
Fixed in version 1.4, thanks for reporting.
