### ISSUE TITLE
<Contribution> Minor Console Aspects fixes for 1.3.3

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#84]
[Console Aspects.zip](https://github.com/Wilyicaro/Legacy-Minecraft/files/14145845/Console.Aspects.zip)
[Programmer Console Aspects.zip](https://github.com/Wilyicaro/Legacy-Minecraft/files/14145846/Programmer.Console.Aspects.zip)

Made some minor bug fixes to work with Legacy4J 1.3.3 better:

- Changed how water transparency works to be compatible with AND without Sodium (Swamp water is no longer accurate, but this exchange is worth it so the water transparency is normal in all other biomes)
- Fixed kelp and seagrass black pixels during interpolation

**Comment by Wilyicaro** [comment]
Added in version 1.4, thanks again for your contribution!
