### ISSUE TITLE
No way to delete worlds?

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#85]
After creating new worlds, there's no way to delete it in game. Also, this is kinda irrelevant but the horse inventory gui does not work, it just opens player inventory instead.

**Comment by BuddarScotchy** [comment]
There is a way to delete worlds, but admittedly it's a little hidden at the moment. If you click once on the world you want to delete (not on the play button), and then press "E" it brings up a prompt to Rename or Delete the world.

**Comment by Wilyicaro** [comment]
#24

**Comment by Wilyicaro** [comment]
> After creating new worlds, there's no way to delete it in game. Also, this is kinda irrelevant but the horse inventory gui does not work, it just opens player inventory instead.

Use I to open the inventory, E is just to open the creative inventory or the crafting interface(only default inventory for now), it's like Y or triangle button on LE, you can see this key binding in settings.
