### ISSUE TITLE
Incompatibility with Polymer mixins

### ISSUE THREAD

**Issue by NotCitraEmu** [Wilyicaro/Legacy-Minecraft#90]
Opening up the inventory when on the Hypixel server causes the entire game to crash

[crash-2024-02-07_21.01.45-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14204026/crash-2024-02-07_21.01.45-client.txt)

**Comment by S-N00B-1** [comment]
Caused by an incompatibility between polymer and legacy4j

**Comment by Wilyicaro** [comment]
> Caused by an incompatibility between polymer and legacy4j

Exactly, not related to Hypixel server

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
