### ISSUE TITLE
Polytone mod causes crash on startup with legacy4j mod (Fabric 1.20.4)

### ISSUE THREAD

**Issue by asweqr** [Wilyicaro/Legacy-Minecraft#91]
simply putting polytone and legacy4j together with its requirements causes the game to crash on startup

mods used

Minecraft-Legacy-1.20.4-1.3.3-fabric
architectury-11.0.12-fabric
fabric-api-0.96.0+1.20.4
polytone-1.20.4-1.14.6-fabric

Polytone link

https://modrinth.com/mod/polytone

logs

[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/14234290/latest.log)

crash log failed to generate

**Comment by Wilyicaro** [comment]
This is a simple mixin incompatibility issue, unfortunately, probably I can't fix it, as this is a necessary modification of the inventory screen, you should create an issue in polystone github asking to add Legacy4J compatibility.
