### ISSUE TITLE
(SUGGESTION): Add different panoramas?

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#95]
Legacy console minecraft had a plethora of different panoramas of the various tutorial worlds. I have a folder with a bunch of said panoramas in a format that seems to work with your mod, applying them seems to work as well.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/c3a3cdb9-6e62-4953-9e1d-007f3e7d4d32)

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/2d06f773-6d48-4f63-8349-56de95892260)

Perhaps you could integrate the panoramas as a feature, where the player could switch between different panoramas through the settings screen?

**Comment by Wilyicaro** [comment]
I don't think it's worth the effort to make this specific feature, you yourself showed two great examples that can be made with just resource packs
