### ISSUE TITLE
(Maybe a bug?) Trading/Villager Gui lets you place stuff where you probably shouldn't

### ISSUE THREAD

**Issue by SnowyBoi64** [Wilyicaro/Legacy-Minecraft#96]
![Screenshot 2024-02-17 175123](https://github.com/Wilyicaro/Legacy-Minecraft/assets/80140847/2be8aa2e-7e2e-41eb-a590-01835f932a7a)
im not sure if this is intentional because it lets you trade if you put the required items in either slot
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/80140847/d456d2ea-cea6-4575-be67-3f6e9ed54954)

though, if this is a bug, this could possibly be used as an easy way to edit villager trades.
Like instead of using a command generator you could just place and remove items from the villager ui.

**Comment by SnowyBoi64** [comment]
also another small bug i saw was that short grass appears to be missing from the creative gui, likely due to the rename of the item id to be called minecraft:short_grass instead of minecraft:grass

**Comment by Wilyicaro** [comment]
> ![Screenshot 2024-02-17 175123](https://private-user-images.githubusercontent.com/80140847/305675843-2be8aa2e-7e2e-41eb-a590-01835f932a7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjYwOTUsIm5iZiI6MTcwODIyNTc5NSwicGF0aCI6Ii84MDE0MDg0Ny8zMDU2NzU4NDMtMmJlOGFhMmUtN2UyZS00MWViLWE1OTAtMDE4MzVmOTMyYTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzMDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2ZhODJkMDZhZWU1ZGU3MDBmNTI4OTliMGY2NzU3ODVmNzc3OTMwOWI0MzAzMzhjY2ZmMDZhMzFmODcwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6-0zfHWnM7C41nlyLcSUsAghomKroa2GPnpYLPG2W30) im not sure if this is intentional because it lets you trade if you put the required items in either slot ![image](https://private-user-images.githubusercontent.com/80140847/305675879-d456d2ea-cea6-4575-be67-3f6e9ed54954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjYwOTUsIm5iZiI6MTcwODIyNTc5NSwicGF0aCI6Ii84MDE0MDg0Ny8zMDU2NzU4NzktZDQ1NmQyZWEtY2VhNi00NTc1LWJlNjctM2Y2ZTllZDU0OTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzMDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWNjYzE3OWJmYjU0NGYxNGRhYjVlZWZmZDc3NGU2N2ZjZjMzYTA4YzQxNDJjNmY4YjdhY2Q1YjhjY2U1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHuYJFQymzgyvL_M5TN2kQvhLGyMr6p9WCoBZCSa-j8)
> 
> though, if this is a bug, this could possibly be used as an easy way to edit villager trades. Like instead of using a command generator you could just place and remove items from the villager ui.

Yeah, this is intentional, as a way of manual trading and compatibility with servers without this mod, you can see that the "fake slots" dissapear when you put any item in any slot.
I'm more intrigued by the aliasing issues in the interface, are you using a version older than 1.2, or does the problem persist on some screen resolutions?

**Comment by Wilyicaro** [comment]
> also another small bug i saw was that short grass appears to be missing from the creative gui, likely due to the rename of the item id to be called minecraft:short_grass instead of minecraft:grass in 1.20.4

Thanks for reporting this, I had forgotten about this change, it'll be fixed in the next version.

**Comment by DanielMC101** [comment]
@Wilyicaro No mean any pressure but I'm just curious what have u been working on for the next update for this mod? Sorry for asking.

**Comment by SnowyBoi64** [comment]
the screen issues may have something to do with the mods im using, as I have encountered some issue that bumps the gui scale up by 1 when i enter the pause screen, so i am always playing on a gui scale one less than usually
so maybe that might have something to do with the ui being messed up?

**Comment by SnowyBoi64** [comment]
it is essential that causes the gui scale increase issue
https://modrinth.com/mod/essential
i guess whatever modifications they make to the pause screen just mess it up

**Comment by Wilyicaro** [comment]
Sorry, but I can't do much, as Essential is apparently closed source, so only its developers can fix it

**Comment by SnowyBoi64** [comment]
yeah thats fine it's really only noticeable in the villager gui
it only causes small like lines in the crosshair and health and hunger bars to appear
