### ISSUE TITLE
Crafting Interface Opacity Issue

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#98]
There seems to be a transparency issue in the crafting interface where the chests are rendered in an odd fashion..

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/ab356da7-2663-4d65-947f-d6742a09ab47)

This also seems to apply to most blocks whose block state isn't a full cube, like the fence and fence gates (you can see this in the picture).

Also wanted to say really good work with this mod, the crafting interface is astoundingly accurate and easy to use on keyboard and mouse. Overall, this mod is easily one of the best recreations of legacy console I have ever seen, and its amazing how much it pays attention to details in recreating the spark the old versions have :)

**Comment by Wilyicaro** [comment]
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/3699da50-4e9b-4fb7-ba38-5983fed84d5b)
What is the opacity issue? It's pretty identical to the LE, as you can see in Xbox 360 edition print above

**Comment by ShatterdPotato** [comment]
Wow, I guess I never noticed that when I played legacy console, sorry about that😅
