### ISSUE TITLE
Missing Crafting Menu Items

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#99]
Many Crafting Table items from 1.14+ are missing, such as hanging signs and Netherite tools. I created an updated full list of crafting table items (1.20 and 1.21 versions) to add these items. Unfortunately, you may have to make some major changes to the data files.

There are some minor rearrangements, but they were all based on the PS4 1.14 table. It also has all banner patterns, fireworks, and dyes listed.

[Minecraft PS4 Edition Crafting Table - Updated to 1.20.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14334198/Minecraft.PS4.Edition.Crafting.Table.-.Updated.to.1.20.txt)
[Minecraft PS4 Edition Crafting Table - Updated to 1.21.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14334223/Minecraft.PS4.Edition.Crafting.Table.-.Updated.to.1.21.txt)

Original PS4 1.14 table:

[Minecraft PS4 Edition Crafting Table - 1.14.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14334210/Minecraft.PS4.Edition.Crafting.Table.-.1.14.txt)

**Comment by ShatterdPotato** [comment]
Hey! I found a short term fix for this, it involves using WinRAR and directly editing the json file.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/eaf45e28-8949-49f4-8060-936f1bab98e6)

As you can see, if you go to assets/legacy, there is a file called  "crafting_tab_listing.json".

Opening said file will let you see this:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/9b8c387f-e9cc-4066-aa28-bfc3fa91273b)

You can see lists that contain each item in a row in the crafting interface, for example the first list is all the planks, second is sticks, and vise versa.

Using this, we can edit the file to add blocks into a list. The stonecutter block is one of the missing blocks in the crafting menu, so we can add it in quotations under the "utility" list, as shown below (MAKE SURE YOU USE PROPER SYNTAX OR THIS WILL NOT WORK!!!). Save the file and let WinRAR know to edit the mod directory, or it will not properly save it.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/a3361a9d-d070-4c04-964e-7a74a57d6f09)

Now, if we go in game, we can see that not only has the stonecutter been added in the utilities row, but in between the two blocks we put it in between in the list, the cartography table and loom.

![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/a6a698c1-6f54-4ee1-997d-2ce977f48557)

This is a relatively quick fix, albeit repetitive as you would have to do it for every block missing, but it works nonetheless, and will most likely be how the mod creator fixes it, but I'm no expert...

**Comment by Wilyicaro** [comment]
@ShatterdPotato 
You're completely right, this is how I'm going to fix it, hahah.
I created the crafting tab listing just for this, an easier way to add recipes to the crafting interface, for those who want to modify/add support for their own recipe tabs and groups.
It'll be fixed in version 1.4.1, thanks for reporting.

**Comment by AgentMindStorm** [comment]
I really appreciate your data-driven implementation. It will make it much easier to adjust the crafting table to my specific preferences in case your 1.21 layout does not match the one I proposed in the TXT file above!
